### ISSUE TITLE
Installscript auf dem RPI 3

### ISSUE THREAD

**Issue by Dtrieb** [Schrolli91/BOSWatch#100]
Ich versuche gerade verzweifelt BOSWatch auf meinem RPI 3 zum laufen zu bekommen.
Wenn ich

> You can easy install BOSWatch with the install.sh Script.
> 
> Download the install.sh in any folder you want.
> Make it executeable sudo chmod +x install.sh
> And use the script sudo sh install.sh

das mache läuft das Script durch aber es gibt nirgends ein Verzeichnis BOSWatch.

**Comment by Schrolli91** [comment]
kann das leider nicht nachvollziehen, da ich keinen RPI3 habe - kann da jemand aushelfen?

**Comment by Dtrieb** [comment]
Nachtrag:

Wenn ich die Befehle einzeln in der Konsole eingebe, (die im Install Script stehen) werden die Befehle ausgeführt.

**Comment by Schrolli91** [comment]
wäre mal interessant, ob die `install_dev.sh` aus dem Dev-Branch auf dem RPi3 funktioniert. Es hat im Laufe der Zeit doch die ein oder andere Änderung gegeben...

**Comment by Schrolli91** [comment]
@Dtrieb - falls das auch nix bringt bin ich leider ratlos, da mir kein RPi3 zur Verfügung steht um das zu testen - Wenn jemand einen hat wäre ich sehr verbunden, wenn der jenige mal drüber schauen könnte

**Comment by flothi** [comment]
Mein RPi3 sollte morgen, spätestens Dienstag eintreffen - dann werd ichs testen.

**Comment by flothi** [comment]
Also, ich habe das Skript mit dem RPi 3 getestet:
Durch das Ausführen des Installers als `root` (su...) referenziert das Skript alle `/home`-Pfade auf /root - und genau dort ist das Verzeichnis boswatch dann auch gelandet (z.B. /root/boswatch/BOSWatch und /root/boswatch/install) - wird wahrscheinlich dann durch den neuen Installer (vgl. issue #101 ) dann erledigt.

**Comment by Schrolli91** [comment]
Naja dann funktioniert der installer defacto auch auf dem RPi 3 ...
damit würde ich das Issue schließen
