### ISSUE TITLE
Mehrere Alarme in bestimmter Zeit filtern

### ISSUE THREAD

**Issue by OmarInkognito** [Schrolli91/BOSWatch#109]
Hallo,

gibt es auch die Möglichkeit Alarme in einem bestimmten Zeitraum zu blocken?
Also nicht "DEN doppelten Alarm" innerhalb von so und so Sekunden, sondern machen wir folgendes Beispiel:
Alarm 1 für A um 12:00
Alarm 2 für C um 12:01
Alarm 3 für A um 12:02

Somit würde er ja bei trotz jetziger, mitgebrachter Doppelalarmunterdrückung in der Config innerhalb von 2 Minuten 2 Alarme ausgeben.
Wie kann ich es anstellen, dass ich eine RIC so und so viele Sekunden / Minuten einfach komplett ignoriere, bzw. einen weiteren Alarm unterbinde?

Ich hoffe hier ist wer findig. :P
Vielen Dank und ein schönes WE! :)

**Comment by flothi** [comment]
Willst du also den Empfänger nach Eingang von Alarm 1 für x Minuten auf "taub" stellen?

**Comment by OmarInkognito** [comment]
Hallo,
Ja, aber nicht global für alle RICs, sondern nur "doppelte" in einer bestimmten Zeit.

**Comment by OmarInkognito** [comment]
Weiß niemand einen Rat?

**Comment by creiner** [comment]
Du möchtest also für jede RIC eine andere Zeitspanne definieren, für welche diese RIC dann gemutet ist?

**Comment by OmarInkognito** [comment]
Nein, ich habe einfach das Problem, dass ich Alarme durch 2 DAUs bekomme und diese dann quasi doppelt auflaufen, obwohl ich sie in der config.cfg mit 4 Sekunden ignoriere.
Das sieht dann quasi so aus:
2016-09-13 17:03:27 1234567 RTW     1
2016-09-13 17:03:27 1234568  NEF    1
2016-09-13 17:03:23 1234567 RTW     1
2016-09-13 17:03:23 1234568  NEF    1

Und ich möchte diesen Alarm halt nur ein Mal haben

**Comment by flothi** [comment]
Was spricht gegen eine Erhöhung der Zeitspanne? Ich arbeite mit 15 Sekunden.

**Comment by OmarInkognito** [comment]
Die 4 Sekunden waren nur ein Beispiel.
Anscheinend werden nur Alarme unterdrückt, wenn nur eine einzelne RIC doppelt alarmiert wird und keine weitere "dazwischen" steht.

Bei uns (mit EA) sieht es z.B. so aus:
DAU1: NEF (RIC 1234567), dann DAU2: NEF (RIC 1234567) -> blockiert, nur 1x zu sehen
oder
DAU1: NEF (RIC 1234567), dann DAU2: RTW (RIC 7654321 -> 2x zu sehen, nicht blockiert.

Egal wie viele Sekunden ich einstelle, DAU Alarme mit mehreren Kräften / RICs, werden nicht blockiert.

**Comment by K3vP0** [comment]
Hey, du solltest mit folgender Config klar kommen:
doubleFilter_ignore_entries = 20
doubleFilter_ignore_time = 60
doubleFilter_check_msg = 1

Es werden also 20 Einträge der letzten 60 Sekunden überpruft(auch wenn ein Alarm dazwischen ist), wenn ihr eine Schnelle Alarmierung habt, werden die Texte dann natürlich nochmal alamiert. 

Sollte das nicht funktionieren poste doch Mal bitte deine Config, und einen realen geschwärzten Log mit debuging messages.

Grüße

**Comment by Schrolli91** [comment]
@OmarInkognito schon getestet? sonst würde ich schließen...
