### ISSUE TITLE
Android Alarmierung

### ISSUE THREAD

**Issue by fwmarcel** [Schrolli91/BOSWatch#110]
@Schrolli91 @CryJack

Hallo ihr!

Da ich neu hier bin und relativ wenig Ahnung von python habe, brauche ich eure Hilfe. Gibt es bereits eine einfache möglichkeit der Alarmierung bzw weiterleitung der nachrichten auf Android ?
Wenn ja wäre es super, wenn jemand hier tipps gibt wie ich das ganze in BOSWatch und Android realsiere 

Schonmal Danke im vorraus

**Comment by flothi** [comment]
Ich bin zwar nicht angesprochen, aber definiere doch bitte mal "Nachrichten auf Android" - meinst du eine App,  per Email, Sms,...

**Comment by fwmarcel** [comment]
@flothi per Email geht es ja schon sehr einfach über BOSWatch. 
Ich meinte eher eine App, welche die Alarmierungen per Pushbenarichtigung raushaut und alte einsätze auflistet.

**Comment by K3vP0** [comment]
Hey, das sind zwei paar Schuhe, per Push Benachrichtigungen ist notifymyandroid wichtig, um alle alten nach zu lesen, würde ich dir die Webseite empfehlen.

Grüße

**Comment by Cryjack** [comment]
Mit Pushover kannst du Alarmierungen auf allen Endgeräten empfangen. Das geht auch in Windows oder auf iPhone. Die Alarme werden dort auch archiviert zum nachlesen. Jedoch ist die Übersichtlichkeit zum nachlesen etwas ungünstig, wenn du viele Alarme von unterschiedlichen Rics empfängst.

**Comment by Schrolli91** [comment]
dann schließe ich das hier mal - #112  Pushover ist ja gemerged
