### ISSUE TITLE
interface.txt hinzufügen

### ISSUE THREAD

**Issue by thejockel** [Schrolli91/BOSWatch#118]
Bitte die 'interface.txt' zum Repo hinzufügen.

`
[Filters]
...
DATAFIELD     = the field of the Data Array (See interface.txt)
...
`

Mir ist nicht klar, welche Parameter ich für DATAFIELD nutzen kann.

Danke und Gruß
Jockel

**Comment by Schrolli91** [comment]
Ich hab ehrlich gesagt keine Ahnung, wann genau diese Datei verloren gegangen ist ... In irgend einem Commit muss die sich wohl verabschiedet haben...

Aber hier stehts auch drin:
https://github.com/Schrolli91/BOSWatch/tree/develop/plugins#53-data-

**Comment by thejockel** [comment]
Moin,
Super genau was ich gesucht habe.

Danke & Gruß 
Jockel
