### ISSUE TITLE
Webinterface

### ISSUE THREAD

**Issue by dabenzel** [Schrolli91/BOSWatch#120]
Hi!
I've seen, that you've deleted the `www`-folder. I'd like to make a new web interface for BOSWatch is it okay if I would push it in the `develop` branch?
Are there any plans to put more Data (exept alarms, more like config) into the mysql database?

//Bin deutscher, kannst also auch auf deutsch antworten ;)

**Comment by thejockel** [comment]
+1

**Comment by Schrolli91** [comment]
In diesem Ordner befinden sich 2 Vorlagen für die Weboberfläche
https://github.com/Schrolli91/BOSWatch/tree/develop/exampleAddOns
ob diese allerdings noch funktionieren kann ich nicht sagen...

Wenn du möchtest, kannst du natürlich gerne was dran machen und des in den dev Pullen.
Ich würde dich dann aber bitten solche Sachen wie config für die Online Oberfläche, und evtl User Verwaltung die auch ins MySQL integriert wird, unabhängig vom MySQL Plugin zu gestalten. Damit man am Ende auch das MySQL Plugin weiter wie gewohnt nutzen kann.

**Comment by dabenzel** [comment]
Ich hatte vor, das ganze mit Bootstrap als CSS-Framework zu realisieren, da man hier recht gut und schnell Seiten bauen kann und das ganze denn auch noch responsiv ist.

Wäre es evtl nicht sinnvoll, die komplette Config in die MySQL zu schieben? Denn hätte man in dem Webinterface alle möglichen Einstellungen zu verwalten?

Wie meinst du, dass ich unabhängig vom MySQL Plugin arbeiten soll? Also Datenbanktechnisch (von den Tabellen) oder wie genau?

Ich würde gerne von vorne anfangen, da ich auch noch etwas Übung brauch, was PHP-Klassen angeht.

**Comment by Schrolli91** [comment]
Ja freilich kannst du komplett frisch anfangen...

Was ich zwecks MySQl meinte, dass die Tabellen wie du schon sagtest separat bleiben. Dem Webinterface solltest du dann eine eigene *.sql Datei beilegen, mit der man die Tabellen generieren kann die das Webinterface braucht. Damit bleibt das ganze unabhängig vom derzeit bestehenden MySQL Plugin.

Die Daten für das Web kannst du natürlich aus den Tabellen vom MySQL Plugin auslesen, löschen, usw...

Will nur sicherstellen, dass das Plugin auch unabhängig und ohne das Webinterface an sich nutzbar bleibt.

**Comment by dabenzel** [comment]
Hallo!
Wäre es sinnvoll, die Config.ini auch im Webinterface bearbeitbar zu machen? Vielleicht kann man hiermit einige Fehleingaben abfangen. 

Ist es zudem möglich den Status des Dienstes abzufragen (Dienst aktiv | Dienst inaktiv)?

**Comment by Schrolli91** [comment]
Das kann man evtl für später ins Auge fassen... Dazu sollte man sich aber vorerst ein Konzept überlegen wie man das gestaltet.

Aktuell halte ich das für unpraktisch, da man bei jeder Änderung direkt auch das Webend anpassen muss und es so leicht passieren kann, das alles Inkonsistent wird.

Zum Thema Service kann ich nicht viel sagen, hab das nie probiert. Wurde von @JHCD entwickelt.

**Comment by dabenzel** [comment]
Habe mich nun für Laravel als PHP-Framework entschieden. Mit dem ganzen habe ich keine Erfahrung, somit wird das ganze sicherlich etwas länger dauern. Als CSS-Framework werde ich Bootstrap verwenden.
Was gibt es denn für Wünsche außer der einfachen Darstellung der MySQL Einträge aus der DB?

**Comment by flothi** [comment]
Ich denke die Darstellung reicht in erster Näherung mal aus - erweitern kann man es immer noch ;-)

**Comment by Schrolli91** [comment]
Seh ich auch so... erst mal Tabellarische Darstellung der Einträge.
Dann wäre die Roh-Version soweit fertig und dann kann man gesondert nochmal über Specials reden...

**Comment by dabenzel** [comment]
Ich werde erst ein Mal ohne Laravel arbeiten, sondern mit reinem php.
Laravel ist hier aktuell noch 'too much' wenn es nur um die simple,
tabellarische Darstellung geht.
Ich werde das ganze heute abend beginnen und auch funktionen wie Limits
einbauen. Eine Sortierung ist für später angedacht, Mehrsprachigkeit
ebenfalls.

**Comment by Schrolli91** [comment]
Am besten die ganzen Werte zur config auch in der Datenbank ablegen. Also ich meine nur die, die das webend betreffen...  Sowas wie Limits oder so...  Musst halt mal schauen

**Comment by dabenzel** [comment]
Habe mal angefangen. Bisher für die Version 0.1 für das Webinterface werde ich eine `config.json`Datei nehmen, wo Dinge wie MySQL-Verbindung und ViewLimit (Anzahl der Einträge) drin sind. Noch etwas, was hinterlegt sein sollte?

**Comment by Cryjack** [comment]
Hallöle,

dazu hatte ich in meinem MySQL Plugin Update schon eine neue User-Tabelle für die Anmeldung angelegt. Schau da mal rein, denn ggf. macht es Sinn diese dort zu entfernen und hier separat zu nutzen.

Passwort war bei mir MD5 Hash gespeichert.

**Comment by Schrolli91** [comment]
Ja das wäre nicht schlecht, wenn das wieder aus dem Plugin an sich verschwindet, und dafür dann in die .sql Datei vom Webend integriert wird. Gehört ja an sich nicht ins Plugin....

MD5 denke ich sollte ausreichen...

**Comment by Cryjack** [comment]
Habt Ihr mal drüber nachgedacht, das Webinterface eventuell als Plugin für ein CMS zu bauen? Ich könnte mir das Ganze recht nett im Wordpress vorstellen. Dortige vorhandene Plugins, Benutzerverwaltung und eine Integration direkt in einzelne Pages wäre sicher interessant.

**Comment by flothi** [comment]
Ich wäre mit der "Veröffentlichung" wozu so ein Layout verleiten könnte, vorsichtig.
Da gab's in letzter Zeit gerade in Hamburg und Siegen massive Probleme. 

Optik an sich wäre für mich zweitrangig, das lässt sich mit CSS etc hinbiegen.

**Comment by Cryjack** [comment]
Das stimmt. Das könnte in der Tat dazu verleiten.

**Comment by dabenzel** [comment]
Anfangs wird das Webinterface keine Benutzerverwaltung oder Login-Funktion bekommen. Ich finde, es kann jeder hier eigenverantwortlich handeln und mit einer simplen .htaccess ist das ganze schon erledigt. Sofern das Webinterface mal wachsen soll, kann man auch über User/Login nachdenken. So meine Meinung.

**Comment by Cryjack** [comment]
Dann verstehe ich den Sinn des Ganzen nicht so recht. Keine Konfiguration speichern, keine Userverwaltung, was bleibt denn dann noch übrig? Ein paar Tabellen aus MySQL schön machen und per Htaccess sichern bekommen sicher alle hin. Dafür brauchen wir kein "webinterface", oder sehe ich das nur so?

Ich hätte das mit jQuery ordentlich gestaltet und wenigstens eine minimale Userverwaltung eingebaut.

**Comment by Schrolli91** [comment]
@dabenzel gibts schon was neues?

**Comment by OmarInkognito** [comment]
Ich bin auch gespannt, wie ein Fuchs! :)

**Comment by dabenzel** [comment]
Ich bin aktuell in meinem Abschlussprojekt meiner Ausbildung und habe deswegen etwas weniger Zeit. Außerdem habe ich meinen aktuellen Stand noch einmal verworfen, da er mir nicht gefiel. Die letzte Oktoberwoche habe ich Urlaub und wollte da das Webinterface mit Userverwaltung uvm in der MySQL umsetzen, bzw einen zeigbaren Stand erzeugen.

**Comment by Schrolli91** [comment]
Alles klar - bin schon gespannt...

**Comment by dabenzel** [comment]
Kann ich davon ausgehen, dass jeder Kommandozeilenzugriff hat?
Ich würde nun doch [Laravel](https://laravel.com/) nutzen und die BosWatch-Ansicht als Modul einer ganzen Feuerwehrverwaltung machen. (Keine Panik. Es wird zuerst standalone sein!).
Hierfür benötigt man jedoch [composer](https://getcomposer.org/), welcher über die Kommandozeile funktioniert. Ich werde die Tage mit dem Interface beginnen, da ich nun auf der Arbeit viel Erfahrung mit Laravel sammeln konnte!

**Comment by flothi** [comment]
@dabenzel geh davon aus, dass dem so ist ;-)

**Comment by OmarInkognito** [comment]
Huhu, gibt es etwas Neues? :X

**Comment by fwmarcel** [comment]
@Cryjack schon Fortschritte gemacht ?

**Comment by fwmarcel** [comment]
bzw. @JHCD gibt es ne installations erklärung oder so für dein alarmMonitorWeb ?

**Comment by dabenzel** [comment]
Bei mir wird das aktuell aufgrund von Abschlussprüfungen etc. nichts mehr.
Ich plane jedoch etwas größeres, als nur ein Webinterface. Es wird jedoch BOSWatch integriert.
Somit mach ich hier erstmal zu..

**Comment by Schrolli91** [comment]
Schade drum, aber ok, Prüfungen gehen ganz klar vor....

**Comment by dabenzel** [comment]
Ich bin nun wieder zurück im Boot und würde mich gerne wieder ans Interface machen. Dieses jedoch gerne in einem separaten Projekt, da ich ein PHP-Framework drüber setzen will und jetzt schon viele gemischte Sprachen in diesem sind.

**Comment by Schrolli91** [comment]
Tu es ;-)
Wenn du einen ersten Release Stand hast kann man ja nochmal drüber reden, das ganze hier ins Repo zu integrieren, oder man lässt es separat, sehen wir ja dann

**Comment by Schrolli91** [comment]
Ich weis nicht inwieweit sich da noch etwas tut? Notfalls ein frisches Issue aufmachen oder direkt einen Pull-Request stellen ;-)
