### ISSUE TITLE
Readme anpassen/vervollständigen

### ISSUE THREAD

**Issue by Schrolli91** [Schrolli91/BOSWatch#125]
**Nabend zusammen,**
in den letzten Tagen habe ich es endlich geschafft, alles anstehende zu mergen, Konflikte zu beheben, und mich um die ein oder andere Sache zu kümmern.
Was dabei leider komplett auf der Strecke blieb ist die readme.
Evtl hat jemand von euch ja Lust und Zeit, das ganze ein wenig aufzupolieren.

Dabei dachte ich etwa an solche Punkte:
- Grundlegende Installationsbeschreibung
- Grundlegende Bedienung (Parameter und config-Einstellungen)
- Vorhandene Plugins mit kurzer Beschreibung (Funktion und config)

Das wären wohl mal die wichtigsten Punkte die aktualisiert gehören. Ich selbst kann aktuell leider keine Zeit aufbringen, daher wäre es Klasse wenn sich jemand findet und es im develop pullt.

**Gruß Basti**

**PS:** Nachdem die Readme dann auf aktuellen stand ist, würde ich direkt ein Release anstreben damit der Master-Branch mal wieder was neues zu sehen bekommt ;-)

**EDIT:** evtl ist es auch ganz nützlich, statt das readme aufzubessern, direkt die in Github integrierte Wiki Funktion zu nutzen und gleich alles ordentlich zu verpacken?
https://github.com/Schrolli91/BOSWatch/wiki

**Comment by flothi** [comment]
Was wäre denn die bevorzugte Sprache? DEU oder ENG?

**Comment by dabenzel** [comment]
Ich denke, dass 90% der user Deutsch sind. Wobei englisch natürlich international ist. Ich sehe das aber so, dass man englisch immernoch machen kann, wenn es gewünscht ist und die deutsche Doku eine gute Qualität hat.

**Comment by Smith-fms** [comment]
Ja, ich sehe es ähnlich. Die Nutzer sind hier eher aus den deutschen Sprachraum. Eine Short Description in Englisch wäre mit Sicherheit nicht verkehrt, aber ausführliches Wiki/Readme dann eher in DE.

**Comment by Schrolli91** [comment]
Also wenn wir n wiki aufsetzen, gerne in Deutsch... Code Kommentare aber weiterhin bitte Englisch....
Dann würde ich sagen - wir setzen ein umfangreiches Deutsches Wiki auf - und lassen die readme dann langsam auslaufen und irgendwann als Anleitung verschwinden....

**Comment by flothi** [comment]
Ich war mal so frei und habe mit dem Wiki fortgefahren, frei Schnauze und nach Gutdünken. Hoffe es geht in die richtige Richtung.

**Comment by dabenzel** [comment]
Ich war mal so frei und habe schon ein paar Änderungen an deinen doch schon sehr guten Einträgen vorgenommen ;)

**Comment by Schrolli91** [comment]
Sieht gut aus...  Ein richtig oder falsch gibt es sowieso nicht...  Einzige voraussetzung ist am Ende ja nur, daß es am Ende jemanden hilft

**Comment by Schrolli91** [comment]
Also da die Readme ja jetzt einen Hinweis enthält, dass sie Veraltet ist, schließe ich dieses Issue und wir sollten nach und nach das Wiki erweitern
