### ISSUE TITLE
Aktuelen Release Candidate testen

### ISSUE THREAD

**Issue by Schrolli91** [Schrolli91/BOSWatch#127]
Ich bitte euch, den aktuellen Stand nochmal auf Herz und Nieren zu testen, bevor ich dann ein Release anstrebe.

https://github.com/Schrolli91/BOSWatch/releases/tag/v2.1-RC

Neue Plugins und Sonstige Funktionen und Verbesserungen könnt Ihr gerne noch per Pull Request senden. Ich merge die allerdings erst, wenn die 2.1 drausen ist in den Dev.

Sonst zieht sich das noch ewig bis endlich mal wieder eine stabile neue Version rauskommt

**Comment by flothi** [comment]
Ich gehe das mal an

**Comment by dabenzel** [comment]
Ich werde es auch tun, wenn bei mir der MASTER-Branch (also der aktuelle Release) funktioniert. Aktuell tut er nicht mal das, wobei ich nicht ganz genau weiß, woran es liegt...

Sofern ich die nächsten Tage erfolg habe, werde ich den RC auch testen!

**Comment by flothi** [comment]
Was klappt denn nicht? Fehler eingrenzen wäre schon sexy ;-)

**Comment by dabenzel** [comment]
wenn ich `boswatch.py` mit den params `-f 123.456M und -a POC512` starte ist das letzte was passiert, dass er sagt, dass er auf Alarme wartet. In meiner mysql landet aber nichts und in der Ausgabe ist auch nichts, auch, wenn ich boswatch mit dem parameter `-v` starte

**Comment by Smith-fms** [comment]
Nabend, hast du den Gain Wert ermittelt und beim Start gesetzt? Mehr als ein SDR Stick angeschlossen und auch mal die squelch auf den Wert 0 gesetzt? :-)

**Comment by flothi** [comment]
Hast du das Loglevel mal auf Debug gestellt und dir die Logfiles angeschaut? Falls noch nicht geschehen, bitte LogLevel 10 einstellen und ggf mal die Log posten

**Comment by flothi** [comment]
Feedback zum RC v2.1:
Das Installskript installiert in den Ordner /root/boswatch/BOSWatch - meiner Meinung nach sehr unsexy.
Entweder einigen wir uns darauf, standardmäßig in den Ordner /home/pi zu installieren oder es wird ein neuer Nutzer erstellt - sauberer wäre es jedoch, entweder nach /usr/local/BOSWatch oder /opt/BOSWatch zu installieren.
Der Start der boswatch.py scheitert beim aktuellen Installer an fehlendem rtl_fm - ein Neustart behebt das Problem (sollte in den Installer fließen).
Nach dem Start als root wird augenscheinlich nichts dekodiert, die Ausgabe endet mit 
`03.10.2016 20:45:51 - pluginLoader    [DEBUG   ] Plugin [DISABLED] firEmergency`
`03.10.2016 20:45:51 - pluginLoader    [DEBUG   ] Plugin [DISABLED] MySQL`
`03.10.2016 20:45:51 - pluginLoader    [DEBUG   ] Plugin [DISABLED] httpRequest`
`03.10.2016 20:45:51 - pluginLoader    [DEBUG   ] Plugin [DISABLED] template`
`03.10.2016 20:45:51 - boswatch        [DEBUG   ] starting rtl_fm`
`03.10.2016 20:45:54 - boswatch        [DEBUG   ] starting multimon-ng`
`03.10.2016 20:45:57 - boswatch        [DEBUG   ] start decoding`

Der Test mit testdata läuft jedoch durch.

**Comment by Schrolli91** [comment]
@flothi  was den Installer angeht kannst du gerne Hand anlegen, wenn du magst...

Was meinst du mit nichts wird dekodiert? Empfängt den multimon etwas? Denn dekodiert wird von Boswatch selbst ja nix, es parst nur die Daten von multimon und verarbeitet sie weiter

**Comment by thejockel** [comment]
Moin,
ich finde auch die Lösung vom home dir nicht so schön.
Und wäre auch für /opt/BOSwatch

**Comment by flothi** [comment]
@Schrolli91 Werde ich gerne tun, gib mir nur ein paar Tage Zeit ;-)

Ich hab mir mal die Ausgabe von multimon angeschaut, da ist aktuell kein Leben drin (multimon_raw-out nachgebaut zum Testen). htop liefert mir 4 Prozesse rtl_fm und 1 multimon-ng

**Comment by Smith-fms** [comment]
+1
Grund: ich arbeite mit einem extra Benutzer, warum soll ich es im Home von Pi nutzen, der nicht existiert? BosWatch läuft nicht nur auf dem Pi ;-) ich nutze ein Standard Debian mittlerweile.

**Comment by Schrolli91** [comment]
Alles zum neuen Installer an Ideen bitte in den Issue #101 
Die Liste im Startpost wird dann aktualisiert ...

**Comment by flothi** [comment]
@Schrolli91 Erledigt

Ich gehe ansonsten mal weiter auf Fehlersuche und melde mich

**Comment by flothi** [comment]
Feedback zum RC:
Die fehlende Auswertung scheint an meinem Stick zu liegen, selbst der Empfang eines regional starken FM-Senders ist arg bescheiden.
Ich werde mal schauen, ob ich noch nen anderen Stick auftreiben kann.

**Comment by Schrolli91** [comment]
Nochmal kurze Rückfrage, ob weiterhin irgendwelche Probleme aufgefallen sind?

**Comment by flothi** [comment]
Bis auf meine Anmerkungen ist mir nichts weiter aufgefallen

**Comment by Schrolli91** [comment]
Da weiter nichts kam, zieh ich das Release jetzt durch...
