### ISSUE TITLE
Expressalarm

### ISSUE THREAD

**Issue by chbally** [Schrolli91/BOSWatch#131]
In unserem LK wird mit Expressalarm alarmiert.
Es wird / werden als erstes die Alarm-RIC(s) und im Abstand von 1-3 sec mit einer immer gleichen RIC der Alarmtext ausgesendet.
Gut beschrieben wird das [hier](https://bugs.radio-operator.de/projects/radio-operator/wiki/ExpressAlarm).
Gibt es eine Möglichkeit das in BOSWatch umzusetzten.

By the way: Tolle Projekt!

**Comment by Schrolli91** [comment]
Also ist das EIN Text RIC für alle Empfänger und nur die, die vorher "scharf" gemacht wurden, warten auf den Text?

**Comment by chbally** [comment]
Nein nicht ganz. 
Das Ganze wird durch eine "Service-RIC" eingeleitet. 
Die Melder lösen bei der Alarm-RIC aus und der Text wird über die Text RIC dann hinterher empfangen (1-3 sec später).
Aber es gibt auch Alarm-RICs ohne folgenden Text z.B. für Probealarm oder Sirenen etc.

Die gleiche "Service-RIC" wird aber auch vor dem 3 minütlich wiederkehrende Reichweiten RIC geschickt.

**Comment by Schrolli91** [comment]
Aktuell geht das nicht ohne weiteres mit BOSWatch...
