### ISSUE TITLE
cannot load MySQL Plugin

### ISSUE THREAD

**Issue by Schrolli91** [Schrolli91/BOSWatch#133]
siehe hier: https://github.com/Schrolli91/BOSWatch/wiki/M%C3%B6gliche-Fehler

Das kann doch eigentlich gar nicht auftreten, da der python mysql connector über die install mit geladen werden sollte?
Wäre nett wenn da mal jemand drüber schauen kann...

**Comment by flothi** [comment]
Auch da schaue ich mal drüber; heute abend ist erst nochmal der Installer bzw v2.1 (#127) dran

**Comment by dabenzel** [comment]
Habe ich aufgrund des Issues #99 erstellt. Ist bei mir nicht aufgetreten.

Das Install Skript sollte auf jeden fall im ersten schritt auf su Rechte testen!

**Comment by flothi** [comment]
Habe den Hinweis mal übernommen und als Merker gesetzt

**Comment by PeterLaemmle** [comment]
Ich bekomm beim Start folgende Meldung:
`03.10.2016 12:23:22.402 - pluginLoader    [DEBUG   ] load plugin: MySQL`
`03.10.2016 12:23:23.019 - MySQL           [DEBUG   ] unknown error`
`None`
`03.10.2016 12:23:23.020 - pluginLoader    [DEBUG   ] call MySQL.onLoad()`
Weiß jemand, was da schief läuft?

**Comment by flothi** [comment]
@PeterLaemmle 
Welchen Raspi verwendest du denn? In #99 war es der fehlende Connector, welche install (aus welchem Zweig) hast du verwendet? `sudo apt-get install python-mysql.connector` hast du schon probiert?

**Comment by Schrolli91** [comment]
der error kommt ja schon, bevor die onLoad() aufgerufen wird, also entsteht der fehler schon durchs reine importieren...

würde mal gerne noch mehr vom logfile sehen, vor allem davor interessieren mich noch n paar einträge

**Comment by PeterLaemmle** [comment]
Davor steht nichts relevantes mehr in dem Logfile. Das MySQL-Plugin funktioniert übrigens trotz dieser Meldung wunderbar.

**Comment by PeterLaemmle** [comment]
Mein Problem hat sich erledigt.

**Comment by Schrolli91** [comment]
Und was wars?

**Comment by PeterLaemmle** [comment]
Ich hatte vermutlich etwas zu viel hin- und hergemerged. Jetzt hab ich den aktuellen dev-Branch nochmal komplett geclont. Seither passt es wieder :-)

**Comment by Schrolli91** [comment]
dann schließe ich hier... eigenes install für die mysql vermerke ich im installer issue
