### ISSUE TITLE
Plugin mysql: zusätzliches install-file für Datenbank

### ISSUE THREAD

**Issue by flothi** [Schrolli91/BOSWatch#138]
Vorschlag: Im Plugin-Ordner für mySQL wird ein zusätzliches Installskript abgelegt, welches automatisiert mysql und alle Abhängigkeiten installiert und auch die Datenbank gemäß sql-dump vorbefüllt.

**Comment by Schrolli91** [comment]
find ich gut... evtl dann auch direkt als parameter an die normale install, das man dieses script gleich automatisch mit aufrufen kann, wenn man vorher schon weis, mysql nutzen zu wollen

**Comment by flothi** [comment]
Genau so dachte ich mir das ;-)
