### ISSUE TITLE
Automatisches Error Tracking via rollbar.com

### ISSUE THREAD

**Issue by Schrolli91** [Schrolli91/BOSWatch#140]
Was haltet Ihr davon, eine Rollbar Integration anzustreben?
Das Rollbar Plugin wird importiert, und sendet dann bei einem Fehler im Programm die Daten, sowie den Stack-Trace an die Webseite.

Dort laufen alle auftretenden Fehlermeldungen sauber sortiert und übersichtlich zusammen.
Dadurch können öfter auftretende Fehler evtl besser lokalisiert und gefunden werden.

**Comment by dabenzel** [comment]
Ich könnte mir vorstellen, dass einige nicht wollen, dass das Programm nach
hause telefoniert. Nicht jeder raspberrypi hat internetanbindung

**Comment by Schrolli91** [comment]
man könnte die Telefonfunktion ja optional ausschaltbar machen, aber an sich fände ich es schon eine feine Sache, wenn Fehlermeldungen auch wirklich mit dem Stack-Trace zentral auflaufen.... da sieht man halt auch direkt welche Datei wo mit welchen Daten einen Crash verursacht hat...

**Comment by creiner** [comment]
Jeder kann die Fehlermeldungen an einen eigenen privaten Rollbar Account senden oder soll von allen Installationen an einen zentralen Rollbar Account gesendet werden? 
Ersteres könnte man einbauen und die Aktivierung optional dem Anwendern überlassen.
Die zweite zentrale Variante finde aus dem von dabenzel genannten Grund eher unschön. Wobei man könnte diese deaktiviert einbauen und vom Anwender explizit zur Fehleranalyse aktivieren lassen.

**Comment by Schrolli91** [comment]
Ich dachte schon an eine zentrale Lösung... Dafür ist rollbar ja gedacht...  Abschaltbar halte ich schon auch für sinnvoll...  Evtl sogar nur im dev branch verfügbar... Denke schon das es sicher hilfreich sein kann
