### ISSUE TITLE
Attribut für zweiten RIC

### ISSUE THREAD

**Issue by PeterLaemmle** [Schrolli91/BOSWatch#142]
Üblicherweise werden für einen Alarm mehrere RICs alarmiert. D.h. es kommen verschiedene RICs, der Text bleibt aber gleich.
Gibt es schon ein Attribut, welches mir anzeigt, dass ein empfangener RIC der zweite (bzw. nicht der erste) zu einem Alarm ist?

**Comment by chbally** [comment]
Ich glaube was du meinst heißt Expressalarm und wurde am Wochenende hier [https://github.com/Schrolli91/BOSWatch/issues/131](url) behandelt.

**Comment by PeterLaemmle** [comment]
Nein, ich sprech nicht von Expressalarm.

Ich versuch es mal andersrum: Per doubleFilter kann ich ja den zweiten Empfang des gleichen RIC und/oder des gleichen Textes erkennen und die Weiterverarbeitung unterbinden.
Wie kann ich auf die Information, dass ein bestimmter RIC das Duplikat, eine Wiederholung o.ä. ist, im Plugin zurückgreifen?

**Comment by Schrolli91** [comment]
aktuell gar nicht... die doppelten Alarme stehen ja in dieser doubleFilterList oder so ähnlich... wird ein doppelter Alarm erkannt, wird kein Plugin ausgelöst

**Comment by K3vP0** [comment]
So wie ich das verstehe möchtest du gern eine Sammelmeldung haben ? 

Bedeuetet wenn Einheit X alamiert wird und verstärkung fordert, dass dann Bei der Einheit A ein Flag gesetzt wird, das die Meldung schon innerhalb der letzten 3 Stunden sendet wurde ?

**Comment by Schrolli91** [comment]
Es geht wohl eher darum, zu erkennen, wie viele Einheiten zu einem einzelnen Ereignis alarmiert wurden, bzw ob schon andere alarmiert sind.

Aber nein, das geht wie gesagt aktuell nicht.
In meinen Augen wäre die optische Aufbereitung der Daten dann auch eher Webinterface Sache.
BOSWatch selbst soll die Daten ja nur irgendwie Strukturieren und nicht direkt selbst aufbereiten.
