### ISSUE TITLE
httpRequest - urlparse-Verarbeitung fehlerhaft

### ISSUE THREAD

**Issue by DeBukkIt** [Schrolli91/BOSWatch#143]
/* removed */

**Comment by thejockel** [comment]
Schau dir mal im dev branch das Plugin an. Dort habe ich das gelöst.

Gruß Jockel

**Comment by DeBukkIt** [comment]
/* removed */

**Comment by thejockel** [comment]
Moin, ja ist kompatibel mit dem Master Branch

**Comment by DeBukkIt** [comment]
/* removed */

**Comment by Schrolli91** [comment]
da hier an sich kein Fehler vorliegt, und die neue Version sowieso bald veröffentlicht werden soll, schließe ich
