### ISSUE TITLE
Wiki: Liste funktionierender/getesteter USB-Sticks

### ISSUE THREAD

**Issue by flothi** [Schrolli91/BOSWatch#146]
Servus,
ich würde gerne eine Liste pflegen, in der die von uns (also den anwesenden) getesteten USB-Sticks (idealerweise nebst Markenname, Hersteller und Chipsatz) aufgeführt werden; klar könnten wir uns an rtl_fm hängen, aber eigene Erfahrung ist da mMn sinniger.
Also wenn als sinnvoll erachtet: Bitte eintragen oder hier kommentieren.

**Comment by Schrolli91** [comment]
Setz doch im Wiki mal eine Liste auf, mit einer Tabelle welche Informationen alle erfasst werden sollen...
Dort kann dann jeder seinen Stick selbst eintragen - schaden kann es auf keinen Fall...

**Comment by flothi** [comment]
Das ist im Wiki bei den Voraussetzungen schon angefangen, ich denke jedoch hier ist es prominenter aufgehoben. 

Hat jemand Erfahrungen mit der Airspy-Familie?

**Comment by hhansen06** [comment]
ich habe diverse typen an usb sticks bisher getestet, alle eher semi gut.
Kennt jemand einen Stick der gerne auch ne mark kosten darf, der nicht driftet?

**Comment by DaGuich** [comment]
@hhansen06 
http://www.rtl-sdr.com/buy-rtl-sdr-dvb-t-dongles/ der hier läuft prima

**Comment by Smith-fms** [comment]
Erledigt. Entsprechende Hardware kann dann ergänzt werden.
Eintrag im Wiki zu finden. Verlinkungen hier zu dem Thema landen im 404?!

**Comment by flothi** [comment]
@Smith-fms 
Ich war so frei und hab die Infos in de:Voraussetzungen verschoben, da dort eine Liste angelegt war.

**Comment by Smith-fms** [comment]
@flothi 
Ja, alles gut. So passt es sehr gut.

**Comment by Schrolli91** [comment]
Die Kategorie im Wiki steht... jeder der noch nen Stick kennt der nicht dabei steht wird ihn hoffentlich einfügen, ein eigenes Issue dafür sehe ich als überflüssig an
