### ISSUE TITLE
eMail Plugin

### ISSUE THREAD

**Issue by fwmarcel** [Schrolli91/BOSWatch#148]
Wenn ich das eMail Plugin starte, bekomme ich diesen Fehler: 

  File "/root/boswatch/BOSWatch/plugins/eMail/eMail.py", line 106, in run
    server = smtplib.SMTP(globals.config.get("eMail", "smtp_server"), globals.config.get("eMail", "smtp_port"))
  File "/usr/lib/python2.7/smtplib.py", line 256, in **init**
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 317, in connect
    (code, msg) = self.getreply()
  File "/usr/lib/python2.7/smtplib.py", line 368, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")

Ich habe bereits mehrere SMTP server  und accounts probiert ohne erfolg.

**Comment by flothi** [comment]
Manche Mailserver sind recht "eigen" was die TLS-Verbindung angeht - hast du an dem Parameter mal etwas geändert? Ansonsten: Welche Server hast du getestet?

**Comment by fwmarcel** [comment]
Die TLS Verbindung hat in dem Fall keine Rolle gespielt. Ich musste dafür Änderungen in der eMail.py vornehmen. Wenn gewünscht lade ich die Datei / Code hier hoch.

**Comment by flothi** [comment]
Die Änderungen würden mich interessieren - und vor allem auch die verwendeten Server.

**Comment by fwmarcel** [comment]
Geändert habe ich die Verbindung, welche das Script aufbaut. Viele Anbieter erwarten eine SSL verschlüsselte Verbindung. 
server = smtplib.SMTP(globals.config.get("eMail", "smtp_server"), globals.config.get("eMail", "smtp_port"))
server = smtplib.**SMTP_SSL**(globals.config.get("eMail", "smtp_server"), globals.config.get("eMail", "smtp_port"))

Getestet wurden die SMTP Server von GMail und T-online.

**Comment by fwmarcel** [comment]
@Schrolli91 Von meiner Seite aus kann dieser Issue geschlossen werden.

**Comment by Schrolli91** [comment]
so wie ich sehe, ist das ja ein allgemeines Problem? sollte das in der Quelldatei geändert werden?

**Comment by fwmarcel** [comment]
@Schrolli91 Wäre dafür das zu ändern. Bzw eine Möglichkeit einbauen um SSL nochmal in der Config zu aktivieren oder deaktivieren. Ich bin nämlich der Meinung das heutzutage fast alle SMTP Server ssl verschlüsseln
