### ISSUE TITLE
Plugin Idee - Whatsapp

### ISSUE THREAD

**Issue by fwmarcel** [Schrolli91/BOSWatch#149]
Ein Plugin für Whatsapp wäre super. Eine möglichkeit zur übertragung der Daten zu yowsup würde schon genügen. 
https://github.com/tgalal/yowsup

**Comment by thejockel** [comment]
yowsup als plugin wäre super.

Zur Zeit gebe ich die Daten per URL Plugin an einen Webserver. Dieser verarbeitet dann die Daten und startet per PHP exec den demo client.

**Comment by Schrolli91** [comment]
Wäre eine Wirklich feine Sache

**Comment by dabenzel** [comment]
Denkt hierbei bitte an das Thema Datenschutz! Das ganze läuft jedes mal über Amerikanische Server!

**Comment by flothi** [comment]
@dabenzel Whatsapp ist doch E2E verschlüsselt ;-) Aber grundsätzlich hast du recht, nutzen würde ich es nicht, dafür hab ich die SMS-Funktion

**Comment by dabenzel** [comment]
Die Frage ist ja, ob youwsup auf E2E Verschlüsselt (hab hierzu nichts gefunden auf die schnelle). Zudem werden Metadaten nicht verschlüsselt. Letzten Endes muss es jeder selbst wissen. Nur WhatsApp ist im Thema "Datenschutz" immer ein heißes Eisen.

**Comment by fwmarcel** [comment]
@flothi wie hast du das ganze realisiert ? und fallen dabei nicht kosten für die SMS an ?

**Comment by flothi** [comment]
@fwmarcel Ich habe dafür ein Plugin geschrieben, das einen UMTS-Stick ansteuert (s. #102). Und ja, es fallen Kosten in Höhe von 9 cent an (pro SMS), aber bei unserer Alarmierungshäufigkeit reicht das vollkommen.

**Comment by fwmarcel** [comment]
@flothi Wärst du in der Lage nach entsprechenden Vorgaben bei der Realisierung zu helfen. Falls ja wäre eine alternative Kommunikationsmöglichkeit besser ^^. Ich persönlich habe nicht viel Ahnung von Python. Im Grunde müsste das Plugin nur die Meldungen (%msg%) als Parameter für yowsup übergeben und yowsup dann ausführen.

**Comment by fwmarcel** [comment]
Dies wäre z.B der Befehl welcher in dem Script ausgeführt werden sollte:
yowsup-cli demos --yowsup --config /root/yowsup/config.yowsup --send 49151xxxxxxxxx "POCSAG MSG" -M"
Dazu müsste "POCSAG MSG" noch durch die entrechende Meldung ersetzt werden

**Comment by flothi** [comment]
Das wird dann ähnlich dem SMS-Daemon sein, der auch "nur" ein externes Stück Software ist und angesteuert werden muss.
Ich bin im SMS-Plugin nur dazu übergegangen, das Filterkonzept zu erweitern, sodass nur bestimmte (sub-)RICs als SMS rausgehen bzw. unterschiedliche SubRICs verschiedene Nummern erhalten.

Ich kann mir das beizeiten mal anschauen, diese Woche wird aber eng werden.

**Comment by fwmarcel** [comment]
Würde mich und glaube auch andere Nutzer sehr freuen. Natürlich darf auch jeder andere sein Glück bei der Plugin Gestaltung versuchen ^^

**Comment by PeterLaemmle** [comment]
Ich bin an WhatsApp gescheitert. Die Nummer wurde jedesmal innerhalb kürzester Zeit wegen eines Verstoßes gegen die Nutzungsbedingungen gesperrt.
Hatte es mit [yowsup2](https://github.com/tgalal/yowsup) versucht, mich aber nur auf essentiellen Kommandos beschränkt. D.h. Verbindung aufbauen und Nachricht schicken. Sonst nichts.
Ohne die ganzen Statusmeldungen (Nutzer schreibt...) und Quittierungen zu setzen und vielleicht Verzögerungen einzubauen wird es meiner Meinung nach nichts mit einem Plugin für WhatsApp.

**Comment by fwmarcel** [comment]
@PeterLaemmle Wärst du bereit dein Code / Plugin mir bereit zustellen. Würde gerne dein Ansatz sehen. Gerne auch über andere Plattformen, wenn du nicht möchtest das alle dein Werk sehen

**Comment by thejockel** [comment]
#erhalten des SMS codes
`yowsup-cli registration -E android --cc 49 --phone 491750000000 --requestcode sms`

#Code zurück senden
`yowsup-cli registration -E android --cc 49 --phone 491750000000 --register 000-000`

Danach erhaltet hier das Password und könnt per Nachrichten senden:
`yowsup-cli demos -l <$number>:<$password> --send 491750000000 "whatappapi test"`

Wichtig ist dabei, dass ihr immer den selben user benutzt.
Den für diesen wird das Verzeichnis .yowsup2 in seinem homedir angelegt.

Zudem wird nach dem 3 request für den SMS Code die Nummer für eine Stunde blockiert.
Danach sogar für 24h und dann wird die gesperrt.

**Comment by fwmarcel** [comment]
@thejockel  die yowsup befehle kenne ich. Und yowsup2 läuft auf meinem pi bereits. Jedoch fehlt das plugin, welches automatisch den Senden Befehl mit dem entsprechenden Meldungsinhalt startet

**Comment by fwmarcel** [comment]
@PeterLaemmle Wärst du bereit dein Plugin für yowsup2 hier bereitzustellen. Auch wenn du selber nicht damit weiter arbeitest, wäre dies eine wunderbare Sache für mich und andere User

**Comment by PeterLaemmle** [comment]
Ein Plugin hab ich nie daraus gebaut. Wurde immer schon während meiner Versuche gesperrt.
Wenn aber @thejockel yowsup2 sauber am Laufen hat und damit dauerhaft kommuniziert, sollten wir ja eine solide Basis haben. Ein Plugin ist dann nur noch Formsache.

**Comment by fwmarcel** [comment]
Achso dann habe ich das von dir falsch verstanden. Würdest du ein Versuch für ein Plugin starten ? @PeterLaemmle 
Zur Beschreibung:
+ POCSAG Meldungen sollen nur übermittelt werden 
+ Muss das yowsup Python Script starten 
+ Muss den Melder Text als Parameter mit an yowsup übergeben 

Befehl zum senden der Nachricht "Test Meldung" an die Nummer 49151... mit den Config/Logindaten aus "/root/yowsup.../" wäre z.B. 
yowsup-cli demos --yowsup --config /root/yowsup/config.yowsup --send 49151xxxxxxxxx "Test Meldung" -M

**Comment by fwmarcel** [comment]
@Schrolli91 Ich habe mittlerweile ein gut funktionierendes Plugin, welches mit der aktuellen master Version arbeitet.

**Comment by thejockel** [comment]
Ich würde vorschlagen, dass man den Text mit an das Plugin übergeben kann.

z.B.
`[yowsup]`
`...`
`msg = Alarm %DESCR%`

Damit können dann auch Nachrichten für ZVEI sinnvoll verwendet werden und auch für Pocsag statische Texte.

**Comment by fwmarcel** [comment]
@thejockel Wollte es allgemein erstmal zum laufen bringen. Und gucken wie es sich verhält mit yowsup. Solch eine Funktion werde ich wahrscheinlich später noch mit einbringen

**Comment by fwmarcel** [comment]
@thejockel Funktion ist in die dev Version nun mit implementiert

**Comment by thejockel** [comment]
Plugin sieht gut aus und läuft bei mir.

**Comment by Schrolli91** [comment]
habe es nun gemerged... Damit kann man hier schließen oder?

**Comment by fwmarcel** [comment]
Korrekt
