### ISSUE TITLE
[Vorschlag] Umstieg auf Forum / Labels bei Issues mitgeben

### ISSUE THREAD

**Issue by dabenzel** [Schrolli91/BOSWatch#151]
Moin Moin!
Wäre es eventuell sinnvoll, auf ein Forum für Fragen und Wünsche umzusteigen? So kann man auch besser zwischen Wunsch/Hilfe/Bug separieren. 
Sonst würde ich mir wünschen, dass man bei der Erstellung eines Issues schon ein Label mitgeben kann (kenne GitHub hierbei nicht, bei GitLab geht das jedenfalls). Sonst geht ein Stück Übersichtlichkeit verloren.

**Comment by Schrolli91** [comment]
Weis nicht ob ein Forum nicht evtl. den Rahmen sprengt? Ich bezweifel ehrlich gesagt, dass wir wirklich so viele User habe.

Zwecks Labels - ich weis nicht genau, ich als "Besitzer" des Repositories kann es auf jeden Fall... Dachte, Labels kann jeder am rechten Rand angeben?

**Comment by flothi** [comment]
Ich hab's bis dato nicht gesehen / gefunden - aber das Verteilen von Labels wäre schon ne Erleichterung mMn.

**Comment by OmarInkognito** [comment]
Da hier viele Gäste mitlesen und dieses "Issue" noch offen ist, habe ich mal kurz eine öffentliche Umfrage erstellt:
 http://onlinevoten.de/poll/60635-boswatch-forum-ja-nein/

Ein solches Forum würde ich sonst nämlich super gerne organisieren

**Comment by flothi** [comment]
Unabhängig von der Frage eines Forums: Wie wäre es mit einer geschlossenen Gruppe auf Facebook?

**Comment by dabenzel** [comment]
Ich könnte sonst sehr gerne einen Bereich in meinem Forum hierfür zur Verfügung stellen. Das Forum befindet sich aktuell noch im Aufbau und soll sich an Mitglieder von BOS richten. Später, wenn ein akzeptabler Stand meiner Feuerwehr Verwaltung erreicht ist, wird diese dort auch ihren Bereich finden.

**Comment by Schrolli91** [comment]
Hat sich hier eigentlich schon was getan?

**Comment by flothi** [comment]
Schaut mau aus, ich würde es aktuell eher zusätzliche Belastung ansehen (sofern sich kein Freiwilliger für die Verwaltung findet)

**Comment by dabenzel** [comment]
Scheint ja nun etwas zu geben.
