### ISSUE TITLE
Telegram Error

### ISSUE THREAD

**Issue by fwmarcel** [Schrolli91/BOSWatch#152]
Ich bin mal dabei alle Plugins durchzuprobieren, wie jetzt auch Telegram. Dabei ist mir aufgefallen:

  File "/root/BOSWatch/includes/pluginLoader.py", line 109, in loadPlugin
    return imp.load_module(plugin["name"], *plugin["info"])
  File "/root/BOSWatch/plugins/Telegram/Telegram.py", line 14, in <module>
    import urllib, telegram, googlemaps
ImportError: No module named telegram
23.10.2016 16:43:02 - pluginLoader    [ERROR   ] error loading plugin: Telegram
23.10.2016 16:43:02 - pluginLoader    [DEBUG   ] error loading plugin: Telegram
Traceback (most recent call last):
  File "/root/BOSWatch/includes/pluginLoader.py", line 32, in loadPlugins
    plugin = loadPlugin(i)
  File "/root/BOSWatch/includes/pluginLoader.py", line 109, in loadPlugin
    return imp.load_module(plugin["name"], *plugin["info"])
  File "/root/BOSWatch/plugins/Telegram/Telegram.py", line 14, in <module>
    import urllib, telegram, googlemaps
ImportError: No module named telegram

Kann mir da jemand weiter helfen ? Hab ich oder der Code was falsch gemacht ^^

**Comment by Schrolli91** [comment]
Er findet das telegram Modul nicht, welches er importieren will...  Muss man das separat installieren?

**Comment by flothi** [comment]
Würde es Sinn machen, bei plugins, die zusätzliche Abhängigkeiten haben, ein shell-Skript hinzuzufügen? Quasi wie den SQL-Dump für die Datenbank?

Beachtet der Plugin-Loaeder Groß- u Kleinschreibung (in der config)?

Aus dem Plugin:
`@requires: Telegram BOT token, Telegram chat ID, library python-telegram-bot and optional googlemaps`

**Comment by PeterLaemmle** [comment]
Es braucht nur die Bibliothek [python-telegram-bot](https://python-telegram-bot.org/).
Lässt sich u.a. per pip installieren.
Das Gleiche gilt für die Bibliothek [googlemaps](https://github.com/minglongzzz/GoogleMaps2.43).

**Comment by fwmarcel** [comment]
Diesen Fehler hatte ich schon behoben. Dafür war ein anderer da. Kann diesen jedoch gerade nicht übers Handy zeigen...

**Comment by fwmarcel** [comment]
@PeterLaemmle Und funktioniert das Plugin mit der aktuellen Master Version ?

**Comment by PeterLaemmle** [comment]
Das weiß ich nicht. Der Development-Branch funktioniert bei mir aber inklusive dem Plugin für Telegram.

**Comment by fwmarcel** [comment]
Hm schade  beim Dev bekomme ich komischerweise keine Meldungen rein. Daher frage ich...

**Comment by PeterLaemmle** [comment]
Schau mal, ob du den Parameter zur Geräteauswahl beim Aufruf angegeben hast:
`-d DEVICE, --device DEVICE            Device you want to use (Check with rtl_test)`

**Comment by Schrolli91** [comment]
DEVICE sollte im Code mal dringend auf required gesetzt werden, dann würde BOSWatch bei vergessen nämlich auch einen Fehler werfen

**Comment by PeterLaemmle** [comment]
Done
https://github.com/Schrolli91/BOSWatch/pull/153

**Comment by PeterLaemmle** [comment]
Funktioniert das mit Telegram jetzt bei dir @fwmarcel?

**Comment by fwmarcel** [comment]
Hatte bis jetzt noch keine Zeit das zu testen. Werde ich Donnerstag tun.

**Comment by fwmarcel** [comment]
@PeterLaemmle Habe meiner Meinung nach alles nun eingerichtet. BOT Token und Chat ID hinzugefügt. Bekomme jedoch diesen Fehler. 
  File "/root/BOSWatch-develop/plugins/Telegram/Telegram.py", line 122, in run
    except Unauthorized:
NameError: global name 'Unauthorized' is not defined
Ich habe bereits verschiedene Bots und deren Token und entsprechenden ID versucht. Kein Erfolg.

**Comment by Schrolli91** [comment]
da is wohl noch ein Fehler im exception Handling @PeterLaemmle ?

**Comment by PeterLaemmle** [comment]
Es scheint, ich merge immer nur die Hälfte. Sorry!
https://github.com/Schrolli91/BOSWatch/pull/154

**Comment by Schrolli91** [comment]
:-D
@fwmarcel dann bitte nochmal den aktuellen Dev testen...

**Comment by fwmarcel** [comment]
@Schrolli91 @PeterLaemmle Muss dich leider enttäuschen ^^

  File "/root/BOSWatch-develop/plugins/Telegram/Telegram.py", line 91, in run
    bot.sendMessage('%s' % BOTChatIDAPIKey, output)
  File "/usr/local/lib/python2.7/dist-packages/telegram/bot.py", line 124, in decorator
    result = func(self, _args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telegram/bot.py", line 150, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/usr/local/lib/python2.7/dist-packages/telegram/utils/request.py", line 205, in post
    *_urlopen_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telegram/utils/request.py", line 132, in _request_wrapper
    resp = self._con_pool.request(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/urllib3/request.py", line 72, in request
    *_urlopen_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/request.py", line 135, in request_encode_body
    **urlopen_kw)

es wird nicht unbedingt besser....

**Comment by PeterLaemmle** [comment]
Hat die config das richtige Format?
Bei mir sieht das ungefähr so aus:
`BOTTokenAPIKey = 123456789:ABC-DEF1234ghIkl-zyx57W2v1u123ew11`
`BOTChatIDAPIKey = -123456789`

**Comment by fwmarcel** [comment]
@PeterLaemmle Ja so sieht das bei mir auch aus. Ist das "-" erforderlich ? Ich habe es sowohl für das - als auch ohne probiert beides mal mit dem selben fehler

**Comment by PeterLaemmle** [comment]
Kannst du sämtliche Versionen, die du verwendest, aufführen? Python, Bibliotheken python-telegram-bot, urllib, etc.
Schau dir mal dein `output` an. Vielleicht passt ja was beim Basteln des Inhalts nicht. Evtl. mal nur `output = timeHandler.curtime()` versuchen?

**Comment by PeterLaemmle** [comment]
An was lag es jetzt?

Am 29.10.2016 um 11:33 schrieb fwmarcel <notifications@github.com <mailto:notifications@github.com> >:

Closed #152.
