### ISSUE TITLE
Neues Webinterface zur Überwachung / Auswertung / Einstellung 

### ISSUE THREAD

**Issue by K3vP0** [Schrolli91/BOSWatch#163]
Moin,

ich sitze grade daran, eine neue Webseite zu gestalten. Ich würde gerne auch unteranderem die Einstellungen die momentan in der Config.ini liegen mittels php interfache ändern. 

Eine Überlegung von mir war, die Einstellungen in mysql zu migrieren und sie dann on the fly zum Pythonscript verschieben. Würde bedeuten das man essentiell in den confighandler eingreifen müsste. 

Bevor ich mir nun allerdings die große Arbeit mache und alles in mysql migierere und einen confighandler schreibe der in mysql angebunden ist, erstmal die Frage ob ihr das für sinnvoll erhaltet? 

Ziel des ganzen soll sein, das man den BOSWatch Server nur noch über ein Webinterface steuert, und von dort aus dann auch dynamisch die Logs / Nachrichten lesen kann. Dazu würde dann PHP seitig noch eine Benutzersteuerung kommen.

Viele Grüße

**Comment by Schrolli91** [comment]
Die Gesamt Idee als Server Interface gefällt mir sehr...
Die config in MySQL dagegen gar nicht, wenn ich ehrlich bin, denn dann wird MySQL Voraussetzung.

Was ich mir vorstellen könnte, aus der Weboberfläche direkt die config.ini zu bearbeiten und diese dann wieder zurück zu schreiben. INI Parsen dürfte mit PHP keine allzu Große Sache werden.

**Comment by OmarInkognito** [comment]
Bitte bitte bitte realisieren!❤️

**Comment by DaGuich** [comment]
Ist da schon jemand dran?

**Comment by DaGuich** [comment]
Also um hier mal einen Plan reinzubringen:
Statt das Webinterface mit PHP zu machen könnten wir uns auf Python beschränken und uns mit wsgi bei apache bzw. nginx einklinken. Python bietet viele Frameworks an, das bekannteste ist wohl Django, welches bei uns jedoch Overkill wäre. Ein schönes Microframework wäre [Bottle](http://bottlepy.org/docs/dev/index.html).

**Comment by carrier92** [comment]
Ich hab mal das Ganze als PHP umgesetzt, noch sehr einfach gehalten aber es funktioniert.
Im Moment können keine neuen Plugins (sections) eingefügt werden, muss vorher manuell in die ini.
Die config.ini wird komplett überschrieben (vorher ein Backup machen)
Ich hab das Ganze auf einem Raspi mit Apache und PHP laufen, parallel zu BOSWatch.
[BOSWatchEditor.zip](https://github.com/Schrolli91/BOSWatch/files/690096/BOSWatchEditor.zip)

**Comment by flothi** [comment]
@DaGuich 
Hast du da Erfahrungen mit, also mit Django / Bottle? Ich bin auf dem Gebiet Neuling, aber durchaus gewillt da etwas zu realisieren.

**Comment by Schrolli91** [comment]
@carrier92 habe ich eben nach ein paar kleinen Änderungen Fehlerfrei zum laufen gebracht. Sieht an sich recht gut aus wie ich finde...

Die Frage ist wies mit dem restlichen Webend inzwischen aussieht? Gibts da schon nen Stand?
@Tauebenuss  @DaGuich  @carrier92

**Comment by carrier92** [comment]
Was hast du Ändern müssen?
Ich hab hier schon einer Version mit zusäzlicher Beschreibungsdatei für die einzelnen Abschnitte?

**Comment by Schrolli91** [comment]
Waren nur Kleinigkeiten die nen Fehler hervorgerufen haben. Weis nimmer genau was es war, da es abseits von GIT passiert ist... Glaube `$sectionOld = '';` habe ich hinzugefügt, damit es definiert ist, wegen Vergleich mit nicht existenter Var

```php
<?PHP
// Mit diesem script kann die config.ini von BOSWatch editiert werden.
// Da das script mit dem user des php interpreder läuft (bei ubuntu ist es 'www-data') muss diesem das schreibrecht auf diese Datei gewährt werden.
// Dateiberechtigung mit 'sudo chmod o+w config.ini' ändern. ACHTUNG das gibt allen usern die Schreibberechtigung!
//
// Author: Karl-Heinz Ziegler
// Version 1.0 06.01.2017

// Pfad zur config.ini
$source = 'config.ini';
//prüfen ob Datei beschreibbar ist
if (is_writable($source)) {
	// prüfen ob formular abgeschickt wurde
	if (isset($_POST['senden'])) {
		$fp = fopen ($source,"w");
		fwrite ($fp,"");
		//Datei leeren
		fclose ($fp);
		$fp = fopen ($source,"a");
		unset ($_POST['senden']);
		$sectionOld = '';
		foreach ($_POST as $rawsection=>$keys) {
			$section = explode ('|',$rawsection);
			if ($sectionOld != $section[0]){
				$sectionOld = $section[0];
				fwrite ($fp,"[".$section[0]."]\n");
			}
			fwrite ($fp,$section[1]);
			fwrite ($fp, "=");
			fwrite ($fp, $keys);
			fwrite ($fp, "\n");
			$sectionOld = $section[0];
		}
		fclose ($fp);

	}
} else{
	echo"<h1 style='color:red'>Die Datei $source ist nicht schreibbar!</h1>";
}
$configContent = parse_ini_file($source,true,INI_SCANNER_RAW);
echo"<form method='post'>";
foreach ($configContent as $section=>$keys) {

	echo "<fieldset>";
	echo "<legend>".$section."</legend>";
	foreach ($keys as $key=>$val) {
		echo $key;
		echo"<br>";
		echo"<input type='text' name='".$section."|".$key."' value='".$val."' size='30'";
		echo"<br>";
		echo"<br>";
		}
	echo "<input type='submit' name='senden' value='Speichern'>";
	echo "</fieldset>";
	}

echo "</form>";

?>

```

**Comment by carrier92** [comment]
okay, wäre dann zu überlegen ob wir das script in git aufnehmen?

**Comment by Schrolli91** [comment]
Wäre ich definitiv dafür...  Machst du einen pull request in den dev branch?  Am besten in einen unterordner `dev/ORDNERNAME` dann sieht man auch gleich das sich dieser Teil noch in Entwicklung befindet wenn wir Releasen

**Comment by carrier92** [comment]
hoffe ich hab es richtig gemacht.
Ich hab noch nie mit github gearbeitet.

**Comment by K3vP0** [comment]
Ich habe hier jetzt mal ein Anfang gesetzt, der allerdings noch sehr Alpha ist. 

Habe noch einige Punkte die ich die nächsten Tage beheben möchte:

ToDo:

Login.php, firstSignin.php loginredirect.php erstellen !

-->Dashboard
-->Alarme
* SQL Config auslagern
* SQL Abfrage generalisieren
-->--> FMS
* FMS SQL Abfrage erstellen
-->--> ZVEI
* ZVEI SQL Abfrage erstellen^
-->--> POCSAG
--> Einstellungen
-->--> Globale Einstellungen
* Beschreibung der einzelenen Optionen mittels SQL Datenbank??? 
* Einstellungen per "service boswatch reload" einspeisen --> Anpassung im Python Script
-->--> Plugins
* Einstellungen pro Plugin erstellen
-->--> Addons
* Platzhalter für Addons die hinzugefügt werden können
--> Testcenter
* Zum Alarmieren aus dem Webfrontend



Als "Framworks" kommen Frameworks:
https://github.com/fethica/PHP-Login und
https://startbootstrap.com/template-overviews/sb-admin-2/

zum Einsatz, sowie den oben stehenden INI Parser, allerdings gibt es noch Fehler mit Kommentaren. Woran das liegt, weiß ich noch nicht.

**Comment by carrier92** [comment]
Hallo Tauebenuss,

gibt es schon was zum Anschauen?
Bei den INI Dateien hab ich gelernt das sich die INI Datei Struktur von der "INI" (eigentlich cfg) Struktur von python unterscheidet. 
Am meisten Ärger machen Semikolon , Zeilenumbrüche und Leerzeichen in den Werten.
Ich war dann soweit das ich ein eigenen INI Parser in PHP geschrieben habe.
Schlussendlich war der Tenor das wir das ganze in eine SQLite Format bringen wollten.
Die Datenbank hatte ich auch schon begonnen und aller Einstellungen eingebracht bin aber dann am Umstellen von  INI auf SQL im BOSwatch code gescheitert.

Gruß
carrier92

**Comment by K3vP0** [comment]
Hey Carrier, 

also Stand heute habe ich in meinem Fork ein Webend schon mal abgelegt, werde das gleich mal aktualisieren. 

Um eine Funktionalität herzustellen sind folgende Schritte von nöten:
SQL Benutzer für die Abfragen einrichten
/config/*.* bearbeiten. sowie eine leere Datei "FIRSTLOGIN" erstellen.
Rechte auf der INI Datei setzen.
Danach solltest du dich unter /*/pages/main-register.php registerien. (Kontrolle ob in SQL geschrieben).
Jetzt solltest du unter /*/pages/index.php dich anmelden können.

Wichtig sind die Ordner: config,includes und pages.
Probier mal und berichte. 


Was steht noch auf der ToDo Liste:

User-Managment (Self Service (Passwort,E-Mail,Name)
Übersichten und Grafiken / Statistiken
Verbesserung der Einstellungen mit Beschreibungen und Hilfen / min/max Werte bzw. Syntax Check. --> Hier steht eventuell ein großer Meilenstein an, den config parser zu verändern....
Config->Filter -> Hier muss noch eine andere Lösung her.
Config->Addons -> Hier muss noch meine neue Version des Alarmmontiors hinterlegt werden.
PS: Der muss auch noch veröffentlicht werden.

Dann möchte ich eine Objektorientierung in die Pluginabläufe bringen, d.h. man kann Plugins ggf. mehrmals für ein und den selben Alarm aufrufen.

Ich glaube wenn wir damit fertig sind dürfen wir uns auch BOSWatch 3 nennen.


Grüße
die Tauebenuss

**Comment by stereu** [comment]
Hallo zusammen,

sitzt jemand aktuell aktiv an einem Webend? Würde sonst anfangen eines in Meteor/React oder ggf. in PHP komplett neu zu schreiben inkl. responsive Design. Speichern der Einstellungen habe ich als Temp-config-File im Webspace vorgesehen. Wenn jemand mag kann er sich ja mit dem getten des Files vom Webspace auf die Maschine beschäftigen.

Grüße, Stephan

**Comment by Schrolli91** [comment]
@Tauebenuss wie ist denn dein aktueller Stand bei der Thematik?
Gernle lege ich für das Webend hier im Repo einen eigenen Branch an, in dem dann zusammen gemeinsam an einem Webend entwickelt werden kann, wenn entsprechendes Interesse besteht.

**Comment by stereu** [comment]
Ich fang mal in einem eigenen Fork an, sobald du den Branch erstellt hast commite ich den Code rüber.

**Comment by Schrolli91** [comment]
Tu dir keinen Zwang an :)
Will ja niemanden von seinem freiwilligen Dienst abhalten ;)

Dennoch würde mich mal interessieren was @Tauebenuss inzwischen erstellt hat
Im #297 war ja schon einiges an Material, ich weiß nur nicht, wieso er den PR direkt wieder selbst geschlossen hat ??

**Comment by K3vP0** [comment]
Da standen Dinge drin, die da hätten nicht drin stehen dürfen... ;) 

Bin Momentan Beruflich recht eingespannt, wenn es wieder ruhiger wird, stelle ich auch eine Demo Version zur Verfügung, allerdings, will ich nicht wie beim Alarm-Monitor so eine unfertige Version in den Umlauf bringen. 

Werde dann beides in einem Alpha fertigen Zustand die nächsten Wochen hochladen.

**Comment by Schrolli91** [comment]
@stereu @Tauebenuss 
Hier scheint aktuell ja zumindest was zu Laufen.
Ich close das hier einfach mal. Wenn Ihr was habt, bitte einfach per PULL ins Repo pushen
