### ISSUE TITLE
install.sh failed to build multimon-ng

### ISSUE THREAD

**Issue by hhansen06** [Schrolli91/BOSWatch#165]
Es scheint das aktuell multimon-ng nicht mehr compiliert wird ... Es fehlt qt-default.
Kann durch apt-get install qt5-default gefixxt werden.

Auszug aus setup_log:
> Cloning into 'multimonNG'...
> qmake: could not find a Qt installation of ''
> make: *** No targets specified and no makefile found.  Stop.
> make: *** No rule to make target 'install'.  Stop.
>

**Comment by Schrolli91** [comment]
gehts um den Dev oder master branch?

**Comment by hhansen06** [comment]
master

**Comment by Schrolli91** [comment]
Das sollte sich dann mit dem neuen Release erledigt haben, da die Install großflächig überarbeitet wurde

**Comment by hhansen06** [comment]
kann man das install.sh aus dem master nicht kurz fixxen? So wie es aktuell ist, kann man boswatch nicht out-of-box verwenden. Und es ist relativ schwierig herauszufinden was genau gebrochen ist.

**Comment by flothi** [comment]
Wenn der neue Release quasi aktuell auf dem Weg ist sollte das binnen kürzester Zeit erledigt sein - Schrolli ist dran ;-)

**Comment by Schrolli91** [comment]
Denke damit ist das hier vorerst erledigt ;-)
