### ISSUE TITLE
install.sh von master defekt

### ISSUE THREAD

**Issue by hhansen06** [Schrolli91/BOSWatch#168]
das install.sh was mit dem heutigen release kommt ist kaputt.

>This may take a several minutes... Don't panic!
Caution, script don't install a Webserver with PHP and MySQL
So you have to make up manually if you want to use MySQL support
install.sh: 20: install.sh: Syntax error: Bad for loop variable
root@raspberrypi:~#

Beim zweiten lauf klappt es ?!

**Comment by hhansen06** [comment]
Abschlussmeldung ist auch falsch:
 BOSWatch is now installed in ~/boswatch/
Unter /opt/ wird zwar nen Ordner BosWatch angelegt, der ist aber leer.

**Comment by Schrolli91** [comment]
Die Änderungen zum Installer sind im merge #134 von @thejockel durchgeführt.
Evtl kann er sichs mal anschauen, was da schief gelaufen ist?

Wo liegen die Daten denn tatsächlich?

**Comment by flothi** [comment]
Also, die Meldung bezüglich der bad loop variable kommt vom fehlerhaften Aufruf - das Skript schreibt zwar /bin/bash mehr oder minder vor, wird aber (in der Anleitung) mit "sh" aufgerufen.
Ein Aufruf `sudo bash install.sh` und es läuft - Installationsanleitung anpassen fixt zumindest dieses Problem.

**Comment by flothi** [comment]
Das viel größere Problem:
Der neue Installer macht einfach nix - er lädt zwar munter nach /opt/boswatch/... herunter, aber installiert wird nix. Dass am Ende von install.sh ein unärer Operator in der Reboot-Abfrage erwartet wird fällt da aktuell am wenigsten ins Gewicht.

setup_log.txt:

`Einige Pakete konnten nicht installiert werden. Das kann bedeuten, dass`
`Sie eine unmögliche Situation angefordert haben oder, wenn Sie die`
`Unstable-Distribution verwenden, dass einige erforderliche Pakete noch`
`nicht erstellt wurden oder Incoming noch nicht verlassen haben.`
`Die folgenden Informationen helfen Ihnen vielleicht, die Situation zu lösen:`

`Die folgenden Pakete haben unerfüllte Abhängigkeiten:`
`qt4-default : Kollidiert mit: qt5-default aber 5.3.2+dfsg-4+rpi1 soll installiert werden`
`qt5-default : Kollidiert mit: qt4-default aber 4:4.8.6+git64-g5dc8b2b+dfsg-3+deb8u1+rpi1 soll installiert werden`
`E: Probleme können nicht korrigiert werden, Sie haben zurückgehaltene defekte Pakete.`
`install.sh: Zeile 64: git: Kommando nicht gefunden.`
`install.sh: Zeile 72: cmake: Kommando nicht gefunden.`
`make: *** Keine Targets angegeben und keine »make«-Steuerdatei gefunden.  Schluss.`
`make: *** No rule to make target 'install'.  Schluss.`
`install.sh: Zeile 82: git: Kommando nicht gefunden.`
`install.sh: Zeile 91: qmake: Kommando nicht gefunden.`
`make: *** Keine Targets angegeben und keine »make«-Steuerdatei gefunden.  Schluss.`
`make: *** No rule to make target 'install'.  Schluss.`

**Comment by hhansen06** [comment]
hatte es mit nem Pi3 getestet, der Pi war frisch "geimaged" mit 2014-06-20-wheezy-raspbian.zip

**Comment by flothi** [comment]
@hhansen06 Das ist auch mein Testsystem - ich versuch mal bissl was zu drehen...

**Comment by flothi** [comment]
Update:
Das Problem scheint aus der Kombination von qt4-default und qt5-default zu kommen; entferne ich qt4-default läuft zwar alles durch, aber die Kompilierung von Multimon schlägt fehl.
Der Installer packt zumindest die Dateien an die richtige Stelle (/opt/boswatch/...) suboptimal ist die Tatsache, dass ich es als Root ausführen muss, aber das ist Kosmetik

**Comment by Schrolli91** [comment]
#101 Ja das mit den root Rechten steht noch auf der ToDo Liste

Ich habe aktuell keine Möglichkeit zu testen, daher kann ich mich an der Problem Lösung nicht wirklich beteiligen. Aber ich denke diese Bugs zu beheben hätte schon eine sehr Hohe Priorität.

**Comment by flothi** [comment]
Ich werde wohl erst morgen weiterschauen können, definitiv müssen wir das mit qt4/5-default auf den Weg bringen. 

Für die Akten: auch bei mir ein Raspi3 mit raspbian

**Comment by thejockel** [comment]
Das wundert mich jetzt auch.
Ich betreibe es im Container aufm Pi.

Sprich das Setup wird bei jedem build neu durchgeführt.

Ich werde morgen auch nochmal schauen.

**Comment by flothi** [comment]
Ich hab noch weitere Fehler entdeckt (Datei in modprobe.d wird falsch, d.h. ohne newline erstellt) und in einem Fix angepasst.

**Comment by Schrolli91** [comment]
Der fix wurde soeben gemerged...

**Comment by hhansen06** [comment]
habe meinen test pi hier jetzt nicht neu gemacht, nur den installer aktualisiert, und einmal /opt/boswatch geleert. Bekomme folgende Meldung:

> Caution, script don't install a Webserver with PHP and MySQL
> So you have to make up manually if you want to use MySQL support
> 
>                [10/10] [##########]
> 
>      -> configure............................
> 
>  BOSWatch are now installed in /opt/boswatch/
> Install ready!
> install.sh: line 134: [: =: unary operator expected
> root@raspberrypi:~#

Und irgendwas am Installscript macht mir jedes mal den Curser kaputt...

**Comment by flothi** [comment]
Der Fehler mit dem unären Operator kam bei meinen Tests nicht - da er im Gegensatz zu den anderen Fehlern die Funktion (bis auf einen eventuellen Reboot) nicht beeinträchtigt sollte der zwar zügig gefixt werden, eine 2.1.1 würde mMn reichen. 
(UPDATE: Mit #172 gefixt!)

Was ist denn am Cursor kaputt?

**Comment by hhansen06** [comment]
Putty -> SSH -> Pi
Cursorfarbe wird auf schwarz gesetzt ... d.h. nach der installation kann man etwas schwer die config anpassen weil der Cursor weg ist.

**Comment by flothi** [comment]
Der Cursor war unsichtbar; ich habe das ganze im Skript ergänzt.

**Comment by Schrolli91** [comment]
ist nun ebenfalls gemerged... 
Stehen jetzt noch akut Probleme im Installer an?

**Comment by flothi** [comment]
Ich sehe aktuell keine Probleme mehr - die Verwendung deiner Forks wäre was für 2.1.1 - insofern hier erledigt

**Comment by Schrolli91** [comment]
dann schließe ich das vorerst mal
