### ISSUE TITLE
Umgang mit 3rd-party-Software

### ISSUE THREAD

**Issue by flothi** [Schrolli91/BOSWatch#171]
Moin,

mal unabhängig vom Release 2.1 - aktuell wird ja von rtl_fm und multimon_ng das jeweils aktuelle Release aus git geclont.
Wäre es, im Zuge der Kompatibilität nicht sinnvoll, einen auf die jeweilige BOSWatch-Version freigegebenen/getesteten Release in einem Fork vorzuhalten? 

Florian

**Comment by Schrolli91** [comment]
Halt ich für eine gute Idee... 

Die aktuellen Versionen laufen soweit ja mit BOSWatch zusammen? Dann würde ich die beiden mal forken und dann können wir die Install anpassen, dann kommt alles direkt aus einem Account von Github.

**Comment by flothi** [comment]
Kann ich für meine Installationen bestätigen - neue Versionen der betroffenen Software können dann ja bei Bedarf nach dem Testen übernommen werden

**Comment by Schrolli91** [comment]
evtl in der install wieder n Flag vorsehen mit dem man alternativ die aktuellen Versionen installieren kann.
Standard mäßig werden dann eben die beiden geforkten installiert

Hier mal die Forks:
- https://github.com/Schrolli91/multimon-ng
- https://github.com/Schrolli91/rtl-sdr

eben gezogen - entspricht also dem jetzigen stand

**Comment by flothi** [comment]
Wird im Installer angepasst, issue hier geschlossen

**Comment by Schrolli91** [comment]
#101 - ich referenziere hier mal ;-)
