### ISSUE TITLE
PPM Error

### ISSUE THREAD

**Issue by hhansen06** [Schrolli91/BOSWatch#175]
Moin, wie ermittelt ihr die PPM Error rate? 
mit rtl-kalibrate?
Wäre es nicht sinnvoll ein tool wie rtl-kalibrate in boswatch zu integrieren?

**Comment by Schrolli91** [comment]
Denke es wäre schon möglich einen automatischen Kalibrier-Modus vorzusehen.
Im Prinzip müsste man nur die Ausgaben von rtl-kalibrate anzapfen und auswerten.
https://www.turais.de/ein-rtl_sdr-mit-kalibrate-sdr-kalibrieren/

**Comment by flothi** [comment]
Wobei ich finde, dass man es nicht allzu sehr aufplustern sollte - eine Funktion ist auch ohne Kalibrierung möglich; von daher würde ich mich mit einem Hinweis auf die Möglichkeit begnügen.

**Comment by hhansen06** [comment]
Ich hab hier vorhin nen Stick gehabt mit ner PPM Abweichung von knapp 200 ... Damit ist dann ohne Fehlerkorrektur der normale Betrieb nicht mehr möglich ;) Aber ein Eintrag im Wiki sollte da Ausreichen denke ich ...

**Comment by Schrolli91** [comment]
ne Kalibrations Anleitung wäre schon nicht schlecht - rtl-kalibrate wird schließlich sowieso im Paket mit installiert - das Werkzeug ist also vorhanden

**Comment by flothi** [comment]
Ich schreib mal ein paar Zeilen ins Wiki - evtl ergänzt man den Installer mit der Schlussmeldung um den Hinweis, den Stick zu kalibrieren

**Comment by Schrolli91** [comment]
Würdest du das auch gleich machen? Wäre super...!

**Comment by flothi** [comment]
Gib mir bis heute abend Zeit ;-)

**Comment by Schrolli91** [comment]
:-D freilich, mach wanns dir passt - meinte damit nur, ob du dich der Sache annehmen würdest...
Dann close ich das hier mal - ist ja jetzt quasi in Bearbeitung - und vor allem nur ne Kleinigkeit

**Comment by flothi** [comment]
Ich muss das leider nochmal aufmachen - zumindest bei mir wird kein Kalibrierungstool mit installiert; ich würde dann auf die Anleitung referenzieren. Die Alternative wäre, es wirklich noch in den Installer zu packen.

**Comment by Schrolli91** [comment]
Hab das gerade überprüft... Tatsächlich
Das wird separat entwickelt, dachte das gehört zum RTL-SDR Paket...

https://github.com/steve-m/kalibrate-rtl

**Comment by flothi** [comment]
Also Version 2.2? Dann würde ich das im Develop mal einbasteln

**Comment by hhansen06** [comment]
Rtl_test -p paar minuten laufen lassen. Drauf achten das der stick warm ist.

Am 24.11.2016 22:07 schrieb "Florian" <notifications@github.com>:

**Comment by flothi** [comment]
Paar Minuten ist für den D.A.U. wahrscheinlich schon zu viel ;-) Automatisiert wäre ja ein Traum (*schwelg*träum*)

**Comment by hhansen06** [comment]
rtl_test ist nicht so exakt wie rtl-kaliber. Da es nur zwei takte
gegeneinander laufen lässt. D.h. hier wird nur der drift aus dem quarz
berücksichtigt nicht aus der A/D komponente. Das macht kal deutlich besser
da es gegen bekannte frequenzen abgleicht.

Am 24.11.2016 22:47 schrieb "Florian" <notifications@github.com>:

**Comment by Schrolli91** [comment]
Evtl würde es schon reichen eine saubere und verständliche Anleitung für rtl-kal aufzusetzen? Irgendwas müssen die User schließlich auch noch selbst machen :-D

**Comment by flothi** [comment]
Du meinst wie unter https://github.com/Schrolli91/BOSWatch/wiki/de:Installation mit Link beschrieben? Klar könnte man das noch selber umschreiben mit Screenshots etc, aber grundsätzlich ist das in der verlinkten Seite gut beschrieben.

**Comment by Schrolli91** [comment]
Oh das hab ich übersehen - stimmt die Anleitung ist wirklich ausreichen !
