### ISSUE TITLE
BOSWatch & 3rd Party neu installieren

### ISSUE THREAD

**Issue by OmarInkognito** [Schrolli91/BOSWatch#177]
Hallo,

nachdem die neue Version raus ist möchte ich BOSWatch und die 3rd Parties (mutlimon-ng...) neu installieren.
Wie bekomme ich eine saubere DEinstallation und danach eine saubere Installation hin?

Liebe Grüße!

**Comment by flothi** [comment]
BOSWatch installiert sich im klassischen Sinne nicht, ein Löschen des Ordners, in dem das Skript wohnt, reicht aus.
Bei multimon und rtl_fm bin ich derzeit überfragt, aber ich bin mir unschlüssig, dass da in letzter Zeit so viel passiert ist (vgl. #171 ) - eine Deinstallationsroutine ist aktuell nicht vorgesehen (todo?)

Wann hattest du BOSWatch denn das erste Mal installiert?

**Comment by hhansen06** [comment]
da während des compilens die binarys von multimon und rtl_fm jeweils nach /usr/local/bin/ kopiert werden, sollte eine deinstallation nicht notwendig sein. 

Wenn du noch nicht geupdated hast, einfach das installscript laden und laufen lassen dann solltest du auf den sollte alles aktuell sein. Leider haben rtl_fm und multimon-ng keine ausgabe einer buildversion  so das man den erfolg eines updates prüfen kann.

Aber wie gesagt, boswatch beenden, gucken das kein rtl_fm und kein multimon-ng process mehr läuft, dann solltest du problemlos updaten können.

**Comment by OmarInkognito** [comment]
Danke, habe also einfach den Ordner gelöscht und es neu installiert.
Scheint so alles funktioniert zu haben. :)

**Comment by Schrolli91** [comment]
Würde sagen - closed ;-)
