### ISSUE TITLE
http-Requests allgemein

### ISSUE THREAD

**Issue by flothi** [Schrolli91/BOSWatch#179]
Servus,

beim Bearbeiten des Bugs #176 ist mir aufgefallen, dass die abgesetzten TCP-Requests (auch zB im json-socket) alle blockierend auf das System wirken; meinem Empfinden nach findet keine weitere Dekodierung/Verarbeitung durch das Skript statt, während versucht wird, die TCP-Verbindung aufzubauen. Evtl sollte das global ausgelagert werden.

VG

**Comment by Schrolli91** [comment]
in der config gibts eins "async" Flag... ist das gesetzt werden alle Plugins in eignen Threads gestartet...
Damit kann dieses Problem verhindert werden.

Das das starten der Threads aber auch etwas Zeit benötigt, ist das ganze Standard mäßig aus, und sollte nur zugeschalten werden, wenn viele, oder langsame Plugins genutzt werden.

**Comment by flothi** [comment]
Mir ist es halt nur beim Testen des httpRequests aufgefallen, als mein Webserver noch nicht am laufen war - ok, dann gilt es abzuwägen was "wichtiger" ist.
