### ISSUE TITLE
Nach Update auf neuen RC /dev -d Fehler

### ISSUE THREAD

**Issue by OmarInkognito** [Schrolli91/BOSWatch#180]
Moin, habe gerade den neuen /dev RC installiert, allerdings konnte ich per "altem" Service BOSWatch nicht starten.
Also probierte ich es per Konsole:
"root@pi:~# python /BOSWatch/boswatch.py -f 123.456M -d 0 -a POC1200 -e 17 -s 52 -u -q"

Aber es kommt nicht zum altbekannten BOSWatch Logo, bzw. zu Dekodierung.
Es passiert einfach nichts mehr. :(

Wenn ich unter rtl_test schaue:
root@pi:~# rtl_test
Found 1 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 00000001

Using device 0: Generic RTL2832U OEM
Found Rafael Micro R820T tuner

Ist doch alles richtig, oder bin ich blöd?

**Comment by Schrolli91** [comment]
-q `Shows no information. Only logfiles`

Normalerweise wird bei -q GAR NICHTS angezeigt, lass es probehalber mal weg

**Comment by OmarInkognito** [comment]
-q funktioniert, nur leider werden keine Logfiles, bzw. der Ordner mit den Logs, erzeugt.
Woran kann das nun wieder liegen?

Rechte sind:
/BOSWatch = 0755
/boswatch.py = 077
/etc/init.d/boswatch.sh = 0755

edit: Läuft aber trotzdem! Danke!!

**Comment by Schrolli91** [comment]
-u erzeugt die Logfiles an einem anderen Ort...
`Use '/var/log/boswatch' for logfiles instead of subdir 'log' in BOSWatch directory`

evtl mal mit -v starten, dann siehst du alle Meldungen, evtl tritt iein Fehler auf?

**Comment by OmarInkognito** [comment]
Ich sage mal wieder danke! :)
Keine Ahnung warum es erst immer alles läuft und dann doch nicht mehr. :D

**Comment by Schrolli91** [comment]
Naja, wenn du die ganzen Flags setzt :-D
