### ISSUE TITLE
Verschieden Empfänger based on regex

### ISSUE THREAD

**Issue by thejockel** [Schrolli91/BOSWatch#181]
Hallo,
ist es möglich die Regex so zu erweitern, dass es für ein Plugin verscheiden Configs geben kann.

Hier ein Beispiel für Sms77:

default:
[Sms77] 
user = user1 
password =password1
to = 123456789
from = BOSWatch
type = quality

ZVEI A:
to = 987654321

ZVEI B:
to = 56789123

Gruß
Jockel

**Comment by fwmarcel** [comment]
Du könntest das Plugin für dich selber verändern, dass du im Plugin selber noch den regex Filter anwendest

**Comment by Cryjack** [comment]
Ich würde das auch eher über eine Art Adressbuch/Matching im Plugin selbst lösen. Auch ein CSV Mapping wäre denkbar.

So ala,
IF zvei = 123456 then to = 123456789
IF zvei = 654321 then to = 987654321

Im Aufruf dann das to weg lassen und die ZVEI nochmal vorher abgleichen.
