### ISSUE TITLE
Pushover

### ISSUE THREAD

**Issue by OmarInkognito** [Schrolli91/BOSWatch#184]
Hallo,

ich denke das ist meine vorerst letzte Frage:
Ich nutze das Plugin Pushover und lasse mir bestimmte RICs pushen.
Da wir Verschlüsselte Alarme nutzen, bringt es mir nichts, dass der Alarmtext mit übertragen wird.
Kann ich diesen unterbinden und quasi nur RIC / description übermitteln lassen?

Danke und liebe Grüße!

**Comment by Schrolli91** [comment]
am einfachsten wäre es, du fummelst einfach lokal bei dir den Alarmtext im Plugin direkt raus

**Comment by OmarInkognito** [comment]
Danke Dir!
Dazu fehlt mir leider das programmiertechnische Fachwissen. :/
Gibt es hier wen, der mir die entsprechenden Zeilen aus den betreffenden Datein nennen kann?

Ich wäre demjenigen zutiefst verbunden!
Vielen Dank! :)

**Comment by Cryjack** [comment]
pushover.py
Zeile 84 auskommentieren, also einfach ein # an den Anfang der Zeile. Das war's dann schon.

**Comment by OmarInkognito** [comment]
Mein Held! ♥ :D
Dankeee!
