### ISSUE TITLE
Device als default-Parameter setzen

### ISSUE THREAD

**Issue by flothi** [Schrolli91/BOSWatch#188]
Macht es Sinn, den Parameter -d per default auf 0 zu setzen? Meiner Meinung nach ist der Betrieb mit mehreren Sticks eher die Ausnahme, sodass nichts dagegen spricht. Natürlich ist der Parameter übersteuerbar.

**Comment by Schrolli91** [comment]
Früher war das auch mal so? Keine Ahnung wo das verloren gegangen ist...

**Comment by flothi** [comment]
Im develop-branch mit #190 abgearbeitet
