### ISSUE TITLE
Plugin für Radio Operator

### ISSUE THREAD

**Issue by Dtrieb** [Schrolli91/BOSWatch#192]
Schön wäre eine Schnittstelle zum Radio Operator.
https://radio-operator.de/

**Comment by flothi** [comment]
Das sieht so aus als sei das Programm für die Auswertung von Audio-Signalen vorgesehen; also eher ein "Konkurrenzprodukt" zu BOSWatch...

**Comment by flothi** [comment]
Ich muss mich korrigieren; Radio Operator kann zB monitord, Crusader oder FMS32 als Quelle nehmen. Also müsste ein entsprechendes plugin ggf. reverse-engineerd werden (für monitord anhand von http://www.monitord.de/download/monitor-protokoll-03.pdf )

**Comment by Smith-fms** [comment]
Ich irre mich vielleicht aber das FirEmergency Plugin dürfte schon funktionieren. Einfach gegen RO IP und Port einstellen. 
Kann das jemand mit RO mal testen?

**Comment by flothi** [comment]
Ich habe es mit der "Express"-Version mal probiert, allerdings bis dato noch nicht zum laufen gebracht...
