### ISSUE TITLE
Pushover Message

### ISSUE THREAD

**Issue by Doxoh** [Schrolli91/BOSWatch#194]
Hallo zusammen,

mir ist aufgefallen das bei IOS die Nachrichten Falsch angezeigt werden. Nach meiner nachfrage bei Pushover selber soll "newline character" anstatt <br> verwendet werden. Ist das irgendwie möglich?

VG
Till

**Comment by Cryjack** [comment]
Das ist seltsam, denn bei mir im iOS wird das korrekt angezeigt. Letztlich ist "newline character" auch keine html syntax, sondern das verwendete BR 


Am 04.01.17 um 19:22 schrieb Doxoh

**Comment by Doxoh** [comment]
In der App selber wird es bei mir richtig angezeigt. Aber im Sperrbildschirm nicht...

**Comment by Soundworld** [comment]
Ich habe mir in diesem Zuge mal das Thema Pushover angeschaut (ist ja der Hammer! Das ist eine geniale Erweiterung für meine Anwendung!) Also bei mir werden alle Nachrichten korrekt angezeigt. Auch im Sperrbildschirm des IPhones und auf der Apple Watch. Einstellungen bei BOSWatch und Pushover sind die Standardeinstellungen.

**Comment by Doxoh** [comment]
so sieht meine Pushnachricht aus : http://puu.sh/tdgOj/7479022d5b.jpg

und gesendet wurde es so : `<b>Message 1<b><br>Message2`

**Comment by Cryjack** [comment]
@doxoh
Du hast recht, ich kann mich erinnern, das Problem auch gehabt zu haben. Aktuelles iOS und App sind aktualisiert? Ich hatte vorher das iPhone4 (nur bis iOS 9), mit dem 6er und dem aktuellsten iOS war das Problem nicht mehr da. 

Problem ist, wenn du es von BR (also html codierter zeilenumbruch, wie es technisch in dem Kontext auch richtig wäre) auf newline (windows codiert) umstellst, dann dreht sich das Problem genau einmal um. Dann ist im Sperrbildschirm alles korrekt, aber in der App nicht mehr. 


@soundworld
Ich nutze Pushover nun seit einigen Jahren für die Zusatzalarmierung. Vorher auch aus Bosmon und FMSpro. Extrem universell und vielseitig. 
Selbst im Job konnte ich es nutzen um Benachrichtigungen von Serversystemen im Netzwerk sofort zu erhalten. Extrem praktisch. 


Am 06.01.17 um 18:49 schrieb Doxoh

**Comment by Doxoh** [comment]
Hallo Zusammen, ich habe mir einmal ein Script gemacht und %0A anstatt <br> verwendet und nun sieht es gut in der App und im Lockscreen aus. Bitte Prüft das mal

**Comment by flothi** [comment]
@Doxoh Magst du deinen Fix posten?

**Comment by Doxoh** [comment]
`<b>%title%</b>%0A%message%`

**Comment by Doxoh** [comment]
Hoffe das hilft so :)

**Comment by flothi** [comment]
Ich werde es mal in den develop-Zweig einbauen und dann anschauen - danke für den Fix!

**Comment by flothi** [comment]
Also, 0x0A entspricht ja dem von Pushover propagierten `\n` - zum Testen habe ich lediglich ein Android-Handy da - da ist im Sperrbildschirm / Taskbenachrichtigung auch kein Umbruch zu sehen, in der App selber passt es jedoch.

**Comment by Schrolli91** [comment]
Ist das Problem nun eigentlich soweit geklärt?

**Comment by flothi** [comment]
Ich würde sagen ja, für das Verhalten der App auf verschiedenen OS in diversen Ständen können wir schlecht was. Laut Doku ist als newline das `\n` resp. das `0x0A` vorgesehen, so wie wir es umsetzen.

**Comment by Schrolli91** [comment]
Also wenn wir konform deren Doku laufen - dann closen?
Da haben wir, wie du schon sagst, ja absolut keinen Einfluss drauf...

**Comment by flothi** [comment]
Als Quelle: 
https://pushover.net/faq#technical-newline

Daher plädiere ich ebenfalls für ein close (wenn ich die Quelle nicht komplett falsch gelesen habe)

**Comment by Schrolli91** [comment]
Die Quelle ist relativ eindeutig - close
Notfalls kann man das Issue ja wiederbeleben...
