### ISSUE TITLE
Email-Fehler im Master-Branch

### ISSUE THREAD

**Issue by Thiwol** [Schrolli91/BOSWatch#197]
Hallo, 

im Master-Branch sind in der eMail.py zwei Fehler. 
Es wurde vergessen, den Variablennamen "globals" in "globalVars" zu ändern.

**Comment by flothi** [comment]
Ist mit pull-request erledigt.

**Comment by Schrolli91** [comment]
Dürfte ja dann damit behoben sein ...

**Comment by Thiwol** [comment]
Jup, hatte noch einen anderen Fehler.
Ich wollte die Email mit SSL versenden, was zuerst nicht geklappt hat, da immer die starttls-Funktion aufgerufen worden ist. 
Habe die Zeile einfach auskommentiert, kann es sein, dass die IF-Abfrage nicht funktioniert?

**Comment by flothi** [comment]
Das Problem hab ich auch, da einer meiner Server offensichtlich auf dem SSL-Ohr taub ist
Ich hatte nur wenig Zeit, meinen Fix zu testen. Ggf müsste die Exception einfach nur gefangen werden.

Mal sehen wie mein Abend läuft ;-)

**Comment by flothi** [comment]
Ich habe den Fix in den Master gepullt ( #200 )- zum Einen ist das Plugin mMn recht wichtig, zum Anderen war die Abfrage in der Tat fehlerhaft (get anstatt getboolean).
Weiterhin habe ich das SMTP_SSL mit einem weiteren try-except-Block versehen; einige meiner Mailserver sprechen (warum auch immer) nicht mit der SSL-Bib von python, obwohl sie es eigentlich können sollten.

**Comment by flothi** [comment]
@Thiwol 
Ist der Fehler beseitigt?

**Comment by Thiwol** [comment]
@flothi 
Jap, es funktioniert.

**Comment by flothi** [comment]
Danke fürs Feedback!

**Comment by chbally** [comment]
Sorry - ich glaube der Fehler existiert in abgewandelter Form noch.
Ich kann mit meinem Mailserver nicht per SSL kommunizieren. 
Ich habe trotz massiver versuche keine Mail mit SMTP über Port 25 ohne TLS zustellen können. Gleiches berichtet ein Kollege.
Per SSMTP mit einem anderen Server, den ich nicht eigentlich verwenden möchte, geht es einwandfrei.

**Comment by flothi** [comment]
Welchen Server verwendest du denn? 
Magst du bitte mal in deiner plugins/eMail/eMail.py in Zeile 111 den Wert für Debug auf 1 schalten und das Ergebnis mitteilen. (und boswatch mit der Option -v starten)

**Comment by chbally** [comment]
Das kann ich morgen gerne mal machen.
Das ist ein Standardmailserver eines Providers, über den ich normal über SMTP Port 25 kommuniziere.
Die config.ini sieht so aus:
```
[eMail]
# SMTP-Server
smtp_server = mail.meine-domain.de
# Port of SMTP-Server (default:
smtp_port = 25
# use tls for connection (0|1)
tls = 0
# Use this, when SMTP-Server has restricted access
user = alarm@meine-domain.de
password = eingeheimesPasswort

# Parameters for Alarm-Msg:
# "to" could be more than one address, comma separated
from = alarm@meine-domain.de
to   = user@irgendwo.de

# Priority of the eMail:
# normal|urgent|non-urgent
priority = urgent
```
Mit einem anderen Skript funktioniert das mit den Daten vom gleichen Raspberry.

**Comment by chbally** [comment]
Fehlalarm:
Ich habe meine komplette config.ini umgebaut und nun geht es. 
Sorry dafür!!!

Kleine Frage am Rande:
Kann man beim Feld `from = alarm@meine-domain.de` noch einen Klarnamen als Absender wie ALARMSYSTEM FF XY einfügen

By the way: Tolle Arbeit!!

**Comment by flothi** [comment]
Verrätst du auch was du umgebaut hast? ;-)
Die Absenderkennung wäre interessant, guter Hinweis (und danke für die Blumen)

**Comment by chbally** [comment]
Umgebaut ist übertrieben...
Ich habe die E-Mail Kontodaten getauscht, den Mailserver und den Port auf 25 wieder gewechselt. 
Ich weiß nicht wieviele Male ich diese Konfiguration erfolglos durchprobiert habe. :-( :-))

**Comment by Schrolli91** [comment]
Also soweit kein Problem, sondern ein "Unfall" ? :-P

**Comment by flothi** [comment]
Seh ich ähnlich, der Hinweis mit dem Absender finde ich jedoch verfolgenswert

**Comment by Schrolli91** [comment]
Dann sollte man dazu aber besser ein eigenes Issue aufmachen.
@chbally it's your turn :-P
