### ISSUE TITLE
Mehrere Filter Ranges für verschiedene Devices?

### ISSUE THREAD

**Issue by Soundworld** [Schrolli91/BOSWatch#201]
Hallo!

Ich bin leider in Python etc nicht so bewandert, aber ist es möglich, wenn man mehrere Devices angeschlossen hat, in der config.ini zu definieren, dass Device 0 eine Filter Range von bspws. 0000000 bis 5999999 hat und das Device 1 eine Filter Range von 6000000 bis 9999999 ?

Ich bin mir nicht sicher, ob man in der config.ini das Device als Variable hat, aber ich könnte irgendwas in der folgenden Art vorstellen:

if device = 0:

   filter_range_start = 0000000
   filter_range_end =   5999999

elif device = 1:
   filter_range_start = 6000000
   filter_range_end =   9999999

else:
   filter_range_start = 0000000
   filter_range_end =   9999999

Meint ihr das würde grundsätzlich funktionieren? Wenn ja, wie müsste man denn die Device-Variable ansprechen?

Viele Grüße,

Thilo

**Comment by flothi** [comment]
Laufen die Devices auf der gleichen Frequenz? Ansonsten wäre es evtl ne Idee, die Config pro Device zu regeln (config.ini als zentrale Datei, config.ini.0, config.ini.1, ... für die Devices)

**Comment by Soundworld** [comment]
Die Devices laufen auf unterschiedlichen Frequenzen. Das mit den unterschiedlichen config.ini wäre natürlich noch besser. Dann könnte man auch beispielsweise auf Device 1 POCSAG auf 2m auswerten und auf Device 0 dann FMS auf 4m und müsste nicht die jeweils nicht benötigten CSV-Dateien mitladen lassen (also bei 2m nur die POCSAG-CSV und bei 4m nur die FMS-CSV). Das wäre genial!

**Comment by Schrolli91** [comment]
Per RegEx Filter kann doch die Frequenz mit verarbeitet werden. So kann man abhängig von der Frequenz das ganze auseinander klauben.

https://github.com/Schrolli91/BOSWatch#filtering-functions-regex

**Comment by Smith-fms** [comment]
Warum so kompliziert? :-)
Ich habe 2 DBs welche ich mit 2 Devices befülle. 
Also einfach den BOSWatch Ordner kopieren und fertig. Jedes Device hat hierdurch seine eigene ini.
Entsprechend den Aufruf in der rc.local ändern und fertig. 

Läuft!

**Comment by Schrolli91** [comment]
Naja sooo kompliziert wäre RegEX nun ja auch nicht, da man die einzelnen Empfangs Frequenzen ja direkt auseinander pflücken kann.
2 Instanzen sind aber natürlich für eine schnelle und einfache Lösung auch machbar.

@Soundworld wurde deine Frage damit beantwortet?

**Comment by Soundworld** [comment]
@Schrolli91 Ja vielen Dank! Das mit den RegEx-Filtern auf die Frequenzen gesehen funktioniert super!
