### ISSUE TITLE
Filtereinstellungen in der config.ini

### ISSUE THREAD

**Issue by dani9304** [Schrolli91/BOSWatch#203]
Hallo Zusammen, 

erst einmal ein riesen Lob an den Entwickler und alle die an diesem Projekt mitwirken. Auf so etwas haben viele lange gewartet. 

Ich habe nun auch einen Raspberry Pi mit boswatch im Einsatz, der die POCSAG-Telegramme dann an den BOSMon-Server weiterreicht. 

Nun ist es im vorhandenen Alarmierungsnetz so, dass oftmals viele verschiedene RICS mit der selben Nachricht alarmiert werden bzw. auch mehrmals alarmiert werden mit dem selben Text. 

Ich habe bereits etwas mit den Filtereinstellungen experementiert, war aber leider noch nicht wirklich erfolgreich. Die Telegramme werden nach wie vor, teils zu dutzend in den BOSMon Server gefüttert und es geht jeglieche Übersicht verloren. 
Mein Ziel wäre, dass ein Telegramm auch nur einmal angezeigt wird. Also eine Filterung über den msg-Text. 

Meine Filtereinstellungen sehen aktuell so aus: 

doubleFilter_ignore_entries = 25
doubleFilter_ignore_time = 300
doubleFilter_check_msg = 1

Sonst habe ich nichts außer den BOSMon-Pluginsettings verändert. 

Kann mir jemand einen Tipp geben oder wo könnte der Fehöer liegen?

Vielen vielen Dank schonmal.

Grüße

**Comment by Schrolli91** [comment]
Also eigentlich sollte bei deinen Einstellungen alles rausfliegen, was wirklich exakt den selben Text hat. Wundert mich ehrlich gesagt ein bisschen...

Das Logfile dazu wäre mal interessant...

**Comment by Schrolli91** [comment]
@dani9304 hat sich dein Problem inzwischen erledigt? 
Ohne Logfile kann ich dazu leider nicht viel sagen...

**Comment by Schrolli91** [comment]
@dani9304 da jetzt lange nichts kam, nehme ich mir die Freiheit, zu closen.

Falls das Problem immer noch besteht, mach gerne ein Neues Issue auf, versuch das Problem genau zu beschreiben und ein Logfile mit zu posten
