### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by flothi** [Schrolli91/BOSWatch#204]
Wie wäre es, wenn die in GitHub vorhandene Funktion "Projects" für die Darstellung einer Roadmap genutzt wird (ich habs mal ganz rudimentär in meinem Fork gemacht: https://github.com/flothi/BOSWatch/projects/1 ) - das würde 
1. Die Übersichtlichkeit steigern
2. Die Prioritäten für die Entwicklung festlegen und
3. Zu erwartende Funktionen aufzeigen

**Comment by Schrolli91** [comment]
@flothi 
Da du momentan hier ja extrem aktiv bist, und deine Beiträge aus meiner Sicht erste Sahne sind, hab ich beschlossen, dich zum Collaborator zu machen.
Damit hast du jetzt vollen Zugriff auf das Repo - Tob' dich aus ;-)

**Würde dir gerne hiermit auch nochmal im Namen aller Danke sagen, dass du so viel Zeit und Arbeit in das Projekt investierst.** 

Die Idee mit der Roadmap finde ich super. Du kannst das gerne direkt hier im Repo integrieren. Ich selbst bin zeitlich momentan leider zu eingespannt um aktiv mit zu arbeiten.

**Comment by flothi** [comment]
@Schrolli91 Danke für die Blumen, freut mich wenn ich helfen kann ;-)

Ich werde mich beizeiten mal dransetzen und mir weiter Ideen einfallen lassen ;-)

**Comment by Schrolli91** [comment]
Was mir gerade noch auffällt - Die Roadmap an sich ist dem hier ja recht ähnlich
https://github.com/Schrolli91/BOSWatch/milestones

Wäre unter Umständen sinnvoll, diese beiden Informationsquellen zusammenzuführen, und dann eine von beiden zu eliminieren oder?

**Comment by flothi** [comment]
@Schrolli91
Natürlich, das wäre kurzfristig mein Ziel - ich sortiere zur Zeit noch und ziehe das dann nach und nach gerade

**Comment by Schrolli91** [comment]
Gut, dann hab ich nix gesagt - Weitermachen! ;-)

**Comment by flothi** [comment]
Jawohl, weitermachen ;-)
