### ISSUE TITLE
Web Frontend zum Konfigurieren

### ISSUE THREAD

**Issue by carrier92** [Schrolli91/BOSWatch#205]
Ich hab mal das Ganze als PHP umgesetzt, noch sehr einfach gehalten aber es funktioniert.
Im Moment können keine neuen Plugins (Abschnitte) über dieses Frontend eingefügt werden, dies muss vorher manuell in der ini gemacht werden.
Die config.ini wird immer komplett überschrieben (vorher ein Backup machen)
In der config_description.txt stehen die Beschreibungen für die einzelnen config.ini Abschnitte und Parameter.
Ich hab das Ganze auf einem Raspi mit Apache und PHP laufen, parallel zu BOSWatch.
Die BOSWatchConfigEditor.php muss in das http Verzeichnis des Apache kopiert werden.
In dieser Datei stehen auch die Pfade für die config.ini und config_description.txt
Im Kopf steht auch noch ein Hinweis auf die Schreibrechte für die config.ini
[BOSWatchConfigEditor.zip](https://github.com/Schrolli91/BOSWatch/files/735761/BOSWatchConfigEditor.zip)

Gruß
carrier92

**Comment by flothi** [comment]
Duplicate #163 
--
Ich würde das im Gesamtpaket zum kompletten Web-Frontend sehen wollen; das könnte also durchaus ein Part werden, wobei ich den Apache schon fast bissl zu viel halte, ein nginx dürfte da auch langen, aber das ist Geschmackssache.

**Comment by carrier92** [comment]
Ja gern, da hab ich das auch schon mal auf mein Frontend hingewiesen aber es kam keine Rückmeldung.
Des halb dachte ich mach mal ein eigenes auf. Du kannst gerne dises hier schließen und wir machen mit dem #163 weiter.
Der apache ist bestimmt zu viel, im prinzip läuft das ja auf jedem Web Server Dienst

**Comment by Schrolli91** [comment]
da wie schon geschrieben, das Thema an sich das selbe ist wie #163 schließe ich der Übersicht halber hier
