### ISSUE TITLE
Telegram: ZVEI einbauen 

### ISSUE THREAD

**Issue by flothi** [Schrolli91/BOSWatch#206]
Aus #106
Im Plug-in telegram die Funktion für ZVEI realisieren

**Comment by PeterLaemmle** [comment]
@hobo2k, schau dir das mal an: [Telegram.py](https://github.com/PeterLaemmle/BOSWatch/blob/master/plugins/Telegram/Telegram.py)
Leider kann ich das zur Zeit nicht selbst testen.

**Comment by Schrolli91** [comment]
#208 
FMS und ZVEI Support ist nun dank @PeterLaemmle integriert - closed
