### ISSUE TITLE
Absenderkennung im eMail Plugin

### ISSUE THREAD

**Issue by chbally** [Schrolli91/BOSWatch#209]
Das eMail Plugin kann zur Zeit als Absender nur die Mailadresse verwenden.
Schön wäre, wenn auch eine Absenderkennung z.B 

 

> Alarmsystem FF XY <alarm@ff-xy.de>

 versendet werden könnte. 
Die eckigen Klammern um die Mailadresse fehlen, weil github die herausgenommen hat

**Comment by PeterLaemmle** [comment]
Es sollte ausreichen, den Absender in der config.ini wie folgt anzugeben:
`from = BOSWatch eMail-Plugin <me@domain.com>`

**Comment by flothi** [comment]
@PeterLaemmle 
Vollkommen richtig, danke für den Hinweis

@chbally 
In deinem Fall wäre es dann
`Alarmsysten FF XY <alarm@ff-xy.de>`
Wichtig sind die spitzen Klammern um die Adresse.

**Comment by Schrolli91** [comment]
Falls sich jemand dem Mail Plugin im Wiki annehmen will, sollte das dann mit erwähnt werden ;-)

**Comment by flothi** [comment]
Ist in Arbeit ;-)

**Comment by flothi** [comment]
Die Doku wird aktuell nachgezogen, das Feature ist bereits so nutzbar, daher hier geschlossen.

**Comment by chbally** [comment]
Sehr schön!!
Funktioniert auch für den Adressaten - sieht auch beim Empfänger netter aus.

Ich es reicht im ersten Schritt zur Doku eine Zeile 213 in die config.* Datei einzufügen:

```
# "from" only one address. Example: from = Sendername<sender@domain.com>
from =
# "to" could be more than one address, comma separated. Example: to = receiver1<receiver1@domain1.com>,receiver2<receiver2@domain2.com>
to =

```
Ich glaube es gibt im Moment wichtigeres zu dokumentieren ;-)

**Comment by flothi** [comment]
Guter Hinweis, danke - im Wiki hab ichs bereits drin ;-)
