### ISSUE TITLE
Keine Dekodierung möglich? -> Hardware!

### ISSUE THREAD

**Issue by Smith-fms** [Schrolli91/BOSWatch#210]
Hallo Zusammen,

ich habe noch folgende Infos, welche ich hier noch hinterlegen mag:

Sollte trotz einer Kalibrierung mit dem Programm kal keine Dekodierung möglich sein, kann es auch einfach einem zu schlecht abgestimmten SDR-Stick liegen. 
Ich habe 3 einfache, meist für 8€ per Ebay bezogene, Sticks aus China hier liegen. Bei allen Sticks kam eine negative PPM Correction raus, mit allen war keine Dekodierung möglich. 

Entweder wird der Wert nicht richtig übergeben (kann auch ein Issue sein, denn ich denke auch wenn der Wert beim Start von BosWatch als -31 angezeigt wird, muss dieser nicht unbedingt auch bei rtl_fm angekommen sein) oder was auch immer. 

Ich kann die 30€ für einen NooElec Stick nur empfehlen. Der Threshold ist vielfach niedriger, die Error-Correction liegt bei 1 (!) ppm, der Betrieb funktioniert sofort. Dies mag auch an dem Aluminium Gehäuse liegen. Für 32€ bei Amazon zu finden inkl. 3 Antennen mit direktem SMA Anschluss. 
Das schöne, es passen sofort 2 Sticks an den RPi 2 (3) dran ohne am Gehäuse zu tunen. :-)

Vielleicht schreibe ich auch die Tage nochmal ein Wiki.

Und kurz nochmal an alle, welche hier mitwirken:
Ich finde super, was aus meinen paar Zeilen damals im Forum geworden ist. Ich zolle euch für diese Arbeit RESPEKT! Danke und macht weiter so!

**Comment by Schrolli91** [comment]
@Smith-fms Schön von dir zu hören :-) Danke für die Blumen, aber vor allem Danke für deine paar Zeilen Code ;-) Die erst hab mich dazu gebracht das ganze weiter aufzubohren und haben letztendlich dank der Hilfe vieler anderer zu einem Projekt in diesem Ausmaß geführt :+1: 

Ein Eintrag im Wiki wäre eine tolle Sache...

**Comment by Schrolli91** [comment]
gehört ja irgendwie zu #146 
Daher - closed ;-)
