### ISSUE TITLE
Release 2.2

### ISSUE THREAD

**Issue by Schrolli91** [Schrolli91/BOSWatch#212]
Ich würde gerne ein Release 2.2 anstreben, da im aktuellen Master ja noch eine Menge Bugs und Probleme vorhanden waren, die in den letzten Wochen Großteils behoben wurden.

Um diesen nun mal auf einen einigermaßen stabilen Stand zu pushen habe ich alle unnötigen Erweiterungen auf die 2.3 verschoben.

Daher ist nun aktuell aller höchste Priorität die letzten größeren Probleme zu fixen.
#194 #187 und #101

Damit dürfte der master dan zumindest halbwegs gefixt sein und stabil laufen, sodass ein Produktiver Einsatz ohne Probleme möglich sein dürfte

**Comment by flothi** [comment]
Guter Plan, mein Vorschlag :
Fixen der 3 Issues
Danach 2.2 RC1 für eine Woche zum Testen rausbringen 
Wenn RC1 ohne Bugs, direkt zu 2.2; mit Bugs einen RC2 und den dann wieder eine Woche testen...

**Comment by thejockel** [comment]
Hört sich gut an.
Aber wie erkennen wir den, dass es noch Bugs gibt bzw. das alles getestet wurde?

Ich würde dafür eine Testmatrix oder so was empfehlen.
Damit auch alle Teile getestet werden.

| Version | installation ok| pocsag Empfang | zwei Empfang | fms Empfang | mySQL Plugin | ...| 
|---------|--------|-------------|---------------------------------------|-----------------|---------------|---|
| 2.2 RC1 | | | | | | | |

**Comment by flothi** [comment]
Ich würde evtl sogar einen Schritt weitergehen und die Aufgaben ein oder zwei "Aktiven" zuweisen

**Comment by thejockel** [comment]
Am besten wäre natürlich, wenn wir die Daten durch ein CI Tool laufen lassen würden.

Können für sowas Simulations-Daten an BosWatch senden?

**Comment by flothi** [comment]
Starte Boswatch doch einfach mit -t, dann wird rtl_fm und multimon-ng nicht gestartet und das File testdata.txt als Input genommen

**Comment by Schrolli91** [comment]
richtig... mit -t gibt es Testdaten um eben alle möglichen wichtigen Fälle zu testen..
siehe auch #45

**Comment by flothi** [comment]
Wir sollten die `testdata.txt` ggf dann um die in #187 genannten Fehler ergänzen und als Testgrundlage nutzen

**Comment by flothi** [comment]
Ich habs mal unter https://github.com/Schrolli91/BOSWatch/projects/4 graphisch dargestellt

**Comment by Schrolli91** [comment]
ja, gerne ergänzen ...

**Comment by thejockel** [comment]
Das ist doch super!
Dann baue ich nächste Wochte dafür mal ein paar Ci Tests.

**Comment by Schrolli91** [comment]
Gibts da nicht schon fertige Dienste für CI? Bspw. Travis-CI... So wie wir jetzt schon Codacy zur Statischen Code Analyse nutzen.
Kenn mich was das angeht leider zu wenig aus, aber evtl will mich zu dem Thema CI mal jemand schnell bisschen auf-schlauen :-P

**Comment by dabenzel** [comment]
Moin!
Die bekanntesten Dienste sind glaub ich drone und travisci..

Die meisten Anbieter haben auch wir codacy ein preismodell, welches es
opensource Software kostenlos erlaubt dir Dienste zu nutzen.

Am 18.02.2017 11:06 schrieb "Bastian Schroll" <notifications@github.com>:

**Comment by thejockel** [comment]
Moin,
ich habe bei mir im Fork travis.ci aktiviert. 
Und eine base Test, mysql und http Plugin gebaut.

Für die anderen Plugins werden ja Handnummern oder ähnlich benötigt.
Daher können wir diese schlecht im CI Testen.
  
[travis example build](https://travis-ci.org/thejockel/BOSWatch/builds/203388693)

#222 hier der pull dazu.

Dazu muss Travis-ci muss noch für das Repo aktiviert wenden.

**Comment by Schrolli91** [comment]
Wo wir grade beim Thema automatisierte Tests sind. Was genau wird eigentlich bei einem `code coverage` getestet? Bietet so ein Test uns auch einen weiteren Nutzen?

**Comment by dabenzel** [comment]
Code Coverage schaut nach wie viel Prozent deines Programmcodes durch
automatisierte Tests abgedeckt ist. Also, dass jede Funktion auch einen
Test hat, der sie testet.

Am 21.02.2017 12:33 schrieb "Bastian Schroll" <notifications@github.com>:

**Comment by Schrolli91** [comment]
Würde uns das einen Nutzen bringen? Um die Testdaten und Test-Routinen evtl besser anzupassen?

**Comment by dabenzel** [comment]
Wenn man für alles, was die Software macht auch einen Test schreibt, ja.
Denn es bewahrt einen vor einer falschen Implementation einer Funktion
(wenn man davon ausgeht, dass der Test korrekt geschrieben ist)...

Man muss sich nur die Mühe machen, diese Tests zu schreiben. Meist gibt es
da auch Frameworks für, die dies erleichtern.

Es gibt auch Vorgehensweisen, wo man bevor man ein Feature programmiert,
erst den Test schreibt und danach die Funktionalität. (Test-driven
Development)

Am 21.02.2017 12:47 schrieb "Bastian Schroll" <notifications@github.com>:

**Comment by Schrolli91** [comment]
Hab mal Travis noch eben angepasst, sodass beim build auch das install file des jeweiligen branches genutzt wird. Denn was bringt es, wenn er den Dev Branch mit dem Installer vom Master installieren will, durch größere Änderungen das ganze aber unmöglich funktionieren kann...

1b5993119ebf9a520c4f42b6b978e2be75818ef4

**Comment by Schrolli91** [comment]
Release wird heute für die V2.2 vollzogen ...
