### ISSUE TITLE
Funkscanner

### ISSUE THREAD

**Issue by mlupoo** [Schrolli91/BOSWatch#220]
Hallo zusammen,

gibt es eine Möglichkeit das "Signal" über einen Diskriminatorausgang von einem Funkscanner zu beziehen?

Viele Grüße und danke.

Michel

**Comment by Schrolli91** [comment]
Aktuell Nein - aber...
... theoretisch ja, müsste man eben statt rtl_fm direkt eine Audioquelle anzapfen

**Comment by mlupoo** [comment]
Magst du mir das ein bisschen für Dummies erklären?

Gibt es eine Möglichkeit dies in der aktuellen Version "einzubinden"?

**Comment by flothi** [comment]
Nicht ohne im Code einiges zu ändern - auf den ersten Blick müsste es mit dem Linux-Tool pulseaudio gehen, das kannst du multimon als Eingabequelle mitgeben.
Ich habs selber nicht getestet, dafür fehlt mir der Scanner ;-)

Weiterhin brauchst du eine USB (oder wie auch immer angebundene) Soundkarte für den Pi - das wäre schon fast ein eigenes Projekt

**Comment by mlupoo** [comment]
rtl_fm -M fm -f 137.325M -s 22050 -g 10 -l 250 | multimon-ng -t raw /dev/stdin

Diesen Befehl nur "umdrehen" weiß jemand wie ich die Ausgabe von rtl_fm simuliere? Wo und Wie wird das empfangene im Programm implementiert und verarbeitet? 

Grüße

**Comment by Schrolli91** [comment]
https://github.com/Schrolli91/BOSWatch/blob/master/boswatch.py#L338

Hier wird der stdin von multimon zugewiesen, hier müsste einfach nur ein stdout von zB pulseaudio o.Ä. drauf, wenn ich das Richtig sehe

**Comment by flothi** [comment]
Japp, so richtig - wenn wer ne Audio-In-Option am Pi hat kann er es ja evtl mal testen - als "Programm" dürfte pacat infrage kommen (sagt mir zumindest Tante google)

**Comment by Smith-fms** [comment]
Jedes Sound-Programm, welches in stdout schreiben kann, kann genutzt werden. 
Man könnte dies eventuell mit in die Config aufnehmen oder sogar in den Parameter Start.

Und an alle welche Pocsag dekorieren wollen, ohne SDR: ihr braucht einen Diskriminator- Ausgang. Dieser gibt alles ohne Filter aus um auch jeden Ton unverfälscht an das Programm zum dekodieren gibt. 
FMS und Zvei geht auch ohne. Hab früher sogar nen RE229 dafür umbauen können.... :-)

**Comment by Schrolli91** [comment]
Hat jetzt ja nix direkt mit BW zu tun - closed

**Comment by Hobo2k** [comment]
Als Hinweis, ich habe es hier quick und dirty eingebaut...

[https://github.com/Hobo2k/BOSWatch](https://github.com/Hobo2k/BOSWatch)

**Comment by Schrolli91** [comment]
@Hobo2k funktioniert das so mit dem Sound Eingang?
Dann könnte man das ganze wie @Smith-fms schon sagte, das ganze per Flag in der config direkt integrieren

**Comment by Hobo2k** [comment]
ja bei mir läuft es jetzt recht stabil seit ca 3 Monaten.

Evtl sollte man es schöner machen, als ich ;-)

**Comment by Schrolli91** [comment]
Wird in einem späteren Update auf jeden Fall in Erwägung gezogen - Schon mal vielen Dank für deine Versuche. Da hat man nun zumindest schon mal einen Ansatz.

Aber falls dich mal die Lust packt, das irgendwie zu implementieren mit Auswahl über die config, wird dich niemand aufhalten :-D

**Comment by flothi** [comment]
@Hobo2k Welche Hardware verwendest du denn?

**Comment by Hobo2k** [comment]
Ich habe eine 2€ Soundkarte mit einem PI-B 1 am laufen.
So eine: https://de.aliexpress.com/item/10pcs-lot-New-USB-2-0-Interface-5-1-Stereo-Audio-Sound-Card-Adaptor-for-PC/32716761185.html

**Comment by Schrolli91** [comment]
Für BW3 umgesetzt
https://github.com/BOSWatch/BW3-Core/pull/38
