### ISSUE TITLE
WIKI

### ISSUE THREAD

**Issue by Schrolli91** [Schrolli91/BOSWatch#221]
Inzwischen ist BOSWatch ja ein ziemlich "dicker Batzen" geworden ;-)
Jedoch wurde seit das Wiki besteht die Readme nicht mehr nachgeführt.
Im Wiki selbst stehen aber auch noch nicht all zu viele Infos.

Evtl. sollte man dann, wos jetzt Richtung 2.2 geht auch da etwas weiter arbeiten.
Hier mal ein paar Stichpunkte die in nächster Zeit evtl. mal aufgegriffen werden sollten.

1. - [ ] BOSWatch Beschreibung + grobe Funktionsliste
2. - [ ] Installations Anleitung an neuen Installer anpassen (falls nötig?)
3. - [ ] Dokumentation der config Parameter + Sinn/Nutzen/Fuktion (Nur BOSWatch eigene)
4. - [ ] Liste der aktuellen Plugins prüfen/erweitern
5. - [ ] Plugins dokumentieren (Funktion + config)

**Comment by flothi** [comment]
Super wäre es, wenn diejenigen, die die Plug-ins geschrieben haben, kurz ein paar Sätze loswerden könnten

**Comment by fwmarcel** [comment]
Ich würde mich der Aufgabe annehmen das Wiki und Readme zu überarbeiten. Dazu noch die Frage, in welcher Sprache das verfasst werden soll. Aktuell ist das ja hier alles teils Englisch Teils Deutsch...

**Comment by flothi** [comment]
@fwmarcel 
Bis dato handhaben wir es so: Wikitexte primär in Deutsch, Quelltext-Kommentare und Debug-Ausgaben in Englisch. 

Die Struktur im Wiki habe ich bereits so vorbereitet, dass wir durch das Präfix `en:` anstatt `de:` die Artikel ins Englische übernehmen können.

Ins Readme würde ich, aufgrund der Übersichtlichkeit, wenig bis keine Energie investieren. Die Wiki-Doku steht für den Moment schonmal gar nicht so übel dar.

**Comment by Schrolli91** [comment]
Ja im Wiki deutsch
Quelltext englisch

Naja die Plugin Dokumentation im Wiki wäre schon durchaus ein Punkt...

**Comment by flothi** [comment]
Das war ja meine Bitte, dass die Autoren Set jeweiligen Plug-ins äußern - verteilt die Arbeit etwas

**Comment by Schrolli91** [comment]
ja aber bevor's dann niemand macht - freiwillige vor :-D

**Comment by flothi** [comment]
Freiwillig? Hier werden Leute freiwillig ausgesucht ;-)

**Comment by KampfkeksMRZ** [comment]
Auch wenn ich noch nicht sooo tief drin bin - für Übersetzungen, v.a. im Code wäre ich zu haben...

**Comment by Schrolli91** [comment]
@KampfkeksMRZ der code ist Englisch dokumentiert und nach aktueller Planung soll er das auch erst mal bleiben

**Comment by Schrolli91** [comment]
@KampfkeksMRZ aber wenn du Lust am Übersetzen hast?
https://github.com/Schrolli91/BOSWatch/wiki/de:Plugin-entwickeln
Das müsste irgendwann auch mal im deutschen landen :-P

**Comment by KampfkeksMRZ** [comment]
@Schrolli91 Hab mich mal dran gegeben

[BOSWatch.docx](https://github.com/Schrolli91/BOSWatch/files/885090/BOSWatch.docx)

Wenn mal jemand gegenlesen mag?

**Comment by fwmarcel** [comment]
@Schrolli91  @KampfkeksMRZ sieht gut aus. Werde ich ins Wiki übernehmen.

**Comment by Schrolli91** [comment]
alles klar - super

**Comment by Schrolli91** [comment]
wiki sollten wir auch weiter ausbauen bei Gelegenheit... aber dafür wird kein eigenes Issue benötigt
