### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by Schrolli91** [Schrolli91/BOSWatch#223]
Dank @thejockel wird nun bei jedem Commit oder Pull Req. ein Build mittels Travis-CI angestoßen

siehe: https://travis-ci.org/Schrolli91/BOSWatch

Evtl bekommen wir es hin, uns was zu überlegen, auch für andere Plugins einen Test laufen zu lassen.
Aktuell wird nur das Hauptprogramm sowie MySQL und HTTP getestet...

**Comment by thejockel** [comment]
Guten morgen,
gerne :)

Das "Problem" bei den anderen Plugins ist, dass dort persönliche Daten benötigt werden.
z.B. Handynummer, Email Adressen und Passwörter.

Bei firEmergency und firEmergency werden sogar weitere Server Anwendung benötigt.

Wenn also jemand eine Idea hat ;)

**Comment by Schrolli91** [comment]
**E-Mail** könnte evtl noch gehen - einfach kleinen Mailserver einrichten in der VM und ne Mail ins nirwana senden? Ist uns doch egal ob die ankommt, solange BOSWatch seine Daten an einen Mailserver los wird?

**jsonSockert** könnte auch klappen, dazu bräuchten wir nur einen UDP Server starten auf dem das BOSWatch Plugin dann conected

**Comment by flothi** [comment]
Würde es für Bosmon etc nicht analog zum json-socket funktionieren, dass ein kleiner "Fakeserver" die Anmeldesequenz der originalen Server wiedergibt (als ne Art Replay), zB durch Whireshark identifiziert?

Bei den Webanwendungen (pushover, telegram,...) hab ich auch noch keine zündende Idee

**Comment by Schrolli91** [comment]
Hab jetzt auf Travis noch eben Cronjobs hinzugefügt, sodass alle Builds einmal die Woche automatisch angestoßen werden, sollte innerhalb der letzten 24h kein Build gelaufen sein.

Sollte sich also etwas bei den zugehörigen Programmen ändern, (SQL Connector, etc...) wir das auch mitbekommen, wenn im Branch nichts passiert, commit technisch...

@thejockel hier nochmal als Merker - beim Job `module=bash` erfolgt keine BOSWatch Ausgabe, dass sollte man sich nochmal anschauen, woran das liegt


EDIT:
https://github.com/Schrolli91/BOSWatch/blob/develop/exampleAddOns/jsonSocketServer/jsonSocketServer.py
Evtl kann man den ja umbauen um die Server Geschichten zu testen?

**Comment by thejockel** [comment]
@Schrolli91 Fehler gefunden
#230

**Comment by Schrolli91** [comment]
Super... gemerged...

**Comment by Schrolli91** [comment]
Ich schließe - wird für BOSWatch 3 in dieser Form nicht mehr benötigt.
Auf Travis-CI werden dann nur noch die Unittest gemacht, sowie die Code-Abdeckung automatisiert gemessen
