### ISSUE TITLE
E-Mail bei neuer Version

### ISSUE THREAD

**Issue by Schrolli91** [Schrolli91/BOSWatch#224]
Mir kam grad die Idee, in der config eine eigene E-Mail Adresse hinterlegen zu können, und bei erscheinen einer neuen Version automatisch per E-Mail darüber benachrichtigt zu werden.

Findet ihr sowas sinnvoll?

**Comment by flothi** [comment]
Also prüft BOSWatch selbstständig auf das Erscheinen einer neuen Version (mal überlegen, wie das beim Service zB klappt) - schlecht wäre es nicht.

**Comment by fwmarcel** [comment]
Finde das sogar sehr sinvoll. Nicht jeder achtet, wenn sein System läuft, darauf es auf dem aktuellen Stand zu halten.

**Comment by KampfkeksMRZ** [comment]
Ich finde das auch sehr Sinnvoll. Jetzt würde ich es vermutlich mitbekommen, weil ich im Moment regelmäßig reinschaue, würde das aber auch sehr befürworten

**Comment by Schrolli91** [comment]
ongoing in BW3 dev
