### ISSUE TITLE
weiteren Branch - beta ???

### ISSUE THREAD

**Issue by Schrolli91** [Schrolli91/BOSWatch#225]
Kurz in die Runde gefragt.
Was meint Ihr dazu, einen weiteren Branch anzulegen - beta
Wenn wir dann einen RC Veröffentlichen, wird dieser quasi in den beta gemerged.
Bei offizielem Release gehts dann von beta in den master.
So kann im Dev weiter wild probiert werden, ohne den Veröffentlichten RC zu verändern.
Denn, ich kann zwar ein Label auf den Stand des RC's im dev-Branch setzen, sodass die Sourcen vom RC unverändert downloadbar sind, aber per installer wäre der RC nicht ladbar, da hier der aktuelle dev gezogen wird.

Kurz un knapp - weiter branch **beta** + option im installer (master|beta|dev) ???

**Comment by flothi** [comment]
Klares Ja

**Comment by thejockel** [comment]
Ja!

**Comment by Schrolli91** [comment]
Ok, brauchen wir nicht weiter drüber reden...
Ich bau den Branch ein, sowie die Auswahl im installer. Travis passe ich auch gleich auf den weiteren Branch an...
