### ISSUE TITLE
Fehlermeldung bei Installation 

### ISSUE THREAD

**Issue by TobiasM112** [Schrolli91/BOSWatch#228]
Moin ich musste heute leider BOSWatch neu aufsetzen. Dieses mahl ging es leider nicht so ohne Probleme wie beim letzten mal.
Es bricht leider beim 2.Schritt ab. Hat einer von euch eine Idee?

```
     ____  ____  ______       __      __       __
    / __ )/ __ \/ ___/ |     / /___ _/ /______/ /_
   / __  / / / /\__ \| | /| / / __  / __/ ___/ __ \
  / /_/ / /_/ /___/ /| |/ |/ / /_/ / /_/ /__/ / / /
 /_____/\____//____/ |__/|__/\__,_/\__/\___/_/ /_/
            German BOS Information Script
                 by Bastian Schroll

This may take several minutes... Don't panic!

Caution, script does not install a webserver with PHP and MySQL
So you have to make up manually if you want to use MySQL support

               [ 2/10] [##--------]

     -> download GIT and other stuff..........
Action: download on stuff failed.
Exitcode: 100
```

**Comment by flothi** [comment]
Schau bitte mal nach der log-Datei vom Installer und poste mindestens die letzten Zeilen

**Comment by Schrolli91** [comment]
evtl auch mal das install file vom dev testen..
Wobei auch die vom master funktionieren müsste, denn Travis schafft damit ja auch sein build...

**Comment by TobiasM112** [comment]
wo ist den die Log-Datei vom Installer ?

**Comment by flothi** [comment]
Üblicherweise in `opt/boswatch/install/setup_log.txt`

**Comment by TobiasM112** [comment]
ich habe nur die install.sh (habe es mal nach der Anleitung im Wiki installiert.)

**Comment by flothi** [comment]
und wenn du die ausgeführt hast legt der die log-Datei im o.g. Verzeichnis an

Aufgerufen hast du den Installer wahrscheinlich mit `sudo bash install.sh`?

**Comment by TobiasM112** [comment]
Genau habe es mit "sudo bash install.sh" aufgerufen

Ich sehe aber nur die Install.sh nichts anderes also das o.g. Verzeichnis existiert anscheinend nicht.

**Comment by flothi** [comment]
Sorry, mein Fehler:
`/opt/boswatch/install/setup_log.txt`

**Comment by TobiasM112** [comment]
so in der log stand "Um den Fehler zu Beheben muss "sudo dpkg --configure -a" ausgeführt werden.
danach funktioniert die Installation

**Comment by Schrolli91** [comment]
Post bitte mal die letzten paar Zeilen davor + die Meldung...  Evtl kann man das abfangen oder anderweitig einbauen...

**Comment by flothi** [comment]
Und schreib bitte mal dazu welches Betriebssystem du nutzt (`uname -a`) und auf welchem Raspi

**Comment by TobiasM112** [comment]
ja ich war wohl etwas zu schnell was die install log angeht wurde leider überschrieben durch die erneute Installation nach dem befehl werde es aber morgen nochmal genau so machen und es dann hier rein stellen 

aber ich verwende einen Raspi 3 mit
>> Linux raspberrypi 4.4.34-v7+ #930 SMP Wed Nov 23 15:20:41 GMT 2016 armv7l GNU/Linux

**Comment by Schrolli91** [comment]
@flothi
Evtl sollte man den Namen der log File beim kopieren mit Datum und Uhrzeit versehen, damit sie nicht überschrieben wird...

**Comment by TobiasM112** [comment]
komischerweise funktioniert es auf meinem V-server zum testen ohne Probleme darauf läuft: Linux vps 2.6.32-042stab116.2 #1 SMP Fri Jun 24 15:33:57 MSK 2016 x86_64 x86_64 x86_64 GNU/Linux

ich werde morgen wie gesagt den Rpi mal neu aufsetzen genau so wie heute.

**Comment by Smith-fms** [comment]
`sudo dpkg --configure -a` bedeutet meistens ein Fehler aufgrund vorher abgebrochener Installation eines Paketes. Dies kann zum Beispiel dabei auftreten wenn du in mitten eines `apt-get upgrade` die Console vom Pi verlierst (WLAN Probleme) oder der Pi in der Zeit seine Power verliert. 

`sudo dpkg --configure -a` Ausführen und danach die install.sh nochmal starten. 
Es sollte vorher allerdings zu keinen Fehlern kommen.

**Comment by TobiasM112** [comment]
So es scheint so zu sein wie Smith-fms gemeint hat beim neu aufsetzen (diesmal mit LAN) gab es keine Fehler.  Habe mal nach dem W-LAN Signal geschaut ist nicht der Brenner an dem Standpunkt

**Comment by Schrolli91** [comment]
Was genau macht `sudo dpkg --configure -a`? 
Könnte man das prophylaktisch vor dem apt - get einfach aufrufen?

**Comment by flothi** [comment]
Ich glaube das erscheint nur, wenn der vorhergehende Befehl (in dem Fall `apt-get`) fehlgeschlagen ist. Prophylaktisch dürfte das glaube ich nichts bringen.

**Comment by Schrolli91** [comment]
Ok, dann Haken wir das so ab

**Comment by Smith-fms** [comment]
dpkg ist vom Prinzip der Paketmanager hinter apt-get

Das Problem ist, dass im Rahmen von Installationen einige Sachen umgeworfen werden und am Ende wieder zusammen gebaut. Gerade dann wenn dependencys ins Spiel kommen. 

Ein dpkg --conf..... Kann meines wissens prohylaktisch eingebaut werden, aber es würde bei einem unsauberen System bedeuten das wir damit rum pfuschen und das an Sachen welche nicht schuld des Script sind. Ich würde es nicht einbauen! 
Jeder der BOSWatch produktiv nutzt, sollte wissen was er tut. 
Und wenn nicht, Google nutzen. :)
Gerade bei MySQL etc...
