### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by Schrolli91** [Schrolli91/BOSWatch#231]
Mir kam heute Morgen die Idee, direkt einen Localization Dienst einzubauen, mit dem die Software dann in verschiedenen Sprachen verfügbar gemacht werden kann.
Vor allem besteht dann die Möglichkeit, dass andere User mit beim übersetzen helfen.

Sinnvoll oder Oversized?

**Comment by thejockel** [comment]
Guten morgen,
ich fände Deutsch und Englisch sinnvoll.

Mehr finde ich dann schon Oversized.

**Comment by Schrolli91** [comment]
Python bietet da wohl ein Modul für - gettext
https://docs.python.org/3.6/library/gettext.html

Auch wenn ich dessen Funktion noch nicht so ganz durchschaut habe

**Comment by flothi** [comment]
Provokant gefragt:
Was willst du außer der Doku hier im Wiki und ggf dem Hilfetext lokalizieren? Die Meldungen sind in Landessprache, Debug-Error/Warning/Logs international auf Englisch - ich behaupte, die Mühe können wir uns sparen.

**Comment by Schrolli91** [comment]
@flothi eigentlich hast du ja Recht.
War wohl doch noch etwas zu Müde heute Morgen um das ganze mal vernünftig zu Ende zu denken :-D

Lassen wir das einfach :-D

**Comment by flothi** [comment]
Ich finds ja gut dass du / wir uns kreativ austauschen - und es ist ja nur meine Meinung, kein Gesetz ;-)
