### ISSUE TITLE
BOSWatch 2.2-beta

### ISSUE THREAD

**Issue by Schrolli91** [Schrolli91/BOSWatch#233]
Ich werde jetzt mal eine beta releasen.
Ein paar Kleinigkeiten wie installer MySQL und Service werden bis zum finalen Release der 2.2 noch nachgezogen.

Aber dann gibt es jetzt mal einen Stand der getestet werden kann.
Denn der aktuelle master ist ja eher ein wildes Grab mit vielen Bugs :-D

Installierbar ist der beta Branch über den installer mit dem flag `-- branch beta`
Also bitte fleißig testen :-)

**Comment by thejockel** [comment]
Hallo,
base, mysql, http und yowsup laufen.

**Comment by Schrolli91** [comment]
Wie es aussieht, scheinen in der beta an sich aktuell keine gravierenden Bugs mehr zu sein? Sehe ich das Richtig?

Weis nicht ob man den aktuellen dev nochmal auf den beta mergen sollte? Denn selbst im dev sind ja keine wirklichen neuen Funktionen dazugekommen, sondern eigentlich nur Bugfixing passiert.

Also dev in beta mergen? Nochmal testen! und dann erst mal n Release, damit endlich der halb-"defekte" master nen sauberen stand bekommt?

**Comment by flothi** [comment]
Ich würde dafür plädieren den jetzigen Beta-Stand einzufrieren und nur noch Bugfixing zu betreiben - also die Erstellung des 2.2-RC1 durchzuführen. 

Ein merge auf dev bezogen macht nur Sinn, wenn die Bugs nicht eh schon behoben sind, da habe ich aktuell aber keinen Überblick

**Comment by Schrolli91** [comment]
also im dev war nur die Kleinigkeit mit der ZVEI Umstellung...
Das habe ich jetzt noch gar rüber gemerged... 
Außerdem habe ich Änderungen vom beta in den dev hochgezogen, nicht das uns der beta, dem dev vorraus läuft und am Ende Änderungen verloren gehen.

Da die letzten Tage aber für den beta auch keine Infos mehr kamen, würde ich langsam wirklich mal Richtung Release gehen

**Comment by flothi** [comment]
Kurz und knapp: Feuer frei für RC1 :-)

**Comment by Schrolli91** [comment]
Wenn ich ehrlich bin, würde ich den beta jetzt direkt in den master mergen, da der master aktuell mehr Fehler hat ;-) Damit da wieder ein einigermaßen sauberer Stand liegt.

Und dann im Dev mal Anfangen Bugs usw zu beheben für die 2.3

Wenn dann im dev was vorwärts gegangen ist, das wieder als beta bringen

**Comment by flothi** [comment]
Da bin ich ganz bei dir - dann sortieren wir mal was in welcher Prio als nächstes ansteht

**Comment by Schrolli91** [comment]
ok, dann mache ich das heute sobald ich daheim bin
- beta in master -> Relase 2.2
- beta liegt dann erstmal auf dem selben Stand wie master
- weitere Entwicklungen im dev

**Comment by flothi** [comment]
Wäre es sinnvoll, den beta zu löschen und erst kurz vor einer neuen Version aufleben zu lassen?

**Comment by Schrolli91** [comment]
da bekommen wir dann Probleme mit dem installer sowie Travis... ich würde das eher einfach stehen lassen...

Wer dann den beta installiert hat eben auch den stabilen master - weh tut das nicht

und eigentlich ist es dann auch ersichtlich an der Versionsnummer, wenn der master v2.2 ist und der andere dann v2.2-beta
Das sollte ja eindeutig genug sein

**Comment by Schrolli91** [comment]
so master is raus... alle weiter entwicklungen gehen bitte dann direkt inden  dev
