### ISSUE TITLE
Tageslog wird bei Neustart bzw Stop nicht geschrieben.

### ISSUE THREAD

**Issue by chbally** [Schrolli91/BOSWatch#236]
- **BOSWatch Version 2.1 + master**
- **eMail, MySQL**

Mir ist soeben aufgefallen, dass bei eingerichtetem Service boswatch.sh und dem Befehl "service boswatch stop" bzw. "service boswatch restart" ein neues Logfile erstellt wird und bzw. das bisher erzeugte Logfile des Tages überschrieben wird.
Das ist nicht schön - kann man das ändern?

**Comment by Schrolli91** [comment]
Zwischenfrage: Wie verhält sich das, wenn BOSWatch nicht als Service sondern normal gestartet wird? Wird das Logfile da auch überschrieben?

Diese automatischen Tageslogfiles werden hiermit erzeugt:
https://docs.python.org/2/library/logging.handlers.html#timedrotatingfilehandler

**Comment by chbally** [comment]
Ja auch beim Starten nicht als Service wird auch ein neues  Logfile erzeugt. Ist ja zum Testen vielleicht auch OK.
Wenn ich aber nur eine Config Änderung machen will (mit Service Boswatch) ist das nicht gut, weil dann Informationen fehlen.

Das Problem hat aus meiner Sicht auch nichts mit dem Tageslogfiles zu tun, sondern dass das bowatch.log beim Beenden von Boswatch nicht richtig geschlossen wird und damit die alten Einträge weg sind.

**Comment by Schrolli91** [comment]
Das logging an sich wird beim beenden von BOSWatch aber sauber geschlossen...
Ich weis grade nicht genau, was dieses `doRollover` genau macht
siehe: https://github.com/Schrolli91/BOSWatch/blob/master/boswatch.py#L137

**Comment by chbally** [comment]
Sagt der Kommentar:
https://github.com/Schrolli91/BOSWatch/blob/master/boswatch.py#L135
nicht alles?

**Comment by Schrolli91** [comment]
kannst ja mal testen, das rollover auszukommentieren, ob es dann tut wie gewünscht...

**Comment by flothi** [comment]
Die angegebene Zeile und folgende behandelt zum großen Teil die Logs, die die Ausgabe von rtl_fm und multimon-ng handeln.

Ich bin noch nicht ganz durchgestiegen, habe aber ne grobe Idee wo man suchen könnte

**Comment by chbally** [comment]
Moin,
ich hätte es ja nicht geglaubt, aber das Auskommentieren in 
https://github.com/Schrolli91/BOSWatch/blob/master/boswatch.py#L137
`#fh.doRollover()` 
hat verhindert, dass ein neues Logfile über das bestehende Logfile erstellt wurde, sondern fortgeschrieben wurde.

Ich habe noch etwas Google befragt und folgenden Hinweis gefunden:

> Log Rotation and RoatatingFileHandler are usually designed and desirable when the application is running for a very long time (days) and you want the log to keep rotation. Under cases where I have to rotate the log upon restart of the application, I had to do that outside of the Logfile handler, which was easier. It was like, before the log writer call for the first time, I would see if the log file already existed, and if yes, rename it and create a new log file. The renaming should be differentiated from the handler's renaming mechanism.

Sorry - ich bin nicht in der Lage das programmiermäßig abzufangen.

**Comment by JHCD** [comment]
Mit Logrotate ist das Thema, wie bereits beschrieben, nicht umsetzbar.
Hier müsste ein eigener Loghandler geschrieben werden, was ich für den normalen Einsatzzweck als nicht sinnvoll erachte.

Workaround: im Shell-Skript vor dem Aufruf boswatch.log nach boswatch.log.timestamp umbenennen.
Das produziert zwar Leichen, aber so oft startet man boswatch normalerweise ja auch nicht

**Comment by flothi** [comment]
Macht es Sinn das zu verfolgen?

**Comment by chbally** [comment]
Ja - ich glaube schon. 
Wenn nach Konfigurationsänderungen die Logfileeinträge des Tages nicht mehr habe, ist das wenig sinnig - oder?
Insbesondere da bei den CSV-Änderungen jeweils ein Neustart der Konfig erforderlich ist.

**Comment by JHCD** [comment]
Reichen Dir im Log die Alarmierungen oder was erwartest Du? Wozu nutzt Du die Log?

Aktuell werden Linux-Bordmittel genutzt, die sind nicht dafür ausgelegt Services andauernd neu zu starten.

Um diese Anforderung zu erfüllen, müsste man einen eigenen Logger implementieren. Alarmmeldungen wegschreiben wäre als Plugin einfach möglich. Alle Log-Einträge und das auch noch historisiert wäre schon Aufwand.

**Comment by chbally** [comment]
Ich nutze, wie sicher die meisten Anwender, Logfiles zur Analyse bei Fehlern.

Du hast schon recht, man startet den Service im Betrieb nicht dauernd neu.
Allerdings, wenn man die CSV Dateien aufbaut, kommt das durchaus häufiger vor. 
Wenn ein Neuladen der CSV Dateien ohne Neustart des Service möglich wäre, wäre das für mich mehr als hinreichend.

Blöde Frage: Kann man nicht das Tageslogfile beim Stop des Service umbennen?

**Comment by JHCD** [comment]
Ja, das könntest Du händisch machen, das Log File wird automatisch erst beim Neustart wieder "überschrieben"...

Sonst hat man keinen weiteren Zugriff auf die Log Files. BOSWatch kann bei der bisherigen Lösung nichts machen. Die Log-Parameter wären noch eine Option. Evtl. Gibt es andere Parameter, die Dir helfen würden.

Ich denke der korrekte Ansatz wäre hier ein Feature-Request: csv bei Änderungen neu laden

**Comment by Schrolli91** [comment]
siehe #261 - daher closed ...
https://github.com/Schrolli91/BOSWatch/issues/261#issuecomment-298756039
