### ISSUE TITLE
ZVEI1 statt ZVEI2

### ISSUE THREAD

**Issue by whiteshirtman** [Schrolli91/BOSWatch#237]
Guten Abend zusammen,

- wie kann ich die Dekodierung vom multimon-ng von "ZVEI2" auf "ZVEI1" umstellen?
- gibt es da Einschränkungen?

Erklärung:
ZVEI1: Repeat-Tone = 2600 Hz
ZVEI2: Repeat-Tone = 970 Hz

siehe:
https://de.wikipedia.org/wiki/5-Ton-Folge
http://www.sigidwiki.com/wiki/ZVEI_Selcall

- **BOSWatch Version + Branch** = 2.1 + beta
- **genutzte Plugins** = Pushover
- **Fehlerbeschreibung** = Probleme mit ZVEI1 / ZVEI2 : Repeat-Tone

---------------------------
Lob und Anerkennung:
Saubere Geschichte, was ihr hier auf die Beine gestellt habt - RESPEKT!
---------------------------

**Comment by Schrolli91** [comment]
Danke für deinen Beitrag. Geb mir ne Stunde, ich bau das direkt ein, dass man beide wählen kann.

Für dich auf die schnelle:
https://github.com/Schrolli91/BOSWatch/blob/master/boswatch.py#L176
In der zeile einfach auf `-a ZVEI1` ändern

Was genau ist eigentlich mit ZVEI3, DZVEI  und PZVEI? Wie gängig sind die?

**Comment by whiteshirtman** [comment]
Hallo Bastian,

danke für die schnelle Antwort!
Deinen Lösungsvorschlag für "auf die Schnelle" hatte ich auch schon mal probiert, leider ohne Erfolg....

Ich teste aber gerne nochmal.

**Comment by Schrolli91** [comment]
Eigentlich müsste das gehen... Wundert mich jetzt gerade etwas... Probier das bitte nochmal, ja

**Comment by whiteshirtman** [comment]
Habe nochmal die "auf die Schnelle"-Variante getestet: mit dieser Änderung wird zwar (laut mm_raw.txt) nach ZVEI1 dekodiert, aber das Ergebnis wird nicht weiterverarbeitet. In meinem Fall wird Pushover nicht getriggert.

Also wieder zurück auf ZVEI2: dekodieren läuft - außer Folgen mit "R" für Wiederholungen....

Konnte das schon mal jemand verifizieren?

**Comment by Schrolli91** [comment]
wie sind die ausgaben in der mm_raw.txt ?
bräuchte eine Zeile für jede ZVEI art... dann kann ich dem mal auf den Grund gehen

Schneller Workaroud:
https://github.com/Schrolli91/BOSWatch/blob/master/includes/decoder.py#L36
Hier auf ZVEI1 ändern

**Comment by whiteshirtman** [comment]
also, ich habe das Ding jetzt einfach mal laufen lassen, ohne dran rumzufummeln; was soll ich sagen:
Der Decoder ZVEI2 dekodiert die wiederholten Töne korrekt! Der zweite Ton wird übersetzt als "F".
--> Problem besteht also nicht in der Software; somit gelöst.

Vermutlich habe ich hier lokal ein anderes Problem mit dem Empfang oder dem Stick.

Sorry, das ich hier so ein Faß aufgemacht habe!
Trotzdem: Vielen Dank für die prompte Unterstützung und Umsetzung.

@Schrolli91 : willst trotzdem das mm_raw.txt ?

**Comment by Schrolli91** [comment]
also is der ZVEI1 support damit völlig überflüssig?
ne wenn das wirklich alles geht lassen wir das, dann baue ich das auch wieder zurück... Ne Funktion die nirgends genutzt wird brauchen wir ja dann auch nicht ;-)

**Comment by whiteshirtman** [comment]
korrekt: ZVEI1 wäre überflüssig - lass wech.

**Comment by flothi** [comment]
Ich muss mich mal fix einklinken, da ich jedes Mal drüber stolpere: Lt Wikipedia wird in Deutschland ZVEI1 verwendet (was bei den Ziffern 0..9 keinen Unterschied macht) - wäre es daher nicht konsequent, das auch hier zu tun?

**Comment by Schrolli91** [comment]
ich blick da selber nicht ganz durch - was genau wäre denn jetzt Richtig? Also Zvei1 dann?

**Comment by flothi** [comment]
Die entsprechende TR schreibt leider nicht explizit welche ZVEI-Folge, aber durch verschiedenen Seiten (Händler etc, vgl. google) wird anscheinend klar, dass ZVEI-1 verwendet wird.

**Comment by Schrolli91** [comment]
dann Münze ich das intern jetzt wieder so um das man nicht wählen muss/kann zwischen ZVEI1 und ZVEI2 sondern einfach das 1er genutzt wird

**Comment by Schrolli91** [comment]
Also im dev jetzt geändert 98b50110a083b3569300b9f25426b3bfd340e0df
sollte nochmal getestet werden sicherheitshalber

**Comment by flothi** [comment]
Sicher kann ichs gerade nicht sagen, aber:
vergleiche ich meine Ausgabe der mm_raw mit den testdata.txt, so ist das Wörtchen `DEMOD` noch vor die ZVEI-Angabe gestellt; somit passt die Stringsuche nicht mehr und die Erkennung schlägt fehl.

Kann das bitte jemand mit der Ausgabe in der mm_raw.txt verifizieren?

**Comment by Schrolli91** [comment]
versteh grad nicht vorauf du hinaus willst?

**Comment by flothi** [comment]
In der testdata.txt heißt es 'ZVEI2: 12345', wenn ich den aktuellen develop-branch nehme steht in der mm_raw.txt (die meiner Meinung nach das gleiche enthalten sollte wie dir testdata.txt) 'DEMOD: ZVEI2: 12345'

Der Decoder (ZVEI.py) nimmt die Stelle 7-12 zur Dekodierung - das passt im zweiten Fall ja nicht mehr

**Comment by Schrolli91** [comment]
das hat mit meiner Änderung jetzt aber nichts zu tun oder?
Das ist durchaus komisch... wieso ist das vorher nie aufgefallen, irgendwas stimmt da doch nicht

**Comment by flothi** [comment]
Gestern abend war leider nix los aufm Kanal. Ich schaue nachher mal nach. Das wäre dann auf jeden Fall was für die 2.2

**Comment by flothi** [comment]
Das scheint ein grundlegendes Problem zu sein; multimon hat da offensichtlich ein anderes Format als erwartet. Push kommt gleich.

**Comment by Schrolli91** [comment]
meinst du damit, das die Grundlegende Ausgabe von MM bei ZVEI2 anders ist als bei ZVEI1 ?

**Comment by flothi** [comment]
Die grundlegende Ausgabe bei allen ZVEI scheint nicht mehr gepasst zu haben; sowohl bei ZVEI1 wie auch ZVEI steht jetzt das benannte `DEMOD: ` davor - theoretisch hätte das gar nicht mehr klappen dürfen.

**Comment by Schrolli91** [comment]
es hat aber geklappt bis vor meiner Änderung, obwohl die ja nichts damit zu tun haben kann... Das irritiert mich jetzt schon gewaltig ??

**Comment by flothi** [comment]
Ich habe auch noch nicht rausfinden können woher das DEMOD kommt - ich werde nachher nochmal einen neuen Pi aufsetzen und es mir anschauen

**Comment by Schrolli91** [comment]
sollte dem wirklich so sein, und sich das bei deinem Test dann nochmals bestätigen müssen wir die Testdaten aber auch entsprechend anpassen, sonst failed das build ja immer ;-)

**Comment by flothi** [comment]
So korrekt ;-) ich bin verwirrt :-D

**Comment by Schrolli91** [comment]
verwirrt wegen? ^^

**Comment by flothi** [comment]
Weil auch der aktuelle Master bei mir nicht klappt...
Im Develop-Branch läuft es.

**Comment by flothi** [comment]
Ich widerrufe - mein multimon war irgendwie arg zerschossen; habs im develop angepasst

**Comment by Schrolli91** [comment]
Hab jetzt mal noch die Testdaten angepasst, damit Travis endlich mal wieder Ruhe gibt :-D
Damit dürfte die Sache ja jetzt durch sein
