### ISSUE TITLE
Fehlerhafte URL-Kodierung bei httpRequest

### ISSUE THREAD

**Issue by DeBukkIt** [Schrolli91/BOSWatch#238]
- **BOSWatch Version + Branch**
Version 2.1, master

- **Fehlerbeschreibung**
Eine per httpRequest an einen HTTP-Server gesendete Nachricht wird zuvor nicht URL-sicher kodiert. Möglicherweise enthaltene &- oder %-Zeichen führen zu ungewollten Ergebnissen, weil sie vom Webserver falsch gedeutet werden.

- **Mein Vorschlag:** Die Methode urllib.quote verwenden, um diese Zeichen umzuwandeln, bevor sie durch den WildcardHandler der URL hinzugefügt werden. Hinweis: Die Anwendung dieser Methode auf die gesamte, fertige URL führt wiederum zu ungewollten Ergebnissen, da auch :// (aus dem Protokoll) und andere gewollte Zeichen ersetzt würden.

**Comment by DeBukkIt** [comment]
Neue Erkenntnis: Sind Sternchen in der Roh-Nachricht, kommen die Daten per httpRequest trotz urllib.quote nicht an. Möglicherweise vertragen sich die Sternchen nicht mit der RegEx-Syntax und es ist neben urllib.quote ein weiterer Entschärfer notwendig, um auch Nachrichten mit Sternchen zu berücksichtigen.

**Comment by Schrolli91** [comment]
@DeBukkIt würdest du dich der Sache annehmen wollen, und versuchen einen fix zu entwickeln?

**Comment by DeBukkIt** [comment]
@Schrolli91 Entschuldige bitte, aber Python ist so gar nicht meine Welt. Vielleicht findet sich irgendwer anders, dem diese Aufgabe besser steht. Falls ich aber mal per Zufall auf eine Lösung stoße, melde ich mich.

**Comment by ghost** [comment]
Ich habe das Problem gelöst, urllib.quote funktioniert bei mir auch mit Sternchen in der Nachricht. Zusätzlich habe ich die Möglichkeit eingebaut, mehrere URLs aufzurufen.
Da ich neu bei GitHub bin, ist mir noch nicht ganz klar, wie ich meinen Quelltext übermitteln soll. Ich habe das Projekt geforkt und dann einen Commit gemacht, wie gehts weiter?

**Comment by flothi** [comment]
Im Anschluss müsstest du einen Pull-Request (in den develop-Zweig) initiieren - dann kommt das dadurch wieder zurück

**Comment by flothi** [comment]
@Mikrocontroller Brauchst du noch Unterstützung beim Erstellen des Pull-Request?

**Comment by ghost** [comment]
Ist schon im dev-Branch drin

**Comment by Schrolli91** [comment]
also erledigt ( #254 )

**Comment by flothi** [comment]
Ok, übersehen
