### ISSUE TITLE
Start as Daemon - Fehler

### ISSUE THREAD

**Issue by KampfkeksMRZ** [Schrolli91/BOSWatch#239]
Hallo zusammen,

erstmal danke für diet tolle Software. InZukunft werde ich mich wohl auch mal beteiligen bei Tests, sofern es mir mit meinen einfachen Linux-Kenntnissen möglich ist.

Leider hab ich seit Neuinstalltion des Pi folgendes Problem:

BOSWatch 2.1 master

Jessie, heute frisch aufgesetzt

Fehlerbeschreibung:

Die boswatch.sh aus dem Ordener Service bringt folgenden Fehler:

pi@RaspberryPi:/opt/boswatch/service $ sudo /etc/init.d/boswatch.sh start
[....] Starting boswatch.sh (via systemctl): boswatch.serviceFailed to start boswatch.service: Unit boswatch.service failed to load: No such file or directory.
 failed!`

Installationsverzeichnis: /opt/boswatch

Inhalt boswatch.sh
#!/bin/sh

### BEGIN INIT INFO
# Provides:          BOSWatch
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Python Service to receive and decode German BOS Informatio$
# Description:       Python Service to receive and decode German BOS Informatio$
### END INIT INFO

# Change the next 3 lines to suit where you install your script and what you wa$
DIR=/opt/boswatch
DAEMON=$DIR/boswatch.py
DAEMON_NAME=boswatch

# Add any command line options for your daemon here

NMA Handler  funktioniert!

**Comment by KampfkeksMRZ** [comment]
Ich habe gerade von Arbeit aus mal die aktuelle Beta installiert - hier habe ich dasselbe Problem.

Mir ist aufgefallen, dass die Pfade irgendwie nicht stimmig sind:
Als Installationsverzeichnis im Script ist /opt/boswatch angegeben, in service/boswatch.sh lautet er jedoch /opt/boswatch/BOSWatch

Ich habe beide Varianten ausprobiert - sowohl im install-Script den Ordner anzupassen, als auch im boswatch.sh. 

Beide Varianten funktionieren leider nicht. Bei der Variante mir angepasstem Pfad im Installer auf /opt/boswatch/BOSWatch bekomme ich allerdings nen Berechtigungsfehler.

`pi@RaspberryPi:/etc/init.d $ /etc/init.d/boswatch.sh start
[....] Starting boswatch.sh (via systemctl): boswatch.serviceFailed to start boswatch.service: Access denied
 failed!`

Selbst mit chmod 777 gehts nicht, und 777 sollte eigentlich nicht nötig sein. 

Bin scheinbar zu blöd, kann mir mal jemand helfen?

Grüße


PS: Der NMA geht in der Beta auch einwandfrei!

**Comment by Smith-fms** [comment]
bitte vor dem kopieren der Datei die Line 14 in folgende ändern:
`DIR=/opt/boswatch`
Danach sollte der Dienst wieder laufen. 
Alternativ die Line direkt in der Datei `/etc/init.d/boswatch.sh` anpassen.

**Comment by KampfkeksMRZ** [comment]
Leider nicht... 

habt aktuell die Installation in  /opt/boswatch/BOSWatch liegen. und in der .sh darauf angepasst.

Bekomme aber nur ein Acces Denied. Siehe Post Nr. 2

**Comment by Smith-fms** [comment]
führe bitte folgenden Befehl aus:
`chmod +x /etc/init.d/boswatch.sh`
danach passe die Line 14 auf den Wert `DIR=/opt/boswatch/BOSWatch` an und versuche bitte nochmal ein 
`/etc/init.d/boswatch.sh start`
Sollte dies so nicht klappen, interessehalber mal ein `sudo /etc/init.d/boswatch.sh start`

**Comment by KampfkeksMRZ** [comment]
`pi@RaspberryPi:/etc/init.d $ /etc/init.d/boswatch.sh start
[....] Starting boswatch.sh (via systemctl): boswatch.serviceFailed to start boswatch.service: Access denied
 failed!'

'pi@RaspberryPi:/etc/init.d $ sudo /etc/init.d/boswatch.sh start
[ ok ] Starting boswatch.sh (via systemctl): boswatch.service.'

'pi@RaspberryPi:/etc/init.d $`

Alles klar - da mal ein Sudo davor zu setzen, daran hab ich natürlich nicht gedacht. Dankeschön.

Bliebe nur noch die Geschichte mit den unterschiedlichen Pfaden. Evt. könnt ihr das ja aufnehmen, bevor der Release kommt. Ich meine mich zu erinnern, dass das im aktuellen master auch bereits falsch ist.

**Comment by Smith-fms** [comment]
Du hast der Service Datei ein rwx-Recht gebenen. Die Datei /opt/boswatch/BOSWatch/boswatch.py allerdings lässt sich bei dir nur per root Rechte ausführen. 
Das ist mit dem Service im Autostart aber eigentlich kein Problem, sollte von den Rechten her passen.

Wenn du dies allerdings anders haben willst, für den manuellen Start dann:
`sudo chown -R BENUTZER /opt/boswatch/BOSWatch/`
`sudo chmod -R 755 /opt/boswatch/BOSWatch/`

Danach sollte es passen.

**Comment by KampfkeksMRZ** [comment]
Ja, mit deinem letzten Tipp gehts auch ohne root. 

Dafür gibt es ein neues Problem:
Der Service ist zwar da, aber die Software arbeitet nicht.

Ich hatte den normalen Log auf 20, und den NMA Handler ebenso. 
Es kommt aber nichts - es wird kein Log geschrieben. 

Gehe ich hin und setzte den bei NMA auf 10 - stürzt das ganze bei normalen Aufruf ab - und sendet mir nen Haufen Meldungen.

Beim Start als Service passiert nix. gar nix. Weder bei 10 noch bei 20, bei 10 müsste die Software abstürzen, der Service läuft aber nach "Status" noch immer

pi@RaspberryPi:/opt/boswatch/BOSWatch $ sudo /etc/init.d/boswatch.sh status
â— boswatch.service - LSB: Python Service to receive and decode German BOS Information with rtl_fm and multimon-NG
   Loaded: loaded (/etc/init.d/boswatch.sh)
   Active: active (exited) since Wed 2017-03-15 17:26:09 CET; 12s ago
  Process: 3484 ExecStart=/etc/init.d/boswatch.sh start (code=exited, status=0/SUCCESS)

Mar 15 17:26:09 RaspberryPi boswatch.sh[3484]: Starting system boswatch daemon:.
Mar 15 17:26:09 RaspberryPi systemd[1]: Started LSB: Python Service to receive and decode German BOS Information with rt...on-NG.
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by Smith-fms** [comment]
Dann doch mit einem sudo....
Das Problem liegt in der Rechte-Ebene von Linux. 
Ob wir da mal dran gehen, ich schau mal...  Starte die Dienste auf meinem Pi allerdings immer mit sudo oder sogar unter root. Es läuft nichts anderes drauf und wenn jemand drin ist, ist er es halt. Dann hat er wahrscheinlich auch root-Rechte.

Auf einem meiner Server im Rechenzentrum würde ich es natürlich nicht machen, das wäre fast schon Selbstmord... :-)

nur um sicher zu sein, mit sudo klappt alles ohne Probleme?

**Comment by KampfkeksMRZ** [comment]
Nein, leider nicht. 

Siehe mein letzter Post: 
BOSWatch scheint nicht zu starten. Es wird kein Log geschrieben - es gibt auch keinen Log auf NMA.

Auch die "Alive"-Ric, die er per Denied ausschließt müsste ich bei 20 als Meldung bekommen - es kommt nichts. 

Die Abfrage mit "Status" ergibt aber, dass der service laufen müsste.

Beim "normalen" Start geht alles!

**Comment by Smith-fms** [comment]
Irgendwas lief schief.
`rm -R /opt/boswatch/` und nochmal den installer starten. 
Schneller gehts nicht. 
den Service im /etc/ auch besser nochmal löschen. 
Und daran denken den Pfad anzupassen. Mein Pull ist noch nicht gemerged.

**Comment by KampfkeksMRZ** [comment]
Wird erledigt. Ich werde in wenigen Minuten berichten.

**Comment by Smith-fms** [comment]
Ich hab die Beta hier laufen, Stand vor 2 Tagen. MySQL und firEmergency laufen.
Und das ganz entspannt übrigens auf einem Pi Zero W :-D

**Comment by KampfkeksMRZ** [comment]
IAlles Bullshit was hier vorher stand.

Jetzt geht es. Danke für die schnelle Hilfe.

Warum es nicht ging, weiß ich allerdings nicht - ich habe keine Idee!

**Comment by KampfkeksMRZ** [comment]
Jetzt gibt es allerdings noch einen Bug:

Startet mal "normal", wird beim beenden alles sauber beendet. 

Startet man als Service, ist auch alles gut - aber bei `/etc/init.d/boswatch.sh stop` wird scheinbar RTL-FM nicht sauber beendet. Jedenfalls kommt bei einem erneuten Start dann immer "cannot start rtl_fm" im Log.

Workaround: Reboot...

**Comment by flothi** [comment]
Ich habe im Develop-Zweig eine Alternative als service eingestellt, das läuft bei mir anstandslos (das beschriebene Problem hatte ich bis dato auch)

**Comment by KampfkeksMRZ** [comment]
Ich teste dann heute Abend mal... Keinen Laptop dabei, und ich schätze per SSH komme ich hier ausm Firmennetz nicht raus...

**Comment by KampfkeksMRZ** [comment]
So, also erster Test verlief positiv. Keine Fehlermeldungen. Auch ein Restart des Services lief einwandfrei, und das auf Anhieb.

**Comment by flothi** [comment]
Dann mache ich hier mal zu, bei neuen Problemen bitte melden.
