### ISSUE TITLE
Zeitstempel entfernt -> Alarmierungsgruppen nicht nachvollziehbar

### ISSUE THREAD

**Issue by JHCD** [Schrolli91/BOSWatch#244]
Ich habe ein Problem mit der folgenen Änderung:

MySQL.py:
> Original: FROM_UNIXTIME(%s)
> Neu: NOW()

Commit: https://github.com/Schrolli91/BOSWatch/commit/e4e3de1abdc2bf2334cfd359333d691aa67c87ed

Es gab einen Grund, warum *NOW()* dort nicht verwendet wurde!
Diese Änderung führt aufgrund der Laufzeiten zu unterschiedlichen TimeStamps in der DB bei "gleichzeitiger Alarmierungen". Für auf die Datenbank aufbauende Folgesysteme sehr ungünstig.

**Comment by flothi** [comment]
Wenn das ein Problem ist (und funktionell gleich oder besser) dann sollten wir das rückgängig machen.

**Comment by JHCD** [comment]
Ich habe bei der damaligen Implementierung den Zeitstempel aus der Alarmierung genommen und nicht einen neuen Zeitstempel generiert...

1. Sammel-Alarmierungen haben (bei uns) den selben Zeitstempel, bekommen jetzt aber deutlich unterschiedliche Zeiten
2. Wer sagt mir, dass die lokale Systemzeit identisch zur Zeit des Alarmierungsrechners ist?

**Comment by JHCD** [comment]
Ich würde gerne den gesamten Commit verstehen?
1.) Was prüft isSignal(poc_id)?
2.) Wieso wurde UFT-8 entfernt?

**Comment by flothi** [comment]
ad 1)
isSignal prüft auf die zyklische Netzkennung - die wird nicht wie "normale" RIC in die Datenbank geschrieben, sondern mit dem letzten Zeitstempel in einer separaten Tabelle eingetragen. Das wiederum könnte man zb für nen Feldalarm nutzen

ad 2)
keine Ahnung ;-)

**Comment by JHCD** [comment]
zu 1.) Okay, da kann man die 2 SQL auf einen zusammenstampfen "INSERT OR REPLACE..." ;)
Wobei ich mit dem Code keinen Nachweis mehr habe, wann die internen Systemtests gelaufen sind.

**Comment by flothi** [comment]
Was meinst du mit internem Systemtest?

**Comment by JHCD** [comment]
Bei uns wird diese RIC für mehrere Dinge genutzt:
1.) Funktioniert der Alarmierungsrechner
2.) Kommen die "Systemtest-Alarmierungen" bei jedem DAU an? 
Wenn ein DAU nach n Minuten keinen solchen RIC empfangen hat, macht er Alarm.
3.) Passen die DAUs ihre Feldstärke dadurch an.
4.) Laufzeiten im DAU-Netz
Das weisen wir im Zweifel nach...

**Comment by flothi** [comment]
Doch, meinem Verständnis nach klappt das trotzdem - du verlierst jedoch die Historie, den aktuellen Stand hast du (Zeitpunkt der letzten Aussendung der Netzkennung).

**Comment by JHCD** [comment]
Ja, das habe ich schon so verstanden...
Ist ja auch als _kann_ implementiert, ich muss die Netzkennung ja nicht nutzen...

Das mit der extra Tabelle finde ich aber eine sehr gute Idee.

a) Ich würde das SQL zusammenschrumpfen... lass die DB das prüfen...
b) Evtl. einen Schalter, ob man die Historie haben will oder nicht.

**Comment by Schrolli91** [comment]
Kann die Änderung den nun ohne Probleme auf den BOSWatch timestamp rückgängig gemacht werden?

**Comment by Schrolli91** [comment]
ich kümmere mich darum
EDIT: @flothi sehe gerade das ist schon zurück gebaut, is wohl an mir vorbei gegangen, warst du das? :-D

**Comment by Schrolli91** [comment]
@flothi hab jetzt mal das flag zum speichern der history implementiert.
Gibt es im Bezug auf dieses Issue noch was zu tun?

**Comment by flothi** [comment]
Ich würde es als komplett ansehen, was meinst du @JHCD ?
