### ISSUE TITLE
DB Event führt zu Datenverlust

### ISSUE THREAD

**Issue by JHCD** [Schrolli91/BOSWatch#245]
Wieso werden als Standard-Einstellung Daten aus der Datenbank gelöscht?

>CREATE EVENT IF NOT EXISTS `Delete POCSAG Entries > 3 Months` 
	ON SCHEDULE EVERY 1 DAY 
    STARTS '2016-01-01 00:00:00' 
    ON COMPLETION PRESERVE ENABLE 
    DO  
	DELETE FROM bos_pocsag WHERE time < DATE_SUB(NOW(),INTERVAL 3 MONTH);

Als Option nett, aber als Standard-Einstellung nicht brauchbar.
Es gibt juristische Gründe Daten auch länger vorhalten zu müssen.

**Comment by flothi** [comment]
Stimmt, das Aufräumen sollte dem User überlassen werden - also raus damit aus der sql-Datei?

**Comment by JHCD** [comment]
Ich würde es in eine weitere SQL-Datei auslagern und wer möchte kann es ja nutzen.

**Comment by flothi** [comment]
Dann trenne ich das gleich mal

**Comment by flothi** [comment]
Im develop-Zweig getrennt, ich würde das dann hier schließen, wenn es keine Einwände gibt.
