### ISSUE TITLE
multimon-ng raw data

### ISSUE THREAD

**Issue by JHCD** [Schrolli91/BOSWatch#246]
Sollte das wirklich als Standard aktiviert sein oder ist das nicht nur im Debug-Fall notwendig?

``# writes the multimon-ng raw data stream into a text file named mm_raw.txt``
``writeMultimonRaw = 1``

**Comment by fwmarcel** [comment]
Wäre für Standardmäßig aus. Für Debugzwecke macht es durchaus sinn. Aber so erspart es etwas an "schreibarbeit"

**Comment by flothi** [comment]
Ist mit #247 erledigt
