### ISSUE TITLE
Installation der Beta. Welches OS?

### ISSUE THREAD

**Issue by Huhu123er123** [Schrolli91/BOSWatch#249]
Hallo,

ich möchte nachher (nach Jahren) BOSWatch neu aufsetzen.
Es ist ja alles ganz anders geworden und ich blicke da nicht mehr durchs Wiki durch...

1. Frage:
Welches OS sollte ich nuitzen?
Jessy? Jessy Lite?
Was anderes?
Wo genau sitzen die Unterschiede?

2. Ich möchte die "neueste" Version (DATUM!) laden.
Das wäre der develop?

Wie lade und installiere ich das?
Früher müusste ich den ganzen Ordner laden und die install ausführen.

Dankesehr.

**Comment by thejockel** [comment]
Hallo,
ich nutze ein RASPBIAN (also vom Raspberry pi).
Würde aber auf x86 eine full Debian Jessy nutzen.

Jessy Lite kenne ich ehh nur aus dem PI Umfeld.

Von Develop würde ich für den produktiv Einsatz abraten!
Diese Version ist noch in der Entwicklung und enthält Fehler.

Am besten fährst du mit der Stable Version.

Die installation ist denkbar einfach:
`wget https://github.com/Schrolli91/BOSWatch/raw/master/install.sh`
`chmod +x install.sh`
`./install.sh  --reboot`

**Comment by Huhu123er123** [comment]
Hallo nochmal.
Ich habe alles! wirklich alles! probiert, bekomme es aber nicht zum Laufen...

Wie genau ermittel ich nun die PPM Fehler?
rtl_test -p liefert viele verschiedene Werte
Und beim Versuch kaliber-rtl zu benutzen erhalte ich nur Fehler...
"aclocal, autoconf, autoheader, automake"
Die Kommandos findet er alle nicht.

**Comment by Schrolli91** [comment]
mal ein `apt-get update` und dann ein `apt-get upgrade` laufen lassen evtl

**Comment by flothi** [comment]
Ich gehe mal davon aus dass du den Hinweis von @thejockel gefolgt bist.
Mit Raspbian rennt es bei mir mit der Verwendung der install.sh aus dem Master problemlos.

Vielleicht postest du mal eine Fehlermeldung vom Installationsprozess bzw vom Startversuch

**Comment by thejockel** [comment]
rtl_test -p ein paar Minuten laufen.
Dann sollte sich das einpendeln.

**Comment by Huhu123er123** [comment]
Danke!

Ich habe es tatsächlich hinbekommen.
Es lag am Stick, bzw. am Empfang...

Zwei Fragen habe ich noch:
Wie ermittle ich den besten Gain Wert?
Ich habe ja keine Ausschlag leiste.

Wie sehe ich allgemein, wie "gut" der Empfang ist?

**Comment by fwmarcel** [comment]
@Huhu123er123 wie ich sehe setzt du BOSWatch ja neu auf. Wie hattest du vorher deinen Gain Eingestellt. Solltest du den nicht angeben, wird ein Gain von 100 als Standartwert gesetzt. 
Dazu noch eine Grundsätzliche Frage an dich. Was für eine Antenne benutzt du ? Welche Antennenlänge bzw. für welche Frequenz ? Aktiv oder Passiv? Bzw. Wo steht diese ?

Wenn du vorher schon Meldungen ohne Probleme und Fehler, also vollständige Meldungen. empfangen hast. Kannst du die Voreinstellung belassen, nur wenn Fehler auftreten würde ich an deiner Stelle etwas ändern. Immer nach dem Motto "Never touch a running system"

**Comment by Huhu123er123** [comment]
Hat sich auch erledigt, läuft alles sauber.
Vielen Dank!!
