### ISSUE TITLE
Stdout fehlerhaft 

### ISSUE THREAD

**Issue by K3vP0** [Schrolli91/BOSWatch#25]
Hallo, 

Die Ausgabe des Programms wird trotz Disown im Terminal angezeigt.

**Comment by JHCD** [comment]
Sorry, den Fehler habe ich nicht verstanden?
Disown = ?

Mit dem Parameter "-q" im Aufruf kommt es hier zu keiner Ausgabe...

**Comment by K3vP0** [comment]
Disown ist ein Befehl unter Linux, um Prozesse in den Hintergrund zu setzen. 
Also man wieder Eingaben im Terminal tätigen kann. 
Die Meldungen der ankommenden Nachrichten werden jedoch trotzdem im Terminal ausgegeben.

Folgend kannst du es ausprobieren:

./boswatch-f yyy -a xxx -p zzz -d 0 & disown

**Comment by JHCD** [comment]
Wie bereits beschrieben, fehlt in Deinem Aufruf der Parameter "-q" für quiet-Mode...
Bitte damit ausprobieren.

**Comment by Schrolli91** [comment]
Ja im "-q" Mode sollte es keine Ausgaben mehr produzieren...

**Comment by K3vP0** [comment]
Funktioniert. #closed
