### ISSUE TITLE
Frage: POCSAG und FMS gleichzeitig ?

### ISSUE THREAD

**Issue by fwmarcel** [Schrolli91/BOSWatch#250]
Ist es aktuell oder sonst auch irgendwie möglich. Mithilfe zweier Sticks sowohl FMS als auch POCSAG auszuwerten und zu dokumentieren. Also Stick / Device 1 -> Frequenz XY und Stick 2 auf Frequenz XZ

**Comment by Schrolli91** [comment]
einfach eine zweite Instanz laufen lassen...
Also BOSWatch in einen weiteren Ordner packen und entsprechen konfigurieren

**Comment by fwmarcel** [comment]
ja das wäre ne Möglichkeit. Hat das jemand schon so im Betrieb ? Bzw. hat jemand damit schon Erfahrungen gemacht ?

**Comment by Schrolli91** [comment]
Soweit ich weis, haben hier mehr Leute den multi-instanz Betrieb Fehlerfrei getestet
