### ISSUE TITLE
Pushover - mehrere Instanzen / Gruppen

### ISSUE THREAD

**Issue by Huhu123er123** [Schrolli91/BOSWatch#253]
Hallo,

ist es möglich mehrere unter pushover.net angelegte Gruppen zu pushen?
Z.B. möchte ich Feuerwehr und RD selektieren.

**Comment by Huhu123er123** [comment]
Mir kam sonst gerade die Idee, dass man vielleicht auch einfach eine Möglichkeit für mehrere Groupkeys einfügen und RICS dann per Einstellung unter den Gruppen sondieren könnte?

**Comment by Huhu123er123** [comment]
Hallo, auch hier muss ich noch mal nerven...
Ich habe einfach den Pushover Ordner kopiert und ihn Pushover2 genannt, in der config unter den Plugins Pushover2 eingetragen, und die pushover.py auch pushover2.py gennant.
Diese habe ich dann so geändert, dass immer auf die pushover2.py anstatt der pushover.py zugegriffen wird.

Leider wird beim Starten aber nur die normale Pushover geladen.
Was mache ich falsch?
Muss ich noch einen "develop" Modus anschalten, oder so?

**Comment by fwmarcel** [comment]
Du musst in der pushover2.py auch Änderungen vornehmen. Aktuell greift die auch auf die gleiche Config Pushover zu

**Comment by Huhu123er123** [comment]
Das  hatte ich auch schon gemacht, aber irgendwie hat sich ein Fehler eingeschlichen.
Jetzt geht alles, danke sehr! :)
