### ISSUE TITLE
Pushover alle Alarme gleich behandeln

### ISSUE THREAD

**Issue by Huhu123er123** [Schrolli91/BOSWatch#258]
Hallo, manche Alarme werden bei mir bei Pushover rot hinterlegt.
ich möchte, dass diese ganz normal dargestellt werden.

Handelt es sich um dei Subric behandlung?

**Comment by flothi** [comment]
Ja, du kannst für verschiedene SubRIC unterschiedliche Prioritäten vergeben (siehe config.template.ini) 
Setz die einfach einheitlich und alles sollte gut sein

**Comment by flothi** [comment]
Bedeutung auch unter 
https://pushover.net/api#priority

**Comment by Huhu123er123** [comment]
Sorry, das hatte ich ganz übersehen. :/
Dankeschön!!
