### ISSUE TITLE
POCSAG Doppelung

### ISSUE THREAD

**Issue by K3vP0** [Schrolli91/BOSWatch#26]
POCSAG Nachrichten werden zwei Mal angezeigt, wenn mehrere Nachrichten auf einmal gesendet werden. ( Trotz eingeschalteter Doppelfunktion)

Ex.: 

1130506
1130607
1130506
1130607

**Comment by JHCD** [comment]
Der Duplikatsfilter funktioniert nur bei direkt aufeinander folgenden Nachrichten.

**Comment by Schrolli91** [comment]
Alles andere wäre auch nicht ohne erheblichen Mehraufwand möglich, da man ja die letzten x-Rics bzw Schleifen vorhalten müsste und das auch noch in Abhängigkeit der Zeit.

**Comment by K3vP0** [comment]
Ok. Ich habe eine Lösung im Rohr, der die letzten 3 Nachrichten des RICs überprüft, wenn ich damit weiter bin, stelle ich den Code zur Verfügung.

Habt ihr schon eine Möglichkeit der Anzeige einzelner Nachrichten ala Alarmdisplay?

**Comment by Schrolli91** [comment]
Das ganze sollte dann aber irgendwie sauber als Funktion gehalten werden, sodass man das ganze zB in der filter.py einbaut und dann auch für ZVEI nutzen kann...

**Comment by JHCD** [comment]
Moin, moin, 
Ich habe eine Idee, wie man das gut und performant umsetzen könnte.
Die Lösung wird 2 Parameter in der config.ini haben:
Anzahl n der zu betrachtenden letzten Meldungen, die in den letzten m Sekunden eingetroffen sind.
z.B.: 10 Meldungen in 5 Sekunden

**Comment by JHCD** [comment]
So, ich habe mal eine neue Version des doubleFilters gebaut.

Zur Realisierung hätte ich noch eine Fragen:
Wer braucht getrennte double-alarm-Filter nach FMS|ZVEI? 
(POCSAG ist sowieso immer eine getrennte BOSWatch-Instanz)

In meinen Augen wird keine Unterscheidung benötigt, es werden einfach die letzten n IDs vorgehalten.

**Comment by K3vP0** [comment]
Ist schon online ? Wo hast du es eingefügt ?

**Comment by JHCD** [comment]
Der Vorschlag ist im Developer-Zweig eingebaut.
Zwei config-Änderungen sind notwendig, siehe Template Abschnitt BOSWatch.

**Comment by Schrolli91** [comment]
Feature ist nun also im Dev eingebaut. Damit würde ich sagen closed...
Wenn Probleme auftreten als BUG-Issue melden ;-)
