### ISSUE TITLE
Wie aktualisiere ich meine Version? CSV Update ohne Restart?

### ISSUE THREAD

**Issue by Huhu123er123** [Schrolli91/BOSWatch#261]
Hallo,

nochmal eine blöde Frage für Anfänger.
Wie aktualisiere ich meine bestehende Master Version, ohne dass die config und die csvs überschrieben werden?

Vor 4 Tagen hat flothi wohl etwas aktualisiert und ich möchte halt up to date sein.

Und, nächste Frage:
Kann man die CSVs im laufenden Betrieb aktualisieren, bzw. sie danach neu initialisieren, ohne BOSWatch zu beenden?

Liebe Grüße!!

**Comment by flothi** [comment]
Grundsätzlich kannst du dir mittels 'git pull origin [master|develop|beta]' die aktuellen Stände ziehen 
Die config.ini wird nicht überschrieben, da sie nicht im Repo existiert, die csv würde ich vorher mittels kopieren/umbenennen sichern 

Ein Update der csv im laufenden Betrieb ist meines Wissens nach nicht möglich

**Comment by Huhu123er123** [comment]
Vielen lieben Dank, dass Ihr Euch so schnell / zuverlässig und kompetent um einen kümmert - auch wnn man sich vielleicht ein wenig blöd anstellt! :) : X :D

**Comment by flothi** [comment]
Davon lebt das Projekt doch - und ich glaube die wenigsten hier konnten von Geburt an programmieren ;-)
Lernen können wir alle noch, wir müssen es nur wollen

**Comment by Huhu123er123** [comment]
:)

ich muss allerdings nochmal nachhaken, wie referenziere ich denn überhaupt, dass ich genau BOSWatch neu möchte?
Sorry für mein Braindead. ❌

**Comment by flothi** [comment]
Das machst du mit dem git-Befehl, den du am besten im Verzeichnis /opt/ ausführst (wenn jemand einen besseren Weg kennt gerne, ich bin eher im SVN zu Hause)

**Comment by Huhu123er123** [comment]
Habe es jetzt mit
"cd /opt/boswatch/ git pull origin master" versucht, aber z.B. Dein Sms77 Change wird nicht übernommen.

**Comment by flothi** [comment]
Gibt er denn nach dem git pull ne Fehlermeldung aus?

**Comment by Huhu123er123** [comment]
Bei sämtlichen eigenständigen Versuchen ja, allerdings wird bei dem oben genannten nichts weiter angezeigt.

**Comment by flothi** [comment]
Benenn die Sms77.py probehalber mal um und schau, ob die neue heruntergeladen wird

**Comment by Huhu123er123** [comment]
Habe ich mal gemacht, es kommt keine "neue" SMS77. :/

Wenn ich den o.g. Befehl eingebe, wird - wie gesagt - nichts kommentiert, danach bin ich aber im Verzeichnis opt/boswatch/.
Gebe ich dann den Befehl git pull origin master ein, wird
"fatal: Not a git repository (or any of the parent directories): .git"
ausgespruckt.

**Comment by flothi** [comment]
Da ich auch gerade unterwegs bin muss ich raten
1 Wechsel nach /opt/BOSWatch
2. sudo git pull origin master

Ansonsten muss ich heute Abend am PC schauen

**Comment by Huhu123er123** [comment]
Leider kein Erfolg.
Trotzdem vielen Dank für die Mühen!! :)

**Comment by flothi** [comment]
Soo, also bei mir funktioniert folgende Sequenz:
`cd /opt/BOSWatch`
`sudo git pull origin [master|develop]` - den Branch musst du dir dann entsprechend aussuchen.

```
From https://github.com/Schrolli91/BOSWatch
 * branch            develop    -> FETCH_HEAD
Already up-to-date.
```

Wäre dann die Ausgabe, wenn alles geklappt hat. Weiterhin habe ich mir erlaubt, die Standard-CSV-Dateien im develop-Zweig umzubenennen, gerade damit diese beim Update nicht überschrieben werden.

**Comment by Huhu123er123** [comment]
Hallo,

danke nochmal! :)
Leider will es immer noch nicht hinhauen.
Kann es sein, dass es daran liegt, dass "BOSWatch" bei mir "boswatch" heißt?
Warum eigentlich? Habe es mit dem Installer aus der Master installiert.

Es kommt immer folgender Fehler:
"fatal: Not a git repository (or any of the parent directories): .git"
Sucht er da jetzt nach einer .git Datei? Diese gibt es bei BOSWatch ja gar nicht, oder?

LG

// Edit:
Habe vom Tipp gelesen, das gibt dann folgendes aus:
pi@raspberrypi:/opt/boswatch $ sudo git init
Initialisierte leeres Git-Repository in /opt/boswatch/.git/
pi@raspberrypi:/opt/boswatch $ sudo git pull origin master
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.
 :(

**Comment by flothi** [comment]
Korrekt, der Pfad lautet
`cd /opt/boswatch/` - Linux ist casesensitiv, Usus ist es, tendenziell die Kleinschreibung zu verwenden

Führ mal ein `ls -al` in dem Ordner `boswatch` aus, da müsstest du einen Ordner `.git` sehen

**Comment by Huhu123er123** [comment]
Genau, der ist da.
"drwxr-xr-x  6 root root  4096 Apr  6 16:14 exampleAddOns
drwxr-xr-x  7 root root  4096 Apr 20 08:36 .git
drwxr-xr-x  5 root root  4096 Apr  7 18:15 includes"

Allerdings bringt mich das ja nicht weiter. :(
Wo liegt denn der Fehler?
Könnte eine neue Installation helfen?

**Comment by flothi** [comment]
Zusammenfassend:
Hat es aufgrund deines Posts im anderen Issue dann geklappt?

Ich nehme an das Problem kam durch vermischen von Master und Develop?

**Comment by flothi** [comment]
Dann mache ich hier zu und vermerke das csv update separat

**Comment by Huhu123er123** [comment]
Hallo, nein, leider hat keine der hier aufgeführten Möglichkeiten eine Lösung gebracht.
Ich habe mich dann dazu entschieden die dev zu installieren und es beim nächsten Merge dann mal zu probieren.

Vermischt war nichts.
Ich hatte nur die Master installiert.

Vielen Dank trotzdem! :)

**Comment by KampfkeksMRZ** [comment]
Zwischenfrage:

Wir hatten zwischendrinne mal Unstimmigkeiten mit Verzeichnisnamen, da passte auch was nicht mit der Service-Script und dem Installationsverzeichnis. 
Da war auf meine Anfrage hin was geändert worden, ich erinnere mich aber nicht mehr genau was... Evt. müsste man hier dann noch mal ansetzen.

**Comment by KampfkeksMRZ** [comment]
Da sich im Dev ja schon mal was häufiger ändert: Wäre es denn nicht eine Überlegung wert, im Dev Branch den csv-Ordner zum gitignore hinzuzufügen?

**Comment by Schrolli91** [comment]
Was soll das bringen? die CSV Dateien haben ja jetzt auch ein `template` im Namen und müssen vor benutzung sowieso umbenannt werden, vondaher wird jetzt auch nix mehr überschrieben

**Comment by flothi** [comment]
Das "online"-Update der csv-Dateien (sprich Nachladen bei laufendem Programm) steht gerade auf meiner ToDo-Liste, Python bietet da glücklicherweise was an ;-)

**Comment by Schrolli91** [comment]
Hat sich da schon was ergeben? Schmeiß mal bitte eben ein Stichwort in den Raum, was Python diesbezüglich im Petto hat ;-)

**Comment by K3vP0** [comment]
Das hört sich sehr gut an, wäre da interessiert dran für meine Webseite :)

**Comment by Schrolli91** [comment]
PUSH - wie ist die Lage? ;-) Hat sich diesbezüglich schon etwas ergeben?

**Comment by flothi** [comment]
Ich experimentiere gerade mit pyinotify, aktuell noch in nem kleinen Testprogramm, die Tage versuche ich es mal in boswatch zu integrieren - ist also weiterhin in Arbeit.

**Comment by flothi** [comment]
So, ein Grundgerüst steht - allerdings stehe ich mit den Threads in Python etwas auf Kriegsfuß.

Die csv wird im laufenden Betrieb aktualisiert. allerdings führt die Beobachtung in des csv-Verzeichnis in einem separaten Thread dazu, dass Boswatch nicht mehr vernünftig schließt. Da würde ich gerne auf die vorhandene Fachexpertise zurückgreifen...

@Schrolli91 Haben wir eine Art Playground/Sandbox für solche Experimente?

**Comment by Schrolli91** [comment]
Versteh net ganz was du mit Sandbox meinst...

**Comment by flothi** [comment]
In meinen Augen ist die Datei für ein develop-pull-request zu unausgereift, ich würde sie aber gerne zur gemeinschaftlichen Arbeit freigeben

**Comment by Schrolli91** [comment]
Gemeinsam daran arbeiten kann man doch aber auch in einem PULL ... mergen darf man ihn eben nicht, bis er ausgereift ist ;-)
 Aber du kannst dir zum "spielen" auch eben noch einen weiteren Branch im Repo einrichten, die Berechtigung solltest du dazu ja haben

**Comment by flothi** [comment]
Dann mach ich mal den pull fertig, sonst wirds unübersichtlich ;)

**Comment by Schrolli91** [comment]
da das ganze im Pull ja jetzt angestoßen ist, schließe ich hier mal
