### ISSUE TITLE
no valid FMS wenn Wachenkennung A/B/C

### ISSUE THREAD

**Issue by seaforester** [Schrolli91/BOSWatch#264]
SW2.2 2017/03/30 Master.

Laut Bosmon ist die Fahrzeugkennung z. B. 1A11A461 für 10-46-1
 Die Log zeigt aber konstant (und nur) bei 10/A 11/B 12/C falsche FMS an:
 1A11B461 :
21.04.2017 16:46:14 - decoder         [DEBUG   ] received FMS
21.04.2017 16:46:14 - fms             [WARNING ] No valid FMS: 1a111146

**Comment by flothi** [comment]
Die Meldung "No valid FMS" ist leider nur mäßig aussagekräftig; die FMS-Auswertung mit Stick, rtl_fm und multimon_ng ist meiner Meinung nach recht fehlerbehaftet - Bitfehler sind eher die Regel denn die Ausnahme.
Welche Eingabequelle nutzt du denn für Bosmon? Scanner?

**Comment by seaforester** [comment]
Ja, Scanner. Wobei die Abfolge auch nach Definition von FMS so sein muss wie in Bosmon empfangen. 
Da die FMS Code aller anderen Wachenkennungen perfekt funktioniert und die A/B/C konstant falsch liegen, würd ich eher von einem Programmierfehler (multimon_ng?) ausgehen, denn Empfangsfehler. 

Ein ähnlicher Fehler bestand bis vor kurzem ja auch bei der Ortskennung...

**Comment by flothi** [comment]
Bei den Ortskennungen waren die beiden Positionen schlicht verdreht, das war also lediglich ein Umschubsen.
Hier scheint, bei deinem Beispiel, die '11' anstatt einem 'A' zu stehen - hast du einen Auszug von der multimon_raw.txt, den du posten kannst?

**Comment by seaforester** [comment]
Die ausgegebene FMS ist ja auch um eine Zeile verschoben:
1A11B461
1a111146

log/mm_raw.txt ? Kommt, sobald da ein entsprechender Eintrag drin ist.

**Comment by seaforester** [comment]
`FMS: 015f164b0000 (FZG 11461	Status f=AutomatQuittun	1=LST->FZG	3=IV (mit NA,mit SIGNAL)	) CRC correct`

`FMS: 745e164b0000 (FZG 11461	Status e=KurzTXT E     	1=LST->FZG	3=IV (mit NA,mit SIGNAL)	) CRC correct`
`FMS: eef3164b0000 (FZG 11461	Status 3=Einsatz Ab    	0=FZG->LST	2=III(mit NA,ohneSIGNAL)	) CRC INCORRECT`

`FMS: 745e164b0000 (FZG 11461	Status e=KurzTXT E     	1=LST->FZG	3=IV (mit NA,mit SIGNAL)	) CRC correct`

`FMS: 5253164b0000 (FZG 11461	Status 3=Einsatz Ab    	0=FZG->LST	2=III(mit NA,ohneSIGNAL)	) CRC correct`

`FMS: bdff164b0000 (FZG 11461	Status f=AutomatQuittun	1=LST->FZG	3=IV (mit NA,mit SIGNAL)	) CRC INCORRECT`

`FMS: 5253164b0000 (FZG 11461	Status 3=Einsatz Ab    	0=FZG->LST	2=III(mit NA,ohneSIGNAL)	) CRC correct`

`FMS: bdff164b0000 (FZG 11461	Status f=AutomatQuittun	1=LST->FZG	3=IV (mit NA,mit SIGNAL)	) CRC INCORRECT`

`FMS: 2a55164b0000 (FZG 11461	Status 5=Fahre Wache   	1=LST->FZG	2=III(mit NA,ohneSIGNAL)	) CRC correct`

`FMS: bdff164b0000 (FZG 11461	Status f=AutomatQuittun	1=LST->FZG	3=IV (mit NA,mit SIGNAL)	) CRC INCORRECT`

`FMS: 2a55164b0000 (FZG 11461	Status 5=Fahre Wache   	1=LST->FZG	2=III(mit NA,ohneSIGNAL)	) CRC correct`

`FMS: bdff164b0000 (FZG 11461	Status f=AutomatQuittun	1=LST->FZG	3=IV (mit NA,mit SIGNAL)	) CRC INCORRECT`

`FMS: 015f164b0000 (FZG 11461	Status f=AutomatQuittun	1=LST->FZG	3=IV (mit NA,mit SIGNAL)	) CRC correct`

`FMS: 1656164b0000 (FZG 11461	Status 6=Sprechaufford 	1=LST->FZG	2=III(mit NA,ohneSIGNAL)	) CRC correct

FMS: bdff164b0000 (FZG 11461	Status f=AutomatQuittun	1=LST->FZG	3=IV (mit NA,mit SIGNAL)	) CRC INCORRECT

FMS: 1656164b0000 (FZG 11461	Status 6=Sprechaufford 	1=LST->FZG	2=III(mit NA,ohneSIGNAL)	) CRC correct

FMS: bdff164b0000 (FZG 11461	Status f=AutomatQuittun	1=LST->FZG	3=IV (mit NA,mit SIGNAL)	) CRC INCORRECT`

**Comment by flothi** [comment]
Hast du in der Ausgabe was geschnitten? Da fehlen u.a. OrgKenner, Bundesland und Ortskennung

**Comment by seaforester** [comment]
Richtig, habe ich. Falls die nötig sind, schick ich die gerne per Mail. Werden jedoch korrekt ausgewertet.
Hier nochmal das gleiche Spiel mit C/12:
`FMS: f755134c0000 (FZG 12431	Status 5=Fahre Wache   	1=LST->FZG	2=III(mit NA,ohneSIGNAL)	) CRC INCORRECT`
`FMS: e0ff134c0000 (FZG 12431	Status f=AutomatQuittun	1=LST->FZG	3=IV (mit NA,mit SIGNAL)	) CRC INCORRECT`
`FMS: fa52134c0000 (FZG 12431	Status 2=Bereit Wache  	0=FZG->LST	2=III(mit NA,ohneSIGNAL)	) CRC INCORRECT`
`FMS: e0ff134c0000 (FZG 12431	Status f=AutomatQuittun	1=LST->FZG	3=IV (mit NA,mit SIGNAL)	) CRC INCORRECT`

**Comment by flothi** [comment]
Schick mal die vollständigen Daten bitte an boswatch@thillmann.de - Danke!

**Comment by flothi** [comment]
Also, das "Problem" ist, dass multimon-ng aus dem A eine 10 macht und somit das Feld "FZG" von 4 auf 5 Stellen anwächst. Dies entspricht folglich nicht mehr der TR.

Ich werde das mal anpassen

**Comment by seaforester** [comment]
Vielen Dank, mit der [Anpassung von multimon-ng](https://github.com/Schrolli91/multimon-ng/pull/2) funktioniert die Auswertung!
