### ISSUE TITLE
Multiple Boswatch

### ISSUE THREAD

**Issue by Hinken** [Schrolli91/BOSWatch#266]
Hi, i have a quick question. Im currently running one raspberry pi with one dongle and it works great. But I'm planning to have multiple dongles to one raspberry. My question is. How do I easiest do that. Is it simple just best to have multiple installations of boswatch?

**Comment by flothi** [comment]
Yes, you can easily do this.
Remember that you have to start Boswatch with the -d switch in order to select the specific device.

Due to installation it might be the best way do just install it once and copy the folder /opt/boswatch to e.g. boswatch1 to... n

**Comment by flothi** [comment]
Did you manage to run several instances of Boswatch?

**Comment by Hinken** [comment]
Hi and thanks. Yes I received more receivers yesterday and i did what you just sad and it works perfekt. So thank you so much.
