### ISSUE TITLE
Install.sh | Installation in etc &service

### ISSUE THREAD

**Issue by K3vP0** [Schrolli91/BOSWatch#27]
Installation in den Stammordner /etc/ und Verknüpfung zu init.d

**Comment by JHCD** [comment]
Hier ein HowTo, um das Skript als Dienst zu starten:
http://blog.scphillips.com/posts/2013/07/getting-a-python-script-to-run-in-the-background-as-a-service-on-boot/

**Comment by JHCD** [comment]
Btw: Installation des Programms sicherlich nicht nach /etc, sondern sondern wenn dann richtig nach usr/local.

**Comment by JHCD** [comment]
Im Develop-Zweig liegt jetzt eine BOSWatch-Version, die als Dienst gestartet werden kann.
Die Installation des Dienstes ist allerdings händisch.

Develop-Version herunterladen, am besten ins Verzeichnis `/usr/local/bin/BOSWatch` kopieren und dann den Dienst einrichten, siehe `service/README.md`

**Comment by Schrolli91** [comment]
Damit wäre das geklärt - closed
Falls ein Problem mit dem Dienst besteht bitte eine neue Issue als "Bug" öffnen ...
