### ISSUE TITLE
Character ü

### ISSUE THREAD

**Issue by Hinken** [Schrolli91/BOSWatch#272]
Hi, i have a small "problem". Here in my country there I live we have a letter, that is: å, Å. With BOSWatch "å" is showing as "ü". Is it possible to do a easy fix. The computer itself is in the right language and "å", "Å" works everywhere else.

Thanks.

**Comment by flothi** [comment]
Where is this character displayed incorrect? Within the Plug-ins or the log file?

**Comment by Hinken** [comment]
In both log files and plugins like pushover, email, mySQL and so on.

**Comment by flothi** [comment]
It sounds as if the conversation to utf8 has to be implemented in the messages. I will have a look at it

**Comment by flothi** [comment]
Ok, I tested it with an å in the message, it was displayed correctly in the logfiles.

Can you please report what is written in "LANG" when you execute `locales` in the shell.

**Comment by Hinken** [comment]
pi@raspberrypi:~ $ locale
LANG=sv_SE.UTF-8
LANGUAGE=
LC_CTYPE="sv_SE.UTF-8"
LC_NUMERIC="sv_SE.UTF-8"
LC_TIME="sv_SE.UTF-8"
LC_COLLATE="sv_SE.UTF-8"
LC_MONETARY="sv_SE.UTF-8"
LC_MESSAGES="sv_SE.UTF-8"
LC_PAPER="sv_SE.UTF-8"
LC_NAME="sv_SE.UTF-8"
LC_ADDRESS="sv_SE.UTF-8"
LC_TELEPHONE="sv_SE.UTF-8"
LC_MEASUREMENT="sv_SE.UTF-8"
LC_IDENTIFICATION="sv_SE.UTF-8"
LC_ALL=


Another thing. This is exactly the same if I buy like a Swissphone or another pager from Germany. Our Å in Sweden is also then showd as ü in the pager.

--------

When I run pdw, I did this in the "language.df" file. Several years a go.

#
# SWEDISH
# Character re-mapping for the Swedish language.

[NEW TABLE]

LANGUAGE=Swedish
REVERSED=0

91=196
92=214
93=197
123=228
124=246
125=229
-

Mayby I can do something like this now? 

https://www.w3schools.com/html/html_charset.asp

Something like this:

252=229
220=197

But I have no idea if it is possible to do that in "linux" or so.

**Comment by Smeti1** [comment]
Die Umlaute haben bei den Beispiel PHP Dateien ein Problem
nachdem ich jetzt eine halbe Stunde nach dem Fehler gesucht habe (in der MySQL Datenbank stimmt alles)
habe ich jetzt mal kurz und schmerzlos direkt nach dem aufbau der Datenbank in der 
**Index.php**  das utf-8 eingestellt: **mysql_query("SET NAMES 'UTF8'");**


Beispiel - index.php
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.$
<?php
require_once ("config.php");
require_once ("parser.php");
require_once ("mysql.class.php");
$db = new Database($dbhost, $dbuser, $dbpassword, $database, 1); //Show Error = 1!
mysql_query("SET NAMES 'UTF8'");
?>
...........................
```

**Comment by Schrolli91** [comment]
@flothi wenn ich das also Richtig verstehe, konntest du das Problem gar nicht selbst reproduzieren?

**Comment by Smeti1** [comment]
Hi Bastian

doch ich hatte das Problem daß mit dem Simple Web "Demo"
alle umlaute so komisch angezeigt wurden
(Firefox, Edge, Opera, Vivaldi und chrome)

wenn man beim Firefox  Ansicht -> Textcodierung von Unicode auf westlich stellte hatte man die Umlaute Richtig nur leider nach einem Reload sprang der FF  wieder auf Unicode zurück und wieder diese Zeichen

na dann mal alles probiert im PHP code auf der index.php, in den einzelnen PHP Aufbereitungsseiten

keine Change  dann bin ich netz auf die Holzhammermethode gestoßen   gleich nach dem Aufbau der Datenbank die Zeichencodierung umstellen

ja und siehe da alles bestens. geht jetzt super

 PS im MySQL  sind die umlaute richtig drinnen

 
Übrigens Danke für dein tolles Programm. habe es ja erst seit 4 Wochen und möchte es gar nicht mehr missen

das einzige was ich noch rausbekommen muß ist bei uns kommt alle 2std. 13minuten eine "Relaistestschleife" und NUR die würde ich gerne in der WEB anzeige rausfiltern.  In der Datenbank soll es stehenbleiben und beim Telegramm muß es auch  kommen damit ich weiß das zu Hause alles in Ordnung ist. 

muß mich mit der Struktur deiner PHP Dateien noch ein bisserl anfreunden :-)

Gruß Smeti

Von: Bastian Schroll [mailto:notifications@github.com] 
Gesendet: Montag, 18. September 2017 19:57
An: Schrolli91/BOSWatch
Cc: Smeti1; Comment
Betreff: Re: [Schrolli91/BOSWatch] Character ü (#272)

 

@flothi <https://github.com/flothi>  wenn ich das also Richtig verstehe, konntest du das Problem gar nicht selbst reproduzieren?

**Comment by flothi** [comment]
Wir müssen hier wohl trennen zwischen Webinterface und Datenbank - mit den Rohdaten hatte ich bis dato keine Probleme, schwedisch ist aber nicht meine Muttersprache ;-)

**Comment by Schrolli91** [comment]
Alle aktuellen Web-Frontend Daten sind derzeit sowieso überholt und werden im Laufe der nächsten Versionen entfernt. Es soll ein neues Web-Frontend aufgesetzt werden.

Durchaus möglich, dass hier Probleme auftreten - wurde ewig nicht gewartet.

Das eigentlich Umlaut Problem bestand ja innerhalb von BOSWatch und den Plugins.
Und ich wüsste gerne, ob dies dort auftritt? Stehen die Umlaute richtig in der Datenbank?

**Comment by Smeti1** [comment]
im MySQL sind die Umlaute richtig drinnen
UTF-8 alles bestens

nur bei der Aufbereitung im PHP kommt der Fehler bei mir zustande

**Comment by Schrolli91** [comment]
Dann ist das Problem so, wie vom Issue Ersteller genannt, also hier nicht reproduzierbar... Was machen wir? Closed? @flothi

**Comment by flothi** [comment]
@Schrolli91
An der Stelle machen wir nen Deckel drauf
