### ISSUE TITLE
alarmMonitorWeb

### ISSUE THREAD

**Issue by fwmarcel** [Schrolli91/BOSWatch#273]
Und zwar hätte ich bezüglich der Beispiel Anwendung alarmMonitorWeb noch ein paar fragen..
Nach der Installation tauchen dauerhaft Fehler auf. Zum einen funktioniert das Einloggen nicht. Error 500 tritt immer wieder auf. Zum anderen scheint mir, dass diese Anwendung auch noch auf eine ältere Version zugeschnitten ist, sodass Filter und ähnliches nicht schön funktionieren. Ich würde mich über eine Lösung vom Ersteller oder jedem anderen php und html Fähigen freuen...

**Comment by flothi** [comment]
Ich behaupte mal der müsste dringend angepasst werden - wahrscheinlich ist der im Zuge der Anpassungen sehr stiefmütterlich links liegen gelassen worden.

@Schrolli91 - macht es Sinn, für diese Art der Erweiterungen ein extra Repo aufzusetzen?

**Comment by Schrolli91** [comment]
@flothi die Weboberfläche sollte komplett neu entwickelt werden - das ist teils brutaler Frickelstand
Zeitlich ist bei mir aktuell aber leider nicht viel drin, zwecks Technikerausbildung.

Ein eigenes Repo wäre nur sinnvoll, wenn man das ganze dann wirklich groß aufzieht, für ein kleines feines Webend würde vermutlich ein eigener Branch reichen, den man per installer zieht.

**Comment by flothi** [comment]
Dann würde ich die Branch-Lösung befürworten, dann stiftet das weniger Verwirrung ;-)

**Comment by K3vP0** [comment]
Na wer sagt den zu meinem dahingerotze Frickelstand. :P ....

Es gibt eine neue Version die ich noch nicht veröffentlicht habe.

Habe jetzt damit 3-4 Installationen laufen die alle zufriedenstellend laufen. 

MERGE kommt die Tage...

**Comment by Schrolli91** [comment]
:-D sorry so war das nicht gemeint ;-)

Ich close das hier derweil - wir sollten evtl auch mal die ganzen alten Sachen die mit Weboberfläche zu tun haben aus dem Repo entfernen

**Comment by Schrolli91** [comment]
siehe auch #163
