### ISSUE TITLE
Signal Ric

### ISSUE THREAD

**Issue by fwmarcel** [Schrolli91/BOSWatch#275]
Bei dem Signal RIC werden in die Tabelle nur 6 Stellen der 7 stelligen RIC eingetragen. Bei mir wird die erste 0 am Anfang der Signal RIC verschluckt.

**Comment by flothi** [comment]
Ich schau mal woran es liegt

**Comment by fwmarcel** [comment]
@flothi Gibts da schon was neues dazu ?

**Comment by flothi** [comment]
Ich bin dran, Zeit ist aktuell ein kostbares Gut...

**Comment by jbollacke** [comment]
Was genau ist denn mit Signal RIC gemeint?

**Comment by flothi** [comment]
Es gibt Netzkennungen, zum Teil hersteller-, zum Teil netzspezifisch. Verwendet werden sie als Signalisierung zB für den Feldstärkealarm.

Die RIC eines Herstellers beginnt mit 017..., da wird aktuell die führende null nicht in dir Datenbank übernommen - dürfte ein simples casting-Problem sein

**Comment by jbollacke** [comment]
@fwmarcel Auf welchem Commit (`git rev-parse HEAD` im BOSWatch-Verzeichnis) bist du?

**Comment by fwmarcel** [comment]
@jbollacke Ich verwende den aktuellen Master

**Comment by flothi** [comment]
Also ich habs mir nochmal angeschaut, eine mögliche Ursache ist das Format der Spalte "ric" in der Datenbank.
Ändere ich diese auf `int(7) zerofill` wird die fehlende Null ergänzt - wenn da nichts gegenspricht würde ich das in der sql-Datei entsprechend anpassen.

**Comment by PeterLaemmle** [comment]
Wenn ich den RIC in der Datenbank von Hand um die führende Null ergänze, bleibt er so drin und es wird nur der Zeitstempel aktualisiert.
Das Problem scheint also beim Anlegen des Eintrags aufzutreten. Warum, ist mir aber nicht klar.

**Comment by flothi** [comment]
Aufgefallen sind mir auch (zumindest in meiner Datenbank) mehrere Einträge - evtl hängt das mit #244 zusammen

Wenn ich mir `data["ric"]` anschaue, ist dies korrekt mit führender Null. Es würde mich wundern,wenn die im insert verloren geht

**Comment by PeterLaemmle** [comment]
Müssen wir das UPDATE und INSERT umdrehen?
Pseudocode:
```
if tableSIG is empty:
     INSERT
else:
     UPDATE
```

**Comment by flothi** [comment]
Unzählige müde Augen später - zwei Hochkommata retten das Ganze; gefixed
