### ISSUE TITLE
Bug: service restart

### ISSUE THREAD

**Issue by fwmarcel** [Schrolli91/BOSWatch#276]
Nachdem ich mein System einmal frisch neuinstalliert habe tritt folgender Fehler auf. Wenn ich den service boswatch restarte tritt dieser fehler auf. Die Lösung ist schon im Dev vorhanden. Nur sollte sie auch in den Master verschoben werden, da die meisten ja auch den Master installieren und nutzen..

`Traceback (most recent call last):
  File "/opt/boswatch/boswatch.py", line 323, in <module>
    checkSubprocesses.checkRTL()
  File "/opt/boswatch/includes/checkSubprocesses.py", line 27, in checkRTL
    raise OSError("starting rtl_fm returns an error")
OSError: starting rtl_fm returns an error`

**Comment by Schrolli91** [comment]
Prinzipiell gebe ich dir recht, aber das haben wir beim letzten mal schon gemacht, und dann einen völlig inkonsistenten Stand produziert.
Im "echten" Leben ist es ja auch so, dass man mit einem Bug bis zum nächsten Release leben muss :-D

**Comment by fwmarcel** [comment]
@Schrolli91 das mag ja sein. Es schadet ja nicht den service in beiden Versionen drin zu haben.

**Comment by flothi** [comment]
Die Version 2.3 ist quasi, wenn ich mir die Roadmap anschaue, in den startlöchern.

Der Service funktioniert per se, wenn das jetzt gar nicht klappen würde wäre ich auch für ein direktes Pärchen des Masters.
So geht mir allerdings ein ausgiebiges Testen des Develop eindeutig vor
