### ISSUE TITLE
Exception-Handling in PlugIns

### ISSUE THREAD

**Issue by JHCD** [Schrolli91/BOSWatch#28]
Wenn PlugIn A eine Exception wirft, kann es passieren, dass das PlugIn B nicht mehr aufgerufen wird.
Lösung: try-cath-Block in alarmHandler.py `plugin.run(typ,freq,data)` mit `exception: pass`

**Comment by Schrolli91** [comment]
Schau ich mir bei Gelegenheit mal an ...

**Comment by JHCD** [comment]
Habe ich beim Umbau des Exception-Handlings gleich mit erledigt.
