### ISSUE TITLE
Facebook Gruppe

### ISSUE THREAD

**Issue by ghost** [Schrolli91/BOSWatch#281]
Da hier immer wieder Diskussionen zu Foren und Facebook Gruppen aufkamen, habe ich einfach mal eine erstellt:
www.facebook.com/groups/BOSWatch

Gerne dürfen sich die "Offiziellen" hier melden, diese bekommen dort dann die entsprechende Rechte.

Bis dahin! :)

_/edit: Hyperlink hinzugefügt / Text ergänzt._

**Comment by Schrolli91** [comment]
Nette Idee - Danke 
Ich werde den Link mal noch auf der Github Startseite irgendwo unterbringen

**Comment by ghost** [comment]
Prima!
6 Mitglieder nach 2 Stunden - nur per Issue - finde ich gar nicht mal schlecht. :)

**Comment by Schrolli91** [comment]
Man sollte hier vielleicht erwähnen, das die Gruppe auf geheim steht, wer beitreten möchte, soll sich hier also mal kurz melden ;-)

**Comment by TobiasM112** [comment]
Würde auch dazukommen 😃

**Comment by Schrolli91** [comment]
Da bräuchte ich einen FB-Namen um dich hinzufügen zu können... ich lösche deinen Beitrag dann direkt, nachdem ich dich hinzugefügt habe...

**Comment by TobiasM112** [comment]
https://www.facebook.com/TobiMerkel

**Comment by Schrolli91** [comment]
Und ein weiteres mal lerne ich Facebook lieben - nicht!
Scheinbar kann ich keine Leute hinzufügen mit denen ich nicht befreundet bin, bzw mit denen ich nicht mind. einen gemeinsamen Freund habe...
Irgendwie finde ich das mit der geheimen Gruppe in dem Fall eher sehr suboptimal... :-/

**Comment by Schrolli91** [comment]
Wie ich grad erfahren hab, brauch ich die Mail adresse zum einladen... aber die hier öffentlich zu posten halte ich auch für Grenzwertig ... Jemand ne Idee wie man das halbwegs SpamBot sicher über die Bühne bringen kann?

**Comment by ghost** [comment]
Derjenige könnte uns (Schrolli, flothi, oder mich) per PN bei Facebook anschreiben.

**Comment by nevrrmind** [comment]
Ich würde mich auch gern daran beteiligen. Nur, wie finde ich euch auf FB?

**Comment by Schrolli91** [comment]
Über das Forum kann zur Not auch eine PN an uns gesendet werden - Schade das Github keine PN Funktion anbietet...

Ansonsten - ich bin auf Facebook zu finden unter - Bastian Schroll
Mein Name ist ja kein Geheimnis, steht in nahezu jeder Quellcodedatei :-D
