### ISSUE TITLE
Tester

### ISSUE THREAD

**Issue by Blaine2k** [Schrolli91/BOSWatch#282]
Hellas. 
Bin Nutzer in einem EuroBOS Netz incl. Key.
Stehe als Tester gerne zur Verfügung. 
;)

**Comment by thejockel** [comment]
Moin :)
Super.
Ich nutze auf meinem Test-System den Beta-Branch.

Falls zu Fehler findest, bitte zu diesen einen neuen Issue erstellen bzw. einen bestehenden updaten.

Daher hier erstmal closed.

Gruß
Jockel

**Comment by flothi** [comment]
Ich glaube es ging eher um den Aufruf zur Implementierung der Entschlüsselung, daher mache ich mal wieder auf.

@Blaine2k Super, dann kannst du mir bitte mal ne Mail an boswatch@thillmann.de schicken?
