### ISSUE TITLE
eMail kommt für FMS-Codes obwohl kein Filter hierzu angelegt

### ISSUE THREAD

**Issue by Rumbel84** [Schrolli91/BOSWatch#283]
In der Config sind folgende Filter:
Email bei ausgewählten ZVEI-Codes
MySQL bei allen ZVEI Codes
MySQL bei allen FMS-Codes 

Bei FMS-Codes kommt aber dennoch eine Email.

Fehler:
regexFilter.py 
Zeile: 92 			return True  #müsste False sein

Hätte ich einen Filter angelegt, der zwar generell passt aber nur beim RegEx scheitert, käme Zeile 88 zum Tragen (korrekt return False)
Da ich aber keinen Filter habe kommt Zeile 92 und hier müsste ebenso false stehen. :-D

Log:

> 23.05.2017 20:42:15 - boswatch        [INFO    ] Testdata: FMS: 43f314170000 (9=Rotkreuz       3=Bayern 1         Ort 0x25=037FZG  7141Status  3=Einsatz Ab     1=LST->FZG 2=I  (ohneNA,ohneSIGNAL)) CRC correct
> 23.05.2017 20:42:15 - decoder         [DEBUG   ] received FMS
> 23.05.2017 20:42:15 - doubleFilter    [DEBUG   ] checkID: 9325714131 ()
> 23.05.2017 20:42:15 - fms             [INFO    ] FMS:93257141 Status:3 Richtung:1 TSI:I
> 23.05.2017 20:42:15 - alarmHandler    [DEBUG   ] [  ALARM  ]
> 23.05.2017 20:42:15 - regexFilter     [DEBUG   ] search Filter for FMS to eMail at 85235000 Hz
> 23.05.2017 20:42:15 - regexFilter     [DEBUG   ] no Filter found
> 23.05.2017 20:42:15 - alarmHandler    [DEBUG   ] call Plugin: eMail
> 23.05.2017 20:42:15 - configHandler   [DEBUG   ] read [eMail] from config file
> 23.05.2017 20:42:15 - configHandler   [DEBUG   ]  - smtp_server = smtp.gmail.com

Ich bin komplett neu bei Github und Programmiere nie Python (Perl, C, C++, ...).
Dennoch bin ich mir da aber relativ sicher, daher bereits per Pull-Request die Korrektur gemeldet.
Bitte reviewen. :-)

**Comment by Rumbel84** [comment]
In der Config sind folgende Filter:
Email bei ausgewählten ZVEI-Codes
MySQL bei allen ZVEI Codes
MySQL bei allen FMS-Codes 

Bei FMS-Codes kommt aber dennoch eine Email.

Fehler:
regexFilter.py 
Zeile: 92 			return True  #müsste False sein

Hätte ich einen Filter angelegt, der zwar generell passt aber nur beim RegEx scheitert, käme Zeile 88 zum Tragen (korrekt return False)
Da ich aber keinen Filter habe kommt Zeile 92 und hier müsste ebenso false stehen. :-D

**Comment by Schrolli91** [comment]
das wäre soweit eigentlich aber Richtig - zumindest nach der damaligen Denke, als es entwickelt wurde..

Die Idee war, alles was per RegEx an ist wird gefilltert, wenn der Filter nicht passt False...
Wird für etwas gar kein Filter gefunden gibts ein True, da die ensprechende Funktion ja NICHT befiltert ist

**Comment by Rumbel84** [comment]
Es liefert leider aber auch True, wenn gar kein Filter existiert

**Comment by Schrolli91** [comment]
Richtig - weil die entsprechende Funktion NICHT befiltert wird... Filter ist in dem Fall "ausfiltern"
Will ich nix ausfiltern auf FMS kommt alles durch

So war zumindest damals der Gedanke

**Comment by Rumbel84** [comment]
im Fall ohne Regexfilter kommt man ja gar nicht in diese Funktion rein

```
if globalVars.config.getint("BOSWatch","useRegExFilter"):
				from includes import regexFilter
				if regexFilter.checkFilters(typ, data, pluginName, freq):
					logging.debug("call Plugin: %s", pluginName)
					try:
						plugin.run(typ, freq, data)
						logging.debug("return from: %s", pluginName)
					except:
						# call next plugin, if one has thrown an exception
						pass
			else: # RegEX filter off - call plugin directly
				logging.debug("call Plugin: %s", pluginName)
				try:
					plugin.run(typ, freq, data)
					logging.debug("return from: %s", pluginName)
				except:
					# call next plugin, if one has thrown an exception
					pass
```

**Comment by Schrolli91** [comment]
Ja es könnte aber sein ich möchte ZVEI nur an bestimmt Plugins weiterleiten, den Rest aber komplett passieren lassen

siehe https://github.com/Schrolli91/BOSWatch#filtering-functions-regex
`No filter for a combination typ/plugin = all data will pass`

So war es damals geplant, über eine Änderung kann man sich natürlich hier gerne nochmal austauschen.
@flothi @thejockel was meint Ihr denn dazu?

**Comment by Rumbel84** [comment]
Daher hatte ich auch einen FMS-Filter mit Email angelegt und einer komplett falschen Frequenz damit der auch auf keinen fall verwendet wird. :-)

**Comment by Rumbel84** [comment]
Zur info noch meine Filter (anonymisiert und Zahlen geändert=
AAAZVEIEMail = ZVEI;zvei;eMail;*;1234[0-9]
BBBZVEIeMail = ZVEI;zvei;eMail;*;1235[1-2]
CCCZVEIeMail =  ZVEI;zvei;eMail;*;45678
DDDZVEIeMail = ZVEI;zvei;eMail;*;78945

AlleFMSMySQL = FMS;fms;MySQL;*;.*
KeineFMSeMail = FMS;fms;eMail;12345678;TESTTESTNIXRAUS

der letzte war eben zum testen, da ich mit dem -t parameter immer auch die FMS-Codes per EMail bekommen hab... und das wird mir zu viel spam ;-)

**Comment by Schrolli91** [comment]
Ja ich wäre Prinzipiell für eine Änderung zu haben, da man RegEx ja global aktivieren/deaktivieren kann, wäre es durchaus sinnvoll das Filtern "hart" zu machen, also wirklich nur weiterleiten, was auch explizit zugelassen ist

**Comment by Rumbel84** [comment]
Gäbe es sonst eine anderen Alternative, um die FMS-Emails zu deaktivieren?

Ich will eigentlich nur: ausgewählte ZVEI per Email, alle ZVEI und FMS in MySQL
(Evtl später mal die FMS-Codes ausgewählter Fahrzeuge auch per Mail)


Edit: Frage selber beantwortet
Mit einem Filter wie
`Test = FMS;fms;*;*;WIRRER TEXT DER NIEMALS PASST`
könnte ich das senden wohl auch umgehen da ein Filter gefunden wird und nur der Regex nicht matcht.

**Comment by Rumbel84** [comment]
> Ja es könnte aber sein ich möchte ZVEI nur an bestimmt Plugins weiterleiten, den Rest aber komplett passieren lassen
ja stimmt

Ist halt die Frage, ob du WhiteList oder BlackList willst.
Ich bin eher der Blacklist-Fan: alles Verbieten und das aktivieren, was man auch wirklich möchte :-)

Nur ZVEI an bestimmte Plugins und FMS an alles geht ja auch
`WhiteListFMS = FMS;fms;*;*;.*`

**Comment by Schrolli91** [comment]
Also es hat sich zwar bisher niemand dazu geäußert... ich halte es - im nachhinein betrachtet - absolut für sinnvoller ;-)

Ich baue das nun also entsprechend um, und werde einen Hinweis in der readme einfügen.

**In Zukunft ist bei aktiviertem RegEX Filter ALLES verboten, außer ich lasse es explizit zu**
