### ISSUE TITLE
FORUM online - http://boswatch.tk/

### ISSUE THREAD

**Issue by Schrolli91** [Schrolli91/BOSWatch#287]
Absofort gibts ein Forum zum Austausch bei Problemen und zu Absprache für die Weitere Entwicklung.

Zu finden ist das gute Stück unter:
http://boswatch.tk/

Vielen Dank nochmal an `SieSpricht`

Das Forum befindet sich allerdings noch im Aufbau

**Comment by ghost** [comment]
Kein Problem! :P
Wünsche, Anregungen und Kritik sind übrigens sehr gern gesehen.

**Comment by ghost** [comment]
Guten Abend,

ab morgen Mittag sind wir auch unter boswatch.de erreichbar. :)
Eventuell wird von phpBB auf Woltlab gewechselt.
