### ISSUE TITLE
Installation Fehlermeldung

### ISSUE THREAD

**Issue by 1nt4x** [Schrolli91/BOSWatch#289]
Hallo,
folgende Fehlermeldung tritt bei Installation von master/beta/dev Version auf:
(setup_log.txt)
E: Unable to locate package qt4-default
Action: download on other stuff failed.
Exitcode: 100

**Comment by Schrolli91** [comment]
Könntest du bitte mal den gesamten setup log auf https://pastebin.com/ hochladen?

**Comment by 1nt4x** [comment]
setup log:
https://pastebin.com/EVQHx7Vh

Edit: installation war nun erfolgreich, Pi neu aufgesetzt.
