### ISSUE TITLE
qt4-default kann nicht gefunden werden

### ISSUE THREAD

**Issue by jokeeen** [Schrolli91/BOSWatch#291]
Hallo,
irgendwie will die Installation bei mir nicht klappen:
`Paketlisten werden gelesen...
Paketlisten werden gelesen...
Abhängigkeitsbaum wird aufgebaut....
Statusinformationen werden eingelesen....
E: Paket qt4-default kann nicht gefunden werden.
Action: download on stuff failed.
Exitcode: 100
`
Auch manuell kann ich qt4-default nicht installieren:
`sudo apt-get install qt4-default
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
E: Paket qt4-default kann nicht gefunden werden.
` 
Hat jemand eine Idee an was das liegen kann?

**Comment by flothi** [comment]
Servus,

Hast du mal ein `apt-get update` zusätzlich laufen lassen? Welche Version des Betriebssystems nutzt du?

**Comment by thejockel** [comment]
Moin,
bei mir hat dort die Installation von qt5 geholfen

`apt-get install -y qt5-qmake qt5-default`

**Comment by flothi** [comment]
Dann sollten wir dringend das install-Skript anpassen, wenn qt4 rausgeflogen ist.

**Comment by jokeeen** [comment]
Wow, das ging ja schnell :-)

qt5 findet er auch nicht:
```
sudo apt-get install qt5-qmake
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
E: Paket qt5-qmake kann nicht gefunden werden.
```
Zur Version:
```
cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 7 (wheezy)"
NAME="Raspbian GNU/Linux"
VERSION_ID="7"
VERSION="7 (wheezy)"
ID=raspbian
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

**Comment by flothi** [comment]
Auch nicht mit einem Update vorweg?

**Comment by jokeeen** [comment]
Macht ja der boswatch-installer schon. Aber auch manuell entliche Male update und upgrade gemacht.

**Comment by flothi** [comment]
Dann auch mal bitte nach dem Paket:
`sudo apt-cache search qt5`

**Comment by jokeeen** [comment]
```
sudo apt-cache search qt5
libmgl-qt5 - library for scientific graphs. (Qt runtime library)
```

**Comment by jokeeen** [comment]
Was mir grad so auffällt:
ich hab ja noch "Wheezy".
Wäre sicherlich nicht verkehrt mal auf "Jessie" zu wechseln?

**Comment by thejockel** [comment]
Genau Jessie oder den wheezy-backports als repo mit aufnehmen.

`echo "deb http://ftp.debian.org/debian jessie-backports main" >> /etc/apt/sources.list.d/backports.list`

**Comment by jokeeen** [comment]
Kaum macht man's richtig gehts.... Danke für die Hilfe :-)

**Comment by thejockel** [comment]
Hast du es mit den backports gelöst?

**Comment by jokeeen** [comment]
Nein, ich habe ein Upgrade auf Jessie gemacht. Ist allerdings sehr aufwenig und hat nur bei einem von zwei Himbeeren geklappt.
Neuinstallation wäre wohl deutlich schneller gegangen.
