### ISSUE TITLE
Bosmon suffix in Plugin

### ISSUE THREAD

**Issue by einmalacht** [Schrolli91/BOSWatch#293]
Hallo zusammen,
ich sende mit mehreren Boswatch zu Bosmon und trag immer im plugin manuell einen Suffix ein:

in der Zeile 177 (meineINFO )
params = urllib.urlencode({'type':'pocsag', 'address':data["ric"], 'flags':'0', 'function':data["functionChar"], 'message':data["msg"] + 'meineINFO'})

damit kann ich in Bosmon direkt sehen wo die Sendung hergekommen ist.
Kann man sowas mit in die Config aufnehmen ? 

Grüße

**Comment by Schrolli91** [comment]
@einmalacht welche Art von Suffix wird denn hier verwendet?

Mir erschließt sich der Sinn nicht ganz - Alarm ist schließlich Alarm, egal aus welcher BW Instanz?

**Comment by einmalacht** [comment]
Sorry für die Späte Antwort ... ich nutze mehrere Boswatch an verschiedenen Standorten ... und so kann ich immer sehen wo die Meldung empfangen wurde ... die speisen alle einen virtuellen Kanal im bosmon , sodass doppelte im bosmon gefiltert werden .. und der längste Text gewinnt ... so kann ich mit der Suffix länge steuern welcher "empfänger" bevorzugt werden soll

**Comment by Schrolli91** [comment]
Du löst das ganze aktuell durch manuelles Eintragen.
Ich sehe für eine solche Funktion derzeit aktuell keinen Nutzen.
Das macht nur Sinn wenn die Info dann an allen Plugins verfügbar wäre.

Dies wird mit BOSWatch 3 aber sowieso umgesetzt. Dort wird jeder Client einen eigenen Namen haben, woran sie dann unterscheidbar sind.

Aus diesem Grund, closed
