### ISSUE TITLE
Fehler bei Installation

### ISSUE THREAD

**Issue by Djgraphy** [Schrolli91/BOSWatch#294]
Fehler bei Installation,
nach apt-get update erscheint der Fehler
dass  qt4  nicht gefunden werden konnte.
Unable to locate package qt4-default

E: Unable to locate package qt4-default
Action: download on stuff failed.
Exitcode: 100

**Comment by flothi** [comment]
Dann hast du wahrscheinlich auch noch eine alte Version des Betriebssystems (Wheezy?)

Am sinnigsten wäre eine Upgrade, ansonsten findest du in #291 Hinweise
