### ISSUE TITLE
BosWatch startet trotz belegtem RTL_FM

### ISSUE THREAD

**Issue by K3vP0** [Schrolli91/BOSWatch#30]
BosWatch startet ohne Fehlermeldung obwohl RTL_FM nicht frei ist
 --> Meldung erscheint bloß im Log

**Comment by Schrolli91** [comment]
Log Auszug, von betreffender Stelle?

**Comment by JHCD** [comment]
Kevin hat da recht, BOSWatch bekommt davon nichts mit, habe ich auch schon auf dem Zettel.
Fehlermeldung nur in rtl_fm.log

**Comment by JHCD** [comment]
Im Develop-Zweig liegt jetzt eine Version, die prüft ob rtl_fm und multimon-ng ohne Fehlermeldung starten...

Für Testzwecke wurde der Parameter "-t" hinzugefügt. Wird er benutzt, werden rtl_fm und multimon-ng nicht gestartet.

**Comment by K3vP0** [comment]
Tut noch nicht ganz was  es soll : 

30.06.2015 00:32:25 - descriptionList [DEBUG   ] -- loading csv finished
30.06.2015 00:32:25 - boswatch        [DEBUG   ] starting rtl_fm
30.06.2015 00:32:28 - boswatch        [DEBUG   ] 
Found 1 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 00000001

Using device 0: Generic RTL2832U OEM
Found Rafael Micro R820T tuner
Tuner gain set to 49.60 dB.
Tuner error set to 75 ppm.
Tuned to 172992800 Hz.
Oversampling input by: 64x.
Oversampling output by: 1x.
Buffer size: 5.80ms
Exact sample rate is: 1411200.013458 Hz
Sampling at 1411200 S/s.
Output at 22050 Hz.

30.06.2015 00:32:28 - boswatch        [CRITICAL] cannot start rtl_fm
30.06.2015 00:32:28 - boswatch        [DEBUG   ] cannot start rtl_fm
Traceback (most recent call last):
  File "./boswatch.py", line 268, in <module>
    raise OSError("starting rtl_fm returns an error")
OSError: starting rtl_fm returns an error
30.06.2015 00:32:28 - boswatch        [WARNING ] SystemExit received
30.06.2015 00:32:28 - boswatch        [DEBUG   ] BOSWatch shuting down
30.06.2015 00:32:28 - boswatch        [DEBUG   ] terminate rtl_fm (3393)

rtl_fm war bei mir zu dem Zeitpunkt frei, trotzdem hat er abgebrochen...
