### ISSUE TITLE
Service startet aber rtl_fm und multimon-ng starten als <defunct>

### ISSUE THREAD

**Issue by BernhardK91** [Schrolli91/BOSWatch#301]
Hallo zusammen,

erstmal vorne weg: Tolles Tool! Vielen Dank für Eure investierte Zeit!

Ich bin gerade dabei ein unabhängiges Webinterface zu bauen, welches die Alarme auswertet und dann Alarmierungen auf Basis von Gruppenstrukturen über diverse Dienste (aktuell pushover) versendet. 

Das funktioniert auch alles wunderbar. Dank Wiki und Readme. Allerdings nur, wenn ich /opt/boswatch/boswatch.py direkt starte. Ich möchte aber sichergehen, dass auch bei einer Spannungsschwankung oder eines Stromausfalles (oder Wartungsreboot oder oder oder...) BOSWatch beim starten des Odroids automatisch mitstartet. 

Ich hatte es erst durch Eintrag in die rc.local versucht. Nun aber per service so, wie in der Readme.md in /service erklärt. Es scheint grundsätzlich auch zu funktionieren, allerdings starten rtl_fm und multimon-ng als \<defunct> (also "defekt").

![image](https://user-images.githubusercontent.com/5526334/30177672-d867401a-9406-11e7-80bc-64340dd9a5b0.png)

Allerdings tritt der Fehler wohl nicht jedes Mal auf. 
In der /opt/boswatch/log/rtl_fm.log steht:
`No supported devices found.`

Ich habe den Verdacht, dass hier ein treiber nicht geladen wird, oder der Stick nicht schnell genug erkannt wird.

Kennt jemand dieses Problem? Gibt es einen Workaround?

Danke schon mal!

Gruß
Bernhard

- **BOSWatch Version + Branch**
2.2
- **genutzte Plugins**
httpRequest
- **Fehlerbeschreibung**
siehe oben

**Comment by flothi** [comment]
Versuch mal die Anleitung (und das Skript), welches aktuell im Develop-Zweig liegt; das Service-Konstrukt von Raspbian wurde etwas modifiziert...
https://github.com/Schrolli91/BOSWatch/tree/develop/service

**Comment by Schrolli91** [comment]
@BernhardK91 
durch das Einführen eines Changelogs sind wir inzwischen bei Version 2.2.1
Der aktuelle Master enthält das neue Service Script also nun auch

Läuft das ganze denn normal, wenn du es händisch - also nicht als Service startest?

Was meldet der BOSWatch Log?

**Comment by Schrolli91** [comment]
@BernhardK91 konntest du den aktuellen master inzwischen testen?

**Comment by Schrolli91** [comment]
Da sich hier nichts mehr rührt und es sich außerdem um einen Einzelfall zu handeln scheint - closed
