### ISSUE TITLE
CHANGELOG

### ISSUE THREAD

**Issue by Schrolli91** [Schrolli91/BOSWatch#306]
Ich bitte euch in Zukunft, bei euren Commits auch immer den Changelog mit nachzuführen.
https://github.com/Schrolli91/BOSWatch/blob/develop/CHANGELOG.md

Eine grobe Log Anleitung findet Ihr als Link ganz unten.

**Comment by Smeti1** [comment]
Link geht leider nicht

**Comment by thejockel** [comment]
Und bitte einen Link zur dem Pull.

**Comment by Schrolli91** [comment]
Wie meinst? Link zum pull direkt mit in den changelog?

**Comment by thejockel** [comment]
Genau

z.B.
Description Liste kann nun zusätzlich Einträge für jede Subric enthalten (POCSAG) - [Pull 271](https://github.com/Schrolli91/BOSWatch/pull/271)

**Comment by Schrolli91** [comment]
soeben angepasst: 45f4887163c65d2cc187dc78dea093f1983a8e54
