### ISSUE TITLE
Nach apt-get upgrade --> 

### ISSUE THREAD

**Issue by K3vP0** [Schrolli91/BOSWatch#308]
Hallo zusammen,

nach einem Update über apt-get lässt sich meine Installation nur noch mit "python boswatch.py" starten und nicht mehr mit ./boswatch.py 
Dadurch bedingt funktioniert auch der Service nicht mehr.
Der Start Prozess wird beim Laden von yowsup ohne Exception einfach dauerhaft pausiert. 

Hat jemand die selbe Problematik ?

Version --> Stable und Beta getestet. 

root@SRV01:/opt/boswatch/BOSWatch# ./boswatch.py -f 172.64M -a POC1200 -g 40 -d 0 -e 30.5 -u
     ____  ____  ______       __      __       __   
    / __ )/ __ \/ ___/ |     / /___ _/ /______/ /_  
   / __  / / / /\__ \| | /| / / __ `/ __/ ___/ __ \ 
  / /_/ / /_/ /___/ /| |/ |/ / /_/ / /_/ /__/ / / / 
 /_____/\____//____/ |__/|__/\__,_/\__/\___/_/ /_/  
            German BOS Information Script           
          by Bastian Schroll, Jens Herrmann         

SW Version:	2.2-dev
Build Date:	2017/03/30

Frequency:   **********
Device-ID:   0
Error in PPM:   *******
Active Demods:   1
- POC1200
Squelch: 0
Gain: 40

21.09.2017 22:41:12 - pluginLoader    [WARNING ] Plugin [NO CONF ] yowsup

^C21.09.2017 22:41:21 - boswatch        [WARNING ] Keyboard Interrupt
^CTraceback (most recent call last):
  File "./boswatch.py", line 422, in <module>
    time.sleep(3)
KeyboardInterrupt`

**Comment by flothi** [comment]
Hast du mal versucht, yowsup in der config zu deaktivieren?

**Comment by Schrolli91** [comment]
`pluginLoader [WARNING ] Plugin [NO CONF ] yowsup`
irgendwas stimmt da mit deiner config nicht!

aus der pluginLoader.py
```python
# no entry for plugin found in config-file
except NoOptionError:
   logging.warning("Plugin [NO CONF ] %s", i)
```

Aufhängen dürfte sich das Script aber dennoch unter KEINEN Umständen !

**Comment by flothi** [comment]
@Tauebenuss Kannst du uns noch ein wenig Input liefern oder klappts wieder?

**Comment by Schrolli91** [comment]
**Vermutung**
`yowsup` kommt direkt nach dem `telegram` Plugin.
Ich könnte mir vorstellen, dass er beim konfigurieren ausersehen den `[yowsup]` Block zerstört hat und daher die config nicht mehr auffindbar war.

Mit aktuellem DEV testen (habe Logausgaben der config angepasst) und bei wiederholtem nicht gelingen den GESAMTEN LOG per PN zB über das Forum zu mir.

Sorgen bereitet mir das AUFHÄNGEN von BOSWatch, was so nicht passieren dürfte.
Ein Fehler in einem Plugin kann/darf nie zu einem Stillstand führen

**Comment by flothi** [comment]
Also ich habe bis jetzt schon viel in den Plugins geschraubt und gemacht - einen Absturz/Stillstand konnte ich noch nicht produzieren. Das scheint mir sehr suspekt zu sein (evtl ein Update von python?)

**Comment by Schrolli91** [comment]
Hab mal das Ausgeben der Versions Nr von Python im Log eingefügt: cc66f4547ac1737200b11ba8283586818f291095

**Comment by Schrolli91** [comment]
@Tauebenuss wie ist die Lage?

**Comment by Schrolli91** [comment]
Da es scheinbar nichts neues dazu gibt und das Problem auch anderweitig nirgends aufgetreten zu sein scheint - closed
