### ISSUE TITLE
Aufruf von rtl_fm.log und multimon-ng ohne festen Pfad

### ISSUE THREAD

**Issue by JHCD** [Schrolli91/BOSWatch#31]
Problem:
Wird BOSWatch als Dienst beim Systemstart in rc2.d/S99 gestartet, findet subprocess.popen() die Binaries nicht.
Workaraound:
Feste Pfadangabe /usr/local/bin 

ToDo: 
Andere Lösung finden, liegt vielleicht auch mal woanders und betrifft nur die, die einen Dienst starten wollen.

**Comment by K3vP0** [comment]
Rc.d wird relativ früh ausgeführt... Hast du schon ausprobiert das Ganze erst mit cron zu starten?

**Comment by Smith-fms** [comment]
Im Shell Script ein wait von 5-10 Sekunden und alles läuft ohne Probleme rc.d. Wobei ich ohne wait auch keine hatte. Allerdings war auf dem Pi ohne wait der Load zu hoch für mich am Anfang. 
Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: kevinkleist notifications@github.com 
Datum: 27.06.2015  17:54  (GMT+01:00) 
An: Schrolli91/BOSWatch BOSWatch@noreply.github.com 
Betreff: Re: [BOSWatch] Aufruf von rtl_fm.log und multimon-ng ohne festen Pfad (#31) 

Rc.d wird relativ früh ausgeführt... Hast du schon ausprobiert das Ganze erst mit cron zu starten? 

---

**Comment by JHCD** [comment]
Ich starte einen Dienst, kein klassisches Shell-Skript...
Aber cron wäre eine Idee, müsste nur mal gucken wie das geht...

**Comment by Smith-fms** [comment]
Entschuldige,  natürlich. Aber dennoch lässt ein sleep (sek) das gleiche zu. Auch im deamon.
Aber per Cron ist es dennoch angenehmer...

Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: Jens Herrmann notifications@github.com 
Datum: 27.06.2015  18:03  (GMT+01:00) 
An: Schrolli91/BOSWatch BOSWatch@noreply.github.com 
Cc: Smith-fms smith@rpd-server.de 
Betreff: Re: [BOSWatch] Aufruf von rtl_fm.log und multimon-ng ohne festen Pfad (#31) 

Ich starte einen Dienst, kein klassisches Shell-Skript...
Aber cron wäre eine Idee, müsste nur mal gucken wie das geht...

---

**Comment by K3vP0** [comment]
http://wiki.ubuntuusers.de/CRON#Eine-Crontab-fuer-einen-Benutzer-einrichten

Statt Zeitangabe einfach "@reboot" davor.

**Comment by JHCD** [comment]
crontab hat den Nachteil, dass BOSWatch beim Herunterfahren der Dienst nicht sauber beendet wird...

Eine Mischform aus crontab und rc6.d etc. fände ich ungünstig. 

Dann doch lieber das wait() im Daemon...

**Comment by K3vP0** [comment]
https://de.m.wikipedia.org/wiki/Runlevel

Beim Starten durch CronTab wird der Service genau so wie beim rc.d beendet bedingt durch den RunLevel der unter Default-Stop eingetragen ist.

**Comment by JHCD** [comment]
Es wird ein `/etc/init.d/boswatch.sh stop` ausgeführt, obwohl kein rc6.d-Eintrag vorhanden ist?
Wer steuert denn das?

**Comment by K3vP0** [comment]
Okay, hast mich überzeugt. Die wait() Variante ist sinnvoller.
Per cron wäre es doppelt.

Also wait einfügen oder den Pfad vorher definieren. 

Ich füge ja nur durch Update rc.d die Links in die einzelnen rc-scripte ein...

https://wiki.ubuntuusers.de/Dienste

**Comment by JHCD** [comment]
`sleep 10` im init.d-Skript klappt bei mir leider nicht. :(
Weiterhin die Fehlermeldung, dass subprocess.popen das Binarie nicht findet.

**Comment by K3vP0** [comment]
Hast du default-Start mal auf 3 4 5 gesetzt ? Update rc.d nicht vergessen

**Comment by JHCD** [comment]
Komme ich beim Raspberry überhaupt im Runlevel 3-5 vorbei?
In der Konsole sagt er mir Runlevel 2

**Comment by K3vP0** [comment]
Laut meiner Liste ist RunLevel 3 commandozeile ohne grafisches Interface

**Comment by JHCD** [comment]
Mein Raspberry 2 meldet als runlevel "N 2"

**Comment by K3vP0** [comment]
Komisch. Finde im Internet auch nichts dazu... Hast du mal mit sleep 60 oder 90 es ausprobiert ?

**Comment by JHCD** [comment]
runlevel 2 scheint bei Raspbian der default-runlevel zu sein:
https://www.raspberrypi.org/forums/viewtopic.php?p=278830

**Comment by JHCD** [comment]
Pfadangabe für den Start des Daemons in rcd2.d wurde in die config.ini verlegt.
Damit ist für "normale Benutzung" keine Pfadangabe mehr im Code.
