### ISSUE TITLE
Installer für Service

### ISSUE THREAD

**Issue by Schrolli91** [Schrolli91/BOSWatch#311]
vorerst als Merker - Installer Script zur Einrichtung des Service

**Comment by flothi** [comment]
Haben wir denn Feedback, ob das neue Skript das tut was es soll?

**Comment by Schrolli91** [comment]
Bei #301 steht ein Abschließendes Feedback ja noch aus

**Comment by flothi** [comment]
Mit #316 mal initiiert.

**Comment by Schrolli91** [comment]
da der pull jetzt läuft, closed

**Comment by Schrolli91** [comment]
btw ich verlinke als vermerk nochmal auf #138
