### ISSUE TITLE
install.sh - unnötige Anweisung

### ISSUE THREAD

**Issue by Schrolli91** [Schrolli91/BOSWatch#318]
Hier wird dazu aufgerufen, vor dem Start die config zu kopieren
https://github.com/Schrolli91/BOSWatch/blob/37829740949168f501910d3d3518c0701bbd13c2/install.sh#L216

Das ganze wird hier aber sowieso automatisiert vorgenommen
https://github.com/Schrolli91/BOSWatch/blob/37829740949168f501910d3d3518c0701bbd13c2/install.sh#L231

**Comment by flothi** [comment]
Dann würde ich nur den Hinweis auf die Anpassung drin lassen und den Hinweis auf das Kopieren entfernen - du oder ich?

**Comment by Schrolli91** [comment]
gerne du, sitz gerade auf arbeit :-P

**Comment by flothi** [comment]
Ich habs  direkt in den dev geschoben, war ja "nur" Text (https://github.com/Schrolli91/BOSWatch/commit/18425e2be22db01f388343fa84b913e7bb21ecbf)

**Comment by Schrolli91** [comment]
Passt... Die Änderung is in meinen Augen auch nicht erwähnenswert, Changelog mäßig...
Hat sich ja nix geändert ;-)
