### ISSUE TITLE
MySQL Connector for Python

### ISSUE THREAD

**Issue by Schrolli91** [Schrolli91/BOSWatch#319]
Wir installieren hier eine fixe Version. Laut der MySQL Seite ist der Connector bereits in Version 2.xxx verfügbar. Evtl sollten wir da mal nachziehen und schauen ob evtl unsere SQL Probleme dadurch verschwinden?
https://github.com/Schrolli91/BOSWatch/blob/37829740949168f501910d3d3518c0701bbd13c2/install.sh#L170

**Comment by flothi** [comment]
Das sollten wir in der Tat tun, v.a. im Hinblick auf MariaDB in Debian/raspbian stretch

**Comment by PeterLaemmle** [comment]
Ich hab den MySQL-Connector in der Version 2.1.4 bei mir drauf, installiert über pip.
Welche Probleme haben wir denn?

**Comment by flothi** [comment]
Die Frage ist, ob der Connector überhaupt noch installiert werden muss oder ob die Bordmittel von python ggf ausreichen würden.

**Comment by Schrolli91** [comment]
sollte man evtl mal abklären und wenn wirklich unnötig "ausbauen"

**Comment by Schrolli91** [comment]
Da stellt sich mir gerade die Frage... für BW3 - überhaupt auf MySQL setzen, oder doch lieber gleich mit python eigenen Mitteln auf die sqlite DB?

**Comment by flothi** [comment]
Auf SQL gehen - und auswählen ob man sqlite oder ne "große" DB nutzen möchte - das wäre mein Plädoyer

**Comment by Schrolli91** [comment]
@PeterLaemmle du nutzt die 2.1.4 - funktioniert damit alles sauber?
Dann könnte man den Installer noch auf die entsprechende Version anpassen. Damit wäre die zumindest etwas neuer.

**Comment by PeterLaemmle** [comment]
Ja, ich hab den MySQL-Connector in der Version 2.1.4 über pip installiert.
Mir sind keine Probleme bekannt.
Hab gerade auf 2.1.6 aktualisiert. Werde das mal beobachten.

**Comment by Schrolli91** [comment]
Da entsprechende Issues ja offen sind, close ich hier
