### ISSUE TITLE
DEB Paketierung

### ISSUE THREAD

**Issue by DaGuich** [Schrolli91/BOSWatch#320]
Da (soweit ich weiß) BOSWatch auf einem Raspberry Pi am laufen haben, wäre es doch eine Möglichkeit den Installationsprozess für die Nutzer zu vereinfachen. Dazu könnte man ein DEB-Package aus dem source Code bauen. Die Installation und Updates würde dann nur noch aus `wget https://github.com/Schrolli91/BOSWatch/archive/boswatch.deb && dpkg -i boswatch.deb` (Link nur zur Veranschaulichung) bestehen. 

Ich persönlich hab das noch nie gemacht, aber vielleicht ist ja jemand hier, der das schon gemacht hat und davon Ahnung hat. 

Kurze Google Recherche hat ergeben:
- [Ein Debian Paket erstellen - Debian Paket Tutorials](http://www.tomprogs.at/tutorials/linux/debian-paket-tutorials-01-ein-erstes-paket.xhtml)
- [Debian-Pakete selbst erstellen](http://www.linux-community.de/Internal/Artikel/Print-Artikel/LinuxUser/2013/08/Debian-Pakete-selbst-erstellen)
- [Paketbau](https://wiki.ubuntuusers.de/Paketbau/)

**Comment by Schrolli91** [comment]
Aktuell ist die Installation auch nur ein `wget install File` und dieses danach ausführen.
Wüsste nicht was da zu vereinfachen wäre?

**Comment by flothi** [comment]
das macht meiner Meinung nach vornehmlich dann Sinn, wenn es keine separate install-Datei gibt. Die Abhängigkeiten verantworten wir ja selber, also sehe ich aktuell wenig Mehrwert.

**Comment by DaGuich** [comment]
Ich würde mich dem ganzen mal annehmen. Mal sehen was dabei rumkommt ;)

**Comment by flothi** [comment]
Gerne :)

**Comment by Schrolli91** [comment]
@DaGuich Ich weiß nicht ob du an dem Thema noch dran bist. Ich würde hier aber jetzt einfach mal schließen. Sollte es Ergebnisse geben, die bitte einfach per Pull Request veröffentlichen.
