### ISSUE TITLE
Wunsch: Pushover & die Wildcard %FUNCTEXT%

### ISSUE THREAD

**Issue by ghost** [Schrolli91/BOSWatch#322]
Ich würde an Pushover Alarm gerne die Wildcard %FUNCTEXT% weitergeben.
Aktuell gibt es diese Funktion ja nicht, wohl aber die "Static Massages for Subrics" in der config.ini.

Ist da wer begabt und hat Lust? :)

Gerne auch im Forum melden:
https://boswatch.de/index.php?thread/18-pushover-global-subric/

**Comment by flothi** [comment]
Nun auch endlich erledigt: #352

**Comment by Schrolli91** [comment]
Weitere Diskussion im Pull
