### ISSUE TITLE
Traceback bei start im Testmodus ohne sudo

### ISSUE THREAD

**Issue by f-kessler** [Schrolli91/BOSWatch#328]
Ich weiß, der erste Fehler ist den Testmodus ohne die erforderlichen Rechte zu starten, aber sollte der folgende Fehler nicht trotzdem nicht erscheinen:

>pi@raspberrypi:/opt/boswatch $ python boswatch.py -f 111 -a POC1200 -t -v
ERROR: cannot create logger
WARNING:root:SystemExit received
DEBUG:root:BOSWatch shuting down
DEBUG:root:exiting BOSWatch
DEBUG:root:close Logging
**Traceback (most recent call last):
  File "boswatch.py", line 428, in <module>
    if globalVars.config.getboolean("BOSWatch","processAlarmAsync") == True:
AttributeError: 'int' object has no attribute 'getboolean'**
pi@raspberrypi:/opt/boswatch $

**Comment by flothi** [comment]
Das liegt an der Location der Logfiles, die per Default in /var/log/... liegen.

Aber du hast Recht, den Fehler sollte man in der Form abfangen.

**Comment by f-kessler** [comment]
Passiert übrigens mit dem aktuellen dev-express-alarm

**Comment by f-kessler** [comment]
Der traceback hängt auch damit zusammen?

**Comment by flothi** [comment]
Japp, der config-reader kommt erst nach dem logger - also kennt er den noch gar nicht.

**Comment by Schrolli91** [comment]
Versteh ehrlich gesagt nicht genau was hier passiert?

Also dass er den Logger nicht anlegen kann leuchtet mir noch ein, wenn keine Rechte auf /var/log/ vorliegen. Aber wieso wirft der config-reader dann noch einen Fehler?

**Comment by flothi** [comment]
Weil der Confighandler nicht initialisiert ist, aber in Zeile 428 nochmal aufgerufen wird. Entweder stellen wir das in der Reihenfolge um (erst den Confighandler, dann den Logger - was eigentlich am meisten Sinn macht, wenn man nicht in /var/log/... loggen will, wie in der config angegeben) oder ersetzen die Abfrage der config-Datei durch eine Variable im Skript. 
Ich würde Variante 1 bevorzugen

**Comment by flothi** [comment]
Alternativ müssten wir hier nochmal an den Benutzer/die Gruppe ran. Aktuell erbt das gesamte Verzeichnis beim Installieren mit sudo die root-Rechte.

**Comment by Schrolli91** [comment]
Reihenfolge umstellen klingt wohl am sinnigsten denke ich
