### ISSUE TITLE
3 Frequenzen zu gleich möglich?

### ISSUE THREAD

**Issue by clemensthaler** [Schrolli91/BOSWatch#329]
Können 3 unterschiedliche Frequenzen zugleich abgehört und aufgenommen werden? Also mit dem selben Stick und dem selben Raspberry Pi?
MFG; Clemens Thaler, FF Winklern/Mölltal

**Comment by Smeti1** [comment]
Leider nur ein Kanal pro Stick
Und 2 Sticks an einem Raspberry Pi gehen auch 
bei 3 wird die Last schon bisserl grenzwertig

**Comment by clemensthaler** [comment]
Okay Danke für deine Hilfe.
Also ein Stick pro Kanal und 2 Sticks am Pi ohne Probleme möglich.

**Comment by flothi** [comment]
Scheint beantwortet, daher mal close
