### ISSUE TITLE
NMA-Plugin

### ISSUE THREAD

**Issue by JHCD** [Schrolli91/BOSWatch#33]
NotifyMyAndroid-Unterstützung einbauen.
1. als normales Plugin
2. als Infodienst im Fehlerfall (siehe #46)

**Comment by K3vP0** [comment]
Bin grade über den Gedanken gestolpert, eventuell eine eigene App für Android/iOS zu implementieren... Der Aufwand dürfte nicht viel größer sein als ein Plugin für NMA? 
Mit Endeffekt brauch man ja nur ein push Modul programmieren und eine MySQL Abfrage. Sinnig wäre es dann das MySQL vorkonfiguriert bei der Installation mit zu installieren und eine Webbasierte Lösung der Confog Datei. Ich denke das würde das ganze System abrunden und benötigt dann nicht tiefergehende Kenntnisse ...? Was haltet ihr davon?

**Comment by JHCD** [comment]
Hallo Kevin, 

da unsere Server nie von draußen erreichbar sein werden - das halte ich für Datenschutz-technisch bedenklich - werde ich das nicht bauen.
Ich spreche mich auch entsprechend gegen eine Standard-Freigabe aus.

Wozu benötigt ein Push-Dienst einen MySQL-Zugriff? Die Plugins sollten keinen SQL-Zugriff benötigen. 

Wenn Du einen externen Zugriff haben möchtest, gehört das ins www-Verzeichnis. Dort kann man natürlich beliebige WebServices implementieren.

Grüße Jens 

PS: das NMA-Plugin bauen dauert ca. eine Stunde :-)

**Comment by K3vP0** [comment]
Sorry, hatte grade zwei Baustellen auf einmal im Kopf. Klar brauch man kein MySQL dafür. Bin grade dabei eine Abfrage zu erstellen die nachguckt ob der Alarm in den letzten 10 Meldungen vorhanden ist. Damit die Doppelmeldungen endlich verschwinden...

**Comment by Hobo2k** [comment]
Ich verwende https://www.pushbullet.com/

Bin aber noch nicht darauf gekommen, aus der Flut nur bei ganz bestimmten mittel HTTP-API was zu schicken.
Vielleicht kann man das einfach als plugin einbinden, ebenso SMStrade :-)
Danke

**Comment by Schrolli91** [comment]
naja wenn die API sowieso per HTTP kontaktiert wird, kann man evtl sogar direkt das schon vorhandene HTTPrequest Plugin nutzen...

**Comment by JHCD** [comment]
1.) Es gibt eine fertige Python-API, die werde ich nicht selber bauen 
2.) NMA hat eine Prio, die abhängig von der ID etc. ist
3.) ID-abhängige Empfänger-Adresse

Will das über eine csv-Konfiguration lösen

**Comment by K3vP0** [comment]
Würde die gleichen Funktionen auch für Growl nutzen wollen. 

Wollen wir / du das dann in ein Plugin schreiben oder dann zwei verschiedene?

**Comment by JHCD** [comment]
Moin Kevin, 

Ich bin die Woche an der Landesfeuerwehrschule und werde daher erst ab dem WE wieder zum Entwickeln kommen.

Ich glaube aktuell nicht, dass man Powl und NNA in einem Plugin realisieren kann.
Aber genaueres weiß man erst hinterher. Auf jeden Fall gäbe es dann ein Gerüst, welches Du oder ich dann für Powl übernehmen könnten.

Grüße, 
Jens

**Comment by JHCD** [comment]
Das Plugin ist jetzt Vollständig.
Es gibt zwei Betriebsarten für das Plugin:
1. In der `config.ini` ist ein APIKey angebene und alle Alarme, die im Plugin ankommen, werden dorthin gesendet
2. Es wird eine `nma.csv` importiert, in der für jede ID (FMS, ZVEI, POCSAG inkl. FunktionsCode) ein oder mehrere Empfänger festgelegt werden können. Jeder Eintrag hat außerdem eine eigene Priorität.
