### ISSUE TITLE
Übergabe BOSWatch -> firemergency2 

### ISSUE THREAD

**Issue by TobiasM112** [Schrolli91/BOSWatch#332]
**BOSWatch Version**
SW Version:     2.2.2
Branch:         master
Build Date:     21.10.2017
Firemergency2 version: 2.15.359-STABLE

**genutzte Plugins**
firemergency

**Fehlerbeschreibung**
Seit ein paar Tagen funktioniert die Kommunikation zwischen BOSWatch und FE2 nicht mehr. 
Hat jemand zufällig BOSW mit FE2 am laufen? bin langsam am Ende mit probieren. Es wurden eigentlich keine Änderungen vorgenommen.
Hat jemand einen Tipp wie ich weiter nach Fehlern suchen könnte?
**Logfile (Auszug)**

19.11.2017 19:37:50 - alarmHandler    [DEBUG   ] call Plugin: firEmergency
19.11.2017 19:37:50 - configHandler   [DEBUG   ] read [firEmergency] from config f                             ile
19.11.2017 19:37:50 - configHandler   [DEBUG   ]  - firserver = ****
19.11.2017 19:37:50 - configHandler   [DEBUG   ]  - firport = 5555
^C19.11.2017 19:38:05 - firEmergency    [ERROR   ] cannot connect to firEmergency
19.11.2017 19:38:05 - firEmergency    [DEBUG   ] cannot connect to firEmergency
Traceback (most recent call last):
  File "/opt/boswatch/plugins/firEmergency/firEmergency.py", line 73, in run
    firSocket.connect((globalVars.config.get("firEmergency", "firserver"), globalVars.config.g                 etint("firEmergency", "firport")))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
KeyboardInterrupt
19.11.2017 19:38:05 - firEmergency    [DEBUG   ] close firEmergency-Connection
19.11.2017 19:38:05 - alarmHandler    [DEBUG   ] return from: firEmergency
19.11.2017 19:38:05 - alarmHandler    [DEBUG   ] [END ALARM]

**Comment by flothi** [comment]
Ein Ping auf die Adresse des Firserver ist möglich? Es scheint ein TCP-Problem zu sein, ggf ist die Windows-Firewall ein Problem (probehalber mal deaktivieren)

**Comment by TobiasM112** [comment]
Ja Ping ist möglich.
Habe die Firewall mal deaktiviert jetzt kommen wir zwar einen Schritt weiter aber jetzt wird die Verbindung abgelehnt.

30.11.2017 23:08:04 - alarmHandler    [DEBUG   ] call Plugin: firEmergency
30.11.2017 23:08:04 - configHandler   [DEBUG   ] read [firEmergency] from config file
30.11.2017 23:08:04 - configHandler   [DEBUG   ]  - firserver = xxx.xx.x.xxx
30.11.2017 23:08:04 - configHandler   [DEBUG   ]  - firport = 5555
('xxx.xx.x.xxx', 5555)
30.11.2017 23:08:04 - firEmergency    [ERROR   ] cannot connect to firEmergency
30.11.2017 23:08:04 - firEmergency    [DEBUG   ] cannot connect to firEmergency
Traceback (most recent call last):
  File "/opt/boswatch/plugins/firEmergency/firEmergency.py", line 74, in run
    firSocket.connect((globalVars.config.get("firEmergency", "firserver"), globalVars.config.getint("firEmer                                     gency", "firport")))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused
30.11.2017 23:08:04 - firEmergency    [DEBUG   ] close firEmergency-Connection
30.11.2017 23:08:04 - alarmHandler    [DEBUG   ] return from: firEmergency

**Comment by TobiasM112** [comment]
Sollte ja jetzt nicht an Boswatch liegen sondern eher an firemergency. So wie ich das verstehe?

**Comment by flothi** [comment]
Würde ich auch so sehen - gab es denn ein Update (evtl eines, was im Hintergrund gelaufen ist)?

**Comment by TobiasM112** [comment]
Eigentlich nichts bekanntes

**Comment by TobiasM112** [comment]
So habe heute nochmal diverse Sachen ausprobiert und habe eine Lösung gefunden.

Bei mir funktioniert es nun nicht mehr mit dem FMS32 Server Alarmeingang bei FE2 sondern nur noch mit der Standart Schnittstelle.

**Comment by Schrolli91** [comment]
@TobiasM112 
Also kann man das als gelöst betrachten?
BOSWatch ist fehlerfrei und es war reine Einstellungssache an FE2, hab ich das richtig verstanden?

**Comment by TobiasM112** [comment]
Ja kann man als gelöst betrachten.

BOSWatch funktioniert fehlerfrei

Laut dem Plugin sollte man FMS32 als Quelle angeben, geht aber nicht(mehr) aber mit der Standartschnittstelle geht es jetzt wieder.

**Comment by Schrolli91** [comment]
@TobiasM112 
dann passe ich die Beschreibung eben an
`- set input to "FMS32" at Port 5555` das steht aktuell drin
Die neue Schnittstelle ist dann `standard input` ? Port unverändert?

**Comment by TobiasM112** [comment]
neue Schnittstelle "Standartschnittstelle"
Port bleibt unverändert

`- set input to "Standartschnittstelle" at Port 5555 `

**Comment by Schrolli91** [comment]
super Danke dir

**Comment by Schrolli91** [comment]
Damit wäre das Thema dann erledigt... Danke für den Tip zur Lösung
