### ISSUE TITLE
httpRequest Plugin encodiert Daten

### ISSUE THREAD

**Issue by grinsekatze003** [Schrolli91/BOSWatch#336]
Das Plugin httpRequest encodiert alle Daten im Array `data`. Das Problem dabei ist, dass das Array zuvor nicht kopiert wird, sodass die Originaldaten im Array verändert werden. Alle danach laufenden Plugins bekommen dann beispielsweise nicht mehr die originale ZVEI Beschreibung, sondern die encodierte.

Vielleicht könnte man das, auch wenn die Arbeiten an Boswatch 3 im vollen Gange sind, kurz zwischendurch fixen! :-)

**Comment by Schrolli91** [comment]
Oh, das ist natürlich ganz schlecht und darf so auf keinen Fall sein, da hast du Recht!

Hättest du die Möglichkeit das zu machen?

(siehe: c77f2a9fdd11b72dc62d5e5da8cbb3c6c25e1341)

**Comment by Schrolli91** [comment]
Als Querverweis: https://boswatch.de/index.php?thread/27-leerzeichen-durch-20-ersetzt/&postID=141

**Comment by Schrolli91** [comment]
Bitte mal kurz testen https://github.com/Schrolli91/BOSWatch/pull/337

**Comment by grinsekatze003** [comment]
Das kann nicht funktionieren, da `dataCopy = data` nur die Referenz speichert, also eine flache Kopie. `dataCopy = dict(data)` oder auch `dataCopy = data.copy()` sollte funktionieren! :-) Ich teste das und melde mich heute Nachmittag.

**Comment by Schrolli91** [comment]
Du hast natürlich Recht
``` python
data = {"test":1,"abc":2}
dataCopy1 = data
dataCopy2 = dict(data)

print(data)
print(dataCopy1)
print(hex(id(data)))
print(hex(id(dataCopy1)))
print(hex(id(dataCopy2)))
```

```
{'test': 1, 'abc': 2}
{'test': 1, 'abc': 2}
0x1f3f0217af8
0x1f3f0217af8
0x1f3f06a9288
```

passe ich noch an

EDIT: Anpassung ist durch, würdest du nochmal kurz drüber schauen?

**Comment by grinsekatze003** [comment]
Funktioniert! Vielen Dank für den schnellen Fix. 👍

**Comment by Schrolli91** [comment]
Super - Danke für deine mithilfe
