### ISSUE TITLE
multimon und rtl-sdr im installer

### ISSUE THREAD

**Issue by Schrolli91** [Schrolli91/BOSWatch#343]
Aktuell ziehen wir die beiden Tools von einem Fork, welcher in meinem Account liegt. Damit wir eine Version haben, welche getestet ist und garantiert läuft.

Wäre es nicht einfacher vom origial Repo auf einen bestimmen commit/label/release auszuchecken? Dann hätten wir auch eine definierte Version aber wir könnten uns den Fork bei mir sparen.

@flothi vor allem deine Meinung würde mich dazu mal interessieren ;-)

**Comment by flothi** [comment]
Wir hatten das ja gemacht, um einen definierten Stand zu haben.

Ich stimme aber auch deinem Vorschlag zu, auf ein bestimmtes Label im Originalrepo zuzugreifen, dann können wir entscheiden, ob und auf welche Version wir zB nachziehen. 

Lass uns nur bitte schauen, ob es diffs gibt - das hab ich gerade nicht mehr im Kopf

**Comment by Schrolli91** [comment]
Sollten man evtl einen Pull machen, der von beiden Tools die jeweils aktuellste letzte release Version nutzt.
Dann kann man da die neue Version mal testen und falls alles wie gewohnt funktioniert beim nächsten BW Release dann direkt mit den neuen Versionen fahren.

**Comment by flothi** [comment]
Guter Plan ich setze mich zwischen den Jahren mal dran

**Comment by Schrolli91** [comment]
super, Danke

EDIT: In dem Zug kann man evtl direkt eine neue Version des MySQL Connectors in der install ansetzen
Siehe #319 bzw #342

**Comment by Schrolli91** [comment]
@flothi hat sich dahingehend eigentlich schon etwas ergeben?

**Comment by flothi** [comment]
Ich steige gerade wieder richtig ein, gib mir noch ein paar Tage bitte

**Comment by Schrolli91** [comment]
Keine Hektik ;-) War nur rein interessehalber

**Comment by flothi** [comment]
Also, nach dem ersten drüberschauen:
rtl-sdr hatte ich eh nicht angefasst, war also unkritisch
multimon-ng hatte ich direkt im origin eingebaut, die Änderungen, die uns da konkret betreffen, wurde auch übernommen.

Aus meiner Sicht spricht also nichts dagegen, wieder auf die offiziellen Versionen (ggf. fixierte Stände) zu gehen.

Den mysql-connector habe ich noch auf der todo-Liste.

**Comment by flothi** [comment]
@Schrolli91 das Ergebnis müsste noch in den Installer übernommen werden, korrekt?

**Comment by Schrolli91** [comment]
Welches Ergebnis?

**Comment by flothi** [comment]
Dass wir die originalen Repos nehmen können ;-)

**Comment by Schrolli91** [comment]
Ja, ich hab bisher nichts geändert, falls du das meinst ;-)

**Comment by flothi** [comment]
Dann setze ich unsere Erkenntnis beizeiten in Code um ;-)

**Comment by Schrolli91** [comment]
Wenn du den Installer sowieso anfässt - Take a look at #319 and #342

**Comment by flothi** [comment]
Aye sir
