### ISSUE TITLE
FMS wird nicht richtig ausgewertet.

### ISSUE THREAD

**Issue by BachelPaul** [Schrolli91/BOSWatch#346]
Hallo Zusammen, 

bisher habe ich zur Auswertung von POCSAG rtl_fm und multimon-ng mit selbst geschriebener Auswertesoftware genutzt (läuft seit 4 Jahren stabil).
Da ich gerne die hier implementierten Plug-ins mitverwenden möchte habe ich die migration auf die letzte Version von BOSWatch gestartet. Die Auswertung der POCSAG Meldungen funktioniert einwandfrei. 
Bei der Auswertung der FMS telegramme scheint jedoch irgendwie der Wurm drin zu sein.

Bei Fragen und Problemen zu BOSWatch oder Plugins bitte unten gennante Informationen angeben:

- **BOSWatch Version + Branch**
SW Version:    2.3
Branch:                master
Build Date:    22/12/2017
Python Vers:   2.7.13 (default, Nov 24 2017, 17:33:09)

- **genutzte Plugins**
noch keine

- **Fehlerbeschreibung**
FMS gibt keine sinnvolle Dekodierung der Telegramme aus.
Mit CRC aktiv bekomme ich permanent CRC fehler.

- **Logfile (Auszug)**
```
01.01.2018 14:48:01 - decoder         [DEBUG   ] received FMS
01.01.2018 14:48:01 - fms             [WARNING ] FMS CRC incorrect
01.01.2018 14:48:01 - decoder         [DEBUG   ] received FMS
01.01.2018 14:48:01 - doubleFilter    [DEBUG   ] checkID: dfaa291700 ()
01.01.2018 14:48:01 - fms             [INFO    ] FMS:dfaa2917 Status:0 Richtung:0 TSI:I
```

- **ggf. Config File (Auszug)**
```
[FMS]
#look-up-table for adding a description
# using description (0 - off | 1 - on)
# descriptions are loaded from csv/fms.csv
idDescribed = 0

# Check for correct CRC-information is provided by multimon-ng
# As this seems to be incorrect in many cases it might be useful to disable this
# (0 - off | 1 - on)
# Better use RegEX to verify the correct data
checkCRC = 1
```

**Comment by Schrolli91** [comment]
Der Stick ist kalibriert bzw der korrekte PPM Wert der Error-Correction angegeben?

Mit welchen Parametern wird BOSWatch aufgerufen?

Es wäre mal interessant die Rohdaten zu sehen die multimon-ng ausgibt.
`writeMultimonRaw = 1`
Die Daten liegen dann in einem Textfile im BOSWatch Verzeichniss.
Bitte auf den Datenschutz achten beim Posten und sensible Stellen fiktiv ändern.

**Comment by BachelPaul** [comment]
Servus, 

 

der Stick ist kalibriert. 

 

Sieht so aus, wie wenn die Rohdaten nicht korrekt sind. 

 

Gruß

 

Von: Bastian Schroll [mailto:notifications@github.com] 
Gesendet: Montag, 1. Januar 2018 15:27
An: Schrolli91/BOSWatch <BOSWatch@noreply.github.com>
Cc: BachelPaul <chb86@web.de>; Author <author@noreply.github.com>
Betreff: Re: [Schrolli91/BOSWatch] FMS wird nicht richtig ausgewertet. (#346)

 

Der Stick ist kalibriert bzw der korrekte PPM Wert der Error-Correction angegeben?

Es wäre mal interessant die Rohdaten zu sehen die multimon-ng ausgibt.
writeMultimonRaw = 1
Die Daten liegen dann in einem Textfile im BOSWatch Verzeichniss.
Bitte auf den Datenschutz achten beim Posten und sensible Stellen fiktiv ändern.

**Comment by BachelPaul** [comment]
Der Stick ist kalibriert. 
Die Rohdaten schauen nicht korrekt aus. Ich bekomme Meldungen aus Bundesländern, die am anderen Ende von Deutschland liegen. Ich kann die Tage nochmals im Fahrzeug eine direktmessung machen. 

Die Rohdaten habe ich per PN geschickt.

**Comment by Schrolli91** [comment]
PN wo?

Aber wenn die Daten in der Multimon Ausgabe schon falsch sind, scheint hier Grundlegend etwas schief zu laufen. Also schon weit vor BOSWatch

**Comment by BachelPaul** [comment]
Ich suche gerade die PN funktion hier im Forum. 
Erst schauen dann schreiben würde helfen.

**Comment by Schrolli91** [comment]
Auf Github geht das nicht... aber im Forum unter: Http://www.boswatch.de

**Comment by Schrolli91** [comment]
Die Daten von multimon sehen ganz klar nach massiven Empfangsproblemen aus.
CRC Incorrect muss nichts heißen. Aber ein deinem Fall sieht es tatsächlich so aus, als wären die Daten totaler Müll.

Evtl bei der kalibrierung etwas schief gelaufen? Welchen Wert verwendest du?

**Comment by BachelPaul** [comment]
Als Korrekturwert habe ich -e 0,865 
Als Stick verwende ich den NooElec NESDR SMArt
Wenn ich POCSAG auswerte funktioniert die Auswertung perfekt.

**Comment by Schrolli91** [comment]
0,865 ???
Versuche mal einen Punkt statt einem Komma ;-)
Falls das nichts hilft, lass den Korrektur Wert ganz weg, der ist so gering, eigentlich dürfte das keinen Unterschied machen

**Comment by BachelPaul** [comment]
Habe beides verucht (mit Komma, mit Punkt).
Die Korrektur ist seht gering und verändert das Ergebnis nicht.

**Comment by Schrolli91** [comment]
Dann Versuch mal mit einem glatten Wert. also entweder 1 oder eben 0 bzw. weglassen

@flothi fällt dir zu dem Fall evtl noch irgendwas ein?

**Comment by BachelPaul** [comment]
Gibt es ein Set an Einstellungen die ziemlich sicher funktionieren?

**Comment by Schrolli91** [comment]
Was genau meinst du mir Set an Einstellungen?
Die Config nahe dem Urzustand mit Anpassungen die man selbst benötigt... Frequenz, Decoder, usw angeben und das ganze sollte laufen...

Ich tippe bei dir wie gesagt auf ein Problem mit dem Empfang. Mit BOSWatch hat das ganze sehr wahrscheinlich nichts zu tun. Welche Antenne verwendest du? Evtl. solltest du eine Probieren die sich im Bereich Lamda/2 oder Lamda/4 zur Funkfrequenz bewegt.

**Comment by flothi** [comment]
Ich klinke mich mal kurz ein, da ich mich auch erfolglos am FMS versucht habe:

Selbst mit ner 4m Feststationsantenne von Kathrein habe ich keine vernünftige Auswertung hinbekommen. 

Den Hinweis von Schrolli bezüglich FMS_CORRECT kann ich nur bestätigen, da kommt aus multimon-ng schon viel Grütze. 

Ggf müssen wir an den Modulationsparametern drehen, aktuell scheint FMS eher die Diva unter den Codecs zu sein

**Comment by Schrolli91** [comment]
Also ich hatte bei früheren Tests nie Probleme mit FMS. Auch völlig ohne ppm Korrektur.
Allerdings ist der Empfang in meiner Gegend auch recht akzeptabel.

Evtl sollte man dazu mal ein Thema im Forum eröffnen und andere Leute um Erfahrungsaustausch beten. Den es scheint ja so, als ob FMS tatsächlich bei mehreren Probleme zu bereiten scheint.

**Comment by PeterLaemmle** [comment]
@BachelPaul, schau dir mal das Frequenzspektrum mit SDRSharp an. Damit kannst du auch deine Antenne ausrichten.
Anschließend mal mit soRFmon auswerten. Wenn das tut, Parameter übernehmen und mit BOSWatch auswerten
Außerdem die gefixte Version von multimon-ng verwenden, vgl. Issue #95  
CRC würde ich mal abschalten.

**Comment by Schrolli91** [comment]
multimon wie es aus dem installer gezogen wird, ist gefixt
