### ISSUE TITLE
Folgefehler zu #30 --> BOSWatch startet nicht mehr

### ISSUE THREAD

**Issue by K3vP0** [Schrolli91/BOSWatch#35]
Folgefehler zu #30 
Tut noch nicht ganz was es soll :

```
30.06.2015 00:32:25 - descriptionList [DEBUG ] -- loading csv finished
30.06.2015 00:32:25 - boswatch [DEBUG ] starting rtl_fm
30.06.2015 00:32:28 - boswatch [DEBUG ] 
Found 1 device(s):
0: Realtek, RTL2838UHIDIR, SN: 00000001

Using device 0: Generic RTL2832U OEM
Found Rafael Micro R820T tuner
Tuner gain set to 49.60 dB.
Tuner error set to 75 ppm.
Tuned to 172992800 Hz.
Oversampling input by: 64x.
Oversampling output by: 1x.
Buffer size: 5.80ms
Exact sample rate is: 1411200.013458 Hz
Sampling at 1411200 S/s.
Output at 22050 Hz.

30.06.2015 00:32:28 - boswatch [CRITICAL] cannot start rtl_fm
30.06.2015 00:32:28 - boswatch [DEBUG ] cannot start rtl_fm
Traceback (most recent call last):
File "./boswatch.py", line 268, in 
raise OSError("starting rtl_fm returns an error")
OSError: starting rtl_fm returns an error
30.06.2015 00:32:28 - boswatch [WARNING ] SystemExit received
30.06.2015 00:32:28 - boswatch [DEBUG ] BOSWatch shuting down
30.06.2015 00:32:28 - boswatch [DEBUG ] terminate rtl_fm (3393)
```

rtl_fm war bei mir zu dem Zeitpunkt frei, trotzdem hat er abgebrochen...

**Comment by K3vP0** [comment]
Grund: Error Correction ... ist leider auch error drin.
WORKAROUND: 

Zeile 266 in boswatch.py 

```
        if ("Failed to open rtlsdr device" in rtlLog):
            logging.debug("\n%s", rtlLog)
            raise OSError("starting rtl_fm returns an error")
```

**Comment by JHCD** [comment]
Bei Dir ist auch alles anders ;-)

Das würde die Fehlererkennung aber auf einen reduzieren, schaue ich mir nochmal an.

**Comment by Schrolli91** [comment]
habe im dev-Branch im Ordner testdata/ mal eine txt Datei hochgeladen, mit allen Fehler die ich im rtl_fm Source finden konnte.

Wenn man den Text auf follgende beiden prüft, sind alle Fehler die geworfen werden können erschlagen:
- exiting
- Failed to open

```
fprintf(stderr, "Signal caught, exiting!\n");
fprintf(stderr, "Failed to open rtlsdr device #%d.\n", dongle.dev_index);
fprintf(stderr, "Failed to open %s\n", output.filename);
fprintf(stderr, "\nUser cancel, exiting...\n");
fprintf(stderr, "\nLibrary error %d, exiting...\n", r);
```

**Comment by JHCD** [comment]
Was ist mit der Error-Zeile?
Bei `Failed to open rtlsdr device` steht z.B. in der Zeile darüber `error -6`

**Comment by K3vP0** [comment]
@Schrolli91 Job sehe ich genau so.
@JHCD wird dann durch Failed to open abgegriffen, oder was meinst du?

**Comment by JHCD** [comment]
Genau das ist die Frage, ob es zu jedem Error einen Text gibt.

**Comment by Schrolli91** [comment]
Kann man ja erst mal auf die gegebenen Schlagworte prüfen.
Wird sich dann zeigen ob in Zukunft auch Fehler ohne Text auftreten.

Man sollte das Problem jetzt zumindest mal soweit als möglich fixen ohne es direkt zu übertreiben, Notfalls kann man immer noch einen Hotfix in den `master` nachschieben.
Aber dann wäre zumindest alles für das `2.0` Release zusammen...

**Comment by JHCD** [comment]
Bug wurde behoben, Issue closed
