### ISSUE TITLE
Pushover KeyError

### ISSUE THREAD

**Issue by Anderl94** [Schrolli91/BOSWatch#351]
Hallo,

bei mir funktioniert die Benachrichtigung mit Pushover leider nicht.
Habe in der config.ini den api_key und user_key eingetragen.
Habe mir die Pushover Plugindatei mal angesehen, besitze aber keine Python Kenntnisse.
Der Fehler scheint aber mit den Prioritäten zusammenzuhängen.

Installiert is BOSWatch 2.3 / 22.12.2017.

Auszug aus der Logdatei:
`14.01.2018 09:14:17 - Pushover        [DEBUG   ] send Pushover FMS`
`14.01.2018 09:14:17 - Pushover        [ERROR   ] cannot send Pushover request`
`14.01.2018 09:14:17 - Pushover        [DEBUG   ] cannot send Pushover request`
`Traceback (most recent call last):`
  `File "/opt/boswatch/plugins/Pushover/Pushover.py", line 68, in run`
   ` if data["function"] == '1':`
`KeyError: 'function'`
`14.01.2018 09:14:17 - Pushover        [DEBUG   ] close Pushover-Connection`
`14.01.2018 09:14:17 - alarmHandler    [DEBUG   ] return from: Pushover`

**Comment by Cryjack** [comment]
Mich stört das „Pushover FMS“ im Fehlertext. 
FMS hat keine Subfunktionen, das ist korrekt. Möchtest du FMS Telegramme per Pushover bekommen oder POCSAG Alarmierungen?

Am 14.01.18 um 10:36 schrieb Anderl94

**Comment by Anderl94** [comment]
Ich möchte FMS Telegramme bekommen. So wie ich das verstanden habe beziehen sich Prioritäten auf POCSAG, welches ich nicht benutze. In der Pushover Pythondatei habe ich Test weise die betroffenen Zeilen gelöscht und versucht eine feste Priorität zu setzten, was jedoch einen anderen Fehler verursacht hat weil mir bei Python einfach die Kenntnis fehlt.

**Comment by Cryjack** [comment]
Das Plugin ist in der Form tatsächlich eher für die POCSAG Texte ausgelegt. Da es in FMS keine „functions“ gibt kommt hier die obige Meldung. Im Prinzip müsstest du den IF Teil herausnehmen und in der Übergabe weiter unten die Priorität rausnehmen. Oder du setzt vorab selbst eine „functions“ Variable mit einem festen Wert. Ich bin momentan mobil unterwegs und kann dir keinen Code schicken. Was hast du denn bislang? Und wo kommt nun die Fehlermeldung.

**Comment by flothi** [comment]
Ich hätte hier einen Fix für ZVEI bzw FMS - du müsstest nur sagen, wie du die Meldung gerne hättest.

**Comment by Schrolli91** [comment]
Siehe: #322 
Evtl will sich dem jemand Annehmen und Pushover für FMS und ZVEI gangbar zu machen und in diesem Schritt gleich die Wildcards implementieren?

**Comment by flothi** [comment]
Wenn du mir versprichst dass das auch in BW3 geht ;-)

**Comment by Schrolli91** [comment]
Das "was" in BW3 geht? :-D

**Comment by flothi** [comment]
Na dass meine Arbeit dann nicht umsonst ist und das Plugin verwendbar bleibt :P

**Comment by Schrolli91** [comment]
Die Plugins nach BW3 zu migrieren wird wohl eher die kleinste Arbeit werden ;-)
Das beschränkt sich auf locker 80% copy-paste.

Also JA, deine Änderung wird auch in BW3 nutzbar sein :-P

**Comment by flothi** [comment]
Dann hast du mich überzeugt ;-)

**Comment by flothi** [comment]
Mit #352 (hoffentlich) gefixt

**Comment by Schrolli91** [comment]
Weitere Diskussion im Pull Request
