### ISSUE TITLE
deprecated extension - mysql_connect

### ISSUE THREAD

**Issue by Tho-Gra** [Schrolli91/BOSWatch#353]
Guten Tag, 

In der mysql.class.php befindet sich eine veraltete php function - mysql_connect.
[ BOSWatch/exampleAddOns/simpleWeb/mysql.class.php ](https://github.com/Schrolli91/BOSWatch/blob/master/exampleAddOns/simpleWeb/mysql.class.php)

Eventuell könntet ihr dies irgendwann aktualisieren!?

[http://php.net/manual/de/function.mysql-connect.php](http://php.net/manual/de/function.mysql-connect.php)

Grüße Thomas

**Comment by flothi** [comment]
Im develop-Zweig ist eine korrigierte Version zu finden - zumindest hoffe ich nichts übersehen zu haben ;-)

**Comment by Tho-Gra** [comment]
Hi,

https://github.com/Schrolli91/BOSWatch/blob/develop/exampleAddOns/simpleWeb/mysql.class.php

Meinst du die Version?
Falls ja, dann ist die auch mit mysql_connect...

**Comment by flothi** [comment]
Sorry, falsches Add-on - ich kümmere mich nachher drum

**Comment by Tho-Gra** [comment]
Super, vielen Dank im Voraus.

**Comment by Schrolli91** [comment]
Sollte erledigt sein....
