### ISSUE TITLE
FF-Agent Plugin falsche Reihung der JSON Daten

### ISSUE THREAD

**Issue by CJHarms** [Schrolli91/BOSWatch#356]
Bei Fragen und Problemen zu BOSWatch oder Plugins bitte unten gennante Informationen angeben:

- **BOSWatch Version + Branch**

SW Version: 2.3
Branch: master
Build Date: 22/12/2017
Python Vers: 2.7.13 (default, Nov 24 2017, 17:33:09) 

- **genutzte Plugins**

FF-Agent Plugin

- **Fehlerbeschreibung**

Im FF-Agent Plugin werden die ganzen der API zu übergebenden Daten innerhalb eines JSON übergeben und dafür werden sie zuerst innerhalb eines Dictionaries gespeichert.

Leider werden vor Python 3.6 die Daten innerhalb eines Dicitionarys bei der Ausgabe zufällig und neu angeordnet. Es ist allerdings zwingend notwendig, dass z.b. innerhalb des JSONs zuerst "Content-Type": "application/json" übergeben wird, da ansonsten die API es nicht akzeptiert.

Eine Möglichkeit wäre die Benutzung der OrderedDict Option für Python <3.6 bei den Dictionaries _alarmHeaders_ und _alarmData_ in der FFAgent.py. Leider sind meine Python Kenntnisse sehr begrenzt und die bisherigen Versuche waren nicht von Erfolg gekrönt.

- **Logfile (Auszug)**

15.02.2018 19:04:45 - FFAgent         [DEBUG   ] {'selectiveCallCode': 'Test', 'Content-Type': 'application/json', 'accessToken': '123456-4D54-1234-9C10-1234567890', 'webApiToken': '123456-1234-5678-B462-1111123456789, 'hmac': 'c22fa45b7ba606401ddb4cf94055d16ca6eb977e3c98996f6494ec5a823f836c'}
15.02.2018 19:04:45 - connectionpool  [DEBUG   ] Starting new HTTPS connection (1): free.api.service.ff-agent.com
15.02.2018 19:04:45 - connectionpool  [DEBUG   ] https://free.api.service.ff-agent.com:443 "POST /v1/WebService/triggerAlarm HTTP/1.1" 500 None
15.02.2018 19:04:45 - FFAgent         [WARNING ] FFAgent response: 500

Wie man sieht ist die Ordnung leider nicht korrekt. 'Content-Type': 'application/json' sollte z.b. an der ersten Stelle stehen.

- **ggf. Config File (Auszug)**

**Comment by Schrolli91** [comment]
Haben denn deine Änderungen aus #354 etwas gebracht?
Im speziellen das `OrderedDict`?

**Comment by CJHarms** [comment]
Leider nein. Habe den Commit auch wieder zurückgenommen, da ich ihn eigentlich auch gar nicht upstream pushen wollte. 🤦‍♂️ Mein Pull Request #354 war lediglich für das Logging und den Typo Fix gedacht. 

Den Fix für das hier beschriebene Problem würde ich mit einem neuen Pull Request einreichen, falls ich es hinkriege. Allerdings habe ich auf jemanden mit etwas mehr Python Wissen gehofft, der das eventuell fix umbauen kann.

**Comment by Schrolli91** [comment]
https://pymotw.com/2/collections/ordereddict.html
Evtl hilft dir das schon weiter

**Comment by flothi** [comment]
Ist das dann hier mit #404 erledigt?

**Comment by CJHarms** [comment]
Ja das sollte damit erledigt sein.
