### ISSUE TITLE
Pushover MSG  nur Adresse Filtern

### ISSUE THREAD

**Issue by Djgraphy** [Schrolli91/BOSWatch#359]
Hallo,
ich habe das Problem das ich nicht in der MSG filtern kann

"message": "<b>"+data["description"]+"</b><br>"+data["msg"].replace(";", "<br>")+"http://google.de/maps/place/" +.join(data["msg"].split("#")[2:2]),

So in etwas dachte ich es mir aber läuft immer auf Fehler Syntax  hab schon mehrere Variationen ausprobiert, kennt vielleicht einer eine Lösung?

**Comment by Schrolli91** [comment]
Mehr Code... Was genau versuchst du da? Soll das ein Dict werden?

**Comment by Djgraphy** [comment]
Ich möchte eigentlich aus der  MSG   nur die Straße ermitteln,  in der original Nachricht sind # verarbeitet ich würde gerne den Bereich nach der zweiten #  bis zur dritten #   ausgeben.

**Comment by Schrolli91** [comment]
siehe https://docs.python.org/2/library/stdtypes.html#str.split

`.split("#")[1]` probiers mal so in der Art

Edit: 2018/03/20
@Djgraphy inzwischen voran gekommen?
