### ISSUE TITLE
Gong

### ISSUE THREAD

**Issue by Medicus3453** [Schrolli91/BOSWatch#360]
Servus, 
Ich wenn ein ein Gong implementieren möchte mach ich das auch über ein Plugin oder hab ich was übersehn?

Grüße und schonmal vielen dank

**Comment by thejockel** [comment]
Moin,
grundsätzlich wird alles extern über Plugins gestartet.
Wie kannst du den Gong den ohne BOSWatch ansteuern oder ist das "nur" ein Sound Datei?

**Comment by Medicus3453** [comment]
Es wäre nur eine Sound Datei

**Comment by Medicus3453** [comment]
Mein plugin is soweit geschrieben jedoch läuft er bei meiner zvei nicht durch mein plugin was hab ich übersehen?
Bei alarm springt er doch normalerweise automatisch in den run abschnitt??

**Comment by flothi** [comment]
Ja, üblicherweise schon - was steht denn in der log-Datei, wenn ein Alarm reinkommt?

**Comment by thejockel** [comment]
Magst du den Code einmal aus also Code-Block anfügen.
Dann können wir uns den ansehen.

**Comment by Medicus3453** [comment]
![image](https://user-images.githubusercontent.com/37834995/38019228-4a5b535a-3277-11e8-9888-340e914f3afe.jpg)
![image](https://user-images.githubusercontent.com/37834995/38019251-5ee69e56-3277-11e8-8ddc-9178a1f1601f.jpg)

**Comment by Medicus3453** [comment]
Hab in meinem plugin extra ganz oben (fast abgeschnitten) jedoch innerhalb der run funktion ein output  'logging.debug(zvei....) dass ich sehen könnte ob er überhaupt in die run funktion springt aber des gibt er mir bis jetzt noch nicht aus

**Comment by thejockel** [comment]
Du hast also das template Plugin angepasst.
Ich würde dir empfehlen, den Folder einmal nach Gong zu kopieren.

Im nächsten Schritt musst in der Config das Plugin aktivieren.

[Plugins]
MySQL = 1
...
Gong =1

Alternative kannst du aber auch einfach das  template in den Plugin aktivieren.

**Comment by thejockel** [comment]
Und solltest du die Filter nutzten, muss du auch einen für das Plugin erstellen.

**Comment by Medicus3453** [comment]
aber ich dachte das template ist genau für solche probier Sachen da? 
hat das große Auswirkungen wenn ich das nicht mache? und die config datei umschreibe?

des mit den filtern is noch von meiner Probierphase was was ist hab das noch nicht wieder deaktiviert.

**Comment by flothi** [comment]
Du musst dem Tool ja schon sagen, dass es das Plugin gibt und dass es den verwenden soll.

Die Config ist ja fix angepasst, du musst bei den Flags (die Sammlung, wo auch Email,  Telegram und Co stehen) nur dein Plugin benennen und ggf Parameter definieren. Wichtig ist, dass du Groß - und Kleinschreibung bzw den Pfad einhältst

**Comment by Medicus3453** [comment]
aaaaaahhh super hat geklappt danke ! :))

**Comment by Medicus3453** [comment]
oke Jungs neues Problem er löst bei jeder zwei aus....wieso? ich dachte er greift nur auf run zu wenn die zwei mit der cdv datei übereinstimmen?

**Comment by flothi** [comment]
Zeig mal deinen Filter, der das Plugin aufruft

**Comment by thejockel** [comment]
Ich vermute, jetzt kommt der "doubleFilter_ignore_time = 15" Value ins Spiel. 
Es wird vermutlich immer der zweite "Alarm" einer zvei sein, der nicht abgespielt wird oder?

Um nur bestimmte zvei's zu übertragen brauchst du die Filter.

useRegExFilter = 1
Customname = ZVEI;zvei;Pluginname;*;(123456)|(654321)

**Comment by Medicus3453** [comment]
Filter schreib ich instant in die config datei oder? und setz halt useRegExFilter = 1 ?
was is das mit dieser regexr Seite? 

@thejockel des mit der doubleFilter_ignore_time stimmt soweit

**Comment by flothi** [comment]
Er löst ja offensichtlich bei jeder Tonfolge aus, also musst du auf deine zvei filtern.

@thejockel hat ja quasi schon gepostet was drin stehen muss. Regex werden dann relevant, wenn du Regeln erstellen willst, für das bloße Filtern auf eine spezifische ZVEI kannst du das ignorieren

**Comment by Medicus3453** [comment]
Gott jetzt stand ich grad echt aufm Schlauch! 
Aber jetzt glaub ich hab ich verstanden wie des Programm funktioniert. :) 
Danke nochmal (y)

**Comment by thejockel** [comment]
@Medicus3453 läuft jetzt alles?
Dann bitte den close bitte den Issue.
