### ISSUE TITLE
Melder Anschluss

### ISSUE THREAD

**Issue by cedw** [Schrolli91/BOSWatch#363]
Wie wäre es mit einer Funktion einen Melder anschließen zu können. Quasi wie bei Bosmon. Dieser wertet dann bestimmte Rics aus und schickt sie an Boswatch, dieser dann die Daten weiterschicken kann.

Wäre so etwas überhaupt Möglich? 
Wenn ja kann man das dann auch Einrichten das man mehrere Melder anschließen kann?

**Comment by flothi** [comment]
Der Eingang wäre dann via serieller Schnittstelle nehme ich an - also konzeptionell in der aktuellen Version 2 nicht wirklich vorgesehen. Vielleicht hat @Schrolli91 ja sowas in Version 3 vorgesehen.

**Comment by cedw** [comment]
Ja genau. 
Hm schade :/ 
Damit wäre für mich und evtl. einigen anderen das Problem mit IDEA gelöst. 
Vielleicht kann man es ja trotzdem für die Verson 3 fest einplanen.
Das wäre echt super wenn es irgendwie klappen würde :)

**Comment by flothi** [comment]
Hast du evtl mal ein paar Daten von der Schnittstelle? Baudrate etc?

**Comment by cedw** [comment]
Wo kann ich denn soetwas finden/herausfinden?

**Comment by flothi** [comment]
welcher melder ist es denn? Was sagt ggf die Programmierung bzw die Hersteller-Doku?

**Comment by cedw** [comment]
Boss 900 Serie. Ich gucke morgen mal :)

**Comment by Schrolli91** [comment]
Wenns weitere Infos zur Übertragung gibt sollte das in BW3 kein Problem darstellen.

**Comment by cedw** [comment]
Moin. 
sorry, dass es so lange gedauert hat. Habe leider nicht sonderlich viel. Das meiste was ich zum einstellen gefunden habe ist von BosMon.

http://www.bosmon.de/doc/BosMon/Serielle_Melder

Leider habe ich so in Foren und bei Swissphone keine weiteren Infos finden können. :/
Ich hoffe es hilft euch trotzdem etwas.
