### ISSUE TITLE
EA-RICs aus dem double...

### ISSUE THREAD

**Issue by NinavonReich** [Schrolli91/BOSWatch#364]
Hallo Ihr,

im Forum habe ich schon länger angesprochen, dass ich Probleme mit den EA-RICs und dem doubleFilter habe.
Um das Problem einer breiteren Masse näher zu bringen, melde ich mich jetzt auch mal hier.

Grob umschrieben, kann man sagen, dass der doubleFilter Meldungen verschluckt, wenn es mehrere Alarmierungen gibt und diese dann noch in ungünstigen Reihenfolgen eintreffen.

Für diejenigen unter Euch, die ähnliche Probleme und **keine Verschlüsselung** haben, wird f-kesslers Einwand (doubleFilter_check_msg auf 1 stellen) funktionieren.
Leider ist unser Netz verschlüsselt und damit wird jeder "kleinste" Alarm mit neuem Text gesendet.

Logisch scheint mir also nur, die EA-RICs komplett zu ignorieren.

Ich hoffe hier hat wer eine zündende Idee! :)

**_2.3.1-dev_**

Ganz ganz liebe Grüße! :)

**Comment by Schrolli91** [comment]
Welche genau, willst du ignorieren?

**Comment by NinavonReich** [comment]
Die multicastAlarm_delimiter_ric & multicastAlarm_ric.

**Comment by NinavonReich** [comment]
Auch hier noch mal, ich setze eine **Belohnung** für das Umsetzen aus!

**Comment by Schrolli91** [comment]
https://github.com/Schrolli91/BOSWatch/pull/370

**Comment by NinavonReich** [comment]
Schrolli hat die Lösung bereits verlinkt, vielen Dank dafür! :)
-> Close
