### ISSUE TITLE
MySQL: cannot connect to MySQL

### ISSUE THREAD

**Issue by MrCoopa** [Schrolli91/BOSWatch#365]
Bei Fragen und Problemen zu BOSWatch oder Plugins bitte unten gennante Informationen angeben:

- **BOSWatch Version + Branch

Master 2.3

- **genutzte Plugins**

MySQL

- **Fehlerbeschreibung**

Nach eingegangenem Alarm wird nicht in die angelegte MySQL DAtenbank geschrieben

Der MySQL Connector 2.1.6 wurde installiert (falls relevant).

- **Logfile (Auszug)**

29.04.2018 16:55:19 - alarmHandler    [DEBUG   ] call Plugin: MySQL
29.04.2018 16:55:19 - configHandler   [DEBUG   ] read [MySQL] from config file
29.04.2018 16:55:19 - configHandler   [DEBUG   ]  - dbserver = localhost
29.04.2018 16:55:19 - configHandler   [DEBUG   ]  - dbport = 3306
29.04.2018 16:55:19 - configHandler   [DEBUG   ]  - dbuser = root
29.04.2018 16:55:19 - configHandler   [DEBUG   ]  - dbpassword = ***
29.04.2018 16:55:19 - configHandler   [DEBUG   ]  - database = boswatch
29.04.2018 16:55:19 - configHandler   [DEBUG   ]  - tablefms = bos_fms
29.04.2018 16:55:19 - configHandler   [DEBUG   ]  - tablezvei = bos_zvei
29.04.2018 16:55:19 - configHandler   [DEBUG   ]  - tablepoc = bos_pocsag
29.04.2018 16:55:19 - configHandler   [DEBUG   ]  - tablesig = bos_signal
29.04.2018 16:55:19 - MySQL           [DEBUG   ] connect to MySQL
29.04.2018 16:55:19 - MySQL           [ERROR   ] cannot connect to MySQL
29.04.2018 16:55:19 - MySQL           [DEBUG   ] cannot connect to MySQL
Traceback (most recent call last):
  File "/opt/boswatch/plugins/MySQL/MySQL.py", line 84, in run
    connection = mysql.connector.connect(host = globalVars.config.get("MySQL","dbserver"), port = globalVars.config.get("MySQL","dbport"), user = globalVars.config.get("MySQL","dbuser"), passwd = globalVars.config.get("MySQL","dbpassword"), db = globalVars.config.get("MySQL","database"), charset='utf8')
  File "/usr/local/lib/python2.7/dist-packages/mysql/connector/__init__.py", line 44, in Connect
    return MySQLConnection(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mysql/connector/connection.py", line 107, in __init__
    self.connect(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mysql/connector/connection.py", line 346, in connect
    self._open_connection()
  File "/usr/local/lib/python2.7/dist-packages/mysql/connector/connection.py", line 313, in _open_connection
    self._ssl)
  File "/usr/local/lib/python2.7/dist-packages/mysql/connector/connection.py", line 165, in _do_auth
    raise errors.get_exception(packet)
OperationalError: 1251 (08004): Client does not support authentication protocol requested by server; consider upgrading MariaDB client
29.04.2018 16:55:19 - MySQL           [DEBUG   ] close MySQL
29.04.2018 16:55:19 - alarmHandler    [DEBUG   ] return from: MySQL
29.04.2018 16:55:19 - alarmHandler    [DEBUG   ] [END ALARM]
29.04.2018 16:55:19 - doubleFilter    [DEBUG   ] Added 56XXX to doubleList
29.04.2018 16:55:19 - decoder         [DEBUG   ] received ZVEI
29.04.2018 16:55:19 - doubleFilter    [DEBUG   ] checkID: 56XXX ()
29.04.2018 16:55:19 - doubleFilter    [DEBUG   ] -- previous id 56XXX is within doubleFilter_ignore_time (5s)
29.04.2018 16:55:19 - doubleFilter    [INFO    ] ZVEI double alarm (id): 56XXX within 0 second(s)
29.04.2018 16:55:19 - doubleFilter    [DEBUG   ] Added 56XXXto doubleList

Danke schonmal.

**Comment by flothi** [comment]
Welche Version des Betriebssystems nutzt du? Die Datenbank hast du eingerichtet?

**Comment by MrCoopa** [comment]
das neuste. ist glaube ich debian 9 stretch
nunja, die datenbank habe ich durch das script angelegt, wie im wiki beschrieben.

**Comment by Schrolli91** [comment]
`OperationalError: 1251 (08004): Client does not support authentication protocol requested by server; consider upgrading MariaDB client`

Google wurde dazu schon mal befragt?

**Comment by MrCoopa** [comment]
ja, hab ich durch, der fehler bleibt bestehen.

**Comment by grinsekatze003** [comment]
Problem hatte ich auch. Einfach die neuste Version des MySQL Connectors herunterladen und installieren. Zusätzlich muss in der plugin Datei "passwd" zu "password" im Connection String geändert werden.

**Comment by MrCoopa** [comment]
Nach vielem rumspielen und Updaten verschiedener komponenten klappts nun bei mir

**Comment by Schrolli91** [comment]
@MrCoopa Könntest du kurz festhalten was du upgedatet hast und was deiner Vermutung nach die Komponente war, die das Problem gelöst hat?

**Comment by MrCoopa** [comment]
Das kann ich leider nicht genau sagen, da ich oft mehrere Komponenten deinstalliert und wieder installiert habe. Ich habe ebenfalls die Vermutung, das es ein Rechte Problem gewesen sein könnte, das ich nach einigem googlen ausgeführt habe.
Nutze das ganze nun mit Phpmyadmin um die Auswertungen online darstellen zu können.
