### ISSUE TITLE
gleiche ZVEI mehrere Filter

### ISSUE THREAD

**Issue by MrCoopa** [Schrolli91/BOSWatch#366]
Servus,

bin nun fast fertig mit meiner Konfiguration, habe aber noch eine Frage.
Ich habe 2 Plugins aktiv, MySQL und Pushover. In MySQL sollen alle ZVEIs mitgeloggt werden, mit Pushover nur bestimmte versendet werden. Trotzdem soll ein Eintrag in die Datenbank geschrieben werden. Bricht Boswatch nach einem Filter ab, oder werden alle Filter durchlaufen und somit auch alle Plugins angetriggert?

Danke schonmal.

**Comment by PeterLaemmle** [comment]
Hallo MrCoopa,
das funktioniert wie gewünscht, es werden alle Filter durchlaufen.

**Comment by MrCoopa** [comment]
Alles klar, vielen Dank. Hab´s getestet funktioniert wie gewünscht.
Wenn es in Sachen Record Plugin weiter gehen würde wäre es noch perfekter ;)
