### ISSUE TITLE
GPIO ansteuern?

### ISSUE THREAD

**Issue by nobbie2009** [Schrolli91/BOSWatch#369]
Ist es irgendwie möglich, einen bestimmten GPIO anzusteuern, bspw. bei Status C um einen Toröffner zu betätigen?

**Comment by flothi** [comment]
Ja, ist es - ich steuere zB bei einem Alarm ein Relaismodul an. Code muss ich mal hübsch machen.

**Comment by nobbie2009** [comment]
beschreib mal bitte wie du das realisierst

**Comment by MrCoopa** [comment]
Eventuell über einen 433mhz Sender eine Funksteckdose anzusteuern wäre ideal.

**Comment by flothi** [comment]
Gib mir noch ein paar Tage, bin derzeit anderweitig gebunden.

Ich sehe es eher so, dass Boswatch einen Pin ansteuert - was du an den Pin hängst ist dem Programm egal.

**Comment by creiner** [comment]
Ich hab mir ein Plugin geschrieben, welches einen GPIO Pin ansteuert und einen Speaker bei bestimmten Rics quäken lässt. 
Bin gerade unterwegs, sollte heute aber im laufe des Tages dazu kommen den Code rauszusuchen und hier zu posten. Für einen Pull-Request war er mir zu unschön..

**Comment by creiner** [comment]
Hier die Datei als gist. Die entsprechenden RICs zieht er sich aus der config.
https://gist.github.com/creiner/de023e3540af4ac6a1d710f84c7fb3eb

**Comment by nobbie2009** [comment]
Supi, werde es mir heute Abend anschauen.:blush:

**Comment by MrCoopa** [comment]
Geht das ganze auch für ZVEI?

**Comment by flothi** [comment]
Klar - das geht für alle Decoderarten.

**Comment by MrCoopa** [comment]
Kannst du den Code auch dafür zur Verfügung stellen?

**Comment by Schrolli91** [comment]
Gibt es dazu noch Fragen?
Oder möchte jemand Code direkt als Plugin beisteuern, für GPIO Funktionen?

**Comment by einmalacht** [comment]
Hallo ich bin ja auf der Suche nach einer Lösung um RIC abhängig verschiedene httprequests #373 auszuführen und frage mich ob dich den hier geposteten code verwenden kann.

Wie binde ich das ganze den in Boswatch ein, dann würde ich mal bisl was testen.

Viele Grüße

**Comment by grosj** [comment]
Hallo zusammen,
bin erst seit ein paar Tage mit Boswatch unterwegs und stöber hier so durch die Gegend. Da bin ich auf dieses Issue gestoßen. Ist ja allerdings schon ein paar Tage alt.
Zwei Anmerkungen bzw. Fragen dazu:
- Die Überrpüfung der Rics, bei welchen das Plugin auslösen soll könnte man doch auch aus dem Plugin raus halten und per Filter umsetzen.
- Das Timesleep zwischen dem High und Low des GPIO-Pin hält doch auch komplett Boswatch für die Zeit an?

Viele Grüße, Marco

**Comment by Schrolli91** [comment]
> * Die Überrpüfung der Rics, bei welchen das Plugin auslösen soll könnte man doch auch aus dem Plugin raus halten und per Filter umsetzen.

Sollte so sein ja - Hart codierte Sachen direkt im Plugin sind immer etwas ungünstig

> * Das Timesleep zwischen dem High und Low des GPIO-Pin hält doch auch komplett Boswatch für die Zeit an?

Auch korrekt, außer man startet BOSWatch im async-Mode. Dann wird nämlich jedes Plugin in einem eigenen Thread gestartet.
Siehe dazu: https://github.com/Schrolli91/BOSWatch/blob/master/config/config.template.ini#L41

**Comment by Schrolli91** [comment]
#438
