### ISSUE TITLE
MySQL Plugin testen

### ISSUE THREAD

**Issue by Schrolli91** [Schrolli91/BOSWatch#37]
Ich habe gerade das MySQL Plugin ein wenig erweitert.
Aktuell kann ich es aber nicht testen, evtl könnte das jemand mal für mich übernehmen und mir eine Rückmeldung geben.

Grüße

EDIT:
Achtung die Datenbank Struktur hat sich ein wenig geändert. Es sollte also die neuste boswatch.sql eingespielt werden. Befindet sich jetzt im Ordner des MySQL Plugins.

**Comment by K3vP0** [comment]
Sieht sehr gut aus, hatte die Änderung bei mir auch schon eingefügt.. aber habe leider keine Möglichkeit es hochzuladen. 
Ansonsten funktioniert es bei mir bis jetzt ohne Probleme.

**Comment by Schrolli91** [comment]
Danke schonmal,
falls was auffällt, einfach schreiben....

Wenn du eigenen Code einbringen willst, musst du den DEV-Zweig "forken", dort kannst du dann schalten und walten wie du möchtest. Wenn du denkst deine Code Änderung ist "bereit" für die Allgemeinheit, dann kannst du einen "Pull-Request" senden. Dann kann ich den Code ins Projekt übernehmen, anpassen, wie auch immer.

**Comment by Schrolli91** [comment]
Es scheint wirklich reibungslos zu laufen - Notfalls ein Bug-Issue aufmachen.
