### ISSUE TITLE
NMA entfernen

### ISSUE THREAD

**Issue by Schrolli91** [Schrolli91/BOSWatch#371]
Da Notify my Android inzwischen ja leider abgeschalten wurde, sollte auch das Plugin sowie alle weiteren Abhängigkeiten entfernt werden.

Config, Plugin Wiki ...

**Comment by flothi** [comment]
Dafür

**Comment by Schrolli91** [comment]
Wiki bereinigt, wäre schön wenn nochmal jemand drüber ließt ob ich noch irgendwo was zu NMA vergessen habe.

**Comment by Schrolli91** [comment]
Falls jemand über den Pull auch noch fix drüber schauen könnte - #374 - Danke ;-)
