### ISSUE TITLE
Pushover: Priorität einzelnen ZVEIs zuweisen

### ISSUE THREAD

**Issue by MrCoopa** [Schrolli91/BOSWatch#377]
Ist es irgendwie möglich, das Plug-in so zu ergänzen, das man ein paar wenigen ZVEIs eine eigene (höhere) Priorität zuzuweisen und diese z.b aus der CSV zu lesen. 
Es soll sich halt eine andere Benachrichtigung bei bestimmten ZVEIs angezeigt werden. 

Vielen Dank schon mal.

**Comment by Schrolli91** [comment]
Einfachste Möglichkeit wäre vermutlich, das Plugin zu duplizieren und dann entsprechend zu konfigurieren.

**Comment by MrCoopa** [comment]
Dann würde er aber manche ZVEIs doppelt verschicken einmal mit normaler und einmal mit höherer Prio, weil ein Plug-in alles verschickt, aber das zweite dann die Ausgewählten auch noch mal.
Die Funktion gibt's schon für RICs aber leider nicht für ZVEI. Ich dachte das könnte man vlt zum großen Teil übernehmen.

**Comment by Schrolli91** [comment]
> Es soll halt eine andere Benachrichtigung bei bestimmten ZVEIs angezeigt werden.
Aber der Teext ist doch nicht anders, nur weil die Prio anders ist?

> Die Funktion gibt's schon für RICs aber leider nicht für ZVEI.
Da bezieht sich das aber auf die Subric, die beim Alarm bereits vorliegt. Bei ZVEI gibt es kein entsprechendes Merkmal.

Am einfachsten wäre vermutlich wirklich, das Plugin zu duplizieren und dann evtl mittels Regex das ganze zu lenken

**Comment by MrCoopa** [comment]
Der Text ist nicht anders, aber die Benachrichtigungseinstellungen ändern sich nach der Prio.

**Comment by Schrolli91** [comment]
Dann wäre der einfachste Workarround, eine Abfrage einfach in das Plugin zu schreiben

**Comment by MrCoopa** [comment]
Leider bin ich in Python nicht ganz so fit.
Könnte das jemand übernehmen. 
Es soll nur bei ein paar wenigen ZVEIs die Prio geändert werden.

**Comment by flothi** [comment]
Ich hab das für POCSAG mit Listen gelöst, ich kann da was basteln

**Comment by MrCoopa** [comment]
Das wäre super, danke.

**Comment by flothi** [comment]
Willst du nur ne andere Prio oder auch einen Text in Abhängigkeit von der Prio?

**Comment by MrCoopa** [comment]
Nur eine andere Prio. 
Hintergrund ist das ich viele ZVEIs bekomme, aber bestimmte hervorheben möchte.

**Comment by flothi** [comment]
Alles klar

**Comment by flothi** [comment]
Ist mit Pullrequest #378 eingestellt.

**Comment by MrCoopa** [comment]
Danke, 
Einfach die ZVEIs mit kommas hintereinander schreiben?

**Comment by flothi** [comment]
Exakt, entsprechend der gewünschten Prio einfach 12345, 54321, 11111 usw

**Comment by Schrolli91** [comment]
Bei weiteren Fragen zur Funktionalität dann bitte direkt im Pull-Req. #378
