### ISSUE TITLE
Filter unterscheidung

### ISSUE THREAD

**Issue by Medicus3453** [Schrolli91/BOSWatch#387]
Servus,

kann das Programm zwischen zwei filtern unterscheiden?
Und wenn ja wo steht der entsprechende Code dazu? 

Grüße

**Comment by flothi** [comment]
Ernäher das mal läuter, bitte

**Comment by Medicus3453** [comment]
Ich möchte je nach filter unschiedliche plugins aufrufen können.

**Comment by Kinick4** [comment]
Klar geht das.
Ich habe ein Plugin für die Übertragung von Feuerwehr-Nachrichten und eins für alles was rein kommt (außer Netz-Ping). Geht problemlos einzurichten. Du legst ja in der Config bei Filters fest, was an welches Plugin übertragen werden soll. Im Plugin selbst legst du ja nur noch fest, welche Bestandteile des übergebenen du "gesendet" haben möchtest (RIC, Datum, ...). Was meines Wissens nach nicht geht ist für ein Plugin Multicast nutzen und für ein anderes nicht. Dafür benötigst du eine Zweite Boswatch-Instanz.
