### ISSUE TITLE
Mehrere Text-RICs hinterlegen

### ISSUE THREAD

**Issue by Reissdorf84** [Schrolli91/BOSWatch#390]
BOSWatch Version 2.4.1  
Branch: Master
genutzte Plugins: MySQL, Telegram

[multicastAlarm]
(...)
 enable multicastAlarm (0 - off | 1 - on)
multicastAlarm = 1

time limit for alarms that do not belong to the multicastAlarm sequence in seconds
multicastAlarm_ignore_time = 15

multicastAlarm delimiter RIC (usually used as a starting point for a alarm sequence). Needs to be empty if multicastAlarms are interrupted by normal alarms.
multicastAlarm_delimiter_ric =

multicastAlarm RIC that is used to send the text message
multicastAlarm_ric =1300(...)

Fehlerbeschreibung: 
Nurton-RICs werden beim Expressalarm verworfen da Text nicht auf der einen TextRIC ankommt. Es werden im Netz zwei verschiedene TextRICs genutzt, ein mal für Klartextübermittlung und eine IDEA verschlüsselt. Angegeben bei "multicastAlarm_ric" ist zu Zeit die Klartext-TextRIC. Alle RICs mit der verschlüsselten Übertragung werden aber dadurch verworfen.

Lassen sich mehrere RICs angeben? Durch Komma getrennt?

Gruß und danke

**Comment by f-kessler** [comment]
Das sollte gehen. Werden verschlüsselte und unverschlüsselte Alarme gemischt, oder sauber nacheinander empfangen?

**Comment by Reissdorf84** [comment]
Vielen Dank für sehr schnelle Antwort. Die RICs werden sauber sortiert gesendet:
Ric1
Ric2
Ric3
Klartext-TextRIC
Ric4
Ric5
IDEA-TextRIC

Ich habe die zweite RIC dem config-file hinzugefügt und laut log hat das Programm es auch geschluckt. Werde es jetzt mal testen und dann berichten.

Wenn es tatsächlich läuft, könnte man es eventuell dem Kommentar hinzufügen. Ich habe nämlich überall gesucht ob das geht, aber nichts gefunden. Dann haben es die Nachfolgenden einfacher.

**Comment by Reissdorf84** [comment]
Heute Nacht getestet und für gut befunden. Läuft hervorragend.
Vielen Dank für eure gute Arbeit.

**Comment by Schrolli91** [comment]
Wo sollte man das Dokumentieren?
Als Kommentar direkt in der config?

**Comment by Reissdorf84** [comment]
Ja, so könnte ich es mir vorstellen.
Bei allow_ric, deny_ric und netIdent_ric steht ja auch dabei das ein Komma als Separator zugelassen ist. Da es hier nicht dabei stand, hatte ich vermutet das es vielleicht nicht geht.
