### ISSUE TITLE
Amazon Echo einbinden

### ISSUE THREAD

**Issue by maeweee** [Schrolli91/BOSWatch#391]
Hallo, ist es möglich den Amazon Echo so einzubinden, dass er mir bestimmte Alarme vorliest?

**Comment by Tho-Gra** [comment]
Moin,

Die DNS Records für BOSWatch.de sind leer...

Leider somit keine Seite erreichbar.

Grüße

**Comment by maeweee** [comment]
Dankeschön, aber leider weiß ich nicht viel mit deiner Aussage anzufangen. :(
Sprich: Es ist nicht möglich?

**Comment by Tho-Gra** [comment]
Sorry, irgendwie ist mir da ein Fehler passiert. Ich wollte Schrolli91 direkt anschreiben.

Bzgl. deines Problems, kann ich dir nichts zu sagen, da mit kein Echo ins Haus kommt ;-)

Grüße

**Comment by flothi** [comment]
Es gibt hier auf GitHub einige Alexabibliotheken, die eine Sprachausgabe triggern können. Da ich mir so ein Ding jedoch nicht anschaffe, kann ichs leider nicht testen.

Magst du ggf mal schauen, ob du die zum laufen kriegst, dann können wir mal schauen, wie die Einbindung klappen kann. (zB https://github.com/ewenchou/alexa-agent)

**Comment by maeweee** [comment]
Hallihallo und vielen Dank für die Verlinkung.
Leider bin ich technisch so unbegabt, dass ich so etwas niemals eingebunden bekomme.

Schade, aber da muss ich wohl warten, bis es wen interessiert, der das auch kann.

**Comment by flothi** [comment]
@maeweee oder du stiftest dem Projekt so ein Gerät :-)

**Comment by maeweee** [comment]
Leider bin ich nicht so solvent, als das ich das einfach so machen könnte.

**Comment by flothi** [comment]
Ich behaupte mal, wir können das hier mal auf Eis legen?!

**Comment by maeweee** [comment]
so ist es. :)
Schade!!

**Comment by flothi** [comment]
Dann schließe ich mal hier, spricht ja nix gegen einen neuen Anlauf zum späteren Zeitpunkt
