### ISSUE TITLE
Boswatch.de - Domain nicht erreichbar

### ISSUE THREAD

**Issue by Schrolli91** [Schrolli91/BOSWatch#392]
@Tho-Gra schrieb:
`Moin, Die DNS Records für BOSWatch.de sind leer... Leider somit keine Seite erreichbar. Grüße`

Die Domain wurde nicht von mir selbst registriert.
Aktuell ist noch nicht bekannt, was da vorgefallen ist.

**Comment by flothi** [comment]
Und zwischenzeitlich hat sie sich jemand geholt ;-)

**Comment by Schrolli91** [comment]
Das Boswatch Communication Center - bwcc.boswatch.de ist wieder erreichbar.
Außerdem auch der Jenkins Server unter jenkins.boswatch.de

**Comment by Schrolli91** [comment]
boswatch.de leitet jetzt zum BWCC

Ein Forum wird es vorerst nicht mehr geben - Aufwand/Nutzen passen nicht
