### ISSUE TITLE
Phillips Hue einbinden

### ISSUE THREAD

**Issue by maeweee** [Schrolli91/BOSWatch#393]
Parallel zu meiner letzten Anfrage, noch eine Frage zu den "Phillips Hue" Lampen.
Ist es möglich (vielleicht mittels IFTTT o.ä.) bei bestimmten Rics bestimmte Lichter zu triggern?

In meiner Traumwelt sogar mit Alexa gekoppelt.

**Comment by flothi** [comment]
Sehe ich das richtig, dass die Kommunikation über diese Bridge läuft?

Ich kenne das System nicht, ggf müsste man mit jemandem, der eins hat, remote entwickeln.

**Comment by f-kessler** [comment]
Ich habe für Hue etwas geschrieben. Es gibt aber noch ein Problem mit der asynchronen Verarbeitung der Alarme. Ein fix dafür teste ich seit kurzem.

**Comment by Schrolli91** [comment]
@f-kessler dein Problem bezieht sich darauf? #375

**Comment by f-kessler** [comment]
Ja, richtig. Habe mal deepcopy eingebaut und teste jetzt.

**Comment by Schrolli91** [comment]
siehe #394 
Bei weiteren Fragen bitte im Pull Request anfragen.
Bei Fehler gerne auch per neuem Issue
