### ISSUE TITLE
Mit einem Filter mehrere Plugins aufrufen

### ISSUE THREAD

**Issue by MrCoopa** [Schrolli91/BOSWatch#395]
Nur ganz kurze Frage: Kann ein Filter mehrere Plugins triggern?

alarm_pushover_sql= ZVEI;zvei;Pushover,MySQL;87xxxxxx;xx[0-9]{3}

?

Vielen Dank!

**Comment by Schrolli91** [comment]
in BW2 nicht.... bei BW3 wird das ganze wesentlich flexibler.
Du musst also den Filter kopieren für jedes Plugin.

**Comment by MrCoopa** [comment]
Okay, danke. Dachte nur das es so vlt etwas schneller geht, da weniger Filter durchlaufen werden müssen.

**Comment by Schrolli91** [comment]
Langsamer ist das aber auch nur in der Theorie - Praktisch fällt das nicht auf.
Die Geschwindigkeit von BOSWatch selbst ist um ein vielfaches höher als die reine Alarmierungszeit auf dem Kanal.
