### ISSUE TITLE
Eingegangene Alarme sortieren

### ISSUE THREAD

**Issue by maeweee** [Schrolli91/BOSWatch#399]
- **BOSWatch Version + Branch**
aktuelle develop
- **genutzte Plugins**
pushover
mysql
- **Fehlerbeschreibung**

hallo!
ich lasse mir bestimmte alarme per mysql / php / html als webübersicht ausgeben und per pushover senden.
nun möchte ich gerne, dass wenn alarme eingehen das programm auf eine bestimmte ric achtet.
diese ric kann am anfang, am ende, oder wahllos zwischen mehreren rics stehen.

boswatc hsoll nun alle rics in gewohnt chronologischer reihenfolge auflisten / per pushover senden, aber genau diese ric immer am ende (wenn nach X sekunden keine weitere ric folgt) anhängen / ausgeben.

an -wenns geht sogar kurzfristigen- lösung wäre ich sehr erfreut!! :)
vielen danK!!

**Comment by Schrolli91** [comment]
Kann dir leider nicht ganz folgen... Hast du mal ein Beispiel parat?

**Comment by maeweee** [comment]
![Unbenannt-1](https://user-images.githubusercontent.com/47451816/61532370-ebebf000-aa29-11e9-85e2-a4f6df3ebad1.png)
hoffe das versteht man= sorry, meien tastatur und meine sprachre ist nich tdeutsch?

**Comment by flothi** [comment]
Ok, verstanden - könnte natürlich sportlich werden, je nachdem, wann diese Meldung kommt. Immer, auch mal einzeln, bei bestimmten Alarmen?

**Comment by maeweee** [comment]
hallo, diese meldung kommt bei jedem alarm für die feuerwehr.
sprich: feuer groß (zb. 4 feuerwehren und diese einheit).
aber auch technischen hilfe (ein feuerwehr und diese einheit).

man kann sagen wie zb ein stadtbrandmaster.

danke für euren hilfr!!

**Comment by Schrolli91** [comment]
Ich würde vermuten, mit dem aktuellen Software Design nicht machbar.
Da müsste man schon gewaltig an den Balken biegen.

**Comment by maeweee** [comment]
Alles klar, danke für die Info!! :-)
Kann man sich das für die nächste Version vielleicht wünschen??

**Comment by Schrolli91** [comment]
Nach der aktuell geplanten Architektur ließe sich so etwas mit begrenztem Aufwand umsetzen.
Denn hier wird die "Routing"-Funktionalität sowieso dynamisch Alarme bearbeiten, zurückhalten und gesammelt versenden können - So zumindest der Plan

**Comment by Schrolli91** [comment]
Falls der Bedarf dazu besteht sollte dann ein eigenes Issue im BW3 Repo erstellt werden
