### ISSUE TITLE
"How to Code Plugins" - Readme schreiben

### ISSUE THREAD

**Issue by Schrolli91** [Schrolli91/BOSWatch#40]
Es wäre so langsam mal angebracht, alle Informationen die zum schreiben eines Plugins von Relevanz sind, zentral als keines Readme zusammenzuschreiben.
Evtl. auch anhand von Beispielen zusammen mit dem `template` Plugin das ganze besser nachvollziehbar gestalten.

Wichtige Punkte die mit rein müssen:
- [x] Grundgerüst eines Plugins (.onload() und .run())
- [x] Benutzen des Loggers
- [x] Loglevel passend wählen
- [x] Nutzung der config.ini + Einlesen der Daten
- [x] Erklärung der globalen Hilfs-Funktionen
- [x] Verarbeitung der von BOSWatch bereitgestellten Daten

Am ende soll die `interface.txt` komplett abegelöst werden

**Comment by K3vP0** [comment]
Besteht eigentlich Intresse/Bedarf den Log farbig zu gestalten? 
https://pypi.python.org/pypi/colorama

**Comment by Schrolli91** [comment]
Damit wäre das ganze soweit erst mal fertig.
Wenn sich was ändert muss eben erweitert/geändert werden.

closed
