### ISSUE TITLE
ImportError: No module named sleekxmpp

### ISSUE THREAD

**Issue by budda85** [Schrolli91/BOSWatch#401]
Hallo, 
ich probiere gerade mir ein Plugin zu basteln, welches mir Meldungen per XMPP/Jabber schicken soll. Dazu hatte ich geplant [SleekXMPP](http://sleekxmpp.com) zu nehmen. Ich bin kompletter python-Anfänger!

Also habe ich mir einen Ordner SleekXMPP unter Plugins erstellt und dann das Plugin template kopiert und in SleekXMPP.py umbenannt.

Dann die Sleekxmpp-Git-Repo geklont und erstmal zwei Tutorial gemacht um zu gucken ob das senden überhaupt klappt.
[Echo-Bot](http://sleekxmpp.com/getting_started/echobot.html)
[Login, Senden, Logout](http://sleekxmpp.com/getting_started/sendlogout.html)
Soo, das funktioniert alles wunderbar.
Nun zum Problem:
Ich hab dann mal das Plugin gefüllt, ob das jetzt richtig funktioniert ist erstmal egal, denn ich bekommen schon beim laden folgende Fehlermeldung:

> 02.08.2019 09:57:18 - pluginLoader    [ERROR   ] error loading plugin: SleekXMPP
02.08.2019 09:57:18 - pluginLoader    [DEBUG   ] error loading plugin: SleekXMPP
Traceback (most recent call last):
  File "/opt/boswatch/includes/pluginLoader.py", line 32, in loadPlugins
    plugin = loadPlugin(i)
  File "/opt/boswatch/includes/pluginLoader.py", line 106, in loadPlugin
    return imp.load_module(plugin["name"], *plugin["info"])
  File "/opt/boswatch/plugins/SleekXMPP/SleekXMPP.py", line 18, in <module>
    import sleekxmpp
ImportError: No module named sleekxmpp

Hier der Anfang meines Plugins:
>import logging 
import sleekxmpp
from includes import globalVars  
from includes.helper import timeHandler
from includes.helper import wildcardHandler
from includes.helper import configHandler
import sys

Ich hab zum testen auch mal probiert meine echobot.py oder send_client.py zu importieren, aber auch hier kommt der selbe Fehler. echobot und send_cient alleine funktionieren super.
Eine config Eintrag habe ich auch gemacht.

Was mache ich falsch?

Danke und Gruß, Jan

**Comment by f-kessler** [comment]
Sieht so aus als hättest du das Modul "sleekxmpp" noch nicht im Python installiert. Schau mal unter https://github.com/fritzy/SleekXMPP "Get the Code".

**Comment by budda85** [comment]
hmm, das hatte ich gestern schon probiert, bin mir aber nicht sicher, ob ich das wie heute als root gemacht habe. Aber daran hat es tatsächlich gelegen....Sorry.
Aber wieso funktionieren die Beispiele ohne die installation und nur mit dem klonen repo?

**Comment by f-kessler** [comment]
Ich vermute, dass es in dem Paket was du heruntergeladen hast, ein Unterverzeichnis mit Namen "sleekxmpp" gibt und darin liegen die entsprechenden Module.

**Comment by budda85** [comment]
genau, aber wieso kann das plugin nicht darauf zugreifen wenn ich den "sleekxmpp" Ordner mit in den Plugin Ordner kopiere?

**Comment by flothi** [comment]
Groß- und Kleinschreibung hast du beachtet?

**Comment by budda85** [comment]
Ja. Hab es genauso importiert wie im Beispiel.

**Comment by flothi** [comment]
Ich meinte auch die der Ordner und der py-Datei im Filesystem

**Comment by budda85** [comment]
Meine beiden Beispiele echobot.py und client_send.py liegen alle im selben Ordner wie mein SleekXMPP.py Plugin.
Die beiden Beispiele gingen ohne das installieren von sleekxmpp über pip. Da hat es gereicht, das ich das GIT-Projekt in dem Ordner habe und einfach ein 'import sleekxmpp' gemacht habe. Nur das Plugin findet oder nutzt nicht das GIT-Projekt

**Comment by Schrolli91** [comment]
Das liegt wohl daran, dass das Plugin selbst nur importiert wird.
Stichwort absoluter- und relativer- Importweg.

Wenn man es per PIP installiert liegt es zentral und Python findet es von überall aus.
Wenn das Modul allerdings aus einem Ordner raus importiert wird, müsste vermutlich auch der Importpfad der Lib relativ vom PluginLoader aus angegebenen werden - so meine Vermutung.

Aber mit dem PIP Install läuft es jetzt? Dann bitte Closen.

**Comment by budda85** [comment]
Ja läuft. Danke
