### ISSUE TITLE
rics zählen, alte ,,aussortieren`` - statistik

### ISSUE THREAD

**Issue by maeweee** [Schrolli91/BOSWatch#402]
hallo, gibt es die möglichkeit alarmierte rics zu zählen, bzw eine statistik einzuführen ??
somit könnte man zb alte ,,tote`` rics finden und aussortieren / löschen.

lgg

**Comment by flothi** [comment]
Das würde ich als Auswertung von der Datenbank laufen lassen, da es nicht originär mit dem Handling zu tun hat

**Comment by maeweee** [comment]
Danke, habe es jetzt selbst mittels phpMyAdmin gelöst. :)

**Comment by flothi** [comment]
Magst du uns noch mitteilen wie?

**Comment by maeweee** [comment]
Also ich mache das alles leider noch händisch. :D
Mittels SQL Kommando RICS für einen Zeitrum anzeigen und dann bei Excel die RICS mit der CSV vergleichen und alte löschen.

**Comment by flothi** [comment]
Danke fürs Feedback
