### ISSUE TITLE
Unterstützung eines Funkscanners mit Diskriminatorausgang

### ISSUE THREAD

**Issue by schmidt-kevin** [Schrolli91/BOSWatch#403]
Hallo, 

wir sind auf euer Projekt aufmerksam geworden und interessieren uns für die Integration von BosWatch auf einem Raspberry PI 3B+ in Kombination mit einem Funkscanner. 

Meine Frage wäre gibt es eine Möglichkeit das Signal von einem Funkscanner anzugreifen so das es wie z.B. BosMon funktioniert?

Beste Grüße

**Comment by Schrolli91** [comment]
In BOSWatch 3 ist ein solches Feature geplant, aktuell wäre das nur ein Eigeninitiative möglich. Ob das bisher jemand umgesetzt hat kann ich nicht sagen (Diskriminatorausgang in den Audioeingang und dann in multimon leiten)
