### ISSUE TITLE
Parameter Charset für multimon-ng

### ISSUE THREAD

**Issue by homer54** [Schrolli91/BOSWatch#407]
Es soll die Möglichkeit geschaffen werden, dass der Charset für multimon-ng als Parameter mitgegeben werden kann. So werden deutsche Umlaute in POCSAG Nachrichten richtig verarbeitet ("-C DE"). Siehe https://github.com/EliasOenal/multimon-ng/blob/ef812874eab0922aed392bbc2cd7694df35797f0/unixinput.c#L589

https://github.com/Schrolli91/BOSWatch/blob/016bd906c365666d2a58b9237488ff1948242139/boswatch.py#L326

**Comment by flothi** [comment]
Lass mich nicht lügen aber die Umlaute kommen bei mir sauber rein. Auch ohne zusätzl. Flag. Wo sind die Umlaute bei dir denn inkorrekt?
