### ISSUE TITLE
FMS CSV-Description list funktioniert nicht

### ISSUE THREAD

**Issue by Kinick4** [Schrolli91/BOSWatch#409]
Hallo,
ich nutze die aktuellste BOSWatch-Version (gezogen letztes WE).
Mein Problem ist aktuell, dass bei FMS die Umwandlung der "IDs" in die Description nicht funktioniert. 
Im Logfile ist ersichtlich, dass alle Einträge ohne Buchstaben in der ID erfolgreich umgewandelt werden, alle mit Buchstaben jedoch nicht. Da unsere FMS-Kennungen jedoch leider an zweiter Stelle einen Buchstaben haben, funktioniert das leider nicht... Gibt es hierfür einen Trick bzw. was genau mache ich falsch? Er decodiert FMS und ZVEI gleichzeitig. ZVEI funktioniert problemlos, hat aber halt auch keine Buchstaben in der Kennung... Hat jemand einen Tipp?
Gruß Kinick

01.10.2019 23:42:14 - descriptionList [DEBUG   ] loading description lists
01.10.2019 23:42:14 - descriptionList [DEBUG   ] - load FMS description list
01.10.2019 23:42:14 - descriptionList [DEBUG   ] -- loading fms.csv
01.10.2019 23:42:14 - descriptionList [DEBUG   ] {'fms': ' ', 'description': None}
01.10.2019 23:42:14 - descriptionList [DEBUG   ] {'fms': '7x679891', 'description': 'Mnao'}
01.10.2019 23:42:14 - descriptionList [DEBUG   ] {'fms': '12345678', 'description': 'TEST'}
01.10.2019 23:42:14 - stringConverter [DEBUG   ] call convertToUTF8('TEST')
01.10.2019 23:42:14 - stringConverter [DEBUG   ] -- UTF-8
01.10.2019 23:42:14 - descriptionList [DEBUG   ] {'fms': '1a234567', 'description': 'Test2'}
01.10.2019 23:42:14 - descriptionList [DEBUG   ] -- loading csv finished

**Comment by flothi** [comment]
Jupp, kann den Fehler nachvollziehen; wahrscheinlich fällt es jetzt erst auf, da kaum einer FMS nutzt ;-) Ich arbeite dran

**Comment by flothi** [comment]
Also, nach meiner Einschätzung liegt hier der Hund begraben:
https://github.com/Schrolli91/BOSWatch/blob/ca26f1dc9a71d166c3dc9612924781511fb97ae6/includes/descriptionList.py#L46

Wir lassen nur numerische Einträge zu, maximal noch eine Subric mit a-d. Ich versuch das mal sinnhaft aufzubohren.

**Comment by flothi** [comment]
Mit PullRequest #416 behoben; Verifikation notwendig.

**Comment by Schrolli91** [comment]
@Kinick4 teste das bitte mal bei Gelegenheit, dann würde ich die Anpassungen mergen.
Weitere Diskussion dann im PR

**Comment by Kinick4** [comment]
Moin! Weder mit -b beta noch mit -b dev war ich erfolgreich. Was genau muss ich fürs Testen tun?

**Comment by flothi** [comment]
Schau dir mal die Änderung in der descriptionList.py an:
https://github.com/Schrolli91/BOSWatch/pull/416/files#diff-38b92d71a911b9d957aac13222021dbbR46

Änder den Inhalt der Klammer mal händisch bei dir und schau mal, ob es klappt. Da es sich noch um einen offenen Pullrequest handelt, steht der in keinem branch

**Comment by Kinick4** [comment]
Moin!
Funktioniert so absolut einwandfrei. Vielen Dank!
Gruß Kinick
