### ISSUE TITLE
eMail-Versand an mehrere Empfänger 

### ISSUE THREAD

**Issue by JHCD** [Schrolli91/BOSWatch#41]
Moin, moin,

folgender Fehler wurde im FMS-Forum gepostet:

```
Problem mit dem versenden von Emails,
d.h. es wird nur an die erste Adresse in der Zeile verschickt,
ich habe schon diverse Alternativen ausprobiert, allerdings ohne Erfolg:

1. to = user@irgendwo, user2@woanders
2. to = user@irgendwo,user2@woanders
3. to = user@irgendwo; user2@woanders
4. to = user@irgendwo;user2@woanders

der erste user@irgendwo bekommt die Email, alles was dahinter steht wird ignoriert :-(
```

**Comment by Schrolli91** [comment]
Google sagt:

> The msg['To'] needs to be a string:
> `msg['To'] = "a@b.com, b@b.com, c@b.com"`
> 
> While the recipients in sendmail(sender, recipients, message) needs to be a list:
> `sendmail("a@a.com", ["a@b.com", "b@b.com", "c@b.com"], "Howdy")`

Workaround String per .split() zur Liste machen:

> email.py Zeile 66
> `server.sendmail(globals.config.get("eMail", "from"), globals.config.get("eMail", "to").split(), msg.as_string())`

**Comment by JHCD** [comment]
Fehler behoben, es können nun mehrere eMail-Adresse angegeben werden... 
Als Trennzeichen sind Komma und Semikolon zugelassen
