### ISSUE TITLE
Plugin für Pushbullet

### ISSUE THREAD

**Issue by mezzobob** [Schrolli91/BOSWatch#42]
Ich würde ein Plugin für pushbullet schreiben.
Push an pushbullet Kanal.
https://docs.pushbullet.com

Ich muss das Tool ersmal zum laufen bringen ;) 
Bekomme im Moment noch diese Meldung "[WARNING ] FMS CRC incorrect"

**Comment by Schrolli91** [comment]
oke, wäre super...

Das CRC incorrect liegt aber an multimon - ergo, du bekommst schon vom Empfang her Mist rein.

**Comment by Schrolli91** [comment]
@mezzobob 
gibt es von dem plugin eigentlich schon eine lauffähige Version die man mergen könnte? Oder hat sich das ganze im Sande verlaufen?
Würde mich über ne kurze Rückmeldung freuen

**Comment by Schrolli91** [comment]
@mezzobob Plugin gestorben?
Falls keine Rückmeldung kommt schließe ich die Tage...
Gruß
