### ISSUE TITLE
Konfiguration Telegram Plugin

### ISSUE THREAD

**Issue by flothi** [Schrolli91/BOSWatch#427]
Hallo zusammen,

ich bekomme das Telegram Plugin einfach nicht zum laufen.

Habe den Telegram Bot so installiert:

![grafik](https://user-images.githubusercontent.com/59511703/71769371-b0ce7200-2f20-11ea-8940-4971ae0ba77a.png)

Die config.ini angepasst:

![grafik](https://user-images.githubusercontent.com/59511703/71769389-ea06e200-2f20-11ea-96e9-4623ae38efed.png)

und Boswatch gestartet. Im log erscheinen dann für den Bot Token und die ChatID Sternchen??

![grafik](https://user-images.githubusercontent.com/59511703/71769403-233f5200-2f21-11ea-8a10-4a4450f77cad.png)

Habe die das im falschen Format eingegeben?

Bei einem Alarm bekomme ich diese Fehlermeldung:

![grafik](https://user-images.githubusercontent.com/59511703/71769415-4cf87900-2f21-11ea-8882-469605902120.png)

Was muss ich machen, damit es funktioniert?

Gruß

_Originally posted by @Maagi93 in https://github.com/Schrolli91/BOSWatch/issues/383#issuecomment-570804224_

**Comment by flothi** [comment]
Frage welche python-Version nutzt du?
`python -V`

**Comment by Maagi93** [comment]
Habe eine neue Datei namens bot.py angelegt:

![grafik](https://user-images.githubusercontent.com/59511703/71774842-29abe900-2f76-11ea-8691-c188bbdf1003.png)

Auch hier bekomme ich eine Fehlermeldung wenn ich diese mit python bot.py starte:

![grafik](https://user-images.githubusercontent.com/59511703/71774861-798ab000-2f76-11ea-823f-2c69b8e0eec1.png)


Ich nutze Python 2.7.16.

**Comment by flothi** [comment]
Entferne in der Chat-ID mal das '-'

**Comment by Kinick4** [comment]
Moin!
Also ich hab den Telegram-Bot mittels "(sudo) pip install python-telegram-bot" installiert.

Frage: Sind die Telegram-Gruppen Supergruppen?
Dann musst du wenn bspw: web.telegram.org/#/im?p=s1234567890_876654321... (aus Telegram Web)
BOTChatIDAPIKey = -1001234567890

So läuft das bei mir zumindest. Hab alle Gruppen als Supergruppen angelegt, da ich das schöner finde. Und immer aufpassen, dass der Bot auch in der Gruppe ist und in der Gruppe auch posten darf, was mein Lieblingsfehler ist...

Gruß Kinick

**Comment by thejockel** [comment]
> Habe eine neue Datei namens bot.py angelegt:
> 
> ![grafik](https://user-images.githubusercontent.com/59511703/71774842-29abe900-2f76-11ea-8691-c188bbdf1003.png)
> 
> Auch hier bekomme ich eine Fehlermeldung wenn ich diese mit python bot.py starte:
> 
> ![grafik](https://user-images.githubusercontent.com/59511703/71774861-798ab000-2f76-11ea-823f-2c69b8e0eec1.png)
> 
> Ich nutze Python 2.7.16.

für mal bitte diese befehle aus:

```
mv bot.py bot.sh
chmod +x bot.sh
./bot.sh
```

**Comment by papierkorb27** [comment]
Genau das gleiche Problem hatte ich gestern auch und ich bin hier fündig geworden: https://github.com/Schrolli91/BOSWatch/issues/389#issuecomment-462079842

> sudo su
pip uninstall telegram
pip uninstall telegram-bot
pip uninstall python-telegram-bot
pip install python-telegram-bot
exit

Ich habe genau die Reihenfolge bei der De- und Installation eingehalten und nun läuft es bei mir...

**Comment by Maagi93** [comment]
Danke papierkorb27! Das hat mein Problem gelöst!
