### ISSUE TITLE
Mehrere DVB-T Sticks und Service

### ISSUE THREAD

**Issue by Maagi93** [Schrolli91/BOSWatch#429]
Hallo zusammen,

ich habe aktuell zwei DVB-T Sticks im Einsatz. Einen für POCSAG und einen für FMS.

Wie schaffe ich es, dass beide durch den Service gestartet werden?

Aktuell sieht die boswatch.service bei mir so aus:

![grafik](https://user-images.githubusercontent.com/59511703/72205707-9ba89480-3486-11ea-9943-abc88f5a90da.png)

Gruß

**Comment by thejockel** [comment]
Moin,
ich würde ein zweites Unit-File erstellen.

LG

**Comment by Maagi93** [comment]
Hi,

ich habe eine zweite Datei: boswatch_fms.service angelegt.

Dann habe ich eine zweite Datei: install_boswatch_fms_service.sh angelegt und den Code auf boswatch_fms.service angepasst.

Anschließend: sudo bash install_boswatch_fms_service.sh und damit den zweiten Service installiert.

Das löst mein Problem und beide RTL werden gestartet. Vielen Dank!
