### ISSUE TITLE
firEmergency Plugin | Sonderzeichen werden fehlerhaft übertragen

### ISSUE THREAD

**Issue by K3vP0** [Schrolli91/BOSWatch#43]
Überschrift sagt alles. 
Umlaute werden fehlerhaft übertragen. Anzeige in firE nur durch "unknown char".

**Comment by JHCD** [comment]
Klingt nach einem Zeichensatzproblem (Unterschied im Sender- und Empfänger-System).
Wir führen (bisher) keine Zeichensatzkonvertierung im Skript durch.

**Comment by JHCD** [comment]
firEmergency erwartet den XML-String in UTF-8
http://alamos-ug.de/mediawiki/index.php?title=TCP/IP

Ich habe mal eine entsprechende Konvertierung eingebaut, bitte testen.

**Comment by K3vP0** [comment]
Dein Fix hat mir leider nicht soviel gebracht...
Habe die firEmergency.py und die bosWatch.py widerwillend meines TextWranglers in UTF8 gespeichert. Und schwups funktioniert es, würde dann bedeuten das man die zweite Zeile in jeder Datei tauschen müsste, oder ? 

Also von 
<code># -_\- coding: cp1252 -_-</code>
zu
<code># -_\- coding: UTF8 -_-</code>
tauschen?

**Comment by JHCD** [comment]
Das macht eigentlich keinen Sinn, da wir keine eigenen Zeichen in die msg packen, sondern die Ausgabe von multimon-ng durchreichen. Der Variable ist der Zeichensatz des Skriptes eigentlich egal. _grübels_

Tauschen alleine hilft nicht, Du müsstest dann auch jede Datei nach UTF8 wandeln und abspeichern.

**Comment by JHCD** [comment]
Probiere doch bitte mal, ob firEmergency.py in UTF8 reicht...

**Comment by K3vP0** [comment]
Oh man
Wenn ich in der BOSWatch.py den Teststring definiere… ist klar das der dann kein UTF8 wird… 

Ich werde mal nur die firE in UTF8 belassen und gucken ob ich noch Probleme mit Sonderzeichen / Umlaute bekomme.

Ansonsten kann das Ticket denke ich erstmal gehalten werden, bis ich morgen ein Ö oder sonst was auf dem Melder habe.

**Comment by JHCD** [comment]
Okay, das ist die Lösung, es handelt sich um einen Teststring und nicht Realbetrieb...
Das erklärt das natürlich, einTeststring in boswatch.py ist natürlich dann nicht in UTF8...

**Comment by K3vP0** [comment]
Ja wobei, ich sonst aber auch Probleme bekommen habe, bei normalen Alarmen … liegt wahrscheinlich daran das die Verbindung via Western 1 geöffnet wird und ich dann kein UTF8 Zeichen senden kann, ist das möglich?

**Comment by JHCD** [comment]
So, ich habe die Testdaten mal in UTF8 konvertiert und die Änderung im Plugin zurückgebaut.

**Comment by Schrolli91** [comment]
Na dann bin ich mal gespannt obs jetzt geht @kevinkleist :smiley:

**Comment by K3vP0** [comment]
Läuft ! 
#closed
