### ISSUE TITLE
firEmergency Plugin

### ISSUE THREAD

**Issue by t1m0** [Schrolli91/BOSWatch#432]
Hi,

ich bin auf der Suche nach der Doku für das firEmergency Plugin, kann diese aber leider nicht finden.

Zudem wäre ich an einer FMS Übergabe an FE2 interessiert, wenn ich das richtig gesehen habe ist dies nicht supported?

**Comment by Schrolli91** [comment]
Korrekt, im Plugin ist aktuell nur ZVEI und POCSAG implementiert.

Eine Doku gibt es dazu nicht - einfach in der Config IP und Port eintragen, dann sollte es schon gehen.
Ich selbst kenne Das Plugin allerdings nicht.

Am besten einfach mal im BWCC nachfragen, evtl nutzt das Plugin ja jemand und kann dir da weiterhelfen. https://bwcc.boswatch.de/

**Comment by Schrolli91** [comment]
#437
