### ISSUE TITLE
Eine Boswatch-Instanz mit mehreren Sticks

### ISSUE THREAD

**Issue by Kinick4** [Schrolli91/BOSWatch#433]
Moin!
Da bei mir der Empfang bei gewissen Wetterlagen nicht zufriedenstellend ist, würde ich gerne eine Boswatch-Instanz mit mehreren DVB-T Sticks betreiben, um die Trefferquote deutlich zu erhöhen.
Unterstützt die aktuelle Version das?
Gruß Kinick

**Comment by Schrolli91** [comment]
Nein, leider nicht...
Mit BOSWatch 3 wird so etwas durch das Server Client Konzept allerdings machbar sein

**Comment by Smith-fms** [comment]
In einer Instanz nicht, aber du kannst die Instanz mehrfach starten und jeweils mit dem Startparameter -d (0,1,..) mehrere Sticks ansprechen.
Wenn du unterschiedliche Configs brauchst, kannst du einfach den Ordner /opt/boswatch kopieren und dann dort auch mit -d unterschiedliche sticks jeweils ansprechen.

**Comment by Kinick4** [comment]
@Schrolli91 Vielen Dank! Dann werde ich mich gedulden müssen...
@Smith-fms Ich versende die Daten per Telegram. Bei 2 Instanzen bekomme ich ja alles doppelt, was beide empfangen. Dann wird das fix unübersichtlich...

**Comment by Nortfid** [comment]
Versuche es mit der richtigen Antenne und einem Antennenverstärker. Das macht Welten aus ;)

**Comment by Kinick4** [comment]
Moin!
Beruflich bedingt schaffe ich es erst jetzt zu antworten...
Ich bin aktuell mit dem Modell Nooelec NESDR Smart v4 unterwegs. Natürlich ist das ein "kostengünstiges" Exemplar. Wollte aber nicht zu viel ausgeben. Wie kann ich das Ding denn "pushen", um einen besseren Empfang zu erhalten?
Gruß Kinick

**Comment by Schrolli91** [comment]
@Kinick4 BW befindet sich allerdings schon im ersten Testlauf, kann also gerne mal versucht werden.
Bei Empfangsproblemen -> Antenne - Da kann BOSWatch selber nix reißen
