### ISSUE TITLE
[CRITICAL] cannot read config file

### ISSUE THREAD

**Issue by dm-o** [Schrolli91/BOSWatch#434]
`sudo python boswatch.py -d 0 -f 16xx.935M -a POC1200`

```
     ____  ____  ______       __      __       __
    / __ )/ __ \/ ___/ |     / /___ _/ /______/ /_
   / __  / / / /\__ \| | /| / / __ `/ __/ ___/ __ \
  / /_/ / /_/ /___/ /| |/ |/ / /_/ / /_/ /__/ / / /
 /_____/\____//____/ |__/|__/\__,_/\__/\___/_/ /_/
            German BOS Information Script
          by Bastian Schroll, Jens Herrmann

SW Version:     2.4.3
Branch:         master
Build Date:     22.09.2019

Frequency:   169.935M
Device-ID:   0
Error in PPM:    0
Active Demods:   1
- POC1200
Squelch: 0
Gain: 100

20.02.2020 19:58:05 - boswatch        [CRITICAL] cannot read config file
20.02.2020 19:58:05 - boswatch        [WARNING ] SystemExit received
Traceback (most recent call last):
  File "boswatch.py", line 405, in <module>
    if globalVars.config.getboolean("BOSWatch","processAlarmAsync") == True:
  File "/usr/lib/python2.7/ConfigParser.py", line 369, in getboolean
    if v.lower() not in self._boolean_states:
AttributeError: 'list' object has no attribute 'lower'
```

Jemand eine Idee?
Frisch aufgesetzter Raspberry mit aktuellem Raspbian Buster lite.
Dann das Installscript ausgeführt und RTL Dongle kalibriert,

**Comment by Smith-fms** [comment]
config.ini in config/ vorhanden? 
wenn da nur eine template drin ist:
`cp config.template.ini config.ini` 
ansonsten mal die Rechte für die config.ini checken.

**Comment by dm-o** [comment]
config ist vorhanden. Gehört jetzt user pi und gruppe pi - vorher root/root
Rechte 777 trotzdem selbe Meldung

**Comment by Schrolli91** [comment]
Was steht bei `processAlarmAsync` in der Config? Ich denke, da steht ein falscher Wert.

**Comment by dm-o** [comment]
processAlarmAsync = 0 aber egal ob ich da 0 oder 1 eintrage: keine Veränderung

**Comment by Schrolli91** [comment]
Was steht in der Zeile davor?
Am besten mal nen Auszug rund um diese Stelle posten.

**Comment by dm-o** [comment]
> Am besten mal nen Auszug rund um diese Stelle posten.

Tut mir leid, ich musste voran kommen und hab nochmals alles neu installiert. Habe dann die Beispieldatei nochmals per "cp" kopiert und die bei der installation vorhandene config damit überschrieben.
Dann lief es.

Ich werde bei gelegenheit nochmals einen Installversuch machen und gucken ob das wieder auftritt. Was mich wunderte war, dass sowohl die config als auch die Beispiel config im Verzeichnis waren nach der frischen installation. Im Installguide wurde aber immer noch davon geschrieben, dass man die Beispieldatei als config Datei kopieren soll. Hielt ich für unsinnig, weil die config ja da war und deshalb habe ich eben in der schon die Änderungen gemacht. 
Das war aber der einzige Unterschied zur zwieten Installation, wo es dann mit dem cp und überschrieben der config auch funktionierte.
Ist die config vielleicht in dem Install-Download und sollte da gar nicht rein?

**Comment by Schrolli91** [comment]
Nein, aber der Installer sollte sie am Ende umkopieren - siehe https://github.com/Schrolli91/BOSWatch/blob/master/install.sh#L229

Evtl. ist da auch beim Installieren nur was schief gegangen - einen Bug sehe ich an der Stelle allerdings nicht. Ich gehe hier nach wie vor von einer Fehlerhaften Config Datei aus, den mit dem jetzigen Stand scheint es zu laufen.
