### ISSUE TITLE
fehler bei der installation

### ISSUE THREAD

**Issue by Walterbraunlage** [Schrolli91/BOSWatch#435]
hier ist der logfile setup_log.txt
kann mir jemand helfen?

OK:1 http://raspbian.raspberrypi.org/raspbian stretch InRelease
OK:2 http://archive.raspberrypi.org/debian stretch InRelease
Paketlisten werden gelesen...
Paketlisten werden gelesen...
Abhängigkeitsbaum wird aufgebaut....
Statusinformationen werden eingelesen....
build-essential ist schon die neueste Version (12.3).
cmake ist schon die neueste Version (3.7.2-1).
git ist schon die neueste Version (1:2.11.0-3+deb9u5).
libpulse-dev ist schon die neueste Version (10.0-1+deb9u1).
libusb-1.0-0 ist schon die neueste Version (2:1.0.21-1).
libusb-1.0-0-dev ist schon die neueste Version (2:1.0.21-1).
libusb-1.0-doc ist schon die neueste Version (2:1.0.21-1).
libx11-dev ist schon die neueste Version (2:1.6.4-3+deb9u1).
qt4-default ist schon die neueste Version (4:4.8.7+dfsg-11+rpi1).
qt4-qmake ist schon die neueste Version (4:4.8.7+dfsg-11+rpi1).
sox ist schon die neueste Version (14.4.1-5+deb9u2).
Die folgenden Pakete wurden automatisch installiert und werden nicht mehr benötigt:
  coinor-libipopt1v5 libmumps-seq-4.10.0 libraw15 realpath
Verwenden Sie »sudo apt autoremove«, um sie zu entfernen.
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 8 nicht aktualisiert.
Action: download on stuff ok.
fatal: Zielpfad 'rtl-sdr' existiert bereits und ist kein leeres Verzeichnis.
Action: git-clone on rtl-sdr failed.
Exitcode: 128

**Comment by Smith-fms** [comment]
Bitte das Verzeichnis von Boswatch löschen. Es sieht für mich so aus, als wäre da bereits was versucht worden zu installieren.

`rm -R /opt/boswatch`

**Comment by Walterbraunlage** [comment]
dann kommt wieder ein fehler und der logfile sie so aus.


OK:1 http://raspbian.raspberrypi.org/raspbian stretch InRelease
OK:2 http://archive.raspberrypi.org/debian stretch InRelease
Paketlisten werden gelesen...
Paketlisten werden gelesen...
Abhängigkeitsbaum wird aufgebaut....
Statusinformationen werden eingelesen....
build-essential ist schon die neueste Version (12.3).
cmake ist schon die neueste Version (3.7.2-1).
git ist schon die neueste Version (1:2.11.0-3+deb9u5).
libpulse-dev ist schon die neueste Version (10.0-1+deb9u1).
libusb-1.0-0 ist schon die neueste Version (2:1.0.21-1).
libusb-1.0-0-dev ist schon die neueste Version (2:1.0.21-1).
libusb-1.0-doc ist schon die neueste Version (2:1.0.21-1).
libx11-dev ist schon die neueste Version (2:1.6.4-3+deb9u1).
qt4-default ist schon die neueste Version (4:4.8.7+dfsg-11+rpi1).
qt4-qmake ist schon die neueste Version (4:4.8.7+dfsg-11+rpi1).
sox ist schon die neueste Version (14.4.1-5+deb9u2).
Die folgenden Pakete wurden automatisch installiert und werden nicht mehr benötigt:
  coinor-libipopt1v5 libmumps-seq-4.10.0 libraw15 realpath
Verwenden Sie »sudo apt autoremove«, um sie zu entfernen.
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 8 nicht aktualisiert.
Action: download on stuff ok.
Klone nach 'rtl-sdr' ...
Action: git-clone on rtl-sdr ok.
-- The C compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Build type not specified: defaulting to release.
-- Extracting version information from git describe...
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29") 
-- Checking for module 'libusb-1.0'
--   Found libusb-1.0, version 1.0.21
-- Looking for libusb_handle_events_timeout_completed
-- Looking for libusb_handle_events_timeout_completed - not found
-- Looking for libusb_error_name
-- Looking for libusb_error_name - not found
-- Found libusb-1.0: /usr/include/libusb-1.0, /usr/local/lib/libusb-1.0.so
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Building with kernel driver detaching disabled, use -DDETACH_KERNEL_DRIVER=ON to enable
-- Building for version: v0.5.3-12-ge3c0 / 0.5git
-- Using install prefix: /usr/local
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/boswatch/install/rtl-sdr/build
Action: cmake on rtl-sdr ok.
Scanning dependencies of target rtlsdr_shared
[  3%] Building C object src/CMakeFiles/rtlsdr_shared.dir/librtlsdr.c.o
[  6%] Building C object src/CMakeFiles/rtlsdr_shared.dir/tuner_e4k.c.o
[ 10%] Building C object src/CMakeFiles/rtlsdr_shared.dir/tuner_fc0012.c.o
[ 13%] Building C object src/CMakeFiles/rtlsdr_shared.dir/tuner_fc0013.c.o
[ 16%] Building C object src/CMakeFiles/rtlsdr_shared.dir/tuner_fc2580.c.o
[ 20%] Building C object src/CMakeFiles/rtlsdr_shared.dir/tuner_r82xx.c.o
[ 23%] Linking C shared library librtlsdr.so
[ 23%] Built target rtlsdr_shared
Scanning dependencies of target convenience_static
[ 26%] Building C object src/CMakeFiles/convenience_static.dir/convenience/convenience.c.o
[ 30%] Linking C static library libconvenience_static.a
[ 30%] Built target convenience_static
Scanning dependencies of target rtl_sdr
[ 33%] Building C object src/CMakeFiles/rtl_sdr.dir/rtl_sdr.c.o
[ 36%] Linking C executable rtl_sdr
/usr/bin/ld: CMakeFiles/rtl_sdr.dir/rtl_sdr.c.o: undefined reference to symbol 'exit@@GLIBC_2.4'
//lib/arm-linux-gnueabihf/libc.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
src/CMakeFiles/rtl_sdr.dir/build.make:97: die Regel für Ziel „src/rtl_sdr“ scheiterte
make[2]: *** [src/rtl_sdr] Fehler 1
CMakeFiles/Makefile2:154: die Regel für Ziel „src/CMakeFiles/rtl_sdr.dir/all“ scheiterte
make[1]: *** [src/CMakeFiles/rtl_sdr.dir/all] Fehler 2
Makefile:127: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2
Action: make on rtl-sdr failed.
Exitcode: 2

**Comment by Schrolli91** [comment]
Raspian Version? Was spuckt `uname -a` aus?
Welchen Branch/BW-Version willst du installieren?

Die Tatsache das rtl_fm nicht baut hat aber erst mal nix mit BOSWatch zu tun. Komisch ist das aber dennoch.

**Comment by Walterbraunlage** [comment]
vorab: es ist ein Banana Pi M2

pi@banana:~ $ uname -a
Linux banana 3.10.108-BPI-M2U-Kernel #5 SMP Fri May 10 10:12:10 CST 2019 armv7l GNU/Linux
pi@banana:~ $ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.11 (stretch)
Release:	9.11
Codename:	stretch

diese version will ich installieren:
wget https://github.com/Schrolli91/BOSWatch/raw/master/install.sh

**Comment by Schrolli91** [comment]
Am besten wendest du dich mit dieser Frage mal ans BWCC https://bwcc.boswatch.de/
Ich selbst hab das nie auf dem Banana getestet - aber evtl einer unserer anderen User.

**Comment by Skipper1990** [comment]
Habe den Fehler auch auf einem Banana Pi 
Hast du es zum laufen bekommen ? Wenn ja wie ?
