### ISSUE TITLE
DIVERA FMS und ZVEI 

### ISSUE THREAD

**Issue by tobkoh** [Schrolli91/BOSWatch#436]
Hallo zusammen,
ich teste gerade das Divera Plugin aktuell ja nur im develop Branch zu finden. 
Divera Version: Alarm 

Aktuell übertrage ich mit dem Plugin ZVEI und FMS:

FMS: 
Die Fahrzeuge sind in DIvera entsprechend hinterlegt mit der passenden Fahrzeug-ric (Bezeichnung von Divera) 
Wenn jedoch ein FMS Status über RegEx erkannt wird, wird dieser als Alarm angelegt und verändert nicht den Fahrzeug-Status. 
Ich hab auch eine Vermutung woran es liegt hier in dieser Zeile wird "Alarm" vorgegeben ist aber für FMS Status falsch: 
https://github.com/Schrolli91/BOSWatch/blob/c77391db88d2ccf84674e5d78b9a8dbde6edaae4/plugins/Divera/Divera.py#L117

Der Link müsste laut Doku so aussehen: 

`https://www.divera247.com/api/fms?status_id=STATUS&vehicle_ric=FAHRZEUGRIC&accesskey=ACCESSKEY `

Link zu Doku: https://help.divera247.com/pages/viewpage.action?pageId=21627859

Leider reichen meine Kenntnis nicht aus um das so umzuschreiben, dass man hier eine Unterscheidung zwischen Alarm und FMS oder einer Mitteilung herzustellen. 

ZVEI: 
Bin ich noch am Test scheint aber soweit ganz gut zu funktionieren. 
RegEX filtert grob die 5-Tonfolgen: 
In Divera habe ich verschieden Gruppen angelegt, diese Gruppen können auch über ein Ric unterschieden werden. Jedoch wird in Divera min. 6 Stellen für den Ric gefordert. (ist bei einer 5-Tonfolge echt doof) 
Ich habe daher die config.ini so angepasst: 

`zvei_title = Alarm: A%ZVEI%`

Einfach ein "A" vorn angefügt. 

Bisher habe ich alle Alarm immer über den httpRequest erledigt funktioniert auch echt nahezu ohne Verzögerung. 

Vielleicht findet sich ja jemand der mich beim Testen etwas unterstützen kann bzw. das Plugin entsprechend anpassen.

**Comment by Schrolli91** [comment]
@grosj - vielleich magst du dir das ja mal anschauen

**Comment by grosj** [comment]
> @grosj - vielleich magst du dir das ja mal anschauen

Kann ich gerne mal machen. Aktuell gibt es im Plugin keine Unterscheidung. Es wird immer die Alarm-Api ausgeführt.

Allerdings bin ich erst in 2 Wochen wieder da. Dann werde ich mich einmal drüm kümmern.

**Comment by grosj** [comment]
Die Doku zu den Divera APIs wird allerdings hier weitergepflegt:
https://api.divera247.com/

**Comment by grosj** [comment]
Hallo zusammen,
ich habe mir das Ganze nochmal angeschaut.
Das PlugIn, welches ich für Divera entwickelt habe, ist für die Divera-Alarmierung.
Über FMS laufen ja sowohl die Statusmeldungen für Fahrzeuge, als auch Alarmierungen.

Für den Anwendungsfall, dass der Fahrzeugstatus über Boswatch an Divera geschickt werden soll würde ich ein zusätzliches DiveraPlugin sehen, welches dann die fms-Api von Divera ansteuert.

Ich könnte dies zwar umsetzen, aber leider nicht testen, da wir bereits auf Digitalfunk umgestiegen sind.

Wenn sich jemand zum Testen findet, dann kann ich es gerne umsetzen.

Viele Grüße, Marco

**Comment by tobkoh** [comment]
Guten Morgen, 

also ich würde das sehr gerne testen, wir werden wahrscheinlich noch nicht so schnell auf Digitalfunk umsteigen. 

Gruß Tobias

**Comment by grosj** [comment]
> Guten Morgen,
> 
> also ich würde das sehr gerne testen, wir werden wahrscheinlich noch nicht so schnell auf Digitalfunk umsteigen.
> 
> Gruß Tobias

Guten Morgen Tobias,

Ok, dann würde ich das mal angehen.
Ich sage dann bescheid, wenn eine testbare Version zur Verfügung steht.

Viele Grüße, Marco

**Comment by tobkoh** [comment]
Hallo Marco, 

vielen Dank.

**Comment by grosj** [comment]
Hallo Tobias,
bei der Umsetzung ist mir folgendes aufgefallen.
In den FMS-Daten gibt es ja keine RIC. D.h. für die Implementierung kann ich nicht auf eine RIC zurückgreifen um hierüber das Fahrzeug in Divera zu identifizieren. Es gibt allerdings den FMS_CODE. Habt ihr diesen in Divera evtl. konfiguriert?
Und wenn ja, in welchem Feld?

Über die Web-Oberfläche kann zu den Fahrzeugen eine/mehrere RICs, eine OPTA und/oder eine/mehrere ISSI konfiguriert werden.
Die konfigurierte RIC dient dazu, dass über die ALARM-API eine RIC mitgegeben werden kann und dann genau dieses Fahrzeug identifiziert und alarmiert.
OPTA und ISSI sind Identifikationen des Fahrzeugs/Endgerätes im Digitalfunk.
OTPA-ist allerdings nicht in der API mit drin genauso wenig wie eine FMS-Kennung.

Ich werde mal versuchen über die Facebook-Gruppe zu Divera etwas mehr zu der FMS-Api herauszufinden.

Viele Grüße, Marco

**Comment by tobkoh** [comment]
Hallo Marco, 
das Feld in der Weboberfläche Ric dient sowohl zur Alarmierung als auch zur Erkennung vom Fahrzeug Status per FMS. 

Wenn ich folgenden Link per Plugin httpRequest hinterlege ändert sich in Divera der Fahrzeug Status. 

https://www.divera247.com/api/fms?status_id=%STATUS%&vehicle_ric=%FMS%&accesskey= XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

Im Prinzip müsste das DIvera Plug in ja nur dies Link irgendwie zusammen basteln. 

Ich hab aktuell bei jedem Fahrzeug in dem Feld Arlamierungs-Ric folgendes hinterlegt: 
FMS-Kennung (8-stellige Zahlen Kombi) 
Eine Klartextfahrzeugbezeichnung (Funkrufnamen) für die Alarmierung über E-Mail die von der ILS
kommt. 
Eine 5-Tonfolge (Fahrzeugmelder) 

Divera erkennt das entsprechend anhand dem vorangehenden Link. 

Ich hoffe ich konnte hiermit etwas weiter helfen. 

Gruß Tobias

**Comment by grosj** [comment]
Hallo Tobias,
helfen konntest Du mir im Prinzip schon.
Allerdings ist dies dann nicht richtig konfiguriert. Eine RIC ist nur 7-stellig. Und wenn Du dort eine 8-stellige Zahlenkombination hinterlegst, dann ist es wohl eher die FMS-Kennung.
Und wie Du schreibst, handelt es sich dabei um die Alarmierungs-RIC, d.h. wenn über /api/alarm auf dieser RIC ein Alarm reinkommt, dann wird dieses Fahrzeug alarmiert.
Und das Plugin sollte ja für alle identisch funktionieren und dafür braucht es meines Erachtens in Divera eine Konfigurations-Möglichkeit zur Hinterlegung der FMS-Kennung in einem separaten Feld und über die API einen Parameter, der das Fahrzeug dann anhand der FMS-Kennung identifiziert.

Natürlich geht es auch so, wie Du es beschrieben hast, wäre aber für andere Einheiten nicht eindeutig nachvollziehbar. Und vielleicht auch nicht möglich, wenn andere das Feld Alarmierungs-RIC mit der "wirklichen" RIC des Fahrzeugmelders belegt haben.

Ich habe mal bei Divera angefragt. Mal sehen, was als Antwort zurück kommt.

Viele Grüße, Marco

**Comment by tobkoh** [comment]
Hallo Marco, 

ich glaub wir missverstehen uns da etwas. 
Wie schon erwähnt in der Alarmierung-Ric des Fahrzeuges in Divera können mehrere Eigenschaften hinterlegt werden. 
Ich separieren all meine 3 Funktionen mit einem komma und ohne Leerzeichen will heißen wenn ich ein Fahrzeug habe das z.b. 1/34 als Funkrufnamen hat steht folgendes in dem Feld Alarmierung-Ri:

FMS Kennung,FW 1/34,ZVEI 
"66661134, FW 1/34,A12555" (ZVEI hat ein "A" vorne dran weil Divera braucht min. 6 Zeichen) 

Dies funktioniert auch alles mit httpRequest und E-Mail 

FMS: 
https://www.divera247.com/api/fms?status_id=%STATUS%&vehicle_ric=%FMS%&accesskey= XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

ZVEI: 
https://www.divera247.com/api/alarm?accesskey=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&type=%DESCR%&text=%DESCR%&ric=A%ZVEI%

Ich meine nur wenn es ein Divera Plugin gibt muss man ja nicht den httpRequest nutzen. 

Klar wir sind jetzt mit unserem Analog Funk sowie Alarmierung ziemlich hinten dran aber vielleicht bekommst du es ja trotzdem hin, diese Funktion mit zu integrieren. 

Gruß Tobias

**Comment by grosj** [comment]
Hallo Tobias,
ich habe schon verstanden, was Du meinst und wie Du es konfiguriert hast. Ich habe auch die Rückmeldung vom Divera-Team gekommen, dass in der Alarmierungs-RIC die FMS-Kennung hinterlegt werden kann/soll.
Aus meiner Sicht fachlich nicht korrekt, weil es heißt ja "Alarmierungs"-RIC. Aber ok.

Ich werde es entsprechend implementieren und Dir bescheid geben, wenn es etwas zu test gibt.

Viele Grüße und danke für die konstruktive Zusammenarbeit.
Marco

**Comment by grosj** [comment]
Hallo Tobias,

kannst Du mal einen ersten Wurf testen?
Allerdings müsstest Du dies auf meinen Fork tun.
https://github.com/grosj/BOSWatch

Dieser basiert auf dem aktuellen Development-Branch.
Bevor ich dies jedesmal dorthin wieder zurück spiele, wäre mir ein bischen Testerei ganz lieb.

Viele Grüße,
Marco

**Comment by tobkoh** [comment]
Hallo Marco, 

ich hab das jetzt mal getestet und es funktioniert wunderbar. 
Der FMS Status kommt in Divera an. 

Jedoch habe ich was anderes festgestellt bei dem eigentlichen Divera Plugin erhalte ich einen Fehler bei der Auswertung der ZVEI. 

Hier mal das Log: 

03.04.2020 02:57:26 - decoder         [DEBUG   ] received ZVEI
03.04.2020 02:57:26 - zvei            [DEBUG   ] remove E: 15XXX -> 15XXX
03.04.2020 02:57:26 - doubleFilter    [DEBUG   ] checkID: 15XXX ()
03.04.2020 02:57:26 - zvei            [INFO    ] 5-Ton: 15XXX
03.04.2020 02:57:26 - descriptionList [DEBUG   ] look up description lists
03.04.2020 02:57:26 - descriptionList [DEBUG   ]  - result for 15XXX: Wachabteilung
03.04.2020 02:57:26 - alarmHandler    [DEBUG   ] [  ALARM  ]
03.04.2020 02:57:26 - regexFilter     [DEBUG   ] search Filter for ZVEI to DiveraFMS at 000000 Hz
03.04.2020 02:57:26 - regexFilter     [DEBUG   ] no Filter found
03.04.2020 02:57:26 - regexFilter     [DEBUG   ] search Filter for ZVEI to Divera at 0000000 Hz
03.04.2020 02:57:26 - regexFilter     [DEBUG   ] found Filter: diverzvei = 15[0-9]{3}
03.04.2020 02:57:26 - regexFilter     [DEBUG   ] Filter passed: diverzvei
03.04.2020 02:57:26 - alarmHandler    [DEBUG   ] call Plugin: Divera
03.04.2020 02:57:26 - configHandler   [DEBUG   ] read [Divera] from config file
03.04.2020 02:57:26 - configHandler   [DEBUG   ]  - accesskey = XXXXXXXXXXXXXXXXXX
03.04.2020 02:57:26 - configHandler   [DEBUG   ]  - suba = true
03.04.2020 02:57:26 - configHandler   [DEBUG   ]  - subb = false
03.04.2020 02:57:26 - configHandler   [DEBUG   ]  - subc = 
03.04.2020 02:57:26 - configHandler   [DEBUG   ]  - subd = 
03.04.2020 02:57:26 - configHandler   [DEBUG   ]  - poc_title = %DESCR%: %MSG%
03.04.2020 02:57:26 - configHandler   [DEBUG   ]  - poc_text = %DATE% %TIME% - %DESCR%: %MSG%
03.04.2020 02:57:26 - configHandler   [DEBUG   ]  - zvei_prio = true
03.04.2020 02:57:26 - configHandler   [DEBUG   ]  - zvei_title = Alarm: A%ZVEI%
03.04.2020 02:57:26 - configHandler   [DEBUG   ]  - zvei_text = %DATE% %TIME%: %ZVEI% %DESCR%
03.04.2020 02:57:26 - configHandler   [DEBUG   ]  - fms_prio = true
03.04.2020 02:57:26 - configHandler   [DEBUG   ]  - fms_title = FMS: %FMS%
03.04.2020 02:57:26 - configHandler   [DEBUG   ]  - fms_text = %DATE% %TIME%: %FMS%%BR%Status: %STATUS% - Direction: %DIRT% - TSI: %TSI% %LPAR%%DESCR%%RPAR%
03.04.2020 02:57:26 - Divera          [ERROR   ] unknown error
03.04.2020 02:57:26 - Divera          [DEBUG   ] unknown error
Traceback (most recent call last):
  File "/opt/boswatch/plugins/Divera/Divera.py", line 71, in run
    priority = globalVars.config.get("Divera","zvei_std_prio")
  File "/usr/lib/python2.7/ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
NoOptionError: No option 'zvei_std_prio' in section: 'Divera'
03.04.2020 02:57:26 - alarmHandler    [DEBUG   ] return from: Divera
03.04.2020 02:57:26 - alarmHandler    [DEBUG   ] [END ALARM]


Gruß Tobias

**Comment by grosj** [comment]
Ohh, da scheint sich ein Fehler in dem DIvera-Plugin dann eingeschlichen zu haben.
Werde ich mal beheben.
Damit das bei Dir läuft kannst Du selber in dem Divera-Plugin unter plugins/Divera/Divera.py in der Zeile 71 einfach das std und ein Unterstrich entfernen.
Die Zeile muss dann wie folgt lauten:
priority = globalVars.config.get("Divera", "zvei_prio")

Danach muss dann BosWatch einmal neu gestartet werden.

Viele Grüße, Marco

**Comment by Schrolli91** [comment]
@grosj wenn das ganze soweit fertig ist, würdest du dann einen Pull-Request gegen den develep stellen?

**Comment by grosj** [comment]
@Schrolli91 Jepp, werde ich machen. Korrigieren dann auch noch den Konfig-Aufruf in dem ursprünglichen Divera-Plugin.

**Comment by lgremme** [comment]
Könntet ihr den PR einmal testen? Ich habe kein ZVEI/FMS zur Verfügung.

Viele Grüße
Lars

**Comment by Schrolli91** [comment]
Ist mit #451 jetzt in den dev eingeflossen - ich close hier mal - bei Problemen bitte erneut in Issue aufmachen

**Comment by grosj** [comment]
Hallo zusammen,
ist schon ein Weilchen her und ich sehe gerade, dass das Divera-Plugin bereits erweitert wurde.
Herzlichen Dank für die Arbeit.
Irgendwie habe ich es wohl verpasst einen PR für meine Änderungen/Erweiterungen zu stellen. War damals im März/April dann ein wenig drubbelig bei mir.
Bleibt alle gesund.
Viele Grüße, Marco
