### ISSUE TITLE
Fehler im IO Plugin ??

### ISSUE THREAD

**Issue by Pasido** [Schrolli91/BOSWatch#458]
Hallo zusammen, 
bekomme folgende  Meldung beim verwenden des IO Plugins.

**-SW Version:	2.5.1
 Build Date:	28.04.2020
 Python Vers:	2.7.16 (default, Oct 10 2019, 22:02:15)** 

-cannot load plugin: gpiocontrol
-pluginLoader    [ERROR   ] error loading plugin: gpiocontr  

- Traceback (most recent call last):
  File "/opt/boswatch/includes/pluginLoader.py", line 106, in loadPlugin
    return imp.load_module(plugin["name"], *plugin["info"])
  File "/opt/boswatch/plugins/gpiocontrol/gpiocontrol.py", line 88
    th = threading.Thread(target = trigger)
     ^
IndentationError: expected an indented block
16.07.2020 18:52:42 - pluginLoader    [ERROR   ] error loading plugin: gpiocontrol
16.07.2020 18:52:42 - pluginLoader    [DEBUG   ] error loading plugin: gpiocontrol
Traceback (most recent call last):
  File "/opt/boswatch/includes/pluginLoader.py", line 32, in loadPlugins
    plugin = loadPlugin(i)
  File "/opt/boswatch/includes/pluginLoader.py", line 106, in loadPlugin
    return imp.load_module(plugin["name"], *plugin["info"])
  File "/opt/boswatch/plugins/gpiocontrol/gpiocontrol.py", line 88
    th = threading.Thread(target = trigger)
     ^
IndentationError: expected an indented block

kann mir hier jemand helfen ?

gruß Pasido

**Comment by Pasido** [comment]
kann hier keiner helfen ??

**Comment by flothi** [comment]
Ich hab den mutmaßlichen Fehler gefixt, allerdings hab ich aktuell keine Testumgebung; siehe #465

**Comment by Schrolli91** [comment]
PR ongoing - closed
