### ISSUE TITLE
Nachrichten kryptisch

### ISSUE THREAD

**Issue by Laemmch3n** [Schrolli91/BOSWatch#463]
Guten Abend, ich bin auf diesem Gebiet völliger Anfänger. Ich habe die Software installiert mit einem Stick, welcher in der Liste genannt wird. 
Nach dem ich die richtige Frequenz eingestellt habe, empfange ich auch etwas. Die Rics werden angezeigt aber die Nachrichten sehen total komisch aus. 

Z. B. in der Message steht so etwas: 
BY<SOH>51?ap<ESC>A<DC1>Z<SUB>,eC<DC2>j<LF>XOtO:/<VT>-<NAK>;\l^5H*<CAN><RS>E3;#J QJ<DC4>p<ACK>1hY1=X*T5zq<US>\Ce(<RS><GS>d*o[,YJ<STX><SO>=V'*Fut<SI><ESC>`1<SYN>pD`"<HT>Tg%F%ts<DEL>~<DC1>'E<LF>n-<HT>:dqvX<CR>]<ETB>,H{pU/<HT>@

Ich denke das soll so nicht sein. Jemand eine Idee was das sein kann?

Vielen Dank für Eure Hilfe.

**Comment by JoeyTimeChris** [comment]
Hi kann es sein das bei dir von der Leitstelle verschlüsselte Pocsag Meldungen Gesendet werden? Dies ist bei RD, FirstResponder Rics usw. der Fall. Die Verschlüsselung die dort häufig verwendet wird heist IDEA bei dem die DMEs auch diese Art der Verschlüsselung können müssen. Hoffe ich konnte dir weiterhelfen.
Gruß Chris

**Comment by Schrolli91** [comment]
Ja das ganze sieht sehr nach IDEA Verschlüsselung aus.
Zum Entschlüsseln gibt es auch keinen einfachen Weg.

**Comment by Laemmch3n** [comment]
Angeblich, wenn man einen Scanner und BosMon hat, dann soll es wohl im Klartext immer stehen.

**Comment by Schrolli91** [comment]
Meinst du einen DME der an den PC angebunden wurde? Dann gehe ich davon aus, dass der DME bereits entschlüsselt.

**Comment by Laemmch3n** [comment]
Nein einen scanner per Soundkarte an den PC, so war die Aussage
Werde mir einen Scanner besorgen und es dann mit BosMon testen.
Wenn es mit BosMon funktioniert, muss es doch auch mit BOSWatch tun, oder nicht ?

**Comment by Schrolli91** [comment]
Wenn wirklich IDEA verschüsselt, dann halte ich das für unwahrscheinlich.
Für den Normalsterblichen, der nicht noch zufällig Zugang zu den Keys hat ist IDEA eher unmöglich.

**Comment by Laemmch3n** [comment]
So Info von dem Kammeraden, welcher das mit BosMon und einem Scanner in Betrieb hat.
Der Rettungsdienst ist verschlüsselt, der Rest ist offen. Kann es sein, dass ich meine Stick noch einmal abgleichen sollte?

**Comment by Nortfid** [comment]
Also die Verschlüsselung umgehst du nicht einfach mit einem Scanner und BosMon. Du brauchst dafür Schlüssel oder einen Melder, der entschlüsselt und die Nachrichten seriell weitergibt.
Ansonsten, wenn er Nachrichten empfängt, wird noch nicht verschlüsselt übertragen.

**Comment by Schrolli91** [comment]
> Der Rettungsdienst ist verschlüsselt, der Rest ist offen. Kann es sein, dass ich meine Stick noch einmal abgleichen sollte?

Kannst du schon machen - aber sobald die Daten in BOSWatch reinkommen, sollte der Stick gepasst haben - sonst wäre schon Multimon am Dekodieren gescheitert. 

Mal warten ob da noch mla was unverschlüsseltes kommt

**Comment by Laemmch3n** [comment]
> 
> 
> Also die Verschlüsselung umgehst du nicht einfach mit einem Scanner und BosMon. Du brauchst dafür Schlüssel oder einen Melder, der entschlüsselt und die Nachrichten seriell weitergibt.
> Ansonsten, wenn er Nachrichten empfängt, wird noch nicht verschlüsselt übertragen.

Wie gesagt, ein Kammarad meinte, dass nur der Rettungsdienst verschlüsselt ist. Und das er einen Scanner hat, und diesen über BosMon betreibt. Ich finde es ja auch sehr verwunderlich. Was mir spanisch vor kommt, wir hatten heute zwei Alarmierungen und den Ric für die Alamierung habe ich nicht gesehen. Schon etwas komisch, oder ?

**Comment by Nortfid** [comment]
Vielleicht bist du auf der falschen Frequenz? Also wenn die Nachrichten tatsächlich für dich bestimmt wären, wüsstest du ob und wie es funktioniert.

**Comment by Laemmch3n** [comment]
> Vielleicht bist du auf der falschen Frequenz? Also wenn die Nachrichten tatsächlich für dich bestimmt wären, wüsstest du ob und wie es funktioniert.

Klar, ich mache das aus langerweil. Die Frequenz ist die, welche ich von den Kollegen habe die unsere Melder Programmieren. Ich bekomme auch die FMS von den Fahrzeugen. Aber die RICs kommen nicht sauber mit den Text rein. Auch habe ich nicht die RICs gesehen von unsern zwei alarmierungen.Wie gesagt ich hole mir jetzt den Scanner vom Kollegen und schaue mal was dann BosMon aufzeichnet.

**Comment by Laemmch3n** [comment]
So ich habe jetzt einen Scanner mit Bosmon und meinen PI komplett neu aufgesetzt. Software installiert. Stick nach Anleitung abgeglichen und die Antenne nach außen gebracht.
Und oh Wunder, ich bekomme die **unverschlüssleten** Nachrichten nun sauber rein. Stellenweise sogar mehr wie über den Scanner.

**Comment by Schrolli91** [comment]
> Und oh Wunder, ich bekomme die **unverschlüssleten** Nachrichten nun sauber rein. Stellenweise sogar mehr wie über den Scanner.

Mit BOSWatch oder über BOSMON?

**Comment by Laemmch3n** [comment]
Erst habe ich den Scanner direkt an BosMon angeschlossen und da kamen die Meldungen sauber rein.
Dann habe ich BOSWatch neu installiert und den Stick abgeglichen. Dort kamen dann auch die Meldungen, sogar mehr wie beim Scanner (FMS). Plugin für Bosmon aktiviert und Kanal im BosMon hinzugefügt. So läuft es zur Zeit um direkt vergleichen zu können.

**Comment by Schrolli91** [comment]
Also scheint es ein im Nachhinein nicht mehr genau nachvollziehbares Konfigurationsproblem gewesen zu sein?
Wenn damit alle Probleme erledigt sind bitte das Issue schließen ...
