### ISSUE TITLE
Fehler im IO Plugin  die zweite  

### ISSUE THREAD

**Issue by Pasido** [Schrolli91/BOSWatch#466]
Hallo,
leider bekomme ich noch immer Fehler wenn ich das GPIO Plugin verwende.

Allerdings komme ich mit dem Update auch nicht richtig klar.
Könnt ihr mir bitte noch einmal helfen.

Danke

- 9.07.2020 17:19:36 - pluginLoader    [DEBUG   ] load plugin: eMail
29.07.2020 17:19:36 - pluginLoader    [DEBUG   ] call eMail.onLoad()
29.07.2020 17:19:36 - pluginLoader    [DEBUG   ] load plugin: gpiocontrol
29.07.2020 17:19:36 - pluginLoader    [ERROR   ] cannot load plugin: gpiocontrol
29.07.2020 17:19:36 - pluginLoader    [DEBUG   ] cannot load plugin: gpiocontrol
Traceback (most recent call last):
  File "/opt/boswatch/includes/pluginLoader.py", line 106, in loadPlugin
    return imp.load_module(plugin["name"], *plugin["info"])
  File "/opt/boswatch/plugins/gpiocontrol/gpiocontrol.py", line 87
    if globalVars.config.get("gpiocontrol", "activerics") == "":
                                                               ^
IndentationError: unindent does not match any outer indentation level
29.07.2020 17:19:36 - pluginLoader    [ERROR   ] error loading plugin: gpiocontrol
29.07.2020 17:19:36 - pluginLoader    [DEBUG   ] error loading plugin: gpiocontrol
Traceback (most recent call last):
  File "/opt/boswatch/includes/pluginLoader.py", line 32, in loadPlugins
    plugin = loadPlugin(i)
  File "/opt/boswatch/includes/pluginLoader.py", line 106, in loadPlugin
    return imp.load_module(plugin["name"], *plugin["info"])
  File "/opt/boswatch/plugins/gpiocontrol/gpiocontrol.py", line 87
    if globalVars.config.get("gpiocontrol", "activerics") == "":
                                                               ^
IndentationError: unindent does not match any outer indentation level
29.07.2020 17:19:36 - boswatch        [DEBUG   ] starting rtl_fm
29.07.2020 17:19:39 - boswatch        [DEBUG   ] starting multimon-ng

**Comment by Schrolli91** [comment]
Sollte jetzt im PR #465  behoben sein
