### ISSUE TITLE
BOSWatch installieren

### ISSUE THREAD

**Issue by hias911** [Schrolli91/BOSWatch#468]
Hallo,

kann mir jemand über VNC Viewer den BOSWatch einrichten? Ich komme einfach nicht weiter.

**Comment by flothi** [comment]
Woran hängt es denn?

**Comment by hias911** [comment]
Überall :D hätten Sie mal kurz Zeit?

**Comment by flothi** [comment]
Schreib mir mal ne mail an boswatch@thillmann.de

**Comment by hias911** [comment]
@flothi erledigt
