### ISSUE TITLE
Whatsapp - **genutzte Plugins**

### ISSUE THREAD

**Issue by hias911** [Schrolli91/BOSWatch#470]
Hallo beim anmelden bei dem Whatsapp Plugin kommt diester Fehler...

Bitte um Hilfe.

pi@raspberrypi:~ $ yowsup-cli registration -c config.yowsup --requestcode sms
W 2020-08-24 21:14:10,696 yowsup.config.v1.config - Setting a password in Config is deprecated and not used anymore. client_static_keypair is used instead
E 2020-08-24 21:14:10,697 yowsup.config.manager - Could not find a config for profile=****, paths checked: /home/pi/.config/yowsup/49*******/config.json:/home/pi/.config/yowsup/49******/config.yo
yowsup-cli  v3.2.0
yowsup      v3.2.3

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

W 2020-08-24 21:14:10,832 yowsup.common.http.warequest - Passing Config to WARequest is deprecated, pass a YowProfile instead
W 2020-08-24 21:14:10,836 yowsup.common.http.warequest - Passing Config to WARequest is deprecated, pass a YowProfile instead
I 2020-08-24 21:14:11,380 yowsup.common.http.warequest - {"login":"********","status":"fail","reason":"old_version"}

I 2020-08-24 21:14:11,986 yowsup.common.http.warequest - {"login":"************,"status":"fail","reason":"old_version"}

status: fail
reason: old_version
login: 49********

**Comment by Maagi93** [comment]
Hallo zusammen,

habe das selbe Problem und konnte leider nirgendwo eine Lösung finden.

$ sudo yowsup-cli registration -c config.yowsup --requestcode sms
W 2020-10-09 01:26:24,053 yowsup.config.v1.config - Setting a password in Config is deprecated and not used anymore. client_static_keypair is used instead
E 2020-10-09 01:26:24,054 yowsup.config.manager - Could not find a config for profile=*****, paths checked: /root/.config/yowsup/*****/config.json:/root/.config/yowsup/*****/config.yo
yowsup-cli  v3.2.0
yowsup      v3.2.3


Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


W 2020-10-09 01:26:24,248 yowsup.common.http.warequest - Passing Config to WARequest is deprecated, pass a YowProfile instead
W 2020-10-09 01:26:24,255 yowsup.common.http.warequest - Passing Config to WARequest is deprecated, pass a YowProfile instead
I 2020-10-09 01:26:24,838 yowsup.common.http.warequest - {"login":"******","status":"fail","reason":"old_version"}

I 2020-10-09 01:26:25,383 yowsup.common.http.warequest - {"login":"******","status":"fail","reason":"old_version"}

status: fail
reason: old_version
login: **********

Vielen Dank vorab!
