### ISSUE TITLE
Ubuntu Desktop Umgebung

### ISSUE THREAD

**Issue by S-Snowball** [Schrolli91/BOSWatch#471]
Hi,

ich bin gerade über googel hierüber gestolpert und finde die Idee ja klasse.

Ich habe für ein anderes Projekt noch einen Raspberry 4 laufen, der nichteinmal ansatzweise ausgelastet ist, daher dachte ich, ich könnte BOSMon noch darauf installieren. Aktuell habe ich auf dem Raspberry ein Ubuntu Server 20.04 laufen. Für den Monitor benötige ich ja allerdings eine Desktop Umgebung, welche Ubuntu Desktop würdet Ihr empfhelen zu nutzen? Und wie rufe ich den Monitor auf? Über die localhost IP im Webbrowser?

**Comment by Schmattek** [comment]
BOSMon wirst du für Linux nicht finden und wenn du im BOSMon Forum nachliest läuft es auch mit Windows-Emulatoren auf Linux nicht zufriedenstellend.
Du kannst mit BOSWatch, was auf Linux läuft, lediglich ein BOSMon, welches auf ner Windows Kiste läuft, "füttern".

**Comment by S-Snowball** [comment]
Ok, ich habe gerade auch gesehen, dass BOSWatch so eine art Monitor anbietet.

Wie kann ich den auf mein Display bekommen? 

Oder auch grundlegende Frage, wie kann ich nach dem testen einen debug starten? Also eine reinkommende Alarmierung simulieren?

Apache2 und PHP7.4 sind natürlich installiert und laufen

**Comment by flothi** [comment]
Du kannst die exampleAddons mal durchprobieren, allerdings sind da ggf Anpassungen notwendig. Wenn du eine konkrete Frage hast, stellst du sie am besten hier - für die reine Anzeige eines Alarms ist `alarmMonitorWeb` zB geeignet
