### ISSUE TITLE
Boswatch Filter + Pushover/Telegramm

### ISSUE THREAD

**Issue by McCrazy** [Schrolli91/BOSWatch#478]
Hallo zusammen,

ich bin neu bei der Nutzung von BOSwatch und muss erstmal meinen Hut nehmen vor der Leistung bei der Umsetzung des Tools.
Mittlerweile habe ich de Dekodierung eines Pocsag-Kanals auf einem Raspberry Pie hinbekommen und konnte auch Nachrichten an einen Rechner mit BOSMON schicken und eine Übertragung an ein Handy über Pushover hat auch geklappt. 

Nun würde gerne nur ein paar RICs aufs Handy übertragen und alle anderen dekodierten RICs in einer MySQL-Datenbank speichern. Leider habe ich keine Ahnung ob das mit den Filtereinstellungen möglich ist. Bisher bin ich noch auf keine Lösung gekommen. 

Entweder ich filter nur die wenigen RICs raus und diese kommen dann auch nur auf dem Handy an oder aber ich lasse alle durch und das Handy vibriert sich zu Tote.

Hat einer eine Idee wie ich das hinbekommen könnte?

Viele Grüße
Simon

**Comment by Schrolli91** [comment]
Bei solch generellen Fragen am besten hier melden: https://bwcc.boswatch.de/
