### ISSUE TITLE
Lookup Description Funktion für Webinterface

### ISSUE THREAD

**Issue by CJHarms** [Schrolli91/BOSWatch#48]
Feature Request/Verbesserung: Die Description Lookup Funktion ist momentan leider noch nicht im BOSWatch "WebInterface" umgesetzt.

Wäre klasse wenn diese Funktion dort ebenfalls implementiert werden könnte.

**Comment by K3vP0** [comment]
Hab ich schon fertig, kommt heute Nacht hoch.

**Comment by CJHarms** [comment]
Super, danke schon mal!

**Comment by K3vP0** [comment]
Sind in meinem Fork kevinkleist/BOSWatch zu finden.

Die Readme einmal beachten, und eine Tabelle für Nutzer muss auch noch erstellt werden, andernfalls musst du den Teil für den Login einfach auskommentieren in den Daten

**Comment by Schrolli91** [comment]
Damit wäre das ja geklärt :white_check_mark:
