### ISSUE TITLE
Mithilfe

### ISSUE THREAD

**Issue by mahlers2** [Schrolli91/BOSWatch#480]
Moin,

ich habe gesehen, dass ihr noch Unterstützung sucht. Vielleicht kann ich euch da helfen. 
Habt ihr ne Kontaktadresse?

Grüße

**Comment by Schrolli91** [comment]
Bei was genau möchtest/kannst du denn Helfen?

**Comment by mahlers2** [comment]
I.D.E.A
also ich weiß nicht ob ich da richtig helfen kann, aber wir können auf jeden Fall mal drüber sprechen und vielleicht ergibt sich ja eine lösung.

**Comment by mahlers2** [comment]
lass uns am besten einfach mal quatschen (TS/Discord?) oder halt schreiben. Möchte hier nicht zu viel erzählen...

**Comment by Schrolli91** [comment]
Am besten einfach mal im BOSWatch Communication Center anmelden
https://bwcc.boswatch.de/
