### ISSUE TITLE
Registrierung von yowsup-Nummer klappt nicht

### ISSUE THREAD

**Issue by Maagi93** [Schrolli91/BOSWatch#485]
Hallo zusammen,

habe das selbe Problemm wie in #470 und konnte leider nirgendwo eine Lösung finden:

$ sudo yowsup-cli registration -c config.yowsup --requestcode sms
W 2020-10-09 01:26:24,053 yowsup.config.v1.config - Setting a password in Config is deprecated and not used anymore. client_static_keypair is used instead
E 2020-10-09 01:26:24,054 yowsup.config.manager - Could not find a config for profile=, paths checked: /root/.config/yowsup//config.json:/root/.config/yowsup/*****/config.yo
yowsup-cli v3.2.0
yowsup v3.2.3

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

W 2020-10-09 01:26:24,248 yowsup.common.http.warequest - Passing Config to WARequest is deprecated, pass a YowProfile instead
W 2020-10-09 01:26:24,255 yowsup.common.http.warequest - Passing Config to WARequest is deprecated, pass a YowProfile instead
I 2020-10-09 01:26:24,838 yowsup.common.http.warequest - {"login":"******","status":"fail","reason":"old_version"}

I 2020-10-09 01:26:25,383 yowsup.common.http.warequest - {"login":"******","status":"fail","reason":"old_version"}

status: fail
reason: old_version
login: **********

Kann mir hier bitte jemand weiterhelfen?

Vielen Dank vorab!

**Comment by Schrolli91** [comment]
Schau mal auf die offizielle yowsup Seite ... https://github.com/tgalal/yowsup

> It seems that recently yowsup gets detected during registration resulting in an instant ban for your number right after registering with the code you receive by sms/voice. I'd strongly recommend to not attempt registration through yowsup until I look further into this. Follow the status of this here.

Außerdem mal in deinen Log schauen:
> W 2020-10-09 01:26:24,248 yowsup.common.http.warequest - Passing Config to WARequest is deprecated, pass a YowProfile instead

Im Prinzip sind das aber keine BOSWatch spezifischen Probleme - am besten mal die Yowsup Doku lesen.. evtl hat noch jemand anders eine Idee, habs selbst leider nie genutzt
