### ISSUE TITLE
Folgetelegramme mit Boswatch auswerten

### ISSUE THREAD

**Issue by Nortfid** [Schrolli91/BOSWatch#487]
Ist es möglich eine Folgetelegramm-Auswertung in Boswatch zu Integrieren?

**Comment by Schrolli91** [comment]
Was ist ein Folgetelegram?

**Comment by Nortfid** [comment]
Wir erhalten Einsatzstichwort und -Ort via FMS. Laut TR-BOS gibt es die Möglichkeit der Kurztextübermittlung (FMS-Folgetelegramm)

FMS32 schreibt dazu:
Nach der TR-BOS (Technische Richtlinie für BOS) müssen bei einer Textübertragung als
FMS-Folgetelegramm von der Leitstelle an das Fahrzeug einige Punkte beachtet werden.
Als Status wird die 10 gesendet. Die TKI muss den Wert 3 und die Baustufe den Wert 0
enthalten. Seit einiger Zeit gibt es jedoch FMS-Geber, die bei einer Textübertragung diese
Vorgaben nicht mehr beachten. Da FMS32-PRO TR-BOS-konform ist, wurden
Textübertragungen von derartigen Gebern ignoriert und nur der Status 10 ausgegeben


Hier ziemlich viel dazu:
https://www.dhpol.de/microsite/pti/medien/downloads/richtlinien/richtlinien/tr-bos-digitale-funkalarm/FMS_06_1999_002.pdf

**Comment by Schrolli91** [comment]
Mir ist nicht bekannt, dass multimon Text Nachrichten per FMS decodieren kann.
Falls du dazu was findest, lass ich mich wissen.
