### ISSUE TITLE
alarmMonitorWeb Benutzername und/oder Passwort waren falsch

### ISSUE THREAD

**Issue by Maagi93** [Schrolli91/BOSWatch#489]
Hallo zusammen,

ein Problem mit alarmMonitorWeb. Welcher Benutzername/Passwort wird hier benötigt? 

Wo kann ich die Benutzerdaten definieren? 

Die Logindaten meines PIs sowie von mariadb funktionieren nicht?

Vielen Dank und viele Grüße!

**Comment by lgremme** [comment]
Hast du die [neue Tabelle](https://github.com/Schrolli91/BOSWatch/blob/master/exampleAddOns/alarmMonitorWeb/MySQL-Import/login.sql) in MySQL importiert?

Dort wird das Passwort als MD5-Summe hinterlegt.

**Comment by Maagi93** [comment]
Danke für die schnelle Antwort!

Hatte die Tabelle nicht importiert, das habe ich nun nachgeholt.

Wie kann ich nun die Zugangsdaten festlegen? Bzw. gibt es Standardzugangsdaten?

**Comment by Maagi93** [comment]
danke für die Starthilfe! Habs rausgefunden. User und Passwort sind identisch und stehen in der genannten Tabelle.
