### ISSUE TITLE
Der optimale Gain-Wert

### ISSUE THREAD

**Issue by webstr4711** [Schrolli91/BOSWatch#492]
Hallo,
ich habe eine Frage zum GAIN-Wert. Wie ermittelt man den?
Zuviel ist ja auch nicht gut...

Viele Grüße!

**Comment by flothi** [comment]
Try and error - ich hab es so lange probiert, bis es gut war und bin in der Tat bei 100 gelandet

**Comment by webstr4711** [comment]
woran merkst du dass es "gut" ist? man hat ja keine Anzeige etc...

**Comment by flothi** [comment]
In der Tat bei POCSAG an der Qualität der empfangenen Nachrichten; es wird ja dadurch einfacher, dass du periodische Signale kriegst.

**Comment by Schrolli91** [comment]
Antwort auf die Frage: `Try and error`
