### ISSUE TITLE
abfliegen vom USB Stick bemerken

### ISSUE THREAD

**Issue by webstr4711** [Schrolli91/BOSWatch#494]
hallo,

ich habe nun schon öfters gehabt, dass der USB Stick rausgeflogen ist - wenn man den raspi anfasst, passiert das offenbar schnell. das blöde ist nur, dass BOSwatch das nicht bemerkt. Kann man da einen check einbauen, der dann (gerne über einen seperaten kanal, z.b. telegram) informiert, so dass man das nicht erst nach stunden/tagen feststell? :)

vielen dank!

**Comment by lgremme** [comment]
Über das Tool monit könntest du die Logdatei von BOSwatch überprüfen lassen:

/etc/monit/conf.d/boswatch.monitrc:
```
check file boswatch-log-nightly with path /opt/boswatch/log/boswatch.log
        if timestamp is older than 2 hour for 5 cycles then alert not every "* 6-22 * * *"
        mode passive

check file boswatch-log with path /opt/boswatch/log/boswatch.log
        if timestamp is older than 50 minutes for 5 cycles then alert every "* 6-22 * * *"
        mode passive
```

Ich habe Monit so konfiguriert, dass es mir ganz klassisch eine Mail schickt. Alternativ kannst du in monit auch telegram anbinden. Du müsstest einmal auf die Parameter für dich anpassen. Gleichzeitig kannst du weitere Dienste überprüfen lassen, wie MySQL, nginx/apach2, ...

**Comment by Schrolli91** [comment]
Unter Umständen ist das auch ein Netzteil Problem - oder hängt der Stick an einem selbst versorgten USB Hub?

**Comment by IT-Fuzzi** [comment]
Hi,

ich habe ein ähnliches bzw. das gleiche Problem bei mir merkt. Sobald man den Raspberry irgendwie berührt verliert der USB Stick scheinbar die Spannungsversorgung und keine Auswertung findet mehr statt. Der Boswatch Service läuft allerdings weiter.

Habe es nun ähnlich wie [lgremme](https://github.com/lgremme) gelöst, checke mit Monit alle 10 Minuten das Logfile auf Veränderungen. Falls der Timestamp älter ich starte ich Boswatch neu.

Danke für die Idee.
