### ISSUE TITLE
Senden an zwei Bosmon Instanzen

### ISSUE THREAD

**Issue by webstr4711** [Schrolli91/BOSWatch#495]
Hallo,
ist es möglich, aus Redundanzgründen herazs an zwei verschiedene Bosmon-Server zu schicken? 
Also Angabe zweier IPs, user,pass, channel

Schöne Adventszeit!

**Comment by thejockel** [comment]
Moin @webstr4711,
zur Zeit ist das nicht möglich. Für BOSWatch3 ist das mit geplant.

Du könntest das Plugin kopieren und unter einem anderen Namen nochmal nutzen.

Folgend Schritte sind dafür nötig:
- Den Ordner plugin/BosMon kopieren (z.b. zu plugins/NeuePlugin)
- In dem neuen Ordner das .py file umbenennen (gleicher Name wie der Ordner - NeuePlugin.py)
- In dem .py file folgendes ersetzen
```
"BosMon" durch "NeuePlugin"
```
Ich mache das nicht händisch, sondern mit diesen Befehlen:
```
mkdir /opt/boswatch/plugins/NeuePlugin/ && \
cp /opt/boswatch/plugins/BosMon/BosMon.py /opt/boswatch/plugins/NeuePlugin/NeuePlugin.py && \
sed -i 's/"BosMon"/"NeuePlugin"/g' /opt/boswatch/plugins/NeuePlugin/NeuePlugin.py

```


- In der Config.ini

```
...

[Plugins]
BosMon = 1
NeuePlugin = 1
...

[BosMon]
bosmon_server = 192.168.0.1
...
[NeuePlugin]
bosmon_server = 192.168.0.2
...
```
