### ISSUE TITLE
SUBRICS Filtern / bestimmte SubRICS an plugins weiterleiten

### ISSUE THREAD

**Issue by davidmskiba** [Schrolli91/BOSWatch#496]
- **BOSWatch Version + Branch**
2.5.1 - master
- **genutzte Plugins**
telegram

Ist es möglich nur bestimmte SubRICS an Telegram / Mail etc zu senden? RegEX hat leider kein Wildcard dafür oder? 
Telegrambots sind auch nicht das gelbe vom Ei und filtern auch nicht oder nicht zuverlässig.

Wenn man RICS filtern kann, sollte man auch SUBRICS filtern können, oder?

Vielen Dank für Hilfe

**Comment by davidmskiba** [comment]
Beziehungsweise: kann man im RegEX "alle durchlassen bis auf "..."" einstellen?

**Comment by Schrolli91** [comment]
Sollte eigentlich gehen - siehe https://github.com/Schrolli91/BOSWatch/tree/master/plugins#5-process-the-data-from-boswatch
Die Subric sollte sich hier also im Feld `function` verstecken (statt `ric` im regex vernweden).

**Comment by davidmskiba** [comment]
> Sollte eigentlich gehen - siehe https://github.com/Schrolli91/BOSWatch/tree/master/plugins#5-process-the-data-from-boswatch
> Die Subric sollte sich hier also im Feld `function` verstecken (statt `ric` im regex vernweden).

Perfekt. Die RegEX nimmt die Wildcards für POCSAG:

ric
function
functionChar
msg
bitrate
description
timestamp

und nicht die % Wildcards.

Vielen vielen Dank dafür!!

**Comment by Schrolli91** [comment]
scheint damit wohl erledigt
