### ISSUE TITLE
mehrere Kanäle überwachen

### ISSUE THREAD

**Issue by K3vP0** [Schrolli91/BOSWatch#50]
Nabend zusammen,

Ich würde gerne im 4m Band FMS und ZVEI Decodieren und im 2m Band POCSAG, auf Grund der Differenz der Frequenzen, werde ich wohl um 2 Sticks nicht drum herum kommen.

<b>1. Frage:</b> Hat jemand sowas schon realisiert? 
<b>2. Frage:</b> Macht es Sinn dann einfach 2 Instanzen von BOSWatch laufen zu lassen (wird auf dem Raspberry dann glaube ich knapp)oder sollte man dann drüber nachdenken den Aufruf von rtl_fm zu verdoppeln im Script?
<b>3. Anregung:</b> Wäre es eventuell sinnvoll einen Multimix so wie unten im Link zu realisieren, und eventuell einzufügen? Mit 2 Sticks hätte man dann relativ viele Kanäle abgedeckt?
Nach Adam Riese würde es ja bedeuten das man maximal wenn man alle Unter und Oberbänder abhören will auf Grund der Frequenzweite von 3,4 MHz 4x RTL-Sticks benötigt, heißt also auch das wäre endlich und müsste nicht dynamisch programmiert werden.
https://github.com/hpdvanwyk/fm-multimix
<b>4. Anregung:</b> Momentan verbraucht mein Raspberry relativ viel seiner geringen CPU-Kapazität, gäbe es die Möglichkeit die Schnittstelle zu RTL SDR etwas zu konkretisieren bzw. zu Verbessern. Es gäbe ja auch eventuell die Möglichkeit Anpassungen an der: https://github.com/steve-m/librtlsdr/blob/master/src/rtl_adsb.c zu nehmen und auf POCSAG bzw. FMS / ZVEI umzubasteln, oder?
(Nur ich glaube sehr Aufwendig, oder?)

**Comment by Schrolli91** [comment]
1. Nein
2. So war es gedacht - daher werden Frequenz usw direkt übergeben und stehen nicht in der config-File. Getestet hat das glaube ich noch niemand
3. Muss ich mir mal anschauen - vermute aber die CPU Last wird dadurch noch erheblich viel mehr.
4. Sprichtst du davon, die adsb_rtl.c mit den Decoder Teilen von multimon zu kombinieren, um einen eigenen komplett fertigen Empfänger/Decoder zu bauen? Könnte in der Tat sehr aufwändig werden. Obs dann Last spart ist das andere...

**Comment by Smith-fms** [comment]
Die Nutzung von 2x SDR Sticks unter 2 Instanzen ist bei übertaktetem Pi B hier gelaufen.Allerdings externe DB und nichts anderes mehr! 
Geht also. Daher auch damals im Ur-Script die Kanal bzw. Freq. Eingabe per Übergabe und nicht Config.
VGRene
Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: kevinkleist notifications@github.com 
Datum: 06.07.2015  02:37  (GMT+01:00) 
An: Schrolli91/BOSWatch BOSWatch@noreply.github.com 
Betreff: [BOSWatch] mehrere Kanäle überwachen (#50) 

Nabend zusammen,

Ich würde gerne im 4m Band FMS und ZVEI Decodieren und im 2m Band POCSAG, auf Grund der Differenz der Frequenzen, werde ich wohl um 2 Sticks nicht drum herum kommen.

<b>1. Frage:</b> Hat jemand sowas schon realisiert? 
<b>2. Frage:</b> Macht es Sinn dann einfach 2 Instanzen von BOSWatch laufen zu lassen (wird auf dem Raspberry dann glaube ich knapp)oder sollte man dann drüber nachdenken den Aufruf von rtl_fm zu verdoppeln im Script?
<b>3. Anregung:</b> Wäre es eventuell sinnvoll einen Multimix so wie unten im Link zu realisieren, und eventuell einzufügen? Mit 2 Sticks hätte man dann relativ viele Kanäle abgedeckt?
Nach Adam Riese würde es ja bedeuten das man maximal wenn man alle Unter und Oberbänder abhören will auf Grund der Frequenzweite von 3,4 MHz 4x RTL-Sticks benötigt, heißt also auch das wäre endlich und müsste nicht dynamisch programmiert werden.
https://github.com/hpdvanwyk/fm-multimix
<b>4. Anregung:</b> Momentan verbraucht mein Raspberry relativ viel seiner geringen CPU-Kapazität, gäbe es die Möglichkeit die Schnittstelle zu RTL SDR etwas zu konkretisieren bzw. zu Verbessern. Es gäbe ja auch eventuell die Möglichkeit Anpassungen an der: https://github.com/steve-m/librtlsdr/blob/master/src/rtl_adsb.c zu nehmen und auf POCSAG bzw. FMS / ZVEI umzubasteln, oder?
(Nur ich glaube sehr Aufwendig, oder?)

---

Reply to this email directly or view it on GitHub:
https://github.com/Schrolli91/BOSWatch/issues/50

**Comment by Schrolli91** [comment]
@Smith-fms genau aus diesen Grund übergeben wir die Frequenz und alles was relevant ist immer noch direkt - statt es ins Config auszulagern.

Lief mit BOSWatch, oder mit RasPOC ?

**Comment by JHCD** [comment]
Moin, 
mit dem Pi 2 ist der Betrieb mit 2 Sticks möglich.
Von einem Scannen über mehrere Frequenzen mit einem Stick halte ich nichts. Wenn bei uns viel los ist, verpasst man die Hälfte. 

Jou, deswegen auch die Plugins, um die Pi - Installation klein zu halten und die restliche Verarbeitung auszulagern.

Grüße, 
Jens

**Comment by Schrolli91** [comment]
Damit sind Frage **1.** und **2.** geklärt...

Zu **3.** - Sehe das ähnlich, Scannen über einen weiten Bereich halte ich für nicht sinnvoll, vorallem weil dabei höchst wahrscheinlich noch mehr CPU Zeit verloren geht.

Bei **4.** gab es bisher ja noch keine großartigen Rückmeldungen.
Ob sich der Aufwand lohnt? Ich wage es zu bezweifeln...

**Comment by K3vP0** [comment]
okay, ich denke wir verschieben dieses Feature auf eine Release mit ner 3 vorm Punkt. _lol_

#CLOSED
