### ISSUE TITLE
Fehler beim IO Plugin

### ISSUE THREAD

**Issue by PasidoPG** [Schrolli91/BOSWatch#500]
Bei Fragen und Problemen zu BOSWatch oder Plugins bitte unten gennante Informationen angeben:

- **BOSWatch Version + Branch**
 SW Version:	2.5.1
 Branch:		master
 Build Date:	28.04.2020
 Python Vers:	2.7.16 (default, Oct 10 2019, 22:02:15) 

- **genutzte Plugins**
- io Plugin

- **Fehlerbeschreibung**
- siehe Logfile, keine Funktion von GPIO

- **Logfile (Auszug)**

- **ggf. Config File (Auszug)**
 - pluginLoader    [DEBUG   ] load plugin: gpiocontrol
 - pluginLoader    [ERROR   ] cannot load plugin: gpiocontrol
 - pluginLoader    [DEBUG   ] cannot load plugin: gpiocontrol
Traceback (most recent call last):
  File "/opt/boswatch/includes/pluginLoader.py", line 106, in loadPlugin
    return imp.load_module(plugin["name"], *plugin["info"])
  File "/opt/boswatch/plugins/gpiocontrol/gpiocontrol.py", line 95
    th = threading.Thread(target = trigger)
     ^
IndentationError: expected an indented block
- pluginLoader    [ERROR   ] error loading plugin: gpiocontrol
- pluginLoader    [DEBUG   ] error loading plugin: gpiocontrol
Traceback (most recent call last):
  File "/opt/boswatch/includes/pluginLoader.py", line 32, in loadPlugins
    plugin = loadPlugin(i)
  File "/opt/boswatch/includes/pluginLoader.py", line 106, in loadPlugin
    return imp.load_module(plugin["name"], *plugin["info"])
  File "/opt/boswatch/plugins/gpiocontrol/gpiocontrol.py", line 95
    th = threading.Thread(target = trigger)
     ^
IndentationError: expected an indented block

Hallo zusammen, habe auf einem neu installierten Raspi 3 Bosmon mit dem Plugin IO installiert. Leider bekomme ich beim starten von Bosmon die oben gezeigten Fehler. Kann mir hier jemand helfen ? 
gruß Patrick

**Comment by Schrolli91** [comment]
Versuche mal den develop Branch - da gab es einen BUG.
Werde aber in den nächsten Tagen/Wochen ein Release bringen, dann sind diese Anpassungen ebenfalls im master.
siehe: https://github.com/Schrolli91/BOSWatch/pull/465/files
