### ISSUE TITLE
Telegram Text fett geschrieben, wie?

### ISSUE THREAD

**Issue by N00Bmeister** [Schrolli91/BOSWatch#502]
Bei Fragen und Problemen zu BOSWatch oder Plugins bitte unten gennante Informationen angeben:

- **BOSWatch Version + Branch**
SW Version:     2.5.1
Branch:         master
Build Date:     28.04.2020

- **genutzte Plugins**
Telegram
python-telegram-bot==11.0.0 (die 13 lässt sich nicht beim Start von BW laden, wirft nur fehler aus)

- **Fehlerbeschreibung**
Texte werden in Telegram nicht fett geschrieben

- **ggf. Config File (Auszug)**

#Wildcards can be used, see end of the file!
POC_message = *** %DESCR% *** %BR%%MSG%

Hallo zusammen, ich weiß nicht ob ich mit dem Problem hier richtig bin.
Ich versuche die ganze Zeit bei der Ausgabe von Mitteilungen (POCSAG oder FMS) das Einsatzmittel in fetter Schrift anzeigen zu lassen.
Bei einem Raspberry Pi 2b läuft das System bereits und dort wird meine %DESCR% auch fett ausgegeben, ich musste dafür vor  und nach der %DESCR" drei * machen.
Bsp. *** %DESCR% ***

Jetzt hab ich auf einem Pi 3b+ Raspberry Pi OS Lite Release date: December 2nd 2020 Kernel version: 5.4 drauf und da funktioniert genau diese Schreibweise nicht.
Ich hab schon gefühlt jede Kombination von Textformatierungsansätze versucht (<b> <b/>, ** **, * *, **** ****, *** ***) aber keine Funktioniert. 
Bei der Ausgabe auf Telegram werden die Sternchen oder andere Versuche vor und nach dem Text ausgegeben.
Bsp. *** RUFNAME ***

Es hat funktiontechnisch nichts mit BOSWATCH zu tun, aber hat jemand noch eine Idee?

Danke und Grüße

**Comment by Halon112** [comment]
Versuch mal mit einem anderen python-telegram-bot.
Ich hatte ein ähnliches Problem mit der Version 12.7 und musste auf 12.4.2 zurück.
Bei mir wurden die * nicht mit übermittelt. -> https://github.com/Schrolli91/BOSWatch/issues/454

**Comment by Halon112** [comment]
Nachtrag: Ich habe gerade die neueste Boswatch-Version 2.5.2 installiert. Dort ist eine Formatierung der Texte möglich.
Changelog: "Telegram Plugin: Add support for simple HTML style message formatting. https://github.com/Schrolli91/BOSWatch/pull/482 "
Nun kannst du einfach mit `POC_message = %DESCR% <b>%MSG%</b>` z.B. die Msg fett schreiben.

**Comment by N00Bmeister** [comment]
@Halon112 danke für deine Hilfe.

Ich hab das Problem gelöst, in dem ich python-telegram-bot==11.0.0 deinstalliert und dafür die Version 12.8 installiert hab.
Zusätzlich musste ich jedoch noch sudo pip telegram-bot installieren. 
Jetzt läuft alles ohne Probleme. 

Nochmals danke für die Hilfe :-)
