### ISSUE TITLE
Installation BOSWatch

### ISSUE THREAD

**Issue by ChrisX1809** [Schrolli91/BOSWatch#503]
Hallo,

bin auf das Projekt BOSWatch aufmerksam geworden und möchte dieses gerne nutzen. 
Ich habe nun gelesen, dass BOSWatch mit  rtl_fm und multimon-NG arbeitet. Wird mit dem Install Script beides installiert oder muss noch irgendwelche händischen Installationen durchführen. Unter den Installationsanweisungen konnte ich nichts finden.

Klar ist mir auch noch nicht, wie ich eine Beschreibungstabelle anlege und mir die ausgewertete Liste anzeigen lassen kann. Vielleicht kann ja jemand Licht in meine dunklen Flecken bringen. 

Gerne würde ich dieses spannende Projekt ausprobieren :-)

Danke.

**Comment by Schrolli91** [comment]
Das Installationsscript `install.sh` sollte alles was benötigt wird mit installieren.
Ggf. braucht das ein oder andere Plugin dann noch zusätzliche Python Libs - diese Info steht normalerweise im Plugin File.

Die Doku ist leider etwas dürftig, aber das meiste lässt sich aus den Kommentaren der Config erschließen.

Je nachdem welche Plugins du benötigst, wäre es evtl auch einen Versuch Wert direkt mit dem Nachfolger BOSWatch 3 zu starten, welcher sich derzeit noch in der Entwicklung befindet (da ists aber mit der Doku deutlich besser).
https://github.com/BOSWatch/BW3-Core
https://docs.boswatch.de/

**Comment by ChrisX1809** [comment]
Hey,

vielen Dank für die rasche Antwort. Dann schaue ich mir BOSWatch 3 mal an.
Ist denn eine Listendarstellung der ausgewerteten Daten mit beiden Apps möglich oder benötige ich da noch was anderes?

**Comment by Schrolli91** [comment]
BW ist ein reines Tool zum Alarmhandling (Filtern, Modifizieren, Weiterleiten, etc.) 
Darstellung muss extern erfolgen - Tool egal, Plugins sind recht einfach zu erstellen

**Comment by ChrisX1809** [comment]
Hey,
ich habe jetzt BOSwatch gemäß Anleitung installiert. Einen RTL Stick habe ich auch. Muss ich nun noch mutimon-ng installieren, oder reicht BOSwatch und der Stick zur Dekodierung?

**Comment by flothi** [comment]
> ich habe jetzt BOSwatch gemäß Anleitung installiert. Einen RTL Stick habe ich auch. Muss ich nun noch mutimon-ng installieren, oder reicht BOSwatch und der Stick zur Dekodierung?

Wenn du es mit dem Installer installiert hast, brauchst du nichts mehr. Ohne Plugins siehst du aber nur mit der Option `-v` etwas auf der Konsole.

**Comment by ChrisX1809** [comment]
Hey, danke. Das hat geklappt und funktioniert!
