### ISSUE TITLE
negativer ppm wert

### ISSUE THREAD

**Issue by Walterbraunlage** [Schrolli91/BOSWatch#505]
hallo, ich habe bei der kalibrierung des sticks einen negativen ppm wert.
ist das normal?

pi@Pi:~/kalibrate-rtl $ kal -s 850
Found 1 device(s):
  0:  Terratec T Stick PLUS

Using device 0: Terratec T Stick PLUS
Found Elonics E4000 tuner
Exact sample rate is: 270833.002142 Hz
kal: Scanning for GSM-850 base stations.
GSM-850:
    chan:  134 (870.4MHz + 39.885kHz)    power:  340670.89
    chan:  137 (871.0MHz - 39.944kHz)    power:  296105.47
    chan:  142 (872.0MHz - 285Hz)    power:  289084.20
    chan:  147 (873.0MHz + 31.993kHz)    power:  248773.00
    chan:  168 (877.2MHz - 27.878kHz)    power:  206325.68
    chan:  179 (879.4MHz + 15.488kHz)    power:  201201.51
    chan:  185 (880.6MHz + 8.063kHz)    power:  238018.88
    chan:  190 (881.6MHz + 23.887kHz)    power:  221063.37
    chan:  214 (886.4MHz + 28.375kHz)    power:  146808.80
    chan:  230 (889.6MHz - 16.144kHz)    power:  303343.58
    chan:  235 (890.6MHz + 15.816kHz)    power:  290762.92
    chan:  242 (892.0MHz + 4.303kHz)    power:  446095.70
...chan 251
Difference of offsets between channels is >1kHz. This likely means that the correct PPM is too far away and you need to provide a rough estimate using the '-e' option. Try tuning against a local FM radio or other known frequency first.
pi@Pi:~/kalibrate-rtl $ kal -c 242
Found 1 device(s):
  0:  Terratec T Stick PLUS

Using device 0: Terratec T Stick PLUS
Found Elonics E4000 tuner
Exact sample rate is: 270833.002142 Hz
kal: Calculating clock frequency offset.
Using GSM-850 channel 242 (892.0MHz)
Tuned to 892.000000MHz (reported tuner error: 0Hz)
average		[min, max]	(range, stddev)
+ 5.605kHz		[3183, 7005]	(3823, 1115.754639)
overruns: 0
not found: 46
average absolute error: -6.284 ppm
pi@Pi:~/kalibrate-rtl $ cd
pi@Pi:~ $ cd /opt/boswatch
pi@Pi:/opt/boswatch $ sudo python boswatch.py -f 1##.###M -a POC512 -e -6.284PPM
usage: boswatch.py [-h] -f FREQ [-d DEVICE] [-e ERROR] -a
                   {FMS,ZVEI,POC512,POC1200,POC2400}
                   [{FMS,ZVEI,POC512,POC1200,POC2400} ...] [-s SQUELCH]
                   [-g GAIN] [-u] [-v] [-q]
boswatch.py: error: argument -e/--error: expected one argument
pi@Pi:/opt/boswatch $ 

Danke schonmal im vorraus!

**Comment by Schrolli91** [comment]
klar, kann gut sein... statt nach oben, wird die Frequenz eben nach unten korrigiert.
Wenn der Empfang damit funktioniert ists doch egal ;-)

**Comment by Walterbraunlage** [comment]
ja aber wie kommt der error zu stande?

**Comment by Schrolli91** [comment]
Der Abgleich funktioniert folgendermaßen: (zumindest im groben)
- Der Stick tuned auf eine feste Frequenz auf der er weiß, dass dort sehr genau getunte Sender stehen (GSM)
- Der Stick schaut, wie weit der Peak des (sehr genauen) Signals von seiner eingestellten Frequenz weg ist.
- ist seine eigene Frequenz zu niedrig muss er also etwas höher tunen - positiver error (frequenz + error = korrete Frequenz)
- ist seine eigene Frequenz zu hoch muss er also etwas niedriger tunen - negativer error (frequenz - error = korrete Frequenz)

Daher ist ein negativer error absolut legitim und kann durchaus korrekt sein.

Evtl. ist aber auch das Signal zu schwach und er "misst Mist" ;-)

**Comment by Walterbraunlage** [comment]
Alles richtig, verstehe ich auch.
Aber warum kommt denn diese Fehlermeldung

pi@Pi:/opt/boswatch $ sudo python boswatch.py -f 1##.###M -a POC512 -e -6.284PPM
usage: boswatch.py [-h] -f FREQ [-d DEVICE] [-e ERROR] -a
{FMS,ZVEI,POC512,POC1200,POC2400}
[{FMS,ZVEI,POC512,POC1200,POC2400} ...] [-s SQUELCH]
[-g GAIN] [-u] [-v] [-q]
boswatch.py: error: argument -e/--error: expected one argument

Wenn ich einen positiven Wert eingebe ist alles schick (außer das er nichts findet) 
Setzte ich ein - vor dem frequenzdrift kommt die Fehlermeldung.

**Comment by flothi** [comment]
Das `-` vor dem Zahlenwert wird als Argument interpretiert. Ich muss mal schauen, wie man negative Werte übergibt

**Comment by Schrolli91** [comment]
Schon mal probiert den Wert in `"` oder `'` zu setzen? Ob das geht weiß ich allerdings nicht.

**Comment by flothi** [comment]
Nach ner ersten Sichtung ist der Parameter dann ohne Leerzeichen an rtl_fm zu übergeben, dann quasi `-e-6`
Mal schauen, ob das wirklich so klappt und wie wir es dann im Programm umsetzen

**Comment by Walterbraunlage** [comment]
Ja genau, in dieser Richtung war meine Frage.
Ich probiere es mal nachher und komme dann mit Lage.

**Comment by Walterbraunlage** [comment]
Hier meine Lage.
Meine sticks scheinen sich irgendwie nicht richtig zu kalibrieren. Der Empfang mit einem negativen ppm Wert hat nicht hingehauen. Erst beim positiven Wert. Meine Konstruktion muss auch Antennenseitig überarbeitet werden. Daher danke ich erstmal für die wie immer kompetente Hilfe. Vielen Dank und weiter so.
