### ISSUE TITLE
Boswatch aktualisieren

### ISSUE THREAD

**Issue by Walterbraunlage** [Schrolli91/BOSWatch#506]
Hallo und ne ganz kurze Frage. 
Wie und mit welchen Befehl aktualisiere ich boswatch?

**Comment by flothi** [comment]
Einen separaten Update gibt es nicht, du kannst lediglich via git die neusten Dateien ziehen. Je nach Versionssprung ist dann mehr oder weniger Nacharbeit nötig

**Comment by Schrolli91** [comment]
wenn du den installer einfach nochmal ausführst sollte er die aktuelle version installieren - alle alten Daten werden in einem backup order im BW Verzeichnis gesichert. Ggf.muss man dann nochmal die Config anpassen, je nach Update - siehe Changelog

**Comment by Walterbraunlage** [comment]
Ok, vielen Dank für die schnelle Hilfe.
