### ISSUE TITLE
WhatsApp Messege Plugin

### ISSUE THREAD

**Issue by Schrolli91** [Schrolli91/BOSWatch#51]
Hab da was gefunden: 
https://github.com/tgalal/yowsup (Python)
https://github.com/WHAnonymous/Chat-API (PHP ?)

**Comment by K3vP0** [comment]
Denke das ein Whatsapp Plugin eher nochmal kritisch zu überprüfen ist...
1) keiner weiß, wie lange whatsapp noch einen unautoriserten  Zugang duldet...
2) Datenschutz
3) man braucht eine ungenutzte Handynummer.
4) ich weiß ja nicht 🙈😁

**Comment by Schrolli91** [comment]
muss ich, wenn ich im Nachhinein so drüber nach denke, in allen Punkten zustimmen
closed...
