### ISSUE TITLE
MySQL Anschluss mit Plugin

### ISSUE THREAD

**Issue by ChrisX1809** [Schrolli91/BOSWatch#511]
Hallo, 

nach dem mein BOSWatch jetzt über die Konsole läuft, möchte ich gerne die Auswertungen optisch irgendwie darstellen.
Hat irgendjemand schon eine funktionierende Konfiguration über eine SQL Datenbank? Steh ein bisschen auf dem Schlauch, was die Konfiguration einer Datenbank und der entsprechenden Abfrage angeht.

Gruß
Chris

**Comment by mrduckspace** [comment]
Hallo Chris,
hast du Probleme beim einrichten einer Datenbank oder beim Anbinden von BOSWatch an die DB?

**Comment by ChrisX1809** [comment]
Hey,
hab mittlerweile die Datenbank am Laufen. Es werden auch Meldungen reingeschrieben. Aktuell bleibt ab und an nur Boswatch hängen und ich muss manuell neustarten. 

Ich stehe gerade an der Stelle, wo ich eine Webseite mit dem Inhalt der Datenbank darstellen möchte.

**Comment by mrduckspace** [comment]
Hey,
also zu dem Erstellen einer Website kann ich dir hier leider keine Tipps geben (Würde auch den Rahmen dieses Repos sprengen)
Wegen dem Aufhängen von Boswatch, es gibt so genannte CronJobs um z.B BosWatch oder den Raspberry Pi regelmäßig neuzustarten

**Comment by ChrisX1809** [comment]
Okay, ich hab noch die Spannungsversorgung in Verdacht, dass ich da noch ein zu kleines Netzteil nutze. Das muss ich aber noch checken.

**Comment by Schrolli91** [comment]
Wenn der Stick direkt one powered-HUB dranhängt, ist es fast zu 100 Prozent die PSU

**Comment by Schrolli91** [comment]
closed, da keine weitere Rückmeldung vom TO.
