### ISSUE TITLE
Express Alarm Text Ric 

### ISSUE THREAD

**Issue by Skipper1990** [Schrolli91/BOSWatch#514]
Hallo,

auf meiner Frequenz laufen 4 Text-Rics.
Alarmiert wird mit Express Alarm.

Ist es möglich einen Filter oder ähnliches anzulegen der sagt das alles Alarm Rics die in Verbindung mit einer gewissen Text-Ric stehen nicht weiter geleitet werden an Telegram ?
Jede einzelne Ric zu sperren oder Ähnliches wäre zu mühselig bei über 1000 Alarmen am Tag.

**Comment by Schrolli91** [comment]
Ich verstehe nicht ganz was du vorhast - vielleicht kannst du mal einen Fall mit fiktiven Daten beschreiben.
Also was durch kommen soll, und was nicht

**Comment by Skipper1990** [comment]
9:00 Uhr Alarm-Ric 1
9:00 Uhr Text-Ric 1 (bsp. Feuerwehr)
9:02 Uhr Alarm Ric 2
9:02 Uhr Text Ric 2 (bsp Rettungsdienst)

Ich möchte nur das es mir alle Rics von der Feuerwehr an Telegram sendet.
Die Anzahl der Rics ist aber unbekannt.

Die Frage ist jetzt, da es ja Express Alarm ist und es ja Blockweise kommt. Das man sagt das alle Rics die in Verbindung mit der Rettungsdienst Text-Ric stehen nicht gesendet werden.

**Comment by Schrolli91** [comment]
Spontan würde ich sagen, dass das leider nicht geht, da das Filtern vor der Express-Alarm Auswertung passiert.
Hundert pro sicher bin ich mir mit der Aussage aber gerade nicht.

Mit BW3 wäre das theoretisch möglich, da man durch die Router flexibel die Module anordnen und konfigurieren kann.
Nur gibt es in BW3 noch kein Express-Alarm Modul - daher nur theoretisch.

Vielleicht findet sich jemand, der ein entsprechendes Modul für BW3 entwickelt - meine Zeit gibt das leider aktuell nicht her.
Evtl. mal im BWCC fragen ob da jemand schon was in der "Pipeline" hat oder die Zeit und Muse ein Modul zu entwickeln.

**Comment by Skipper1990** [comment]
Da versuche ich es halt über den komplizierten Weg.

Wieviel Rics kann ich den bei deny_ric eingeben eh es zu Problemen kommt ?

**Comment by Schrolli91** [comment]
Theoretisch gibt es kein Limit.
Praktisch hat es noch niemand erreicht ...
