### ISSUE TITLE
Nach Neuinstallation auf anderem PC keine POCSAG-Auswertung mehr

### ISSUE THREAD

**Issue by UBeiSa** [Schrolli91/BOSWatch#516]
Nachdem meine bisherige Hardware nach einem Stromausfall nicht mehr zum Booten zu bewegen ist, habe ich einen Raspberry 3B+ neu aufgesetzt mit Raspbian und die aktuelle BOSWatch Version nach Anleitung im WIKI installiert.
Mit Kalibrate den bereits verwendeten RTL-SDR Stick neu kalibriert und die Config.INI neu aufgesetzt.
Nach dem Start von BosWatch erfolgt keine Auswertung der POCSAG-Meldungen mehr.
Log-Files von BosWatch werden angelegt und zeigen keine Fehler.

rtl_fm empfängt sauber und die Ausgabe mit "aplay" funktioniert.

Bei dem Start mit "sudo rtl_fm -f 170.120M -s 22050 - | multimon-ng -t raw" erscheint ein Fenster, in dem die Frequenzdarstellung ein Rauschen und bei Datenempfang das Telegramm deutlich darstellt. 
Multimon-ng mit -t raw -a POCSAG512 -a POCSAG1200 -a POCSAG2400 -f alpha /dev/stdin wertet aber absolut nichts aus.

Weiterer PC mit Debian installiert, gleiches Vorgehen, auch hier kommt mit rtl_fm ein Signal an, welches aplay ausgibt, aber auch hier keine Auswertung der POCSAG-Telegramme durch multimon-ng.

Verschiedenste Einstellungen bei rtl_fm (-g -l und -p) brachten keinen Erfolg. 

Irgendwelche Tipps??? Problem liegt definitiv bei multimon-ng...

**Comment by Schrolli91** [comment]
Welche MM Version wurde genutzt?

**Comment by UBeiSa** [comment]
Diejenige, welche mit dem Install-Script von BosWatch installiert wird.

**Comment by Schrolli91** [comment]
Das war zwar nicht ganz die Frage, aber gut - MM in der Version `die vom Install Script` sollte auf jeden Fall laufen 😉 

Ich tippe hier stark auf einen **Fehler beim Kalibrieren**.
Wenn MM die Frequenz nicht sauber passt, kann es schon vorkommen, das die Auswertung fehlschlägt.
Würde auch dafür sprechen, dass dieses Problem auf mehreren Rechnern auftritt.

**Comment by UBeiSa** [comment]
So, nach dem Testen von verschiedenen MM-Versionen (1.1.1, 1.1.6, 1.1.7, 1.1.8 und 1.1.9) und verschiedenen Parametern bekomme ich jetzt wieder Telegramme bei RTM_FM | MULTIMON-NG, aber nicht bei BOSWATCH.

Problem ist der Aufruf von MultimonNG. 

Hier der komplette Aufruf:
sudo rtl_fm -s 22050 -f 17x.xxxM -p -23 - | multimon-ng -t raw -c -a POCSAG1200 -f alpha **-i** /dev/stdin

Funktioniert auch  ohne Kalibrierung (d.h. ohne -p -23).

Multimon-ng wertet in meinem Fall nur aus, wenn der Aufruf mit dem Parameter -i (Invertierung vom Eingangssignal - "-i : POCSAG: Inverts the input samples. Try this if decoding fails.") erfolgt. Warum auch immer, auf dem alten Rechner hat das ohne -i funktioniert.
Ein weiteres Problem war die Verlängerung des USB-Anschlusses mit einem Kabel, damit der RLT-SDR-Stick am alten Platz verbleiben konnte. Nach ca. 10 empfangenen Telegrammen war plötzlich keine Verbindung zum Stick mehr möglich.

Aktuelle Systemkonfiguration: 
Hardware: 

- CPU Intel G2020 @ 2,90 Ghz, 4 GB Hauptspeicher

Software: 

- Linux 4.19.0.-9-amd64 (x86_64) (Debian GNU/Linux 10 (buster)
- BOSWATCH 2.5.2
- MultiMonNG 1.1.9
- RTL_FM ???

**Comment by Schrolli91** [comment]
Wie lang ist das USB Kabel? USB2 ist meines Wissens nur bis max. 5 Meter spezifiziert.

Zu MM kann ich grad nix sagen, das Verhalten habe ich noch nie beobachten können.
Villt hat sich beim kalibrieren was an den Quadratur-Settings geändert, oder es liegt am Treiber?
Welcher Kernel war das vorher?

**Comment by UBeiSa** [comment]
Kabellänge war/ist 2 Meter, somit in der Spezifikation (allerdings ein "billiges Kabel" :-( ). Zuvor war Debian 9 im Einsatz auf einem Mini-PC von CSL.
Ich habe einen neuen RTL_SDR-Stick bestellt und werde die ganze Geschichte noch mal test. Bis dahin passe ich für mich boswatch.py soweit an, dass der "-i" Parameter mit übertragen wird...

Ich werde weitere Informationen geben - vielleicht kann ich ja die eigentliche Ursache finden...

**Comment by PeterLaemmle** [comment]
Vermutlich muss der Aufruf in der boswatch.py geändert werden:
`command = command+"multimon-ng "+str(demodulation)+" -f alpha -t raw - "`
lass das `/dev/stdin` mal weg.

**Comment by Schrolli91** [comment]
Closed wegen Inaktivität.
