### ISSUE TITLE
Netzkennung in Telegram ignorieren

### ISSUE THREAD

**Issue by ChrisX1809** [Schrolli91/BOSWatch#517]
Hallo,

habe erfolgreich die Verbindung zum Telegram herstellen können.
In der Gruppe taucht aber immer die Netzkennung auf, die ich eigentlich bereits in der Config.ini zur Ignorierung angegeben habe.
Was mach ich falsch? Möchte die natürlich nicht dauernd angezeigt bekommen. 

Gruß

**Comment by Schrolli91** [comment]
Mein Auto springt nicht an - was mache ich falsch?

Scherz beiseite - Ohne deine Config kann man dir nicht helfen.
Vor allem wenn die die NET-RIC bereits "ausgeschlossen" hast.
Da ist sicher nur ne Kleinigkeit falsch.

**Comment by ChrisX1809** [comment]
Hey, 

Ja, kann ich verstehen, dass es zu nebulös ist, hätte ja sein können, dass es einen Standardfehler gibt. Anbei meine config: 

[config.log](https://github.com/Schrolli91/BOSWatch/files/6014671/config.log)

**Comment by Schrolli91** [comment]
Seh ich das Richtig, dass du die bei `netIdent_ric` eingetragen hast?
Dann kommen die freilich IMMER durch 😉 
Pack die mal bei `deny_ric` rein und probier nochmal

**Comment by ChrisX1809** [comment]
Danke, hat geklappt. Ich dachte das mit Identifikation als Net Ident die Ric entsprechend nicht auftaucht.

**Comment by Schrolli91** [comment]
Der Vollständigkeit halber - Was bei NetIdent eingetragen wird, wird nur bei einigen Plugins ggf. anders behandelt (zb. MySQL). Aber per se gefiltert wird es so nicht
