### ISSUE TITLE
Problem RTL_FM

### ISSUE THREAD

**Issue by tile000** [Schrolli91/BOSWatch#520]
Bei Fragen und Problemen zu BOSWatch oder Plugins bitte unten gennante Informationen angeben:

- **BOSWatch Version + Branch**
2.5.2 master
- **genutzte Plugins**
BOSMon mit DVBT Stick NESDR Mini 2
- **Fehlerbeschreibung**
Beim starten von BOSWatch funktioniert alles, anschließend bekomme ich das Problem, dass rtl_fm nicht gestartet werden kann und das Programm sich anschließend beendet.
- **Logfile (Auszug)**
10.07.2021  12:45:32  - boswatch   [CRITICAL] cannot start rtl_fm
10.07.2021  12:45:32  - boswatch   [WARNING] SystemExit received
10.07.2021  12:45:32  - boswatch   [INFO] BOSWatch exit()
- **ggf. Config File (Auszug)**
config ist komplett original, lediglich die BOSMON Zugangsdaten etc wurden eingegeben

**Comment by flothi** [comment]
Du startest aber schon als "sudo"? Hast du rtl_fm mal manuell aufgerufen?

**Comment by Schrolli91** [comment]
Closed wegen Inaktivität.
