### ISSUE TITLE
Sammelalarm 

### ISSUE THREAD

**Issue by K3vP0** [Schrolli91/BOSWatch#53]
Hallo,

Hab da eine Idee, mir fehlt aber noch der richtige Gedanke zur Umsetzung:

Es wird ja meist nicht nur eine Einheit Alamiert für eine Schadenslage, sondern meist mehrere.
Ich will nun das abfangen und global bereit stellen damit ich auf meinem Alarmmonitor darstellen kann wer noch alles kommt. 
Also:
Ric1
Ric2 
RicX werden alamiert innerhalb von y Sekunden zwischen den Meldungen Alamiert, 
Schreibe alle Discriptions und RICs in 2 verschiedene Strings mit Komma getrennt und gebe es aus wenn Ric1 auch Alamiert ist als Pseudo-ric oder zvei ?! 

Jemand ne Idee ?

**Comment by JHCD** [comment]
Das lässt sich am einfachsten per DB-Zugriff lösen.
Wenn der Alarm-RIC kommt, die letzten n Sekunden aus der DB lesen.
Nach m Sekunden evtl. nochmal nachlesen.
Das Vorgehen (dynamische www-Seite für Alarmmonitor) hatte ich in dem Thread #29 bereits beschrieben.

**Comment by Schrolli91** [comment]
Dem kann ich nur beipflichten, hier eignet sich wohl am besten das MySQL Plugin.
Und eine dynamische *.php Seite erledigt den Rest, nicht mal sehr schwierig, würde ich meinen

Grobes Vorgehen: (Zeiten nur als Bsp.)

##### BOSWatch
- Per `allowRic`, `allowRange` oder dem `RegEX` auf die wichtigen RICs Filtern
- Daten per MySQL Plugin in die Datenbank werfen

##### PHP
- php File welches sich automatisch alle Sekunde. neu lädt. (Header-refresh-arg)
- Liest den letzten Alarm aus, wenn älter als 30Min zeige die Uhrzeit und Datum
- Falls neuer als 30 Min nehm Uhrzeit von diesem Alarm und lese alle, die nicht älter als 60sek. sind (Von diesem zuerst gelesenen neuen Alarm aus gerechnet natürlich)
- Die dann als Liste ausgeben

Das wars, damit sollten alle deine Anforderungen erfüllt sein - Aufwand, EXAKT eine php Datei, kein Javascript oder ähnlicher Dreck
Nachtrag: Wenn du hier dann nach der Alarm Meldung gruppierst, kannst du die Alarmierungen sogar Gruppiert nach Einsatz darstellen also 2 Einheiten zu Einsatz xyz und 3 Einheiten sind Einsatz abc. Vorausgesetzt die Meldungen sind auch gleich beim Alarm zum selben Ereignis. Davon gehe ich aber aus

**EDIT:**
Und wenn die Datei auf einem lokalen Server läuft, Raspi o.Ä. dann kannst du in PHP sogar den Shell Zugriff erlauben, dann kann das PHP Script den Bildschrim selber steuern...
- Bei alarm stehen alle alarmierten Rics dann 30 Min da..
- Nach 30Min blendet er die Uhrzeit nebst Datum ein
- Nach 60 Min seit letzten Alarm dann einfach Screen off

Wäre auch bereit dir dabei zu helfen, wenn du magst. Kenne deine PHP Kenntnisse nicht

**Comment by K3vP0** [comment]
Wenn du mir das schreiben könntest wäre das natürlich klasse. Meine PHP Kenntnisse halten sich in Grenzen, also für das Projekt ohne viel Lesen glaube ich wird das nichts. da bin ich schneller über ein Script der statisches HTML erstellt... 

Also wenn du Lust und Zeit hast, darfst du gern mir was schreiben :P

**Comment by Schrolli91** [comment]
Aktuell hab ich wenig Zeit, aber ich setz mich wenns passt gern mal dran :smiley:

**Comment by K3vP0** [comment]
Habe dank

**Comment by K3vP0** [comment]
#closed
