### ISSUE TITLE
Visualisierung der letzten Alamierungen und Statis

### ISSUE THREAD

**Issue by K3vP0** [Schrolli91/BOSWatch#54]
Hallo,

Möchte mal kurz ein kleines neues Projekt von mir vorstellen:

Das Plugin wird in der Lage sein ein Arduino zu steuern welcher x beliebig viele LED's schaltet.
Die Idee dahinter:
Wir haben eine große Karte mit allen Wachen drauf verzeichnet, diese wird auf Holz geklebt und dann von hinten für jede Wache eine LED eingesetzt. ( eventuell RGB LEDs) Bei eingehendem Alarm fängt die Lampe an rot zu blinken, wird der Status von 2 auf 3 gewechselt wird die Lampe nur noch Rot, wird die 4 gedrückt im FMS wird die LED grün, in der 1 gelb und so weiter und sofort. 

Schritt eins wird erstmal sein die POCSAG Meldungen zu übergeben und alleine auszuwerten (rotes Blinken für 5 min)

Danach eine Verbindung zwischen POCSAG-RIC und FMS-Kennung herzustellen.
Dann die einzelnen Statis auszuwerten.

PS. Warum schreibe ich den Text..? Nicht das wir uns hier doppelte Arbeit machen

**Comment by Schrolli91** [comment]
Same here:
JHCD's Json-Server example eignet sich perfekt dafür... das sind an sich ja keine Plugins sondern eigene Steuerprogramme die nur von den BOSWatch Daten gespeist werden...

Das einzige was ich mir aber evtl noch gut vorstellen könnte wäre ein Seriell-Plugin, dass die Daten an eine serielle Schnittstelle sendet. Da könnte man dann auch den Arduino bzw generell Microcontroller Hardware mit UART perfekt einbinden. Die Verarbeitung/Auswertung muss dann natürlich auf dem uC passieren, dafür ist BOSWatch ja nicht zuständig.

Für das seriell-Plugin würde ich mich mal einlesen...

**Comment by K3vP0** [comment]
Okay. Ich denke eine direkte Ansprache der TTY wäre sinnvoll... 
Nen serielles Plugin ist auch schnell gebaut (1Std).

**Comment by JHCD** [comment]
Wie schon beim Alarmmonitor-Thread:
BOSWatch speichert keine Werte zwischen, dies müsste außerhalb passieren.
Entweder dort einen lokalen Speicher bauen oder über eine DB (z.B per MySQL-Plugin) arbeiten.

**Comment by Schrolli91** [comment]
Also da sich die Ansteuerung des Arduino dann sowieso per seriell (siehe #57 ) umsetzen lässt, und der Rest dann nicht mehr Sache von BOSWatch ist, sondern vom Arduino Code sage ich einfach mal closed...
