### ISSUE TITLE
Boswatch 3 - install.sh bricht ab

### ISSUE THREAD

**Issue by Magic-Alwin** [Schrolli91/BOSWatch#543]
Ich möchte gerne die Boswatch 3 auf meinem RaspBerry installieren.
Dazu habe ich folgende Befehle eingegeben:
wget https://github.com/BOSWatch/BW3-Core/raw/master/install.sh

und im Anschluß:
sudo bash install.sh

Die Installation beginnt, aber bricht nach "[ 2/9] [##-------]" 
mit der Fehlermeldung:

Action: download on stuff failed. - Exitcode: 100

ab.

Kann mir jemand weiterhelfen, da ich mich mit RaspBerry und Linux absoluter Laie bin 
un es eigentlcih nur nach einen "Punkt-für-Punkt Anleitung" ausführe

**Comment by Magic-Alwin** [comment]
Hier das dazugehörige "setup_log.txt"


OK:1 http://archive.raspberrypi.org/debian bullseye InRelease
OK:2 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Paketlisten werden gelesen…
Paketlisten werden gelesen…
Abhängigkeitsbaum wird aufgebaut…
Statusinformationen werden eingelesen…
Paket python-pip ist nicht verfügbar, wird aber von einem anderen Paket
referenziert. Das kann heißen, dass das Paket fehlt, dass es abgelöst
wurde oder nur aus einer anderen Quelle verfügbar ist.
Doch die folgenden Pakete ersetzen es:
  python3-pip

E: Paket qt4-qmake kann nicht gefunden werden.
E: Paket qt4-default kann nicht gefunden werden.
E: Für Paket »python-pip« existiert kein Installationskandidat.
Action: download on stuff failed.
Exitcode: 100

**Comment by Schrolli91** [comment]
Issue gehört zu BW3 nicht zu BW2.
