### ISSUE TITLE
FMS Probleme

### ISSUE THREAD

**Issue by SimonTDE** [Schrolli91/BOSWatch#544]
Hallo zusammen,

leider habe ich das Problem, dass ich falsche FMS Signale erhalte. POCSAG klappt Problemlos.
Den RTL SDR Stick habe ich auch schon bereits Kalibriert, doch leider bekomme ich es nicht hin FMS korrekt auszuwerten.
Aus der mm_raw.txt konnte ich leider auch nur komplett falsche dinge erhalten.
Hat jemand eine Idee wie ich die Auswertung für FMS verbessern kann?
Starten tue ich BOSWatch wie folgt: python boswatch.py -f %Frequenz%M -d 0 -a FMS ZVEI POC512 POC1200 POC2400 -v -g 100

Vielen Dank im Voraus!

LG Simon

**Comment by Schrolli91** [comment]
Was heißt denn komplett falsch?
Wenn die Daten in der mm_raw schon falsch sind, liegt es aber nicht an BOSWatch selbst sondern an multimon.

Schau vielleicht mal in der MM Doku ob es hier andere Parameter für die Auswertung braucht, bei dir.

**Comment by theMagicKnight** [comment]
Hallo,

wunder dich bitte nicht wenn die FMS komisch aussehen, die Fahrzeuge sind auch verschlüsselt.

**Comment by Schrolli91** [comment]
closed, da keine weitere Rückmeldung vom TO
