### ISSUE TITLE
no valid ZVEI: xxx

### ISSUE THREAD

**Issue by harakaio** [Schrolli91/BOSWatch#552]
Hallo zusammen,

ich nutze seit ein paar Tagen den "alten" Branch von BOSWatch (diesen hier) und noch nicht BOSWatch/BW3-Core.
- SW-Version 2.5.2
- Branch: master
- bisher nur mySQL genutzt

- Fehlerbeschreibung: siehe unten
- Logfile: siehe unten
- Config-File: siehe unten

**Fehlerbeschreibung:**
aktuell läuft BOSWatch noch mit Debugging-Log. Ich möchte nur ZVEI nutzen, FMS benötige ich nicht. Im Log steht jedoch immer nur "No valid ZVEI: : 272"
Ich habe das Gefühl, dass da zu "früh" mit dem auslesen begonnen wird.

Anbei das Log-File von gestern (30.09.22) und die config.ini
[boswatch.log.2022-09-30.log](https://github.com/Schrolli91/BOSWatch/files/9690085/boswatch.log.2022-09-30.log)
[config.ini.log](https://github.com/Schrolli91/BOSWatch/files/9690088/config.ini.log)

Auszüge aus dem Log:
30.09.2022 14:34:10 - boswatch        [DEBUG   ] BOSWatch has started
30.09.2022 14:34:10 - boswatch        [DEBUG   ] Logfiles cleared
30.09.2022 14:34:10 - boswatch        [DEBUG   ] SW Version:	2.5.2
30.09.2022 14:34:10 - boswatch        [DEBUG   ] Branch:		master
30.09.2022 14:34:10 - boswatch        [DEBUG   ] Build Date:	08.01.2021
30.09.2022 14:34:10 - boswatch        [DEBUG   ] Python Vers:	3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0]
[...]
30.09.2022 16:34:00 - decoder         [DEBUG   ] received ZVEI
30.09.2022 16:34:00 - zvei            [WARNING ] No valid ZVEI: : 272
30.09.2022 16:34:01 - decoder         [DEBUG   ] received ZVEI
30.09.2022 16:34:01 - zvei            [WARNING ] No valid ZVEI: : 272
30.09.2022 16:48:46 - decoder         [DEBUG   ] received ZVEI
30.09.2022 16:48:46 - zvei            [WARNING ] No valid ZVEI: : 279
30.09.2022 16:48:47 - decoder         [DEBUG   ] received ZVEI
30.09.2022 16:48:47 - zvei            [WARNING ] No valid ZVEI: : 279
30.09.2022 16:48:52 - decoder         [DEBUG   ] received ZVEI
30.09.2022 16:48:52 - zvei            [WARNING ] No valid ZVEI: : 279
30.09.2022 16:48:53 - decoder         [DEBUG   ] received ZVEI
30.09.2022 16:48:53 - zvei            [WARNING ] No valid ZVEI: : 279

**Comment by harakaio** [comment]
Problem gelöst durch Anpassung der folgenden Datei:
/opt/boswatch/includes/decoders/zvei.py

Line 60
- vorher:
- 		zvei_id = decoded[7:12]    # ZVEI Code
- nacher:
- 		zvei_id = decoded[9:14]    # ZVEI Code

Die Alarme werden nun sauber verarbeitet.

**Comment by Schrolli91** [comment]
Kannst du davon mal die Rohdaten (bitte anonymisiert) zur Verfügung stellen?
Mich würde interessieren wie das aktuell aussieht - scheinbar hat sich da bei Multimon was geändert ?!?

**Comment by harakaio** [comment]
Klar, kein Problem.
Vielleicht doofe Frage: wie komme ich da an bspw logs oder Stream heran?

Schönen Abend 

Am 3. Oktober 2022 19:12:26 MESZ schrieb Bastian Schroll ***@***.***>:

**Comment by Schrolli91** [comment]
Muss in der config aktiviert werden: https://github.com/Schrolli91/BOSWatch/blob/master/config/config.template.ini#L64

Dann sollte es ein Textfile mit den empfangenen Rohdaten geben `mm_raw.txt` oder so.

**Comment by harakaio** [comment]
Hey,
hier der Output/Inhalt meiner mm_raw.txt aus dem Ordner "var/log/BOSWatch":
`b'Enabled demodulators: ZVEI1\n'b'ZVEI1: 12345\n'b'ZVEI1: 12345\n'b'ZVEI1: 12345\n'b'ZVEI1: 12345\n'`
_(Hinweis: ZVEI-IDs wurden von mir durch 12345 ersetzt._

**Comment by Schrolli91** [comment]
duplicate of #554

**Comment by harakaio** [comment]
Hey,
das Problem ist leider weiterhin noch vorhanden.
Ich habe durch diverse Anpassungen und "Spielereien" leider noch kein sauberes Ergebnis bekommen.
Die ZVEI-IDs werden teilweise einfach "verhackstückelt" und können somit nicht als 5-Ton-Folge im gesamten ausgewertet werden....

Ideen?
