### ISSUE TITLE
ZVEI-IDs werden nicht komplett erkannt

### ISSUE THREAD

**Issue by harakaio** [Schrolli91/BOSWatch#559]
Hey,
das Problem ist leider weiterhin noch vorhanden.
Ich habe durch diverse Anpassungen und "Spielereien" leider noch kein sauberes Ergebnis bekommen.
Die ZVEI-IDs werden teilweise einfach "verhackstückelt" und können somit nicht als 5-Ton-Folge im gesamten ausgewertet werden....

Ideen?

_Originally posted by @harakaio in https://github.com/Schrolli91/BOSWatch/issues/552#issuecomment-1307685542_

**Comment by Schrolli91** [comment]
duplicate of #554
