### ISSUE TITLE
BOSWatch empfängt ganz plötzlich kein Telegramm mehr

### ISSUE THREAD

**Issue by Gummiadler4** [Schrolli91/BOSWatch#562]
Bei Fragen und Problemen zu BOSWatch oder Plugins bitte unten gennante Informationen angeben:

- **BOSWatch Version 2** Wo finde ich die Details?

- **Telegram und Web**

- **seit 5 Tagen kommt plötzlich kein Telegramm mehr rein. Bis dahin lief es seit Jahren problemlos. Es wurde zu dieser Zeit bichts verändert**

- **RTL_FM.log** (xxx) von in der Frequenz von mir gesetzt
- Found 1 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 00000001

Using device 0: Generic RTL2832U OEM
Found Rafael Micro R820T tuner
Tuner gain set to 48.00 dB.
Tuner error set to 65 ppm.
r82xx_read: i2c rd failed=-1 reg=00 len=3
r82xx_set_freq: failed=-1
rtlsdr_demod_write_reg failed with -1
rtlsdr_demod_read_reg failed with -1
WARNING: Failed to set center freq.
Oversampling input by: 64x.
Oversampling output by: 1x.
Buffer size: 5.80ms
Exact sample rate is: 1xxx200.013458 Hz
rtlsdr_demod_write_reg failed with -1
rtlsdr_demod_read_reg failed with -1
rtlsdr_demod_write_reg failed with -1
rtlsdr_demod_read_reg failed with -1
rtlsdr_demod_write_reg failed with -1
rtlsdr_demod_read_reg failed with -1
rtlsdr_demod_write_reg failed with -1
rtlsdr_demod_read_reg failed with -1
rtlsdr_demod_write_reg failed with -1
rtlsdr_demod_read_reg failed with -1
rtlsdr_demod_write_reg failed with -1
rtlsdr_demod_read_reg failed with -1
rtlsdr_demod_write_reg failed with -1
rtlsdr_demod_read_reg failed with -1
rtlsdr_demod_write_reg failed with -1
rtlsdr_demod_read_reg failed with -1
WARNING: Failed to set sample rate.
Output at 22050 Hz.

- **ggf. Config File (Auszug)**
Wer kann mir helfen? Was fehlt noch zur Analyse?

VG

**Comment by Schrolli91** [comment]
Den Stick mal an einem SDR Programm getestet of zB UKW-Radio geht?
Das klingt mir fast nach einem defekten Tuner im Stick.

**Comment by Gummiadler4** [comment]
Hmm, das befürchte ich auch... Hab den gestern mal aufgemacht, sieht aus, als wäre der Chip durchgebrannt.
Habe schon einen neuen bestellt. Wenn ich dann noch Probleme hab, melde ich mich wieder.

Danke erstmal

**Comment by Schrolli91** [comment]
Da das ja recht eindeutig klingt würde ich das Issue erst mal schließen.
Falls du danach wider erwarten wirklich noch weiter Probleme hast, kannst du dich hier ja melden und wir öffnen es wieder.

**Comment by Gummiadler4** [comment]
Ich habe doch noch ein Problem...
Mein neuer Stick ist heute angekommen, aber irgendwas klappt da noch nicht. Beim ersten Start wurde er im Log (rtl_fm-log) erkannt.
Found 1 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 00000001

Using device 0: Generic RTL2832U OEM
Found Fitipower FC0012 tuner
rtlsdr_demod_write_reg failed with -1
rtlsdr_demod_read_reg failed with -1
rtlsdr_demod_write_reg failed with -1
rtlsdr_demod_read_reg failed with -1
rtlsdr_demod_write_reg failed with -1
rtlsdr_demod_read_reg failed with -1
rtlsdr_demod_write_reg failed with -1
rtlsdr_demod_read_reg failed with -1
rtlsdr_demod_write_reg failed with -1
rtlsdr_demod_read_reg failed with -1
rtlsdr_demod_write_reg failed with -1
rtlsdr_demod_read_reg failed with -1
rtlsdr_demod_write_reg failed with -1
rtlsdr_demod_read_reg failed with -1
WARNING: Failed to set tuner gain.
rtlsdr_demod_write_reg failed with -1
rtlsdr_demod_read_reg failed with -1
rtlsdr_demod_write_reg failed with -1
rtlsdr_demod_read_reg failed with -1
WARNING: Failed to set ppm error.
rtlsdr_write_reg failed with -1
rtlsdr_write_reg failed with -1
rtlsdr_demod_write_reg failed with -1
rtlsdr_demod_read_reg failed with -1
rtlsdr_read_reg failed with -1
rtlsdr_write_reg failed with -1
rtlsdr_demod_write_reg failed with -1
rtlsdr_demod_read_reg failed with -1
WARNING: Failed to set center freq.
Oversampling input by: 64x.
Oversampling output by: 1x.
Buffer size: 5.80ms
Exact sample rate is: 1411200.013458 Hz
rtlsdr_demod_write_reg failed with -1
rtlsdr_demod_read_reg failed with -1
rtlsdr_demod_write_reg failed with -1
rtlsdr_demod_read_reg failed with -1
rtlsdr_demod_write_reg failed with -1
rtlsdr_demod_read_reg failed with -1
rtlsdr_demod_write_reg failed with -1
rtlsdr_demod_read_reg failed with -1
rtlsdr_demod_write_reg failed with -1
rtlsdr_demod_read_reg failed with -1
rtlsdr_demod_write_reg failed with -1
rtlsdr_demod_read_reg failed with -1
rtlsdr_demod_write_reg failed with -1
rtlsdr_demod_read_reg failed with -1
rtlsdr_demod_write_reg failed with -1
rtlsdr_demod_read_reg failed with -1
WARNING: Failed to set sample rate.
Output at 22050 Hz.

Daraufhin wollte ich ihn kalibrieren, was mir ein paar Warnungen, aber immerhin auch 2 Kanäle ausgespuckt hat (kal -s 900). Daraufhin habe ich kal -c 46 aufgerufen, was mir ein Offset von 12.700 ppm erbrachte. Den Wert habe ich in der Boswatcher.sh eingetragen und neugestartet. Jetzt wird der Stick nicht mehr erkannt. Im Logfile steht nur "No supported device found".
Auch ein weiterer Neustart hat nichts gebracht.
Was kann das sein?
Muss ich den Chipsatz 2838 noch in eine Blacklist eintragen?

PS: Kann ich Dir irgendwie per PM schreiben und Bilder senden?
![Raspi](https://github.com/Schrolli91/BOSWatch/assets/140969822/9e446459-4283-4199-8a64-979738a779c4)

**Comment by Schrolli91** [comment]
Teste bitte die Sticks mal ganz allgemein mit anderer SDR Software und teste den Empfang von UKW zB.
Ich glaube hier eher an ein OS Problem, da der neue Stick die selben Fehler wirft, wie der alte.

**Comment by Gummiadler4** [comment]
Ich habe eine alte Sicherheitskopie des gesamten OS genommen. Da sieht es manchmal so aus, als würde alles richtig erkannt und gestartet. Es kommt jedoch kein Telegramm rein. Ich bin leider kein Experte in Linux, daher kenne ich keine andere SW. Manchmal zeigt rtl_Test sinnvolle Daten, manchmal nur Fehler.Von meiner Brieftaube in Stein gemeißeltAm 07.08.2023 um 06:49 schrieb Bastian Schroll ***@***.***>:﻿
Teste bitte die Sticks mal ganz allgemein mit anderer SDR Software und teste den Empfang von UKW zB.
Ich glaube hier eher an ein OS Problem, da der neue Stick die selben Fehler wirft, wie der alte.

**Comment by Schrolli91** [comment]
Hängt der Stick direkt am PI oder an einem extern mit Strom versorgten USB Hub?

**Comment by Gummiadler4** [comment]
Direkt am PiVon meiner Brieftaube in Stein gemeißeltAm 07.08.2023 um 08:18 schrieb Bastian Schroll ***@***.***>:﻿
Hängt der Stick direkt am PI oder an einem extern mit Strom versorgten USB Hub?

**Comment by Gummiadler4** [comment]
Könnte es an der STV liegen? Ich sehe öfter mal einen BlitzVon meiner Brieftaube in Stein gemeißeltAm 07.08.2023 um 08:18 schrieb Bastian Schroll ***@***.***>:﻿
Hängt der Stick direkt am PI oder an einem extern mit Strom versorgten USB Hub?

**Comment by Schrolli91** [comment]
Dann kann das absolut an der Stromversorgung liegen.
Der Blitz deutet schon ganz eindeutig darauf hin, das dem PI der Saft ausgeht.
Evtl zieht der Stick inzwischen etwas mehr Strom als früher (Alterung/Empfangssituation/etc) und bringt den RPi damit an seine Grenzen.

Der Stick sollte unbedingt extern versorgt werden.

**Comment by Gummiadler4** [comment]
Ok, dann teste ich das am WE noch mal. Bin gerade nicht zu Hause.DankeVon meiner Brieftaube in Stein gemeißeltAm 07.08.2023 um 09:26 schrieb Bastian Schroll ***@***.***>:﻿
Dann kann das absolut an der Stromversorgung liegen.
Der Blitz deutet schon ganz eindeutig darauf hin, das dem PI der Saft ausgeht.
Evtl zieht der Stick inzwischen etwas mehr Strom als früher (Alterung/Empfangssituation/etc) und bringt den RPi damit an seine Grenzen.
Der Stick sollte unbedingt extern versorgt werden.

**Comment by Gummiadler4** [comment]
So, ich habe die STV getauscht, den Stick mit einem kurzen Kabel etwas vom Pi entfernt, falls es da zu Kontaktschwierigkeiten kommt.
RTL abgeschossen, neu kalibiert, dann kamen zumindest wieder Lebenszeichen. Wieder die Dachantenne dran, jetzt läuft es wieder. Keine Ahnung, was es nun wirklich war. Blitz ist jedenfalls auch weg.
Danke für die Hilfe
