### ISSUE TITLE
Daten per Serieller Schnittstelle

### ISSUE THREAD

**Issue by Schrolli91** [Schrolli91/BOSWatch#57]
Wie der Name schon sagt, ein Plugin, welches die Daten über die serielle Schnittstelle schiebt.

Welche Möglichkeiten gibt es den auf die Schnittstellen zuzugrifen? Direkt wird das Python nicht können, oder?
http://pyserial.sourceforge.net/ wäre eine Möglichkeit...

**Comment by JHCD** [comment]
Wie sieht es denn hier mit Standards etc. aus oder erwartet jedes per serieller Schnittstelle angebundenes Gerät ein anderes Protokoll?

**Comment by Schrolli91** [comment]
am besten wäre wenn man das Datenformat per config.ini vorgibt, hier also wieder mit den Wildcards arbeitet...

Bsp:. `protocol = %ZVEI%;%TIME%;%DATE%/n/r` (hier also ; als Separator)

Und dies einfach als String über seriell jagen, dann muss die gegenstelle das ganze aufsplitten und verwerten wie gewünscht.

So ist man denke ich am Flexibelsten und kann das Protokoll notfalls auch auf kommerzielle Hardware anpassen, wenn sowas nötig werden würde.

**Comment by K3vP0** [comment]
Hört sich sehr gut an, ich würde allerdings nur rs232 unterstützen, alles andere zieht zu große Kreise

**Comment by Schrolli91** [comment]
ja freilich nur RS232 - ergo ja auch USB-COM Umsetzer, sind ja ansprechbar wie eine physische Schnittstelle, passenden Treiber vorrausgesetzt

**Comment by K3vP0** [comment]
Ich mach mich da mal dran, oder hat jemand schon angefangen?

**Comment by Schrolli91** [comment]
Ich noch nicht - werde vermutlich erst in 2 oder 3 Tagen wieder aktiv online sein.

**Comment by Schrolli91** [comment]
@kevinkleist  hat sich dahingehend schon etwas ergeben?

**Comment by K3vP0** [comment]
Sorry... Ich komm im Moment nicht zu...
