### ISSUE TITLE
mysql Plugin

### ISSUE THREAD

**Issue by mezzobob** [Schrolli91/BOSWatch#58]
Habe ich das nicht gesehen oder gib es keine Beschreibung welche Felder in den Tabellen angelegt werden sollen?

**Comment by K3vP0** [comment]
/Plugins/MySQL/mysql.py

Da kannst es draus erkenn

**Comment by Schrolli91** [comment]
@mezzobob Importiere einfach die `boswatch.sql` Datei die im Ordner `Plugins/MySQL` liegt, dann werden die benötigten Tabellen mit allen Feldern automatisch angelegt

**Comment by Schrolli91** [comment]
@mezzobob ich gehe davon aus das ganze hat sich erledigt.
Damit würde ich sagen, closed...
