### ISSUE TITLE
Quellcode in UTF-8

### ISSUE THREAD

**Issue by JHCD** [Schrolli91/BOSWatch#60]
Änderung der Kodierung des Quellcodes in UTF-8.
- alle Dateien ändern
- Datei-Header anpassen

**Comment by Schrolli91** [comment]
Mein Editor speichert sowieso alles in UTF-8 sehe ich gerade.

Im Prinzip heißt das ja nur, alle Header anpassen: `coding: cp1252` -> `coding: utf8`

Und dann alle Dateien einmal öffnen, abspeichern, commiten

Sehe ich das Richtig? Würde ich dann auch gleich übernehmen.

**Comment by JHCD** [comment]
Wenn Dein Editor den Header ignoriert, wäre es ein schlechter Editor.
Und ja, an das Vorgehen dachte ich.
Der korrekte Header müsste aber "utf-8" lauten, bitte mal nachschauen.

**Comment by Schrolli91** [comment]
Du hast Recht - er speichert tatsächlich nicht in UTF-8 :smile: 
UTF-8 steht nur als default drin, falls er keine Angabe findet.

Ok, dann würde ich mich der Sache annehmen, in allen Python Dateien die Header anzupassen und es unter UTF-8 abzuspeichern.

``` python
#!/usr/bin/python
# -*- coding: UTF-8 -*-
#
```

**Comment by Schrolli91** [comment]
Done! - closed
