### ISSUE TITLE
Empfang CRC Fehler 

### ISSUE THREAD

**Issue by mezzobob** [Schrolli91/BOSWatch#68]
Unten ein Auszug aus meinen LOG

Ich habe wohl schlechten Empfang, hier meine Frage wie sieht euer Setup aus?
Ich benutze einen raspberry pi mit DVB-T Stick mit (RTL2838UHIDIR) Chip und die Mitgelieferte Antenne. 
Ich habe das Setup schon an verschiedenen Orten im Haus getestet.
Brauche ich eine Andere Antenne oder einen LNA Vorverstärker? 
Hat jemand ein anderes Setup? 
Der Gain in BOSWatch steht Standard mäßig auf 100, da habe ich auch schon kurz mit rumgespielt, macht das Sinn?

LOG
23.07.2015 16:02:19 - decoder         [DEBUG   ] recieved FMS
23.07.2015 16:02:19 - fms             [WARNING ] FMS CRC incorrect
23.07.2015 16:02:19 - decoder         [DEBUG   ] recieved FMS
23.07.2015 16:02:19 - fms             [WARNING ] No valid FMS: af238121s 
[...]
23.07.2015 19:33:59 - decoder         [DEBUG   ] recieved FMS
23.07.2015 19:33:59 - fms             [WARNING ] FMS CRC incorrect

**Comment by JHCD** [comment]
Natürlich spielt die Antenne eine Rolle, die beiliegende Antenne ist für andere Frequenzbereiche gedacht. Eine gute Scanner-Antenne oder eine richtige 4m-Antenne machen da viel aus.

Aber die erste Frage wäre: Hast Du die Frequenz kontrolliert/ abgestimmt? 
Mein Stick liegt z.B. 9 KHz neben der Frequenz.

**Comment by mezzobob** [comment]
Ja ich bin auch nicht genau auf der Frequenz, ich habe mit gqrx geschaut und liege auch etwas neben der "genannten" Frequenz.

**Comment by K3vP0** [comment]
Schließe mich da Jens an...
Du solltest nochmal penibelst alle Einstellungen kontrollieren,sieht so aus als wenn du zwei drei Hertz daneben liegst.
Desweiteren kann ich dir empfehlen -sollst du eine ausziehbare Antenne haben- diese auf Lambda / 8 oder so einfahren.

Dann spielt der Antennenstandort eine wichtige Rolle. 4m in Gebäuden ist manchmal sehr kritisch, im ländlichen Bereich beinahe unmöglich ohne Tricks. Also gucken wo deine Relaisstation sitzt und die Antenne dort hin positionieren wo möglichst wenig im Weg ist, solltest du in einem Niedrigenergiehaus mit bedampfen Scheiben und doppelter Isolierung wohnen... Dann wirst du nicht um eine Ausenantenne drum her rum kommen.
Nächster Fehler könnte sein, du hast Oberband oder Unterband vertauscht. Je nach dem wie euer netzt geschaltet ist.

Ansonsten kann ich dir noch aus persönlicher Erfahrung sagen, das ein DVB-T Stick kein DME ist, also nicht gesicherter Empfang... 
Ich habe in meinem Log (hauptsächlich POCSAG Signale ) auch pro Meldung 2-3 gefilterte Meldungen die nicht plausibel sind. Liegt aber wie gesagt an den Empfangsbedinnungen.
Wieviel Störsignale du so alle mit nimmst. Die Entstörung ist ein Kapitel für sich ... Gibt's genug bei Google zu. 
Ich hoffe ich konnte dir weiter helfen.

**Comment by K3vP0** [comment]
Dann auf den besten Wert einstellen... Ist fummelig. Aber wenn man es einmal raus hat klappt es ganz gut. 

Wenns nicht funkt, kannst dich ja noch mal melden.

**Comment by JHCD** [comment]
Mit einer richtigen 2m Lambda/2 Antenne auf einem Antennenmast gibt es hier keine Probleme mit POCSAG-Signalen. :-)

**Comment by K3vP0** [comment]
Angeber 😂

**Comment by K3vP0** [comment]
und funktioniert es nun ?

**Comment by Schrolli91** [comment]
Wie sich im Forum herausstellte ging es dabei wohl um ein Problem vom Stick her in Sachen Error Correction usw.
Also kein Thema für die Issue Liste
