### ISSUE TITLE
Berücksichtigung der Startargumente im Testmodus

### ISSUE THREAD

**Issue by K3vP0** [Schrolli91/BOSWatch#70]
Im Testmodus wird keine Rücksicht genommen welche Argumente angegeben sind. wenn ich also nun nur POC1200 lade und FMS einlese, könnte es den ein oder anderen Fehler geben, oder ?

**Comment by K3vP0** [comment]
Gleichzeitig wäre es doch ganz gut, wenn die Config durch eine extra Datei überschrieben wird, müsste man dann nicht immer umstellen.

**Comment by JHCD** [comment]
Moin Kevin,

aber mit dem Testmodus-Verhalten war von uns genau so gewollt. Wir wollen sicherstellen, dass wir immer alles testen. Wenn an einer zentralen Funktion etwas verändert wird, wäre es fatal nur einen Pfad zu testen.

Dir steht es natürlich frei Deine lokale testdaten-Datei anzupassen, solange Du den Code nicht hier hochladen möchtest. ;)

Da ich für Entwicklung und produktives Umfeld verschiedene BOSWatch-Instanzen betreibe, habe ich das Problem nicht. Man könnte mal über eine config.test.ini nachdenken. 

Grüße
Jens
