### ISSUE TITLE
Zeitfunktionen in Plugins

### ISSUE THREAD

**Issue by K3vP0** [Schrolli91/BOSWatch#72]
Um jegliche (maximal eine Sekunde) Differenzen in der Alarmzeit zu eliminieren, schlage ich vor, ein data[time] einzuführen, damit jeder Alarm im Plugin  die selbe Zeit hat - ansonsten kann es passieren, das ein Plugin 13:41:50 und das nächste 13:41:51 bekommt...
Was haltet ihr davon? :+1: ? :-1: ?

**Comment by JHCD** [comment]
Habe ich bei firEmergeny denn überhaupt die Möglichkeit eine Zeit zu übergeben?
Wenn ja, in welchem Format?

**Comment by K3vP0** [comment]
Nein hast du nicht, ich meinte generell.

**Comment by JHCD** [comment]
Generell ist es nun eingebaut, damit hier closed
