### ISSUE TITLE
data[description] --> falscher Zeichensatz

### ISSUE THREAD

**Issue by K3vP0** [Schrolli91/BOSWatch#73]
Überschrift sagt alles. data[description] ist in einem falschen Zeichensatz. daher hängt die Übergabe zu firEmergency .

Momentan hilft mir in der firE.py Zeile 102: einfach ein .encode('UTF-8') an das data[description]
 Woher das rührt, ist mir unbekannt.

**Comment by JHCD** [comment]
So, ich habe da jetzt nochmal ein paar Stunden reingesteckt und hoffe, dass es jetzt vernünftig läuft.
Mit den Testdaten gibt es kein Problem mehr, jetzt läuft es gerade auf einem Raspberry mit SDR-Stick. Wenn dort die ersten Meldungen mit Sonderzeichen korrekt übertragen wurden, checke ich die Änderungen ein.

**Comment by K3vP0** [comment]
Danke.
