### ISSUE TITLE
pluginHandler - unloadPlugin()

### ISSUE THREAD

**Issue by JHCD** [Schrolli91/BOSWatch#74]
Aktuell werden bei jedem Plugin-Aufruf die benötigten connection-Objekte instanziiert und Verbindungen aufgebaut.
Je nach Plugin brauchen die Objekte nur einmal angelegt und teilweise (z.B. MySQL) auch nur einmalig eine Connection erstellt werden.
Um die Verbindungen am Ende sauber zu schließen, benötigt der pluginHandler dafür eine `unloadPlugin()`\- Funktion, die die entsprechende Methoden im aktiven Plugin aufruft.

Neue Plugin-Struktur am Bsp MySQL:

``` python
# lokale Variablen
connection = None

# onLoad (init) function of plugin
# will be called one time by the pluginLoader on start
def onLoad():
    connection = mysql.connector.connect

# Main function of MySQL-plugin
# will be called by the alarmHandler
def run(typ,freq,data):
    cursor = connection.cursor()
    ....
    cursor.close()

# unLoad (close) function of plugin
# will be called one time by the pluginLoader on shuting down BOSWatch 
def unLoad():
    connection.close()
```

**Comment by Schrolli91** [comment]
evtl Sinnvoll - im Falle MySQL aber nicht

Es muss vor jedem Insert ein eigener connect + anschließendem disconnect laufen, da der Server sonst aufgrund eines Timeouts die Verbindung irgendwann selbst schließt.

**Comment by flothi** [comment]
Ich würde das gerne nochmal anstoßen - ein unLoad wäre gerade bei der Verwendung von Hardwareschnittstellen hilfreich; aktuell löse ich es unschön in der main-Datei.

**Comment by Schrolli91** [comment]
werde ich mir anschauen, sobald ich wieder gesund bin

**Comment by flothi** [comment]
Kein Stress, gute Besserung!

**Comment by Schrolli91** [comment]
wird in #229 ja dann sowieso erschlagen - closed
