### ISSUE TITLE
E-Mail: Unterscheidung nach Sub-RIC

### ISSUE THREAD

**Issue by flothi** [Schrolli91/BOSWatch#77]
Servus,

wäre es nicht sinnvoll, die E-Mail-Aktion noch zusätzlich nach Sub-RIC zu unterscheiden? Bei uns wird via D bspw. der Probealarm alarmiert, da muss ich keine E-Mail versenden; bei A-C hingegen schon (und ggf. das als Alarmierung für zB GroupAlarm nutzen).

VG

**Comment by K3vP0** [comment]
1. Frage:  Kann man in der Config-Datei per RegEx-Abfrage einfach rausfiltern.
2. Wunsch: Kannst du doch am einfachsten über firEmergency ? 

Grüße

> Am 24.12.2015 um 00:46 schrieb flothi notifications@github.com:
> 
> wäre es nicht sinnvoll, die E-Mail-Aktion noch zusätzlich nach Sub-RIC zu unterscheiden? Bei uns wird via D bspw der Probealarm alarmiert, da muss ich keine E-Mail versenden; bei A-C hingegen schon (und ggf das als Alarmierung für zB GroupAlarm nutzen)

**Comment by flothi** [comment]
OK; an den RegEx-Filter hab ich gar nicht mehr gedacht, danke für den Hinweis 
Dann werd ich mal schauen, wie ich der config beibiegen kann, sich bei A und B anders zu verhalten als bei C resp. D (also 3 E-Mail-Typen).

Zu FirEmergency: Keine Ahnung, ich find das per Mail smart und sexy ;-)

**Comment by Schrolli91** [comment]
Da seit einem Monat keine Rückmeldung kam, gehe ich davon aus, das ganze wurde zufriedenstellen gelöst... Closed

**Comment by flothi** [comment]
Zwar nicht so ganz, aber ich versuche es weiter
