### ISSUE TITLE
Deutsche Schritt für Schritt Anleitung?

### ISSUE THREAD

**Issue by ThorsBerserker** [Schrolli91/BOSWatch#79]
Liebe Community!
Ich bin über einen Tipp in einem Forum auf dieses Programm/Plugin gestoßen, hab jedoch keine Ahnung wie ich es richtig anwenden kann. Ich nutze SDR Sharp und PDW Pager zum Empfangen und Anzeigen von POCSAG Signalen. Da diese in letzter Zeit jedoch nur noch verschlüsselt gesendet werden, war ich auf der suche nach einem entsprechenden Programm zum entschlüsseln dieser Nachrichten und bin dabei auf BOSWatch gestoßen. Leider stieß ich jedoch bereits bei der Anleitung auf Probleme sodass ich jetzt keine Ahnung habe, wie ich BOSWatch nutzen kann. Daher meine Frage/Bitte - hat sich vielleicht mal jemand die Mühe gemacht, eine Schritt für Schritt Anleitung für Neulinge zu verfassen? Bzw. gibt es die Anleitung auch auf Deutsch? Danke für eure Hilfe und LG

**Comment by Schrolli91** [comment]
@ThorsBerserker 
Eine Deutsche Anleitung gibt es aktuell leider nicht - Installation ist über das `install.sh` Script möglich. Danach muss eben wie in der `README.md` angegeben nur noch die config File umbenannt und angepasst werden.

Die Frage ist aber eher, ob BOSWatch überhaupt das Richtige für dich ist?
Entschlüsseln kann BOSWatch nämlich nichts, es nutzt nur `rtl_fm` zum Empfangen des Datenstreams per DVB-T Stick (ähnlich `SDR#`) und anschließend `multimon-ng` zum decodieren, wie es auch `PDW` tut. Danach schaltet sich erst BOSWatch ein und entscheidet je nach Konfiguration, was es mit den Daten anstellt, bzw wohin sie weitergeleitet werden.
