### ISSUE TITLE
Zwei Frequenzen mit zwei Adaptern

### ISSUE THREAD

**Issue by stereu** [Schrolli91/BOSWatch#80]
Hallo zusammen,
ist es möglich zwei Frequenzen (FMS/POCSAG) mit zwei Adaptern an einem RPi auszuwerten? Wenn eine zweite Instanz gestartet wird, wird rtl-fm nicht ein zweites Mal geöffnet.
Grüße

**Comment by K3vP0** [comment]
Hallo allein ;) ,

Nutzt du die Option -d ? 

Grüße zurück

**Comment by stereu** [comment]
Hat funktioniert! Für alle anderen:
Zwei Instanzen in jeweils einem Shell-Fenster starten und dabei mit dem Parameter "-d" jeweils eines der beiden angeschlossenen Geräte auswählen. Vorher unbedingt die ppm-Korrektur mit "rtl_test -p" ermitteln, diese ist für jeden Adapter unterschiedlich, auch bei gleichem Chiptyp.
@kevinkleist Danke für die schnelle Antwort
@Schrolli91 Danke für das super Script, funktioniert einwandfrei!
