### ISSUE TITLE
Daten per serieller Schnittstelle empfangen

### ISSUE THREAD

**Issue by DeLocke** [Schrolli91/BOSWatch#81]
Ist etwas geplant Daten per serieller Schnittstelle empfangen zu können z.B. via Swissphone BOSS Station?

**Comment by K3vP0** [comment]
Hey,

Ich hatte das mal implementiert, jedoch ging dabei einiges verloren(Frag mich nicht was) ... Ist also nicht wirklich Zielführend gewesen.

Grüße

**Comment by DeLocke** [comment]
Man müsste ja nur per pyserial die Daten abfragen und so formatieren das BOSWatch damit klar kommt z.B. ins multimon Format konvertieren

**Comment by K3vP0** [comment]
Meine Überlegung war das man es sofort ein wenig offener gestaltet und das Hauptprogramm nur noch ein Array von wo auch immer herkommt. 

Heißt man könnte auch eine Übergabe von einer externen Audioquelle nutzen und eventuell gängige Programme wie FMS32 nutzen. 

Ich mach mich mal am Wochenende ans Werk.

**Comment by Schrolli91** [comment]
Siehe #57 - ein Issue reicht, daher closed
