### ISSUE TITLE
RegEX-Filter Fehler

### ISSUE THREAD

**Issue by K3vP0** [Schrolli91/BOSWatch#82]
Wenn zwei RegEX Filter auf ein Plugin zeigen und zwei verschiedene Felder filtern sollen, Wird entweder nach dem einen oder dem anderen RegEX Filter ausgefiltert (Immer unterschiedlich).

**Comment by Schrolli91** [comment]
@kevinkleist  Am besten beide RegEX Config Zeilen Posten inkl einem Logauszug wo ersichtlich wird welches Plugin wie angesprochen wird.
So aus dem blauen heraus kann ich schwer beurteilen was genau passiert.

**Comment by Schrolli91** [comment]
@kevinkleist 
Besteht das Problem noch? Gibts weitere Infos?
Ansonsten würde ich das Issue schließen.

**Comment by K3vP0** [comment]
Das Problem besteht wohl eher darin das es keine und / oder Verknüpfungen gibt... Bekommt man das in RegEx irgendwie implementiert ?

**Comment by Schrolli91** [comment]
in RegEX selber sollte man ohne Probleme UND und/oder ODER Verknüpfungen realisieren können.

Dann denke ich, kann mein die beiden RegEX Befehle auf einen reduzieren und das Problem ist vom Tisch, sehe ich das richtig?

**Comment by Schrolli91** [comment]
Da keine weiteren Infos dazu kamen, das Problem in dieser Art auch nicht mehr aufgetreten zu sein scheint - closed
