### ISSUE TITLE
cannot send HTTP request

### ISSUE THREAD

**Issue by Tweak81** [Schrolli91/BOSWatch#83]
Ich nutze seit gestern dieses fantastische Tool und komme ganz gut zurecht.
Nun möchte ich aber bei einem empfangenen "Alarm" einen http-request ausführen. Die Parameter sollen in einer PHP weiterverarbeitet werden, sodass im Endergebnis eine Pushnachricht auf's iPhone erfolgt.

Leider scheitert es bereits beim http request:
<img width="848" alt="request_error" src="https://cloud.githubusercontent.com/assets/8289700/12615516/6e06acb8-c506-11e5-9a7d-70e9ec184a71.png">

Die config.ini sieht so aus:
<img width="646" alt="config" src="https://cloud.githubusercontent.com/assets/8289700/12615527/7ff52c42-c506-11e5-94ec-5eb980434f90.png">

Wenn ich die Adresse mit der PHP so im Browser aufrufe, funktioniert es. Ich kriege es nur nicht hin, dass die Datei im Plugin aufgerufen wird. Ich bin nicht der Experte, aber liegt es am GET-Befehl in der Plugin-Datei? Es müssen für meine Erfordernisse streng genommen keine Werte zurückgegben werden. Es reicht, wenn die PHP mit entsprechenden Parametern aufgerufen wird. Sozusagen Fire and forget.

Gruß, Christian

**Comment by Schrolli91** [comment]
Da scheint es Probleme mit deiner URL zu geben, da er meldet `name or service not known`
Probiere das ganze nochmal mir der auskommentierten Test URL die in der config eine Zeile über deiner steht und poste dazu bitte den Log

**Comment by Tweak81** [comment]
tatsächlich geht es mit der vordefinierten URL
<img width="934" alt="bildschirmfoto 2016-01-27 um 20 02 39" src="https://cloud.githubusercontent.com/assets/8289700/12624762/069c4d5a-c531-11e5-9e9f-19e63e26907a.png">

jetzt ist die Frage, warum geht "meine" URL nicht. Im Browser funktioniert sie. Wie man sieht, wird über DynDNS-Anbieter geroutet. Vor der URL kann man kein "www" setzen. Meine URL ist etwa so eingetragen: "irgendwas.no-ip.org/Ordner/file.php..." und NICHT "www.irgendwas.no-ip.org..."

Kann ich das Plugin entsprechend abändern, sodass meine URL funktioniert? 

EDIT: Ich habe nun bei no-ip auch die Option für Wildcards gesetzt, sodass es auch mit dem Prefix "www" im Browser funktioniert. 
<img width="651" alt="bildschirmfoto 2016-01-27 um 20 28 07" src="https://cloud.githubusercontent.com/assets/8289700/12625730/62b48fa4-c535-11e5-9686-c84061fca2e4.png">

Im Script funktioniert es dennoch nicht. Stehe total auf dem Schlauch

EDIT 2: Ich vermute, dass es mit dem Bindestrich in der URL oder der Subdomain zusammenhängt. Ich habe im script einfach mal www.google.de eingegeben und es kommt Status 200 zurück. Danach habe ich nur meine DynDNS-URL eingeben (ohne Ordner oder Angabe einer PHP) und es kommt wieder zum Fehler. Kann es sein, dass im Script die URL evtl nicht richtig durch den Bindestrich oder die Subdomain verarbeitet wird?

**Comment by Schrolli91** [comment]
Das Problem an der ganzen Sache ist, dass es so aussieht, als ob der Fehler nicht in BOSWatch entsteht, sondern in der Python `httplib` Library.
Von daher werden wir da kaum Einfluss drauf haben, fraglich ist eben nur WIESO das passiert.

Probiere mal irgendeine andere URL mit Bindestrich.

**Comment by Tweak81** [comment]
Ich hab es erstmal umgangen und über ein Template funktioniert es nun.
in der config.ini musste ich die URL allerdings mit "poc_url = http://" angeben.

in der template.py sieht es dann so aus:
<img width="992" alt="bildschirmfoto 2016-01-28 um 11 08 26" src="https://cloud.githubusercontent.com/assets/8289700/12641386/954ba9e6-c5af-11e5-9f5b-9675e445ddc3.png">
(urllib2 habe ich oben beim import eingetragen)

Damit klappt es bisher. Das PHP-File wird aufgerufen, die Parameter übergeben und ich kann es weiterverarbeiten.

Dies ist erstmal ein funktionierender Workaround, mit dem ich Leben kann. Keine Ahnung, ob es Nachteile bringt und/oder der Code sauber ist, aber es funktioniert.

**Comment by Schrolli91** [comment]
Ok, freut mich wenn es erstmal soweit geht.

Wenn du Lust hast, wäre es nett wenn du mal folgendes testen könntest:

In der original  Plugin Datei `httpRequest.py` die beiden untersten Zeilen mal anfügen und im Log schauen was dabei rauskommt. Der sollte normalerweise die URL splitten und in der ersten Ausgabe den Pfad der Adresse liefern zB. `http://google.de/` und in der zweiten Ausgabe dann den Querry der Anfrage zB. `index.php?ric=####`

``` python
#
# HTTP-Request
#
logging.debug("send %s HTTP request", typ)
url = urlparse(url) #split URL into path and querry
httprequest = httplib.HTTPConnection(url[2]) #connect to URL Path
httprequest.request("GET", url[5]) #send URL Querry per GET

logging.info(url[2])
logging.info(url[5])
```

**Comment by Tweak81** [comment]
Ich hab es eben getestet und es erfolgt keine Ausgabe der URL. Wenn Du magst, gebe ich Dir mal die Adresse und Du kannst es bei Dir/von Dir aus testen.
BTW.. Ich hab die Config derzeit bei mir so:
<img width="766" alt="bildschirmfoto 2016-01-31 um 21 14 16" src="https://cloud.githubusercontent.com/assets/8289700/12704652/b0de97d8-c85f-11e5-8e46-4bea4da6e531.png">
Wenn ein Alarm auf eine RIC kommt, ist manchmal auch ein "leerer Text" dabei. Da ich nicht sicher bin, ob es immer der 2. Alarm ist, der die leere Meldung enthält, möchte ich sicherheitshalber keinen Double-Filter aktivieren. Gibt es aber eine Möglichkeit, komplett alle leeren Meldungen rauszufiltern?

**Comment by K3vP0** [comment]
Ich habe einfach im Hauptablauf -quick and dirty- ein if eingebaut der prüft ob es eine Nachricht enthält.

**Comment by Tweak81** [comment]
Wo hast Du was genau eingefügt? Mir reicht quick&dirty :-D

Edit: Ich habe es jetzt (erstmal) in der angesprochenen PHP so gelöst:

`if($message == '')  {
    echo 'Message leer - Abbruch';
exit();
}`

Noch bessere wäre es natürlich, wenn die PHP gar nicht erst unnötigerweise aufgerufen wird,`

> Ich habe einfach im Hauptablauf -quick and dirty- ein if eingebaut der prüft ob es eine Nachricht enthält.

**Comment by Schrolli91** [comment]
Hat sich zu dem Problem denn nun schon etwas neues ergeben, mit dem ich arbeiten könnte?
Gibts Infos die zur Behebung oder Reproduktion des Problems beitragen?

Ansonsten würde ich das Issue schließen
