### ISSUE TITLE
install.sh-Überarbeiten

### ISSUE THREAD

**Issue by K3vP0** [Schrolli91/BOSWatch#87]
Hey zusammen,

Fehler während des Installationsprozesses werden im Moment nicht abgegriffen.

Wäre vielleicht ganz nett, wenn man das ganze kurz angezeigt bekommt wenn es harkt?

**Comment by Schrolli91** [comment]
falls Fehler auftreten dürften die aber auf jeden Fall im `~/boswatch/install/setup_log.txt` stehen... Oder nicht?
