### ISSUE TITLE
Service Script / Std.config in config auslagern (Idee)

### ISSUE THREAD

**Issue by K3vP0** [Schrolli91/BOSWatch#88]
Hallo zusammen,

habe zwei Ideen grade so im Kopf:
1. eine Ablage der doch lang gewordenen Parameter in die Config-Datei. (Natürlich mit Exception das wenn man boswatch mit Parametern startet das ganze dann auch diese annimmt.
2. Das Dienst-script sofort mit installieren in der install.sh

**Comment by Schrolli91** [comment]
1) Könnte man umsetzen, das wäre evtl sinnvoll und man muss die Parameter, die man eh immer benötigt nicht immer mit dazuschreiben

2) dazu lieber ein eigenes install Script - nicht jeder will das ganze zwangsläufig gleich als Dienst im System kleben haben
