### ISSUE TITLE
Fehlende Dependency: qt4-default

### ISSUE THREAD

**Issue by warmstart** [Schrolli91/BOSWatch#89]
Bitte "qt4-default" zu den zu installierenden Paketen von install.sh hinzufügen (Zeile 29). Sonst schlägt der Build von multimon-ng (konkret der qmake Befehl) fehl.

**Comment by Schrolli91** [comment]
`apt-get -y install git cmake build-essential libusb-1.0 qt4-default qt4-qmake libpulse-dev libx11-dev sox >> ~/boswatch/install/setup_log.txt 2>&1`
sehe ich das so Richtig? kann leider nicht testen und will nichts ändern was am Ende nicht korrekt ist

**Comment by K3vP0** [comment]
Also ich hab gestern das ganze sauber auf nen leeres Debian gezogen...  Da
hats geklappt
Am 13.04.2016 21:06 schrieb "Bastian Schroll" notifications@github.com:

**Comment by warmstart** [comment]
@Schrolli91 Ja genau so!

Bei mir tritt das Problem auf einem Ubuntu Server 15.10 auf. Wahrscheinlich hat qt4-make unter Debian eine Dependency auf qt4-default, aber nicht unter Ubuntu.

**Comment by Schrolli91** [comment]
dann pflege ich das so ein...
ein Update unter Debian schadet dem qt4-default ja nicht, auch wenns schon vorhanden ist
