### ISSUE TITLE
fehlende Zeichen am Textende

### ISSUE THREAD

**Issue by Tweak81** [Schrolli91/BOSWatch#90]
Moin...

ich beobachte öfter mal, dass der letzte Buchstabe eines Textes fehlt. Ich bin sicher, dass die Texte korrekt gesendet werden. Kann es ein Softwareproblem sein oder liegt es am Empfang. Die Texte sind soweit sauber und korrekt, nur ab und zu fehlt der letzte Buchstabe. Ich dachte erst, dass ein Plugin schuld ist, aber selbst im Log tauchen die Texte dann mit fehlendem letzten Buchstaben auf.

**Comment by K3vP0** [comment]
Moin Moin,

hatte das gleiche Problem. Bei mir lag es an einem „zu schlecht“ eingestellten Error Correction Wert…

Grüße
Kevin

**Comment by Tweak81** [comment]
Das kommt ungefähr alle 50-70 Texte mal vor, dass wirklich nur der letzte Buchstabe fehlt. Liegt das wirklich an der Error Correction? 
Das merkwürdige ist zudem, dass wenn der Text an 2 Empfänger geschickt wird, der letzte Buchstabe bei beiden Texten fehlt. Ich kann mir aber nicht vorstellen, dass so oft der letzte Buchstabe vergessen wird zu schreiben. Gibt es in BOSWatch evtl. eine Routine, die die asugewerteten Texte irgendwie nochmal formatiert/bearbeitet oder werden die direkt 1:1 von RTL_FM so übernommen und weitergegeben?

**Comment by Schrolli91** [comment]
Eigentlich sollten die Werte 1:1 aus dem Paket ausgeschnitten werden.
Möglich das hier auch ein Bug in rtl_fm beim Empfang oder in multimon-ng bei der Auswertung vorliegt

**Comment by Schrolli91** [comment]
Da nichts weiter dazu kommt - und es schwer danach aussieht, kein BOSWatch eigener Fehler zu sein -> Closed
