### ISSUE TITLE
install.sh qmake raspberry

### ISSUE THREAD

**Issue by Cryjack** [Schrolli91/BOSWatch#91]
Scheinbar reicht das qt4-qmake nicht auf der jessie-lite Version aus. Erst nach Installation von qt5-default läuft der qmake durch. Ärgerlich zu finden, da lediglich eine Zeile in der setup_log landet und dort nur schwer zu finden (fehlendes Errorhandling).

**Comment by ThomasF88** [comment]
Ich würde den Fehler super gerne verstehen, da ich meinen Pi updaten wollte.
Gibt es das auch für Neulinge, die es gerade so hinbekommen haben, alles stabil laufen zu haben? :/

Tut mir Leid, wenn ich nerve. :sa:

**Comment by Schrolli91** [comment]
@Cryjack würdest du die install.sh im dev-Branch anpassen wollen, sodass alles reibungslos installiert?

oder soll ich quasi einfach nur das qt5-default hinzufügen?

**Comment by Cryjack** [comment]
Hallo, sorry dass ich mich jetzt erst melde. Ich schaue mir das im Dev mal an und packe dort mal meine Install-Routine rein.
