### ISSUE TITLE
FMS-Kennung falsch?

### ISSUE THREAD

**Issue by stereu** [Schrolli91/BOSWatch#95]
Hallo zusammen,

die FMS-Kennung in BOSWatch wird bei mir nicht korrekt ausgegeben. Sie unterscheidet sich von der korrekten Kennung (BOSmon/Berechnung/Programmiert in FMS Hörer). Empfangsfehler kann es nicht sein, da die Stati korrekt empfangen werden, nur mit der falschen Kennung.
Woran kann das liegen?

Viele Grüße und Danke für eure Hilfe

**Comment by joachimbk** [comment]
Hallo, 
wie falsch ist die Kennung den? Ich habe im Moment mit multimon-ng (ohne boswatch) das Problem dass die Ortskennung falsch ist, alles andere passt.
Viele Grüße 
Joachim 
Am 26.05.2016 18:41 schrieb stereu notifications@github.com:Hallo zusammen,

die FMS-Kennung in BOSWatch wird bei mir nicht korrekt ausgegeben. Sie unterscheidet sich von der korrekten Kennung (BOSmon/Berechnung/Programmiert in FMS Hörer). Empfangsfehler kann es nicht sein, da die Stati korrekt empfangen werden, nur mit der falschen Kennung.
Woran kann das liegen?

Viele Grüße und Danke für eure Hilfe

**Comment by stereu** [comment]
Wenn ich das momentan richtig ermittelt hab sind bei mir die Stellen 3 und 4 falsch, also damit auch die Ortskennung. Wie hast du das gelöst?

**Comment by Schrolli91** [comment]
in der `includes/decoders/fms.py` werden die Daten aus dem multimon Datensatz extrahiert...

**Comment by stereu** [comment]
Danke für eure Hilfe, habe es jetzt in PHP gelöst.
Tipp: SQL-Befehl "REPLACE"

**Comment by Soundworld** [comment]
Ich habe komischerweise dasselbe Problem, dass die Ortskennung (Stelle 3 und 4) verdreht ist, also anstatt 30 wird 03 ausgewertet. Gibt es da eine andere Lösung als über PHP? Was mir auch aufgefallen ist: Es kommt relativ oft der Fehler "FMS CRC incorrect". Was meint ihr? Wird eine passendere Antenne da ggf. Abhilfe schaffen können für den CRC Fehler?

**Comment by flothi** [comment]
Ich lasse es bei mir mal über Nacht mitplotten - aber es sieht auch hier nach nem Dreher in der Ortskennung aus - dadurch wird natürlich auch die Checksumme fehlerhaft.
--EDIT
Issue 57 bei multimon-ng: https://github.com/EliasOenal/multimon-ng/issues/57

**Comment by flothi** [comment]
Ich habe einen fix für multimon-ng fertig - werde ihn heute abend aber nochmal in Ruhe testen.

Ich würde gerne in dem Zuge die crc-prüfung optional machen (via config), da in meiner Wahrnehmung viele Status von multimon-ng als inkorrekt gewertet werden.

Gibt's da ähnliche Beobachtungen?

**Comment by Doxoh** [comment]
Ja diese Beobachtung hab ich auch schon gemacht

**Comment by Soundworld** [comment]
Hallo Flothi, war dein Test denn erfolgreich?

**Comment by flothi** [comment]
Aktuell komme ich abends immer erst zum Testen, da ist FMS-mäßig leider nur wenig los ;-) 

Stand jetzt:
- Der Fix in multimon-ng scheint zu laufen, zumindest optisch sieht das alles ordentlich aus

ToDo:
- Anpassen der fms.py
- CRC-Überprüfung optional setzen (die scheint mir recht schlecht in Multimon implementiert, s.a. Hinweise im Quelltext)
- Danach teste ich das ganze als service mal 1-2 Tage, aber ich bin guter Dinge.

**Comment by flothi** [comment]
So, update:
- multimon ist upgedatet (s. Pullrequest dort)
- BOSWatch ist ebenfalls angepasst, Beschreibung siehe Pull request #199 

Ich bitte um ausgiebiges Testen, bei mir schauts primstens aus.

**WICHTIG:**
Multimon-ng muss dafür neu gebaut werden, dazu die fms.c in `/opt/boswatch/install/multimonNG/` ersetzen, dann mit `cd build/` in den Ordner wechseln und mit 
`qmake ../multimon-ng.pro`
`make`
`sudo make install`
multimon-ng neu bauen.

**Comment by flothi** [comment]
Der Patch besteht aus zwei Teilen, die der Reihe nach beschrieben werden:
1. Multimon-ng patchen
a) Ändern der alten Sources
- Wenn BOSWatch mit dem Installer installiert wurde, in das Verzeichnis `/opt/boswatch/install/multimonNG` wechseln; andernfalls in das Verzeichnis, in dem die Sourcen von multimon-ng liegen.

- Die `fms.c` aus dem Repo (Schrolli91/multimon-ng, https://raw.githubusercontent.com/Schrolli91/multimon-ng/master/fms.c ) herunterladen und die alte Datei ersetzen.

- In das Verzeichnis `build` wechseln; dort die Befehlsfolge
`qmake ../multimon-ng.pro`
`make`
`sudo make install`
aufrufen - fertig

b) Multimon-ng komplett neu herunterladen und kompilieren (kommt aufs gleiche raus, da das fertige Programm zentral abgelegt wird)
`git clone https://github.com/Schrolli91/multimon-ng.git`
`cd multimon-ng`
`mkdir build`
`cd build`
`qmake ../multimon-ng.pro`
`make`
`sudo make install`

2. BOSWatch patchen
Geänderte Dateien:
- config.ini (Switch für CRC check aus template.ini kopieren)
- includes/decoder.py (Typo)
- includes/decoders/fms.py (Funktionalität)

Das sollte es gewesen sein.

**Comment by stereu** [comment]
Flothi, in der config.template.ini war die CRC-Check Option falsch platziert. Habe einen neuen Pullrequest gesetzt, der das fixt [#202](https://github.com/Schrolli91/BOSWatch/pull/202)

**Comment by flothi** [comment]
Danke für den Hinweis, da hab ich wohl den Überblick verloren vor lauter FMS und ZVEI ;-)

**Comment by Schrolli91** [comment]
@flothi ist das nicht genau das Problem, was du direkt bei multimon auch gepusht hast, als fix? Damit also behoben?

**Comment by flothi** [comment]
So korrekt, ich wollte noch auf Rückmeldungen warten. Aber ist gefixt.
