### ISSUE TITLE
Multimon_NG Output in seperate file

### ISSUE THREAD

**Issue by einmalacht** [Schrolli91/BOSWatch#97]
Hello together, 
first of all: GREAT SCRIPT !!!

I use it to connect with bosmon on my raspberry pi 3 and SDR Stick.
I use the doublecheck to filter out double messages.
But i want to know how many DAUs i receive and so the output of multimon_ng were fine.
Also i can check my rx conditions in this file .... 
Is there any way to write the plain multimon_ng output to a file?

MANY THX

**Comment by flothi** [comment]
Do you mean the plain text before it's processed by BOSWatch?

**Comment by einmalacht** [comment]
Hi yes right the output of multimon_ng with the decoded messages before BOSwatch is using it.

**Comment by flothi** [comment]
I think magic happens right here:
https://github.com/Schrolli91/BOSWatch/blob/master/boswatch.py#L339

Do you want both a file-out and decoding via BOSWatch?

**Comment by Schrolli91** [comment]
Yes, thats the correct Line. Here catchs BOSWatch die data from multimon-NG over the pipe.

**Comment by einmalacht** [comment]
yes both were cool so i can check the multimon output when i have problems with signal strength.
when double check in boswatch is enabled i dont have a opportunity to check the number of dau i receive.
My number of dau is swaying between one and three depending on the daytime.

**Comment by flothi** [comment]
So I just added some lines of code in the main file to log the output of multimon; please note that it's quick and dirty as I wanted to log both the console-out and the `tail -f output` which only works with a closed filehandle.

while True:
		# Test for writing raw data to file
			try:
				rawOut = open('output', 'a')
			except:
				print "Error opening file"
				exit(1)
			decoded = str(multimon_ng.stdout.readline()) #Get line data from multimon stdout
			rawOut.write(decoded)
			from includes import decoder
			decoder.decode(converter.freqToHz(args.freq), decoded)
			rawOut.close()

Check out around line 338 to replace this section and watch the indentations!

**Comment by Schrolli91** [comment]
I add this functionality in the next version ...

**Comment by Schrolli91** [comment]
please check latetst dev branch 

see: a6239f2

**Comment by Schrolli91** [comment]
Has anyone checked the changes for seperate output from multimon-NG? (see last comment/a6239f2)
I'm without a test system at the moment.

**Comment by flothi** [comment]
Works fine for me with a short test of about half a day, I'll keep it up and running for another few days and report any bugs.

**Comment by Schrolli91** [comment]
ouh, thats right - i will change it into mode `a` and clear the file automaticly on the start of BOSWatch to prevent  too big file

**Comment by flothi** [comment]
Actually I still have the information about available demods in multimon.log 

I can't see any information about decoding in it, but I will keep an eye on it.

**Comment by Schrolli91** [comment]
short feedback please... output runs correctly now?

**Comment by flothi** [comment]
After testing:
mm_raw shows the string provided from multimon - seems legit and working
multimon.log contains the standard information about multimon:
```
multimon-ng  (C) 1996/1997 by Tom Sailer HB9JNX/AE4WA
             (C) 2012-2014 by Elias Oenal
available demodulators: POCSAG512 POCSAG1200 POCSAG2400 EAS UFSK1200 CLIPFSK FMSFSK AFSK1200 AFSK2400 AFSK2400_2 AFSK2400_3 HAPN4800 FSK9600 DTMF ZVEI1 ZVEI2 ZVEI3 DZVEI PZVEI EEA EIA CCIR MORSE_CW DUMPCSV SCOPE
```

**Comment by Schrolli91** [comment]
ok - new function still running - closed

thx for the help
