### ISSUE TITLE
Plugin für Telegram

### ISSUE THREAD

**Issue by Dtrieb** [Schrolli91/BOSWatch#98]
Es wäre cool wenn man bestimmte Alarmierungen an Telegram senden lassen könnte.

[https://telegram.org/](url)

**Comment by PeterLaemmle** [comment]
Ich hab mir da mal was geschrieben:
[sendTelegram.txt](https://github.com/Schrolli91/BOSWatch/files/420860/sendTelegram.txt)

**Comment by PeterLaemmle** [comment]
Ich hab mal einen Pull request dafür erstellt:
[https://github.com/Schrolli91/BOSWatch/pull/106](https://github.com/Schrolli91/BOSWatch/pull/106)

**Comment by Schrolli91** [comment]
der wurde entsprechen gemerged... Telegram ist nun also bei den Plugins verfügbar ...
